### ISSUE TITLE
Option to deploy chalicelib/ as Lambda layer

### ISSUE THREAD

**Issue by danil-smirnov** [aws/chalice#1028]
It would be great to have an option to deploy _chalicelib/_ folder as [Lambda layer](https://docs.aws.amazon.com/en_us/lambda/latest/dg/configuration-layers.html) which can be then shared between all the Lambdas generated with the deployment.

**Comment by kyleknap** [comment]
@danil-smirnov yeah that would be interesting. We have a discussion on this GitHub issue: https://github.com/aws/chalice/issues/1001 about how to integrate Lambda layers into Chalice. It would be great if you could chime in there with the suggestion as we are currently brainstorming our options in that issue. Closing in favor of the linked GitHub issue.
