### ISSUE TITLE
Pipeline with bitbucket source

### ISSUE THREAD

**Issue by calm2018** [aws/chalice#1038]
Hi

I have a project stored in bitbucket and am trying to follow the following tutorial to create a pipeline:

https://chalice-workshop.readthedocs.io/en/latest/todo-app/part2/02-pipeline.html

It references building a pipeline using:
chalice generate-pipeline release/pipeline.json -s github

Chalice does not appear to support bitbucket (only options available are github|codecommit).

I tried to make the pipeline using Codecommit and then change the source to bitbucket but with no luck.

Any advise on how to use bitbucket as the repository?

**Comment by calm2018** [comment]
moved repository to github (now that it allows private repos)

**Comment by robincsamuel** [comment]
I modified the pipeline.json and bitbucket worked fine.

[Followed AWS documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html) to find out the configuration parameter replacements.

This is how my source stage looks like,
```json
{
  "Name": "Source",
  "Actions": [
    {
      "Name": "Source",
      "ActionTypeId": {
        "Category": "Source",
        "Owner": "AWS",
        "Version": "1",
        "Provider": "CodeStarSourceConnection"
      },
      "RunOrder": 1,
      "OutputArtifacts": [
        {
          "Name": "SourceRepo"
        }
      ],
      "Configuration": {
        "ConnectionArn": "arn:aws:codestar-connections:us-east-1:**********:connection/********-****-*****-****-********",
        "FullRepositoryId": "bitbuckerusername/repo",
        "BranchName": "master",
        "DetectChanges": true
      }
    }
  ]
},
```

Refer: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements
