### ISSUE TITLE
Add Type Annotations to Codebase

### ISSUE THREAD

**Issue by BigChief45** [aws/chalice#1042]
Python 3.6+ allows us to add type annotations. Meaning that maybe we could replace these:

```python
    def invoke(self, payload=None):
        # type: (OptStr) -> None
        response = self._invoker.invoke(payload)
        formatted_response = self._formatter.format_response(response)
```

With:

```python
    def invoke(self, payload: OptStr=None): -> None
        response = self._invoker.invoke(payload)
        formatted_response = self._formatter.format_response(response)
```

This allows us to remove all the comments used for type hinting.

Thoughts?

**Comment by kyleknap** [comment]
@BigChief45 So we already are using type annotations in the codebase along with `mypy` to enforce the [type checks](https://github.com/aws/chalice/blob/607338c23bf27ca6886d56f38d3016cfb9540fe7/Makefile#L27-L28) . We are just using the comment based type annotation as described in [PEP 484](https://www.python.org/dev/peps/pep-0484/#type-comments) as we need to support Python 2.7 as well (which does not support type annotations in function signatures). Hope this helps!

**Comment by BigChief45** [comment]
Understood. Had forgotten about Python 2 support.

Closing.
