### ISSUE TITLE
Getting current stage when lambda is scheduled

### ISSUE THREAD

**Issue by budowski** [aws/chalice#1046]
Might be out of scope, not 100% sure:
If you schedule your lambda (`@app.schedule`), the `event` param doesn't hold the stage name (unlike when using a "regular" pure lambda function), so there's no easy way of detecting your current stage.

Use case: In your scheduled lambda function, you want to have different logic (e.g. accessing a different database) according to the stage you're currently running in.

**Comment by budowski** [comment]
What happens currently if I have a scheduled lambda function (e.g. `app.schedule` for once an hour)? If I deploy the code to both `prod` and `dev` - won't that code run twice an hour?

This is related to #1009 as well.

**Comment by stealthycoin** [comment]
Different lambda functions would be getting invoked. Same codepath but a different deployment as stages are entirely separate from one another.

**Comment by budowski** [comment]
So basically set it via the `environment_variables` config, in the config file for that stage? (https://chalice.readthedocs.io/en/latest/topics/configfile.html?highlight=environment#stage-specific-configuration)

**Comment by joguSD** [comment]
Yep, in the config for that stage set the `environment_variables` config.
