### ISSUE TITLE
API Gateway lambda proxy integration with proxy resource

### ISSUE THREAD

**Issue by gopimicky** [aws/chalice#1052]
I am trying to setup proxy integration with proxy resource.

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

I am trying to validate a test endpoint.
```
@app.route('/test')
def index1():
    return {'hello': 'method2'}
```

Created the APIGW via AWS console.  Trying to test.  I am getting the following error:
```
"No view function for: /{proxy+}", "errorType": "ChaliceError", "stackTrace": [["/var/task/chalice/app.py", 647, "__call__", "raise ChaliceError(\"No view function for: %s\" % resource_path)"]]}
```

Is this something supported by chalice?  Is there any documetaion available regards to this?

**Comment by stealthycoin** [comment]
What do you mean with proxy resource? Chalice deploys an API gateway with LAMBDA_PROXY that points at one shared lambda function. You don't need to create an api gateway via the aws console. Chalice does that for you and prints the endpoint out after deployment.

**Comment by gopimicky** [comment]
Hi @stealthycoin thanks for the response.  I have been using chalice cli to deploy the app.  Cli is creating each route as individual resource.  I am trying to experiment whether we could create "Configure it as proxy resource" as shown in this screenshot https://ibb.co/68Q5Y2y.

Can I achieve this through chalice cli?  Does it support?

**Comment by stealthycoin** [comment]
It looks like that's just based on the URI? So Chalice wouldn't have to explicitly support it, just put it i your route. Unless I am misunderstanding the feature still.

```python
@app.route('/{proxy+}')
def index():
    return app.current_request.uri_params
```

```
➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/
{"proxy":"foo"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar/
{"proxy":"foo/bar"}
➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar/baz
{"proxy":"foo/bar/baz"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
```

**Comment by akaulgud** [comment]
For proxy integration between API GAteway and Lambda, you need to pass response with following fields mandetorily

{ "statusCode": 200, "body": json.dumps("some text")}

If you have binary data , there is one more field required, ie. related to Base64 encoding.

**Comment by kanhais** [comment]
This is still not supported. 
`curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar`
this is giving me 403 instead of `{"proxy": "foo/bar"}`

**Comment by WiWhite** [comment]
```
@app.route('/{proxy+}')
def index():
    return app.current_request.uri_params
```

This option will work:
```
➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/
{"proxy":"foo"}
```

But this:                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
```
➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar/
{"proxy":"foo/bar"}
➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar/baz
{"proxy":"foo/bar/baz"}   
```          

returned:
```
{
    "message": "Missing Authentication Token"
}
```

I want to setup proxy integration with proxy resource. (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html
)
For example:
```
import requests

@app.route('/support/{proxy+}')
def index():
    project_url = "https://example.com"
    session = requests.session()
    return session.request(
        app.current_request.method, 
        f"{project_url}/{app.current_request.path}", 
        params=app.current_request.query_params,
    )
```

```
➜  curl https://....execute-api.us-west-2.amazonaws.com/support/admin/users
{"users": [{user_1}...{user_n}]}  # where {"proxy":"admin/users"}

➜  curl https://....execute-api.us-west-2.amazonaws.com/support/admin/users/124
{"user": {...}}. # where {"proxy":"admin/users/124"}
```

**Comment by annjawn** [comment]
Hi there. I am reviving this thread. The Op has a valid question and I don't think using `

> It looks like that's just based on the URI? So Chalice wouldn't have to explicitly support it, just put it i your route. Unless I am misunderstanding the feature still.
> 
> ```python
> @app.route('/{proxy+}')
> def index():
>     return app.current_request.uri_params
> ```
> 
> ```
> ➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/
> {"proxy":"foo"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
> ➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar/
> {"proxy":"foo/bar"}
> ➜  curl https://....execute-api.us-west-2.amazonaws.com/api/foo/bar/baz
> {"proxy":"foo/bar/baz"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
> ```

Hi there, this solution doesn't look right. The idea behind [catch all](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html) `{proxy+}` is that Chalice should be able to handle the routing normally within the app. For example-

`/{proxy+}` with method `ANY`, Should support `/foo` with `GET`, `/bar` with `POST` and so on. So Chalice routing should ideally look like so-

```python
@app.route('/foo', methods=['GET])
def get_foo():
    return app.current_request.uri_params

@app.route('/bar', methods=['POST])
def get_foo():
    return app.current_request.uri_params
```
