### ISSUE TITLE
Query params is sometimes None, sometimes a dict

### ISSUE THREAD

**Issue by jessebrennan** [aws/chalice#1055]
If there are no query parameters then `app.current_request.query_params` is `None`.

From the documentation I have found there is no indication that this may be `None`.

> current_request.query_params - A dict of the query params for the request.

I propose either a documentation change that indicates that this value will be `None` if there is no query, or else have it default to an empty dictionary. I prefer the latter since removes the constant need for checking if `query_params` is `None` before making use of it. Instead the user can just call `query_params.get()`.

**Comment by jamesls** [comment]
Defaulting to an empty dictionary would be preferable, but I suspect this could affect existing code.  I think for now we should update the documentation.  There's a few of these attributes on the request that API gateway will default to null if they're not provided.

**Comment by jessebrennan** [comment]
@jamesls thanks for the fix! Is it possible to make some sort of feature request to have it default to a dict? Is this the right place for that?
