### ISSUE TITLE
Missing watchdog dependency

### ISSUE THREAD

**Issue by Sytten** [aws/chalice#1067]
While working on the lib, I had to manually install the `watchdog` package otherwise `make prcheck` would fail at the linter stage. I didn't see it anywhere in the `setup.py` nor the `requirements-dev.txt` and since it is used in the `eventbase.py` file I assume it is missing.

**Comment by joguSD** [comment]
The `watchdog` dependency is [optional in the setup.py](https://github.com/aws/chalice/blob/e089b3bc2d29ca7981fe272432ba47b91a33f6d0/setup.py#L33) and can be installed like this:
```
pip install chalice[event-file-poller]
```

I assume the linter is failing due to missing imports?

**Comment by Sytten** [comment]
Yes exactly, juste feels strange that it is required for linting but not included as a dep. Maybe it should be documented for developers?

**Comment by kyleknap** [comment]
Yeah I agree. I think having it documented would be good. Specifically, I think we should update this section: https://github.com/aws/chalice/blob/master/CONTRIBUTING.rst#development-environment-setup to use:
```
pip install -e ".[event-file-poller]"
```
@Sytten thoughts? That should be an easy update.

**Comment by Sytten** [comment]
I agree, seems the right place to put it!
