### ISSUE TITLE
Could not install dependencies: pyyaml==3.13

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#1074]
Was https://github.com/aws/chalice/issues/572 resolved?

I got the same issue lately. I built the wheel on EC2 ubuntu 18.04.

chalice 1.6.2, python 3.7.2, darwin 18.2.0

project folder:
requirements.txt
app.py	chalicelib	vendor

requirements:
PyMySQL
PyJWT>=1.5.3
boto3>=1.9.86
botocore>=1.12.86
kubernetes

vendor folder:
PyYAML-3.13.dist-info	yaml

Creating deployment package.

Could not install dependencies:
pyyaml==3.13
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://chalice.readthedocs.io/en/latest/topics/packaging.html

**Comment by kadrach** [comment]
Do you have `wheel` installed in your main environment (i.e. the one containing chalice)?

**Comment by wutachih** [comment]
I followed the instructions in the link. I made a wheel in ec2 Ubuntu and unzipped it in the chalice vendor folder.

**Comment by kyleknap** [comment]
I can confirm that you will have to vendor. For the previously linked issue https://github.com/aws/chalice/issues/572, that was specifically for warnings when someone vendors a library in their chalice application and also downloads its wheel via the `requirements.txt`. Looking at the artifacts uploaded to PyPI for PyYAML: https://pypi.org/project/PyYAML/3.13/#files, it does not have any manylinux1 wheels available. So if you are deploying from other operating systems like MacOSX, the wheel will not be able to be built from that OS. Unfortunately, there is not much we can do from Chalice's side to avoid having to building it yourself on a Linux machine. However if PyYAML had a manylinux wheel available on PyPI, chalice would automatically be able to pick it up. It also looks like PyYAML has a tracking issue that may be worth to follow for manylinux wheels support: https://github.com/yaml/pyyaml/issues/43. Let us know if you have anymore questions.

**Comment by msambol** [comment]
I'm seeing this issue even when building the wheel on Amazon Linux (tried 2 as well).

```
pip download pyyaml==3.13
pip wheel PyYAML-3.13.tar.gz
```

I moved `PyYAML-3.13-cp27-cp27mu-linux_x86_64.whl` to my local machine in the `vendor` directory and ran `unzip`. My `vendor` dir looks like:

````
PyYAML-3.13.dist-info	
yaml
```

I imported `yaml` in `app.py`, but still received the warning when deploying:

```
Could not install dependencies:
pyyaml==3.13
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://chalice.readthedocs.io/en/latest/topics/packaging.html
```

This is required for using Amazon Cognito User Pools for authorization.

**Comment by jamesls** [comment]
So there's a couple of things here:

@msambol: If you're putting packages in vendor, you can omit them from requirements.txt.  That should fix the issue for you.

Also, the pyyaml compilation is only needed for the C speedups.  One option we have is to try to build the C extension (which it does by default), but if it fails, then just use the pure python version.  The end result is that PyYAML will "just work" but it won't have the C speedups enabled if we can't compile them (which will happen on windows and mac).

I'll go ahead and send a PR for this behavior and people can comment on whether or not they'd like this behavior.
