### ISSUE TITLE
subsequent deploy fails when using on_sqs_message

### ISSUE THREAD

**Issue by junaidnasir** [aws/chalice#1075]
when using `on_sqs_message` in chalice, deployment works for the first time but on second time (when deploying next version or other modification on same stage) it fails.

> An error occurred (ResourceConflictException) when calling the
 CreateEventSourceMapping operation: An event source mapping with SQS arn ("
 arn:aws:sqs:eu-west-1:xxxxxxxx:queue-name") and
 function (" lambda-name ") already exists. Please
 update or delete the existing mapping with UUID
 xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Is this intended behaviour? and does deleting the function manually is the only solution?

chalice 1.6.2, python 3.6.6, darwin 18.2.0

**Comment by kyleknap** [comment]
Hmm I was not able to reproduce this. Chalice should be able to handle redeployments. Here is what I tried. My `app.py` is the following:
```python
from chalice import Chalice

app = Chalice(app_name='sqs-redeploy')

@app.on_sqs_message(queue='chalice-queue-2')
def index(event):
    return {'hello': 'world'}

```
I then ran back to back `chalice deploy`'s and it was able to deploy and then redeploy. Could you share the following to help troubleshoot:

1) The code for the `app.py` (or a minimal version of it) that you cannot redeploy
2) The specific change you made between the initial deployment and the subsequent deployment to cause it to fail to deploy.
3) Debug logs from running `chalice deploy`. You can do so by doing `chalice --debug deploy`

**Comment by junaidnasir** [comment]
Oh, I got it. Deployments are made using Travis and status files are not being pushed to some remote storage. on next deployment, it doesn't have the mapping.
Can be closed. thanks for help

**Comment by akurtz** [comment]
@junaidnasir I'm having this same issue when redeploying in a CI pipeline.  Any chance you could clarify what you mean when you say _"status files are not being pushed to some remote storage"_?  How did you fix this?

(Also tagging @JacksonKontny since he also seemed to know what you meant by this when he posted in #287 in June.)

**Comment by junaidnasir** [comment]
@akurtz when you deploy using chalice, it creates a remote resource file (which I called status file) in `.chalice/deployed/stagename.json`. so on next run it checks this file and update/delete/create the resources required. 
But when using CI (travis) this file was being discarded after deployment making it unavailable in the next deployment. 
we now use terraform for managing the triggers. other possible solution can be to merge the status file into the repo from your CI tool, or to upload/download it to some remote (e.g s3) before and after each deployment.

**Comment by akurtz** [comment]
Nice, that makes sense now — thank you!! 👍
