### ISSUE TITLE
Local schedule

### ISSUE THREAD

**Issue by NaxAlpha** [aws/chalice#1076]
Hi,
I wanted to ask if it is possible to test `app.schedule` locally using `chalice local`. I could not find it in documentation. Example use case is:
``` python
@app.schedule(Rate(1, unit=Rate.MINUTES))
def commit(_event):
    url = os.environ['SOLR_URL'] + 'update?commit=true'
    return requests.get(url).json()
```
Currently I am wrapping it myself using `schedule` library:
``` python
def _schedule_wrapper():
    while True:
        schedule.run_pending()
        sleep(1)


schedule.every(1).minutes.do(lambda: commit(...))
Thread(target=_schedule_wrapper).start()
```

**Comment by kyleknap** [comment]
We do not have support for a local mode for scheduled events. It would be nice to have though. We currently have an open GitHub issue tracking this feature: https://github.com/aws/chalice/issues/979. Let's keep the conversation over there.
