### ISSUE TITLE
Execution of app.p upon deployment

### ISSUE THREAD

**Issue by PapoyEdits** [aws/chalice#1077]
So this is more of a question rather than an issue, but I'm not sure where to turn to.
I'm creating a serverless architecture with chalice, and in the app.py file I'm connecting to an RDS Aurora database. The database is set to private and the created lambda for the API is associated with a VPC (subnet and security group). I currently establish the connection to the database outside of the route definition (connect statement). 

However, when I try to deploy with this setup, I get a "Can't connect to MySQL server on ..." timeout, indicating that the actual code of app.py is being run during the deploy? but failing since it is a private database? (if I comment the connect statement before deploying and uncomment it in the AWS console it works as expected). 

I don't get this error if I move the connect statement into the route, which might be the intended way to go. 

So 1. Is the code actually being run once during the deploy, for whatever reason, and is it possible to turn off, as I don't want to uncomment in AWS every time?
2. Does it matter where the connect statement is in terms of performance (thinking about cold-starts and what-not)?

**Comment by kyleknap** [comment]
1) So all code will be ran that is declared at the module level. So if you are creating a connection at the module level, it will try to connect to your database. This is because chalice needs to load your `app.py` file in order to determine all of the lambda functions to create.

2) Yes it does matter. It also makes sense to declare the connection at the module level so that you do not have to recreate it with each invocation of the lambda function. What I recommend doing to make this work is something like this: https://github.com/aws-samples/chalice-workshop/blob/42238fc0dff6b16d926c24140e5b44a58d49a184/code/todo-app/final/app.py#L42-L49 where you define a module level variable, set it to `None`, then whenever you need the connection, check to see if it is `None` and create the connection if needed.

Let us know if that helps or if you have any more questions.

**Comment by PapoyEdits** [comment]
Thanks for the reply. 
Regarding the solution, it seemed fine conceptually, however we encountered another potential issue more closely related to using the Pony ORM. We created a function similar to the one in the example and tried calling it from the route, however we encountered the following error: 
"pony.orm.core.TransactionError: @db_session-decorated create_tables() function with `ddl` option cannot be called inside of another db_session"
And during following requests until the Lambda container shuts down, we get the following:
"pony.orm.core.BindingError: Database object was already bound to MySQL provider"
We suspect that establishing the connection in the route and not in the module level when using the Pony ORM can cause issues.
As this issue is more related to ORM, it might be unrelated to chalice and hard for you to answer, but any input is appreciated.

**Comment by jamesls** [comment]
Do you have any code snippets you can share?  I'm not familiar with the pony orm but I'll try to set this up with chalice and see if I run into any issues.

**Comment by jamesls** [comment]
Ok, so I spun up a test aurora postgres db in a private VPC and played around with pony.  I used their examples on their [getting started page](https://docs.ponyorm.org/firststeps.html).  It was a little confusing at first only calling bind once, but I just wrapped that in my own decorator so I could still just use the `db_transaction` decorator they provide.  Here's what I had:

```python
from chalice import Chalice
from pony import orm

app = Chalice(app_name='testdb')
app.debug = True
db = orm.Database()
db_is_bound = False


class Person(db.Entity):
    name = orm.Required(str)
    age = orm.Required(int)
    cars = orm.Set('Car')


class Car(db.Entity):
    make = orm.Required(str)
    model = orm.Required(str)
    owner = orm.Required(Person)


# Use this as a decorator instead of @orm.db_session
def app_db_session(func):
    wrapped = orm.db_session(func)
    def _view_function(*args, **kwargs):
        global db_is_bound
        if not db_is_bound:
            bind_connection(create_tables=False)
            db_is_bound = True
        return wrapped(*args, **kwargs)
    return _view_function


def bind_connection(create_tables=False):
    # XXX: Pull these from os.environ, don't hardcode them.
    db.bind(provider='postgres', user='james',
            password='',
            host='...',
            database='testdb')
    db.generate_mapping(create_tables=create_tables)


# Test route to make sure everything works without db access.
@app.route('/')
def index():
    return {'hello': 'world'}


@app.route('/users/{name}', methods=['PUT'])
@app_db_session
def make_new_user(name):
    Person(name=name, age=20)


@app.route('/users', methods=['GET'])
@app_db_session
def all_users():
    return list(orm.select(p.name for p in Person))


# Don't actually do this for real.  This is just for test purposes
# because I don't have anything else that can access the db's private
# subnet.
@app.route('/create-tables')
def route_create_tables():
    print("Creating tables...")
    bind_connection(create_tables=True)
    return {'success': True}

```

Seems to work as expected:

```
$ http PUT https://abc.execute-api.us-west-2.amazonaws.com/api/users/james
HTTP/1.1 200 OK
Connection: keep-alive
...

null

$ http PUT https://abc.execute-api.us-west-2.amazonaws.com/api/users/james2
HTTP/1.1 200 OK
Connection: keep-alive
...

null

$ http PUT https://abc.execute-api.us-west-2.amazonaws.com/api/users/james3
HTTP/1.1 200 OK
Connection: keep-alive
...

null

$ http PUT https://abc.execute-api.us-west-2.amazonaws.com/api/users/james4
HTTP/1.1 200 OK
Connection: keep-alive
...

null

$ http https://abc.execute-api.us-west-2.amazonaws.com/api/users/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 34
...

[
    "james",
    "james3",
    "John",
    "james2"
]
```

Now, that being said, I do wish there was something easier than this.  I like the idea of request middleware and startup hooks so you don't have to write these types of decorators yourself.

Let me know if you have any more questions.

**Comment by PapoyEdits** [comment]
Thanks for taking the time to test it out, didn't realize you could create your own decorator, so this was exactly what we needed.
