### ISSUE TITLE
Chalice invoke returns Error: could not find a lambda function 

### ISSUE THREAD

**Issue by ktmd** [aws/chalice#1079]
Hi,
I am new to Chalice. I deployed the sample helloworld app fine. I can access the REST API fine.
But when I tried the command 'chalice invoke' , I got error as shown below.  Notice that AWS cli works fine.  Is it a bug or I did something wrong?  Thanks. 

My log:

`(chalice) C:\helloworld>chalice --version
chalice 1.7.0, python 3.7.1, windows 7

(chalice) C:\helloworld>chalice deploy
Creating deployment package.
Creating IAM role: helloworld-dev
Creating lambda function: helloworld-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:77:function:helloworld-dev
  - Rest API URL: https://jgzwp7f0xe.execute-api.us-east-1.amazonaws.com/api/

## Chalice REST works OK
(chalice) C:\helloworld>http   https://jgzwp7f0xe.execute-api.us-east-1.amazonaws.com/api/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 17
Content-Type: application/json
Date: Thu, 21 Feb 2019 19:38:40 GMT
Via: 1.1 7b01019810c971756b017bcc76055c79.cloudfront.net (CloudFront)

x-amzn-RequestId: 49faca71-3610-11e9-8a97-f5953b87a28c

{
    "hello": "world"
}

## ERROR: Chalice cannot find lambda function via invoke
(chalice) C:\helloworld>chalice invoke --name helloworld-dev
Error: could not find a lambda function named helloworld-dev.

(chalice) C:\helloworld>chalice invoke -n helloworld-dev
Error: could not find a lambda function named helloworld-dev.

## But AWS CLI works OK
(chalice) C:\helloworld>aws lambda invoke --function-name helloworld-dev savedoutput
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}

(chalice) C:\helloworld>aws lambda list-functions
{
    "Functions": [
        {
            "FunctionName": "helloworld-dev",
            "FunctionArn": "arn:aws:lambda:us-east-1:77:function:helloworld-dev",
            "Runtime": "python3.7",
			....
			
`

**Comment by kyleknap** [comment]
@ktmd No worries. It looks like you are trying to invoke the API handler. In chalice, all of the routes are under a single lambda function that we set the logical name as `api_handler`. In order to invoke it, you need to run:
```
$ chalice invoke -n api_handler
```
You can also find that value in the docs if you run `chalice invoke --help`. It is also important to note that if you want to invoke it manually, you will need a properly formatted event from API Gateway. Otherwise, you will most likely get an internal error back such as:
```
{"body": "{\"Message\":\"Unknown request.\",\"Code\":\"InternalServerError\"}", "headers": {}, "statusCode": 500}
```
So it may be a little simpler to use HTTPie instead. Let us know if that helps or if you have anymore questions.

**Comment by ktmd** [comment]
@kyleknap ,
I got it .  It would be nice if there are some examples for this in the help documentation.

Thanks for the quick response and great work with Chalice.

**Comment by Rubyj** [comment]
@ktmd @kyleknap Hi I am suffering from the same issue. My lambda is not decorated with `app.route`, but instead `app.on_s3_event` How can I run this locally?
