### ISSUE TITLE
Slow deploy

### ISSUE THREAD

**Issue by Sytten** [aws/chalice#1086]
My lambda is around 10mb so I expect it shouldn't take long with a 10mbit/s connection to upload, but I always get a timeout (`botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions"`) with the default deploy setting. Not sure how you are doing things, but it's not very efficient...
I raised the timeout using `--connection-timeout` parameter to 5 minutes and it worked though.

**Comment by kyleknap** [comment]
Chalice deployments should be relatively fast and should not have to worry about timeout. Could you provide the sample snippet of the application you are trying to deploy with its requirements? Also could you provide debug logs from running chalice deploy? You can get them by running `chalice --debug deploy`.

**Comment by Sytten** [comment]
My code is not open source, but here is my requirements:
```
psycopg2==2.7.7
boto3==1.9.89
SQLAlchemy==1.2.17
```
I will do a deploy tomorrow.

**Comment by arianpasquali** [comment]
same issue here.
Hello world example works just fine.

When I try something fancier, with my requirements.txt being just:

```
pandas==0.24.2
pymongo==3.8.0
```

it gives me the same error

**Comment by jamesls** [comment]
I think it will depend on your connection to AWS.  Can you confirm that setting the connection timeout to a higher value fixes the issue for you?

I tried the same dependencies (admittedly I have a fast connection to AWS) which seems to work:

```
$ cat requirements.txt
pandas==0.24.2
pymongo==3.8.0
$ chalice deploy
Creating deployment package.
Creating IAM role: testjsonpath-dev
Creating lambda function: testjsonpath-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:288942387673:function:testjsonpath-dev
  - Rest API URL: https://<rest-api-id>.execute-api.us-west-2.amazonaws.com/api/
```

If bumping the connection timeout works, perhaps we should add that as an option in your `config.json` so you don't have to specify it every time.

**Comment by Sytten** [comment]
For me it worked, but it seemed suspicious that is it so slow. A config would be nice.

**Comment by jtwolgamott** [comment]
Slow here as well, and getting the "Connection was closed..." error too.

**Comment by noescapeartist** [comment]
Yes.  Things I could easily deploy very quickly before, now timeout or take a very long time.  This doesn't appear to be a bandwidth problem, as I've tried on various networks and regions.  I've tried commenting out various functions, removed various packages.  I've even tried simple 'Hello World' applications.  This just started happening for us in the last couple of days.

**Comment by shahabyounas** [comment]
I had the same problem while deploying dev stage and this command worked for me. Thank you @Sytten 
`chalice deploy --stage dev --connection-timeout 360`

**Comment by jamesls** [comment]
I'll add something to the docs about raising the connection timeout, but in general, the more dependencies you pull in the longer the deployment will take.  There's some ongoing work to improve that by using layers.

**Comment by t-cun** [comment]
+1 throwing a short note in the docs would be very useful. Agreed minimizing dependencies is ideal but this is a handy option to know about if you're in a situation where you do have a few large ones :slightly_smiling_face:

**Comment by raihanba13** [comment]
Using layer can make the deployment faster but still I am not satisfied. My Chalice file size is less than 3 MB.

**Comment by edumats** [comment]
I am experiencing multiple timeouts too when trying to complete a todo app on Chalice Workshop:

https://chalice-workshop.readthedocs.io/en/latest/todo-app/index.html

It has only 2 dependencies:
boto3==1.24.86
PyJWT==1.6.1

I have a fast connection and never experienced any problems related to network speed. The first deploys were fast, but the last one was giving multiple timeouts and only managed to deploy successfully after bumping the connection timeout to 360, but the whole process was really slow, despite being a small project.
