### ISSUE TITLE
autogen_policy: false not working as expected

### ISSUE THREAD

**Issue by lesatdgl** [aws/chalice#1093]
I have config.json:
{
  "version": "2.0",
  "app_name": "gicContacts",
  "api_gateway_stage": "api",
  "manage_iam_role": "false",
  "iam_role_arn": "arn:aws:iam::762915485767:role/gicLoadCsv",
  "autogen_policy": "false",
  "environment_variables": {
        "BUCKET": "gic-contacts",
        "PREFIX": "csvs/"
      }
    }

Chalice REFUSES to use the IAM I specified

>>> with autogen_policy: false in config.json
lice-projects/gicContacts$ chalice deploy
Creating deployment package.
Creating IAM role: gicContacts-dev
Creating lambda function: gicContacts-dev-handle_s3_event
Configuring S3 events in bucket gic-contacts to function gicContacts-dev-handle_s3_event
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:762915485767:function:gicContacts-dev-handle_s3_event

>>> with --no-autogen-policy inline
(chalice-projects-iFvGfrMz) (xenial)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/gicContacts$ chalice deploy --no-autogen-policy
Creating deployment package.
Creating IAM role: gicContacts-dev-handle_s3_event
Updating lambda function: gicContacts-dev-handle_s3_event
Configuring S3 events in bucket gic-contacts to function gicContacts-dev-handle_s3_event
Deleting IAM role: gicContacts-dev
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:762915485767:function:gicContacts-dev-handle_s3_event

Is there a magic word? Like DOWHATISAID ?

**Comment by JordonPhillips** [comment]
It looks like you're giving the string `"false"` instead of the boolean `false`.

**Comment by lesatdgl** [comment]
I copied this from docs

**Comment by JordonPhillips** [comment]
Where in the docs did you copy it from? I can't seem to find anywhere that uses the string false.
