### ISSUE TITLE
Get the current app when using blueprints

### ISSUE THREAD

**Issue by physicalgraffiti** [aws/chalice#1094]
Hey guys,
I've been using the experimental feature `blueprints` recently. I found this to be extremely useful!

When using blueprints, at registration time the current app is asigned to the `_current_app` attribute of the Blueprint instance. I think it'd be useful to have a `current_app` method (similar to Flask) to avoid calling `blueprint._current_app` in order to get an instance of the current application when defining the routes. I think this should be similar to the `current_request` property method defined in the `Blueprint` class, maybe something like this?

```
@property
def current_app(self):
    if self._current_app is None:
        raise RuntimeError(
            "Can only access Blueprint.current_app if the blueprint is "
            "registered to an app."
        )
    return self._current_app
```
Thanks for the great work on Chalice!

**Comment by kyleknap** [comment]
@physicalgraffiti Thanks! The request seems reasonable, especially since it will help keep parity with flask. Out of curiosity, how would you plan to use the `current_app` property in your blueprint? What methods/properties off of the `current_app` are you planning to use from within your blueprint? A code sample would be great to help illustrate.

**Comment by physicalgraffiti** [comment]
Yes, sure.
Actually I'm using the `app` inside the blueprints to access some configuration parameters, logging and other features we're adding to the main app during setup. Here's an example:

```
from chalice import Blueprint, NotFoundError
from chalicelib.utils import get_current_app

bp_foo = Blueprint(__name__)

@bp_foo.route('/foo', methods=['GET'])
def foo(bar):
    try:
        request = bp_foo.current_request
        # currently, get_current_app is a helper that returns 
        # blueprint._current_app
        app = get_current_app(bp_foo)

        if (f'{bar}_conf' not in
                app.config.SOME_CONFIG.keys()):
            raise NotFoundError(f'no {bar}_conf in app config.')
            app.log.warn(f'Config parameter not found: {bar}')
    except Exception as exc:
        return(f'Ooops, something went wrong: {exc}')
    return request
```

Just wondering, do you have some idea of a release date for this experimental feature?
Thanks again!

**Comment by jamesls** [comment]
Implemented in https://github.com/aws/chalice/pull/1473

**Comment by theobouwman** [comment]
```python
@events_blueprint.on_sns_message(topic='analysis_event')
def handle_analysis_event_sns_message(event):
    events_blueprint.current_app.log.debug("Received message with subject: %s, message: %s", event.subject, event.message)
```

When sending a sns event:
```
2021-11-29 21:55:09.156000 67508b [ERROR] RuntimeError: Can only access Blueprint.current_app if it's registered to an app.
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1605, in __call__
    return self.handler(event_obj)
  File "/var/task/chalicelib/api_events.py", line 20, in handle_analysis_event_sns_message
    events_blueprint.current_app.log.debug("Received message with subject: %s, message: %s", event.subject, event.message)
  File "/var/task/chalice/app.py", line 2000, in current_app
    raise RuntimeError(
```
