### ISSUE TITLE
Browser Accept header binary response fails due to Chalice only checking first content-type

### ISSUE THREAD

**Issue by melevittfl** [aws/chalice#1095]
Apologies if raising this as a new bug is the wrong thing as it is very similar to #391. However, that bug has been closed so I figured it's best to raise a new one.

I have an application that generates an image in response to a GET request from a browser. However, while I can get it working with a pure AWS Lambda function, Chalice does not properly binary encode the response. 

This is due to Chalice determining if it should binary encode the response by checking to see if the response type matches the Accept header. So if you have a response like image/png, and the accept header is image/png, then it will work. However, a browser's accept header is multiple content-types and rarely has the one you want first. 

I have created a PR (#1078) that fixes this issue by iterating over the list of accept header content-types and the list of allowed binary response content types and checking if there are any that match. This allows for serving of binary content to a browser correctly. 

Steps to reproduce the issue:
1) Create an application that serves a binary image like a PNG
2) Set the response to "image/png"
3) Make a request with a browser with an accept header like "text/html,application/xhtml+xml;q=0.9,image/webp,*/*;q=0.8" (this is Firefox's accept header)

Expected result:
Chalice correctly encodes the response an the image is returned to the browser

Actual result:
Chalice determines that the response is binary, but when it checks to see if the Accept header matches the response content-type, it splits the accept header on commas and only checks the first one (i.e., text/html,application/xhtml+xml;q=0.9 in the above example). As this doesn't match the "image/png", Chalice incorrectly returns an Unsupported Media Type error.

**Comment by kyleknap** [comment]
We recently merged this PR: https://github.com/aws/chalice/pull/1116 to support the multiple content type headers. It will be available in the next release of chalice. Thanks for reporting this issue and the PR! Closing this issue.

**Comment by atramos** [comment]
@kyleknap I've attempted testing this from the master branch and it doesn't seem to be working. I still get `{"Code":"BadRequest","Message":"Request did not specify an Accept header with image/jpeg, The response has a Content-Type of image/jpeg. If a response has a binary Content-Type then the request must specify an Accept header that matches."}`

**Comment by melevittfl** [comment]
Hi @atramos. Can you post the request Accept header you're using?

**Comment by atramos** [comment]
My problem has been resolved after uninstalling and reinstalling Chalice.

**Comment by atramos** [comment]
Hi @melevittfl actually I spoke too soon. The code below does not work (returns base64 encoded or corrupted data) unless I monkey-patch the API Gateway configuration by adding "*/*" to the Binary Media Types under settings:

```
from chalice import Chalice, Response
from urllib.request import Request, urlopen
from urllib.parse import unquote

app = Chalice(app_name='photo')

@app.route('/get-photo/{url}', methods=['GET'])
def index(url):
     return Response(
        load(unquote(url)),
        headers={
            'Content-Type': 'image/jpeg'
        },
        status_code=200)

def load(url):
    print(url)
    req = Request(url)
    req.add_header('accept', 'image/*')
    return urlopen(req).read()

```

**Comment by atramos** [comment]
Here is the accept header:
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`

**Comment by atramos** [comment]
Just found out, I can eliminate the monkey-patching by setting `app.api.binary_types =['*/*']` in app.py

`

**Comment by SkySor44** [comment]
I know this is much later but I figured I would document. Adding `app.api.binary_types = ['image/*']` solved it for me. I know most people are running into this when grabbing image assets and just adjusting from all content types to 'image/*' not only made it work but also prevented the Bad Request error
