### ISSUE TITLE
route decorator does not accept "name" parameter, as defined in docs

### ISSUE THREAD

**Issue by ehriq** [aws/chalice#1112]
When using the 'name' parameter on the app.route decorator, the `chalice deploy` command returns `TypeError: TypeError: route() got unexpected keyword arguments: name`. 

I'm trying to use the parameter as defined in https://chalice.readthedocs.io/en/latest/api.html#Chalice.route 

One example of code that raises the exception:
```
@app.route("/evaluate", methods=["POST", "OPTIONS"], name="post_evaluation")
def post_evaluation():
   ...
```

Using versions 1.7.0 and 1.8.0; both with same result.

**Comment by stealthycoin** [comment]
@ehriq Thanks for the report. I have a fix in #1145.
