### ISSUE TITLE
lambda_timeout doesn't work from config.json

### ISSUE THREAD

**Issue by dhruvagarwal** [aws/chalice#1113]
I've been referring to the docs [here](https://chalice.readthedocs.io/en/latest/topics/configfile.html#lambda-specific-configuration)
I'm setting up an application for a job which takes more than 60 seconds to run.
I've defined my env vars in the `config.json` which work, but `lambda_timeout` doesn't reflect up when i do `chalice deploy`.
I'm defining everything under `dev` stage.

**Comment by Rubyj** [comment]
Paste your config here so we can see please.

**Comment by joguSD** [comment]
As @Rubyj mentioned posting your config would help.

**Comment by dhruvagarwal** [comment]
Hey @Rubyj @joguSD
Here's my config
```{
  "version": "2.0",
  "app_name": "issue-poll",
  "stages": {
    "dev": {
      "api_gateway_stage": "api",
      "environment_variables": {
        "GITHUB_TOKEN": "",
        "SLACK_TOKEN": ""
      },
      "lambda_functions": {
        "issue-poll-dev-post_issues": {
          "lambda_timeout": 600
        }
      }
    }
  }
}```

**Comment by Rubyj** [comment]
@dhruvagarwal I am not sure about your setup, but my working setup looks like the following:

```
{
  "version": "1.0",
  "app_name": "issue-poll",
  "stages": {
    "dev": {
      "environment_variables": {
        "TEST": "VALUE"
      },
      "lambda_memory_size": 128,
      "lambda_timeout": 120
    }
  }
}
```

**Comment by dhruvagarwal** [comment]
@Rubyj  It works if I keep `timeout` in the scope of stages directly and not in functions. Thanks
