### ISSUE TITLE
Deterministic zipfile generation

### ISSUE THREAD

**Issue by kislyuk** [aws/chalice#1114]
When running `chalice package` multiple times, the zipfile outputs are normally different. This appears to be due to both order of file insertion and also zipfile mtime timestamps. For reference, the package https://github.com/esoule/strip-nondeterminism provides the ability to strip "extended file attributes" (`zip -X`) and reset mtimes, but not to reorder files in a deterministic order.

To enable change/drift detection, it's important to know when a package has meaningfully changed. It would be nice if Chalice built the zipfile in such a way that it's bit for bit reproducible when the input files/wheels have not changed.

**Comment by kislyuk** [comment]
I think I've found a more portable way of doing what strip-nondeterminism is doing (by setting all mtimes to a fixed timestamp):
```
find build_root -exec touch -t 201901010000 {} \;
```

**Comment by kislyuk** [comment]
In order to avoid using the platform-specific package `strip-nondeterminism`, I had to do the following:
- Remove *.pyc files from my source module directories
- Set the timestamp on all of my source module directories (staged in `vendor`) to a fixed value, so autogenerated *.pyc files were reproducible (see https://www.python.org/dev/peps/pep-0552/)
- Unzip the chalice generated zipfile, run `find PATH -exec touch -t 201901010000 {} \;`, and zip it back up with `zip -X`.

**Comment by joguSD** [comment]
Marking this as an enhancement.

Could definitely see how this is useful, but it might be hard to actually achieve in all situations. Some of these things should be easy enough to do though. That being said, some of these things are potentially out of the scope of what chalice should be doing.

**Comment by kapilt** [comment]
I also do deterministic zip file gen for some of my other lambda projects to minimize deployment churn, nutshell doing python zip file write string instead of add file, will also zero out the timestamp to start of epoch time. note there's a long standing lambda issue, that permissions on added files need group read permission else its a mystery failure in lambda.
