### ISSUE TITLE
support terraform config generation?

### ISSUE THREAD

**Issue by kapilt** [aws/chalice#1121]
I keep running into lots of orgs that are strongly committed to terraform. I end up doing gross hacks of layering infrastructure provisioning to try incorporate chalice's deploy/package operations in between terraform executions. But I think the simpler answer would be to just have chalice support terraform generation, curious if that's of interest.

**Comment by jamesls** [comment]
Yes this is of interest and something I'd like to support,  marking as feature request.  I'd like to gauge community interest on this, feel free to +1 this issue!
