### ISSUE TITLE
support for subscribing to cloud watch events (not just scheduled)

### ISSUE THREAD

**Issue by kapilt** [aws/chalice#1124]
Currently chalice supports periodic functions via cloud watch events, but doesn't support subscribing to other events (via event pattern). I think it would be very useful to support the fuller range of cloud watch events. In terms of a syntax proposal to kick off discussion.

```python
@app.on_cloud_watch_event({'source': 'aws.ec2'})
def on_instance_state_change(event, context):
     print(event)
```

**Comment by kapilt** [comment]
Fwiw pull request implements this currently as `app.on_cw_event(`

**Comment by jamesls** [comment]
Closing out old proposal, PR was merged a while back.
