### ISSUE TITLE
Support for multi-value query string paramters

### ISSUE THREAD

**Issue by or150** [aws/chalice#1131]
A few months ago, API Gateway added support for multi-value query string parameters, which I'd like to use in my app.

The key that contains the multi value version of the qs is 'multiValueQueryStringParameters'.

Can you add support for this?

**Comment by or150** [comment]
I implemented support for this feature myself. 
I would appreciate it if you could take a look and merge it in the future.

**Comment by stealthycoin** [comment]
I will put some feedback in the pull request. It's unfortunate that we need to preserve backwards compatibility with the existing behavior, and have a separate API for the list options. It's a little awkward having to do your own validation for each parameter based on whether or not it has multiple values or not. I think in the longterm it would be cool to have another layer on top of this that uses some model to determine if something is a single value or a list, and can abstract over this entirely. Maybe something like [marshmallow](https://marshmallow.readthedocs.io/).
