### ISSUE TITLE
store tokens in session?

### ISSUE THREAD

**Issue by whatsdis** [aws/chalice#1138]
I am using warrant with aws Chalice and after warrant authenticates a user in the cognito pool it gives me access tokens.

Is there some way of storing this in the user session ?

**Comment by stealthycoin** [comment]
Not sure exactly what you mean here. Do client's session or in the cognito pool session, or am I misunderstanding something here. I'm not very familiar with either warrant and I'm not a cognito expert, I'd have to read the docs to figure out how their sessions work.
