### ISSUE TITLE
query_params now returns a chalice.app.MultiDict object

### ISSUE THREAD

**Issue by danialranjha** [aws/chalice#1158]
[This commit](https://github.com/aws/chalice/commit/3a0e15f17a4632bfff3376490ad80a817f967ebf) has broken our app.

app.current_request.query_params now returns a chalice.app.MultiDict object, whereas it used to be a dict. So we could call app.current_request.query_params.pop('xyz', None) but can't do that anymore.

Not a huge deal as we can make changes at our end, but it's slightly annoying since there are quite a few patterns of this usage in our app.

**Comment by danialranjha** [comment]
I'm now finding a lot more of these issues throughout our code. For example, here is another example of code that is now broken because we are receiving a app.chalice.Multidict object where we expected a dict.

```
self.obj = obj
...
self.obj['collection_id'] = self.pkey
```

So I have to do something like this to fix the problem:
```
self.obj = {k:v for k,v in obj.items()}
```

**Comment by jamesls** [comment]
This was definitely unintentional and we'll get this fixed.  It seems like the immediate fixes would be to support `pop()` and make this not a read only object, but I'll also go through and audit multidict this to ensure there's no additional issues.

**Comment by danialranjha** [comment]
Thanks for looking into this. Just FYI this is not a blocker for us anymore as we’ve already worked around these issues. 

If I were prioritizing I would say ability to change the multidict object  is a higher priority than supporting `pop()`.

Thanks again.
