### ISSUE TITLE
Chalice 1.9.0 Tutorial - Additional Routing

### ISSUE THREAD

**Issue by lesatdgl** [aws/chalice#1161]
When I add the new routing:
@app.route('/resource/{value}', methods=['PUT'])
def put_test(value):
    return {"value": value}

And deploy

And execute
(xenial)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http PUT https://c09jqcgoek.execute-api.us-east-1.amazonaws.com/api/resource/foo
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Sat, 06 Jul 2019 20:25:51 GMT
Via: 1.1 268e769f31ddc5887a8b3a085f826161.cloudfront.net (CloudFront)
X-Amz-Cf-Id: q5FN89oEP07BRiYNYDi2rORhRRHrvQ2nGKPfdyGEo2ptdPkU2AJPug==
X-Amz-Cf-Pop: ATL51
X-Cache: Error from cloudfront
x-amz-apigw-id: ca2IdHHqoAMFo6w=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: 3f96721f-a02c-11e9-b038-3fe979a9174e

{
    "message": "Missing Authentication Token"
}
????

**Comment by stealthycoin** [comment]
I need more info here. This works fine with the current version. 
```
$ python --version
Python 3.7.3
$ pip install -U chalice
$ chalice new-project test
$ cd test
$ cat app.py
```
```python
from chalice import Chalice

app = Chalice(app_name='issue')


@app.route('/')
def index():
    return {'hello': 'world'}


@app.route('/resource/{value}', methods=['PUT'])
def put_test(value):
    return {"value": value}
```

Deploying and testing
```
$ chalice deploy
...
$ http PUT $(chalice url)resource/foo
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 15
Content-Type: application/json
Date: Mon, 08 Jul 2019 21:28:19 GMT
Via: 1.1 768a2670e63a97b7ac4065216c345a7a.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 9fsYCtykTDfVGu9BreSNC4P03kR_muRwIrj1UIP65OHyrVTWNLInWw==
X-Amz-Cf-Pop: HIO50-C1
X-Amzn-Trace-Id: Root=1-5d23b572-d2dd331ff44a68cda2837d06;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: chlJ8G8zvHcFoIw=
x-amzn-RequestId: 4de0c2e4-a1c7-11e9-ac52-e372418f4598

{
    "value": "foo"
}
```
That error usually means the route doesn't exist. So either you didn't deploy it, or its possible the request you made came too quick after the deployment, sometimes API gateway isn't up to date yet.

**Comment by lesatdgl** [comment]
Let me set it up and try it again

**Comment by lesatdgl** [comment]
OK, I re-did, from scratch
I started with helloworld app, then added cities, then added resource - saving and deploying.

The error I reported recurred - I took your suggestion to heart - maybe too quick
I tried resubmitting several times, a few minutes apart

All the above is reflected in the attached console and code

Got some weird stuff 

#### Code
from chalice import Chalice
from chalice import BadRequestError

app = Chalice(app_name='helloworld')
app.debug = True

CITIES_TO_STATE = {
    'seattle': 'WA',
    'portland': 'OR',
}


@app.route('/')
def index():
    return {'hello': 'world'}


@app.route('/cities/{city}')
def state_of_city(city):
    try:
        return {'state': CITIES_TO_STATE[city]}
    except KeyError:
        raise BadRequestError("Unknown city '%s', valid choices are: %s" % (
            city, ', '.join(CITIES_TO_STATE.keys())))


@app.route('/resource/{value}', methods=['PUT'])
def put_test(value):
    return {"value": value}

#### Console
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ chalice delete
Deleting Rest API: zn1916wj4k
Deleting function: arn:aws:lambda:us-east-1:762915485767:function:http-dev
Deleting IAM role: http-dev
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ chalice deploy
Creating deployment package.
Creating IAM role: http-dev
Creating lambda function: http-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:762915485767:function:http-dev
  - Rest API URL: https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 17
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:29:54 GMT
Via: 1.1 11253cbd3cb533d52b14abd664bee3da.cloudfront.net (CloudFront)
X-Amz-Cf-Id: OUReuC87LM8wyflALaSv9WRavMZHYosA8SeXkd_ZyLxA2QPk7_JHcg==
X-Amz-Cf-Pop: ATL51
X-Amzn-Trace-Id: Root=1-5d276402-05b869901c5503d0f2857db8;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: cqyQZHGBoAMFuDA=
x-amzn-RequestId: 1d54513c-a3f9-11e9-b95a-a3af1f482d39

{
    "hello": "world"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/cities/portland
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 14
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:30:12 GMT
Via: 1.1 e71e2e7de69d8943b38fb6581bce3335.cloudfront.net (CloudFront)
X-Amz-Cf-Id: pe4K395wZdIJ6pu6ojf65QFDk_wxVKoaI70EwAUnTEJZ19-TqOyGOw==
X-Amz-Cf-Pop: ATL51
X-Amzn-Trace-Id: Root=1-5d276414-0893171a8b1203b21b6e4c6c;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: cqyTLH_yIAMF0wQ=
x-amzn-RequestId: 27e95cfa-a3f9-11e9-b61b-01653ad95079

{
    "state": "OR"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ chalice deploy
Creating deployment package.
Updating policy for IAM role: http-dev
Updating lambda function: http-dev
Updating rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:762915485767:function:http-dev
  - Rest API URL: https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:31:26 GMT
Via: 1.1 38343488ed12520bf287a2696041ed18.cloudfront.net (CloudFront)
X-Amz-Cf-Id: OWR5HsVZtzQ8hhXWYNcQbkolQriqRdRJytTa_iSfILnA38LlohFEmw==
X-Amz-Cf-Pop: ATL51
X-Cache: Error from cloudfront
x-amz-apigw-id: cqyetEAAoAMFUEw=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: 53edfae3-a3f9-11e9-b0fd-4b9d7ace7d44

{
    "message": "Missing Authentication Token"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:32:27 GMT
Via: 1.1 3b8f30ab9156893ade320e1853d00a15.cloudfront.net (CloudFront)
X-Amz-Cf-Id: rltnm13eLZkJS2atHIuBG5tLrov8wC6U24Ck6Jt7QsrYFvu7dcSmZw==
X-Amz-Cf-Pop: ATL51
X-Cache: Error from cloudfront
x-amz-apigw-id: cqyoUGUboAMFR7g=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: 78933c7c-a3f9-11e9-9feb-8da8a9970ea2

{
    "message": "Missing Authentication Token"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:33:24 GMT
Via: 1.1 7751fd9d7f850b2169ef91a790def7f2.cloudfront.net (CloudFront)
X-Amz-Cf-Id: bP0ip-grhbD-6muKdktnLEpO939QxdtATsUrFf43OXPcIAiXsC4uvw==
X-Amz-Cf-Pop: ATL51
X-Cache: Error from cloudfront
x-amz-apigw-id: cqyxKHvDIAMFQ1g=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: 9a48d817-a3f9-11e9-afe1-6785d7889395

{
    "message": "Missing Authentication Token"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred

http: error: ConnectionError: HTTPSConnectionPool(host='6042jno86e.execute-api.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /api/resource/fred (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7bcdd17dcd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) while doing GET request to URL: https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http  https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred

http: error: ConnectionError: HTTPSConnectionPool(host='6042jno86e.execute-api.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /api/resource/fred (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7877932b4d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) while doing GET request to URL: https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred

http: error: ConnectionError: HTTPSConnectionPool(host='6042jno86e.execute-api.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /api/resource/fred (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x72932e3ccd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) while doing GET request to URL: https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ chalice url
https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ chalice delete
Deleting Rest API: 6042jno86e
Deleting function: arn:aws:lambda:us-east-1:762915485767:function:http-dev
Deleting IAM role: http-dev
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ chalice deploy
Creating deployment package.
Creating IAM role: http-dev
Creating lambda function: http-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:762915485767:function:http-dev
  - Rest API URL: https://sc3snoewpf.execute-api.us-east-1.amazonaws.com/api/
(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/fred
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 23
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:38:32 GMT
Via: 1.1 cbec82431a010799f206b43dbd0489c3.cloudfront.net (CloudFront)
X-Amz-Cf-Id: ZaEU77vzeYzJLwSqSMj8-UejPJiSEQknsiGGzDchp2GA29TQTFO_AA==
X-Amz-Cf-Pop: ATL51
X-Cache: Error from cloudfront
x-amz-apigw-id: cqzhQEe_IAMFldg=
x-amzn-ErrorType: ForbiddenException
x-amzn-RequestId: 51bd90ba-a3fa-11e9-b7a6-9d3c5979b8c6

{
    "message": "Forbidden"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$ http https://6042jno86e.execute-api.us-east-1.amazonaws.com/api/resource/foo
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 23
Content-Type: application/json
Date: Thu, 11 Jul 2019 16:39:18 GMT
Via: 1.1 cbec82431a010799f206b43dbd0489c3.cloudfront.net (CloudFront)
X-Amz-Cf-Id: _SgyTZQ70ax6ycMHzCVZFD4aD6QPT6dY45uVEHRAFVTuXOIK9G-_MA==
X-Amz-Cf-Pop: ATL51
X-Cache: Error from cloudfront
x-amz-apigw-id: cqzogH5XIAMFelw=
x-amzn-ErrorType: ForbiddenException
x-amzn-RequestId: 6d672b6f-a3fa-11e9-89e7-2bfb8a4f81be

{
    "message": "Forbidden"
}

(chalice-projects) (xfce-desktop)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/http$

**Comment by stealthycoin** [comment]
The examples from your most recent example don't have `http PUT` so they are `GET` requests which there is no route for so API Gateway returns 403 by default.
