### ISSUE TITLE
app.current_request.to_dict() returns only first of n query_params -related #1158?

### ISSUE THREAD

**Issue by lesatdgl** [aws/chalice#1163]
app.current_request.to_dict() returns only first on n query_params
**Environment**
+++++++++++++++++++++++++++++++++++++
Ubumtu 16.04 / Chalice 1.9.0 / Python 3.6.6

dgl-form-processor$ pipenv graph
appdirs==1.4.3
autopep8==1.4.4
  - pycodestyle [required: >=2.4.0, installed: 2.5.0]
awscli==1.16.193
  - botocore [required: ==1.12.183, installed: 1.12.183]
    - docutils [required: >=0.10, installed: 0.14]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - urllib3 [required: >=1.20,<1.26, installed: 1.25.3]
  - colorama [required: >=0.2.5,<=0.3.9, installed: 0.3.9]
  - docutils [required: >=0.10, installed: 0.14]
  - PyYAML [required: >=3.10,<=5.1, installed: 5.1]
  - rsa [required: >=3.1.2,<=3.5.0, installed: 3.4.2]
    - pyasn1 [required: >=0.1.3, installed: 0.4.5]
  - s3transfer [required: >=0.2.0,<0.3.0, installed: 0.2.1]
    - botocore [required: >=1.12.36,<2.0.0, installed: 1.12.183]
      - docutils [required: >=0.10, installed: 0.14]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.0]
        - six [required: >=1.5, installed: 1.12.0]
      - urllib3 [required: >=1.20,<1.26, installed: 1.25.3]
boto3==1.9.183
  - botocore [required: >=1.12.183,<1.13.0, installed: 1.12.183]
    - docutils [required: >=0.10, installed: 0.14]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - urllib3 [required: >=1.20,<1.26, installed: 1.25.3]
  - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
  - s3transfer [required: >=0.2.0,<0.3.0, installed: 0.2.1]
    - botocore [required: >=1.12.36,<2.0.0, installed: 1.12.183]
      - docutils [required: >=0.10, installed: 0.14]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.0]
        - six [required: >=1.5, installed: 1.12.0]
      - urllib3 [required: >=1.20,<1.26, installed: 1.25.3]
chalice==1.9.0
  - attrs [required: >=17.4.0,<20.0.0, installed: 19.1.0]
  - botocore [required: >=1.12.86,<2.0.0, installed: 1.12.183]
    - docutils [required: >=0.10, installed: 0.14]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - urllib3 [required: >=1.20,<1.26, installed: 1.25.3]
  - click [required: >=6.6,<7.0, installed: 6.7]
  - enum-compat [required: >=0.0.2, installed: 0.0.2]
  - jmespath [required: >=0.9.3,<1.0.0, installed: 0.9.4]
  - pip [required: >=9,<=19.2, installed: 18.0]
  - setuptools [required: Any, installed: 40.6.2]
  - six [required: >=1.10.0,<2.0.0, installed: 1.12.0]
  - typing [required: ==3.6.4, installed: 3.6.4]
  - wheel [required: Any, installed: 0.33.4]
csv-to-sqlite==2.0.0
  - click [required: Any, installed: 6.7]
dgl-contacts==0.0.1
dgl-obj-store==0.0.1
httpie==1.0.2
  - Pygments [required: >=2.1.3, installed: 2.4.2]
  - requests [required: >=2.18.4, installed: 2.22.0]
    - certifi [required: >=2017.4.17, installed: 2019.6.16]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.3]
pydocstyle==3.0.0
  - six [required: Any, installed: 1.12.0]
  - snowballstemmer [required: Any, installed: 1.9.0]
pyflakes==2.1.1
pylint==2.3.1
  - astroid [required: >=2.2.0,<3, installed: 2.2.5]
    - lazy-object-proxy [required: Any, installed: 1.4.1]
    - six [required: Any, installed: 1.12.0]
    - typed-ast [required: >=1.3.0, installed: 1.4.0]
    - wrapt [required: Any, installed: 1.11.2]
  - isort [required: >=4.2.5,<5, installed: 4.3.21]
  - mccabe [required: >=0.6,<0.7, installed: 0.6.1]
python-language-server==0.27.0
  - future [required: >=0.14.0, installed: 0.17.1]
  - jedi [required: >=0.13.2,<0.14, installed: 0.13.3]
    - parso [required: >=0.3.0, installed: 0.5.0]
  - pluggy [required: Any, installed: 0.12.0]
    - importlib-metadata [required: >=0.12, installed: 0.18]
      - zipp [required: >=0.5, installed: 0.5.1]
  - python-jsonrpc-server [required: >=0.1.0, installed: 0.2.0]
    - future [required: >=0.14.0, installed: 0.17.1]
rope==0.14.0
toml==0.10.0
yapf==0.27.0

**Code**
++++++++++++++++++++++++++++++++++++++++++++++++++++++
```python
from chalice import Chalice
from chalice import BadRequestError, Response

import json

app = Chalice(app_name='dgl-form-processor')
app.debug = True


@app.route('/')
def index():
    rqst = app.current_request.to_dict()

    return Response(
                body=json.dumps(rqst),
                status_code=200,
                headers={'Content-Type': 'text/plain'})

```
**Console**
+++++++++++++++++++++++++++++++++++++++++++++++++++
(chalice-projects-iFvGfrMz) (xenial)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/dgl-form-processor$ chalice deploy
Creating deployment package.
Updating policy for IAM role: dgl-form-processor-dev
Updating lambda function: dgl-form-processor-dev
Updating rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:762915485767:function:dgl-form-processor-dev
  - Rest API URL: https://9dqf6hk7v7.execute-api.us-east-1.amazonaws.com/api/
(chalice-projects-iFvGfrMz) (xenial)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/dgl-form-processor$ chalice url
https://9dqf6hk7v7.execute-api.us-east-1.amazonaws.com/api/
(chalice-projects-iFvGfrMz) (xenial)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/dgl-form-processor$ http https://9dqf6hk7v7.execute-api.us-east-1.amazonaws.com/api/?name=Fred;phone=111-222-3333;fax=222-333-4444
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 1570
Content-Type: text/plain
Date: Sun, 07 Jul 2019 23:44:04 GMT
Via: 1.1 ee7de448a69af99596218caa2e83aa99.cloudfront.net (CloudFront)
X-Amz-Cf-Id: HCd3sCHC9ttmSCY7q6S1qSvCuA4lobIELeVyFqx6gv7lGLcU8721Uw==
X-Amz-Cf-Pop: ATL51
X-Amzn-Trace-Id: Root=1-5d2283c4-3cd72ab60485c03baa782de7;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: cemGsH7hoAMFUPQ=
x-amzn-RequestId: 1a974cf5-a111-11e9-af8c-c90b15279ad4

{
    "context": {
        "accountId": "762915485767",
        "apiId": "9dqf6hk7v7",
        "domainName": "9dqf6hk7v7.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "9dqf6hk7v7",
        "extendedRequestId": "cemGsH7hoAMFUPQ=",
        "httpMethod": "GET",
        "identity": {
            "accessKey": null,
            "accountId": null,
            "caller": null,
            "cognitoAuthenticationProvider": null,
            "cognitoAuthenticationType": null,
            "cognitoIdentityId": null,
            "cognitoIdentityPoolId": null,
            "principalOrgId": null,
            "sourceIp": "24.125.66.56",
            "user": null,
            "userAgent": "HTTPie/1.0.2",
            "userArn": null
        },
        "path": "/api/",
        "protocol": "HTTP/1.1",
        "requestId": "1a974cf5-a111-11e9-af8c-c90b15279ad4",
        "requestTime": "07/Jul/2019:23:44:04 +0000",
        "requestTimeEpoch": 1562543044415,
        "resourceId": "azi4eu94ja",
        "resourcePath": "/",
        "stage": "api"
    },
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "cloudfront-forwarded-proto": "https",
        "cloudfront-is-desktop-viewer": "true",
        "cloudfront-is-mobile-viewer": "false",
        "cloudfront-is-smarttv-viewer": "false",
        "cloudfront-is-tablet-viewer": "false",
        "cloudfront-viewer-country": "US",
        "host": "9dqf6hk7v7.execute-api.us-east-1.amazonaws.com",
        "user-agent": "HTTPie/1.0.2",
        "via": "1.1 ee7de448a69af99596218caa2e83aa99.cloudfront.net (CloudFront)",
        "x-amz-cf-id": "eMeOCHVifOpUxWSOJPftRetztx76p1keDpzQoZ65BegYUZuIlaxb7Q==",
        "x-amzn-trace-id": "Root=1-5d2283c4-3cd72ab60485c03baa782de7",
        "x-forwarded-for": "24.125.66.56, 52.46.18.77",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https"
    },
    "method": "GET",
    "query_params": {
        "name": "Fred"
    },
    "stage_vars": null,
    "uri_params": null
}

(chalice-projects-iFvGfrMz) (xenial)les@localhost:~/dgl-home/dglEnvironments/chalice-projects/dgl-form-processor$

**Comment by stealthycoin** [comment]
Yes this is unfortunate behavior but we can't exactly fix it in this major version. API Gateway originally only surfaced the only the last of each parameter. When they released support for multiple parameters, we added the MultiDict which allows for access to multiple values for the same key. However we have to preserve backwards compatibility, so when serializing it still does so as if there were only the last values in each key, otherwise this would break people's existing code. To work around this you would have to get the values out yourself, using the new getlist API. Likely when we do an update when we break backwards compatibility we will re-address this and make the interface easier to use.

Something like this would be required for now.
```python
@app.route('/')
def index():
    request = app.current_request
    serialized = request.to_dict()
    serialized['query_params'] = {
        k: request.query_params.getlist(k) for k
        in request.query_params.keys()
    }

    return Response(
                body=json.dumps(serialized),
                status_code=200,
                headers={'Content-Type': 'text/plain'})
```

This is as good a place as any to track a feature request to make this easier. Marking as such.

**Comment by lesatdgl** [comment]
Works for me. Thanks
