### ISSUE TITLE
Use CodeDeploy with chalice

### ISSUE THREAD

**Issue by ksharma16** [aws/chalice#1168]
Hi,

I am trying to setup CICD pipeline for my chalice project. So far I have followed the steps in https://chalice-workshop.readthedocs.io/en/latest/todo-app/part2/02-pipeline.html , but need CodeDeploy to grab the transformed.yml file generated by "aws cloudformation package" command and deploy to my beta stack. Is there a way to do that ?

As an alternative I could have run "chalice deploy" command in the CodeBuild step and that would do the above in a single step. However, I would like to leverage CodeDeploy's rollback mechanism and therefore looking for a mechanism to separate build from deploy step.

**Comment by stealthycoin** [comment]
The chalice generated pipeline should do that for you. From a pipeline I just generated witht he most recent version:
```
          {
            "Name": "Beta",
            "Actions": [
              {
                "ActionTypeId": {
                  "Category": "Deploy",
                  "Owner": "AWS",
                  "Version": 1,
                  "Provider": "CloudFormation"
                },
                "InputArtifacts": [
                  {
                    "Name": "CompiledCFNTemplate"
                  }
                ],
                "Name": "CreateBetaChangeSet",
                "Configuration": {
                  "ActionMode": "CHANGE_SET_REPLACE",
                  "ChangeSetName": {
                    "Fn::Sub": "${ApplicationName}ChangeSet"
                  },
                  "RoleArn": {
                    "Fn::GetAtt": "CFNDeployRole.Arn"
                  },
                  "Capabilities": "CAPABILITY_IAM",
                  "StackName": {
                    "Fn::Sub": "${ApplicationName}BetaStack"
                  },
                  "TemplatePath": "CompiledCFNTemplate::transformed.yaml"
                },
                "RunOrder": 1
              },
```

TemplatePath: points to the transformed.yaml as the file to deploy.
