### ISSUE TITLE
minimumCompressionSize is not applied until API Gateway stage is deployed

### ISSUE THREAD

**Issue by topu** [aws/chalice#1171]
I've been trying out `minimumCompressionSize` feature and it doesn't seem to work until I manually, e.g. in AWS Console, deploy API gateway stage.

According to [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html), API Gateway stage needs to be deployed after `minimumCompressionSize` is set: 
> After the compression is enabled and the API is deployed, the client can receive an API response with a compressed payload if it specifies an appropriate Accept-Encoding header in the method request.

Looking at the [code](https://github.com/aws/chalice/blob/master/chalice/deploy/planner.py#L768), it's set in `shared_plan_epilogue` which runs after `deploy_rest_api` call.

**Comment by jamesls** [comment]
Fixed via https://github.com/aws/chalice/pull/1160
