### ISSUE TITLE
How to configure AWS Region

### ISSUE THREAD

**Issue by mrdavidhanson** [aws/chalice#1175]
Is there a way to instruct Chalice what AWS Region should be used for deployment without having to modify the default profile on the machine?

Thanks.

**Comment by kapilt** [comment]
the AWS sdks respect environment variables, ie. `export AWS_DEFAULT_REGION=us-west-2` suffices

**Comment by dstufft** [comment]
As @kapilt mentioned, all of the SDKs respect environment variables, so you can set your region using that.

**Comment by MartijnHarmenzon** [comment]
Where and when would you set this? At the top of the app.py? Or somewhere within config?
