### ISSUE TITLE
Error shows up twice in Cloudwatch Logs

### ISSUE THREAD

**Issue by subssn21** [aws/chalice#1183]
When you have an exception the exception prints twice in the cloudwatch logs.

Looking at the exception handler in app.py lines 1063-1080, the exception is clearly logged twice. Once on line 1065 and again on line 1075. Can we remove one of these? Let me know which one would be preferable to get rid of and I will happily make the pull request.

        except Exception:
            headers = {}
            self.log.error("Caught exception for %s", view_function,
                           exc_info=True)
            if self.debug:
                # If the user has turned on debug mode,
                # we'll let the original exception propagate so
                # they get more information about what went wrong.
                stack_trace = ''.join(traceback.format_exc())
                body = stack_trace
                headers['Content-Type'] = 'text/plain'
            else:
                self.log.error("Internal Error for %s", view_function,
                               exc_info=True)
                body = {'Code': 'InternalServerError',
                        'Message': 'An internal server error occurred.'}
            response = Response(body=body, headers=headers, status_code=500)
        return response

**Comment by kapilt** [comment]
yeah that's odd the second log there looks like it should be removed.

**Comment by kyleknap** [comment]
@subssn21 Thanks for catching this. Let's remove the second log message. In general, we should be logging internal errors. The `debug` property only really returns tracebacks to users in the HTTP response and sets the logger to capture `DEBUG` level messages, which does not really apply to this one because it is an `ERROR` level one. Let us know if you send a PR to fix it and we'll take a look.

**Comment by kyleknap** [comment]
Found the PR for this enhancement: https://github.com/aws/chalice/pull/1187. Just needs a test update and we should be good to merge it.

**Comment by subssn21** [comment]
This was merged into master on 7/25/2019 PR#1187
