### ISSUE TITLE
cors=True fails when app.api.binary_types = ['*/*']

### ISSUE THREAD

**Issue by phubbard** [aws/chalice#1185]
I have a Chalice endpoint that accepts a binary file upload and returns an image. I'd like to enable cors but doing so doesn't work, and from 

https://stackoverflow.com/questions/56204562/chalice-cors-true-annotation-not-working

others have encountered the same bug. The combination to replicate it is something like
app.api.binary_types = ['*/*']
@app.route('/{param}', methods=['POST'], content_types=['application/octet-stream'], cors=True)

**Comment by kyleknap** [comment]
I'm trying to dig more into this. I so far have not been able to reproduce. Here is what I have tried...

Using this chalice version:
```
$ chalice --version
chalice 1.9.1, python 2.7.10, darwin 17.7.0
```
I wrote the following `app.py`:
```python
from chalice import Chalice
from chalice import Response

app = Chalice(app_name='cors')
app.api.binary_types = ['*/*']


@app.route('/echo-image', methods=['POST'],
           content_types=['application/octet-stream'], cors=True)
def echo_image():
    raw_request_body = app.current_request.raw_body
    return Response(body=raw_request_body,
                    status_code=200,
                    headers={'Content-Type': 'application/octet-stream'})
```

Then after running `chalice deploy`, I tried to send a request to the app using HTTPie:
```
$ http POST $(chalice url)echo-image Content-Type:application/octet-stream --download --output sample-echo.jpg < sample.jpg
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 501125
Content-Type: application/octet-stream
Date: Wed, 31 Jul 2019 21:20:32 GMT
Via: 1.1 f90d3247f95b3d929916918b14de82bc.cloudfront.net (CloudFront)
X-Amz-Cf-Id: s7gzlBBOzP24rGbhG0TGb2cCz7cAhhO8l0wJYIXVKveH0tiu5KgnSA==
X-Amz-Cf-Pop: HIO51-C1
X-Amzn-Trace-Id: Root=1-5d42061f-3819e5afa5d2a1ce9de23522;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: dtXk7E81vHcFl-g=
x-amzn-RequestId: 06da5e3d-b3d9-11e9-9e97-bb2dc6e9f32c

Downloading 489.38 kB to "sample-echo.jpg"
Done. 489.38 kB in 0.19907s (2.40 MB/s)
```
And based on the response it did have the correct CORS headers. Could you either take a look at my app and tell me what may be different than what you are doing or share a minimal `app.py` that takes to reproduce the issue?

**Comment by phubbard** [comment]
Go ahead and close it as user error. We have it working. Apologies for the false alarm.
