### ISSUE TITLE
Policy Analyzer fails to follow function calls inside Chalice app

### ISSUE THREAD

**Issue by OverlordQ** [aws/chalice#1190]
```
    def test_nested_call_chalice():
>       assert chalice_aws_calls("""\
            from chalice import Chalice
            import boto3
            app = Chalice(app_name='testapp')
            sdb = boto3.client('sdb')

            @app.route('/')
            def something():
              sdb.list_domains()
              nested_func()

            def nested_func():
              sdb.select()
       """) == {'sdb': set(['select','list_domains'])}
E       AssertionError: assert {'sdb': {'list_domains'}} == {'sdb': {'list_domains', 'select'}}
E         Differing items:
E         {'sdb': {'list_domains'}} != {'sdb': {'list_domains', 'select'}}
E         Use -v to get the full diff
```

Instead of putting all the business logic directly in the route definition, I've abstracted it out into various helper functions. The policy analyzer misses all of it and so thinks a blank policy is good enough for the role. This was the smallest test case to reproduce I could find.

**Comment by OverlordQ** [comment]
While similar to #810 this blocks even keeping the code in the same file.

**Comment by kyleknap** [comment]
This specific issue in the code sample looks similar to this issue I hit: https://github.com/aws/chalice/issues/692#issuecomment-360266110 where if the helper function is declared at the end of the `app.py`, it will not get picked up. So if I update your app to be:
```python
from chalice import Chalice
import boto3
app = Chalice(app_name='testapp')
sdb = boto3.client('sdb')


def nested_func():
    sdb.select()

@app.route('/')
def something():
    sdb.list_domains()
    nested_func()
```

It's able to pick up the `select()` call:
```
$ chalice gen-policy
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "sdb:ListDomains",
        "sdb:Select"
      ],
      "Resource": [
        "*"
      ],
      "Effect": "Allow",
      "Sid": "199188f060664781a66787fb16466272"
    }
  ]
}
```
I think I'd prefer to track this issue in the originally referenced GitHub issue. Thoughts?

**Comment by OverlordQ** [comment]
It does appear to be a dupe of #692
