### ISSUE TITLE
support custom domain names

### ISSUE THREAD

**Issue by kapilt** [aws/chalice#1194]
applies to edge and regional api gateway endpoints.

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-regional-api-custom-domain-create.html

**Comment by kyleknap** [comment]
We should definitely look into supporting this.

**Comment by CircleOnCircles** [comment]
What is the workaround for the current moment?

**Comment by royby-cyberark** [comment]
I would also love to know if there is a workaround for this at the moment. thanks!

**Comment by buzzlaker** [comment]
I am about to start tackling this problem, any timeline on this feature?
