### ISSUE TITLE
chalice deploy import error, with layers

### ISSUE THREAD

**Issue by dzhang** [aws/chalice#1200]
Hi

I got module not found error when deploying, I specify the function to use layers
`{
  "version": "2.0",
  "app_name": "myapp",
  "stages": {
    "dev": {
      "api_gateway_stage": "api",
      "manage_iam_role": false,
      "iam_role_arn": "arn",
      "lambda_functions": {
        "myfunc": {
          "layers": ["layer1", "layer2"]
        }
      }
    }
  },
}`

I did not specify the module in requirements.txt since I have the layers specified. I probably missing something, could not find much docs on layers for chalice.

Thanks
Dong

**Comment by jamesls** [comment]
You've got the syntax right.  If you're using your own layer, I'd double check you've got the layer built correctly.  I'll put together some docs for this.

**Comment by markalexander** [comment]
I think the OP may mean they get an import error at local packaging time, rather than when invoking the lambda function.

MWE using the official AWS SciPy layer:

    chalice new-project layer-test

`app.py`:
```from chalice import Chalice
import scipy

app = Chalice(app_name='layer-test')


@app.route('/')
def index():
    return {'version': scipy.__version__}
```

`.chalice/config.json`:
```{
  "version": "2.0",
  "app_name": "layer-test",
  "stages": {
    "prod": {
      "api_gateway_stage": "api",
      "lambda_functions": {
        "api_handler": {
          "layers": [
            "arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python36-SciPy1x:2"
          ]
        }
      }
    }
  }
}
```

Leave `requirements.txt` blank and __don't__ `pip install scipy` (otherwise it will get packaged, which we don't want).  

Now do:

    chalice package --stage prod /tmp/packaged

This gives me:

    ModuleNotFoundError: No module named 'scipy'

**Comment by dzhang** [comment]
Hi
yes, that is exactly my problem, I don't have the module installed locally, since it is in the layer, was hoping chalice can just deploy it. seems I still have to install all modules locally.

Thanks
Dong

**Comment by kennymatsudo** [comment]
Hi all,

Ran into the same issue presented here but was able to work around this by wrapping my imports in a try/catch. This allowed Chalice to deploy and because my layer was defined in the config.json, my application ran successfully.

**Comment by jamesls** [comment]
There was another issue where people were running into this issue as well.  Due to how Chalice works, we have to import your `app.py` file.  A simple option would be to set some sort of environment variable you could check whenever we run any chalice CLI commands.  The main benefit would be that it's more explicit than a `try/except`.

**Comment by vrinda1410** [comment]
Hi @jamesls 
Could you please elaborate the point mentioned above
"A simple option would be to set some sort of environment variable you could check whenever we run any chalice CLI commands. "

I am looking to solve this very problem in my project and wants to explore all available options over try/catch workaround.

Thanks!

**Comment by jamesls** [comment]
I can't find the original comment (I believe it was from @stealthycoin), but whenever we run a commands like `chalice deploy/package` we could set an env var to let you know that we're only importing your app for introspection purposes, and it's not actually running on lambda.  I don't remember the name proposed, but maybe `CHALICE_CLI_MODE` or something like that.

Another option is to make better use of the `AWS_EXECUTION_ENV`, which is always set when you run in Lambda, but right now we also set that var when we instantiate the app object.  They'd both work the same though, something like:

```
if 'AWS_EXECUTION_ENV' in os.environ:
    # Running in Lambda, need to import modules.
    import package_from_layer
```
