### ISSUE TITLE
Chalice intentionally prevents use of LambdaContext.client_context

### ISSUE THREAD

**Issue by rkeiii** [aws/chalice#1202]
So I'm not certain because I'm not real familiar with the Chalice codebase but it looks like Chalice is intentionally not allowing use of the special LambdaContext.client_context field which is supported by the Lambda API and also by normal (non-Chalice) Python Lambda functions.

On first glance it looks like this is happening in chalice/local.py in LambdaContext at line 260 when they call self.client_context = None.

The comments in chalice/local.py at lines 267-272 seem to indicate the authors thought it appropriate to disregard any potential client_context. I disagree with this assessment especially since these days Chalice portrays itself as a general purpose solution for Python Lambdas that is not particular to being using in conjunction with API Gateway. Additionally LambdaContext.client_context.custom is a very handy field to be able to carry around some custom user metadata without contaminating/consuming space in the payload.

**Comment by jamesls** [comment]
I think you may be reading too much into this.  To clarify, the comment in the code is:

```
        # The last two attributes have the following comment in the
        # documentation:
        # Information about the client application and device when invoked
        # through the AWS Mobile SDK, it can be null.
        # Chalice local doens't need to set these since they are specifically
        # for the mobile SDK.
        self.identity = None
        self.client_context = None

```

For local testing (which is the module you're referencing), we didn't need it because we only support local testing for rest apis where we spin up a dev http server (so it's not possible to have `client_context` be populated).

This only matters once we support local lambda testing without rest APIs.

**Comment by rkeiii** [comment]
Hi @jamesls,

I apologize for that, I did not understand how your codebase is structured and what "local" meant (probably should have). So my real question then is, do you know of any particular reason why a Chalice managed Lambda invoked with a client context provided by the caller would not receive that client context or convert the client context into a None type? I should expect LambdaContext.client_context to be received if a caller provides it and I'm probably dong something dumb, right?

I used the following to encode the data prior to calling lambda.invoke()
```
    # assemble context to send along to ImageProcessingWorkflow
    client_context_dict = {
        "custom": {
            "originating_request": {
                "api_key_id": app.current_request.context["identity"]["apiKeyId"],
                "aws_request_id": app.current_request.context["requestId"]
            }
        }
    }
    # convert the dict to a json string and then encode it as UTF-8 bytes
    client_context = json.dumps(client_context_dict).encode("utf-8")
    # take the UTF-8 encoded bytes and base64 encode them
    client_context = base64.b64encode(client_context).decode("utf-8")

    lambda_output = awslambda.invoke(
        FunctionName=os.environ["PROCESS_IMAGE_FUNC"],
        InvocationType="RequestResponse",
        Payload=payload,
        ClientContext=client_context
    )
```

Thanks for any help you can provide and I really like the project/framework. We're using it on a project to help increase the accessibility of core STEM material for the blind/print disabled.

Cheers,
Ron

**Comment by rkeiii** [comment]
Also here's what I'm using:
```
rkeiii@ate:~$ chalice --version
chalice 1.9.1, python 3.6.8, linux 4.15.0-52-generic
rkeiii@ate:~$ 
```

**Comment by rkeiii** [comment]
It looks like I'm running into an undocumented part of how the client context is handled by AWS. Apparently if you invoke a lambda asynchronously the client context gets lost.

https://github.com/aws/aws-sdk-js/issues/1388
