### ISSUE TITLE
Return multiple Set-Cookie headers

### ISSUE THREAD

**Issue by dmicic** [aws/chalice#1205]
I am trying to return multiple Set-Cookie statements in my header. However, it doesn't work given that key within the dictionary is the same for both cookies and therefore, only the 2nd Set-Cookie is been returned resp. actually been added to the dict.

```js
"headers": {
  "Set-Cookie": "refreshToken=myToken1; httpOnly; secure; path=/auth/refresh/;",
  "Set-Cookie": "accessToken=myToken;2 httpOnly; secure; path=/;"
 }
```

Is there solution to this problem in chalice?

**Comment by markalexander** [comment]
I'm not sure that API Gateway supports this, even if Chalice could, per https://forums.aws.amazon.com/thread.jspa?threadID=205782

**Comment by dmicic** [comment]
@markalexander it is supported: https://forums.aws.amazon.com/ann.jspa?annID=6185

**Comment by dmicic** [comment]
I am currently using one of those workarounds. But would be good to align chalice with the capabilities of the API Gateway.

**Comment by stealthycoin** [comment]
Ah, ill mark as feature request.

**Comment by jamesls** [comment]
Supported via #1214
