### ISSUE TITLE
About request raw query string

### ISSUE THREAD

**Issue by cftang0827** [aws/chalice#1213]
Hi there, I had a question about raw query string, since we can get the query parameter dictionary data, is there any way that we can get the "raw URL" ?

Example
```
@app.route('/hellos')
def index():
    req = app.current_request
    a = int(req.query_params["a"])
    b = int(req.query_params["b"])
    return {"hello": a - b}
```

if we use Postman to GET `http://localhost/hellos/?a=2&b=3`, we can use `query_params` to get `a` and `b` separately, but I am wondering is there any way that we can get the raw URL? 

Take Flask as an example, https://flask.palletsprojects.com/en/1.0.x/api/#flask.Request.query_string

Thanks. 👯‍♂

**Comment by stealthycoin** [comment]
From my reading of the API Gateway documentation it seems that value isn't available. The closest I can see is in the context you have access to the path and resourcePath properties. [Documented here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html).

```python
import json

from chalice import Chalice

app = Chalice(app_name='example')


@app.route('/foo/bar')
def example():
    return json.dumps(app.current_request.context, indent=4)

```

```
$ curl "$(chalice url)foo/bar?key=value"
{
    "resourceId": "id",
    "resourcePath": "/foo/bar",
    "httpMethod": "GET",
    "extendedRequestId": "....",
    "requestTime": "15/Aug/2019:16:42:38 +0000",
    "path": "/api/foo/bar",
    "accountId": ".......",
    "protocol": "HTTP/1.1",
    "stage": "api",
    "domainPrefix": ".......",
    "requestTimeEpoch": 1565887358768,
    "requestId": "..............",
    "identity": {
        "cognitoIdentityPoolId": null,
        "accountId": null,
        "cognitoIdentityId": null,
        "caller": null,
        "sourceIp": "xx.xx.xx.xx",
        "principalOrgId": null,
        "accessKey": null,
        "cognitoAuthenticationType": null,
        "cognitoAuthenticationProvider": null,
        "userArn": null,
        "userAgent": "curl/7.54.0",
        "user": null
    },
    "domainName": "id.execute-api.region.amazonaws.com",
    "apiId": "id"
}
```

The closest things I see are `resourcePath`, and `path`.
