### ISSUE TITLE
IAM settings have no effect

### ISSUE THREAD

**Issue by johntmyers** [aws/chalice#1221]
The keys: `manage_iam_role` and `iam_role_arn` seem to have no effect.

Issue: I manually edit my role on AWS then re-deploy, my role is overwritten back to where it was.

Only adding `manage_iam_role` key does NOT result in an error like the documents specify (since `iam_role_arn` should also be required if the former is set to "false").

Version 1.10.

**Comment by yehuda-elementryx** [comment]
Hi John,

I remember hitting this issue a while back and being incredibly confused.

For me it was that I had enclosed false in quotation marks as in: `"manage_iam_role": "false"`. The parser evaluates this as a non empty string with a truthy value. I was able to fix this issue by setting 
` "manage_iam_role": false`.

**Comment by johntmyers** [comment]
Ugh, yes that was it thank you. Unfortunately, it cannot delete the roll without manually removing policies from the existing role anyway.
