### ISSUE TITLE
[Question] Is there a way to add a Mapping Template to an Integration Request for a Resource when running `chalice local`?

### ISSUE THREAD

**Issue by nservidio** [aws/chalice#1222]
Hi, newb here,

I have 2 questions:

It looks like chalice once generated API Gateways that used VTL mappings: https://github.com/aws/chalice/issues/226. Is there a way to re-enable this functionality in the current version?

Also, is there a way to provide local VTL mappings when running `chalice local`? I asked a similar question on the aws-sam-cli repo, but the answer was "no".
https://github.com/awslabs/aws-sam-cli/issues/1353

Please let me know. Thank you for your time!

**Comment by jamesls** [comment]
Hi, no this is currently not possible.  The VTL mapping ended up being challenging to keep up to date whenever API gateway added new functionality.

Let me know if you have any more questions.
