### ISSUE TITLE
How to translate HTTPIE into jQuery / ajax ?

### ISSUE THREAD

**Issue by lesatdgl** [aws/chalice#1226]
HTTPIE has defaults, assumptions, ... that control how the request is made

jQuery/ajax - to put in my /js in my webpage - has it's own set ...

So, just looking at Tutorial: URL Parameters - what's the jquery/ajax incantation to do what's being done with http https://endpoint/api/cities/seattle
Has someone worked this out? And written it down?

If not, I will and contribute it to the cause

**Comment by lesatdgl** [comment]
What one must "say" to HTTPIE is different than what one must "say" to whatever jScript lib is used to issue the http request and handle the response - especially since HTTPIE doesn't handle anything

Therefore, showing examples using HTTPIE , is less useful than it could be - not a criticism!

I'm trying to get to where I can do it and then show others how to use Chalice-built lambdas from webpages

Make sense?

Les Dunaway
770-490-7546

**Comment by arhea** [comment]
I took a stab at adding a section to the documentation that talks about making a call from the browser to your local API endpoints. @lesatdgl, let me know if that helps. I used the new `fetch` API in the browser rather than jQuery. As @stealthycoin alluded to it is pretty simple.

```javascript
const response = await fetch('http://localhost:8000/') // or whatever your API URL is
const json = await response.json();
console.log(json);
// this should print "{"hello": "world"}" to the console
```

**Comment by lesatdgl** [comment]
I'm assuming that you are referring to this section:
```
$ http https://qxea58oupc.execute-api.us-west-2.amazonaws.com/api/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 18
Content-Type: application/json
Date: Mon, 30 May 2016 17:55:50 GMT
X-Cache: Miss from cloudfront

{
    "hello": "world"
}
```
 - If so, OK, cool!

 - Now, the code you show appears to be javascript, so it can't by typed into the console, the way httpie command is - so how is that done? I'd expect to put it in a webpage??
 - If so, what's the  necessary <script statement(s) to make fetch available?

 - Here's the lines I have in a Bootstrap template:
```
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
```
 - Given all that, the question still remains - how do I get the response into the html ?
Is the response actually a json object or is it just formatted that way.

 - My thought is to take your code and wrap it in a script:
``` <!-- your code here -->
<script type="text/javascript">

</script>
```
 - Is that what you had in mind?

 - The returned text might get displayed 
- however, that's not really useful 
- I think there's a line of two of code needed to get the response into a var that can be properly styled
 - The issue I'm seeing is the lack of clear docs about what is expected by lambda and returned by lambda - a problem not confined to Chalice. 
 - I've read through a number of examples on this subject and found that they all end with "and the magic happens here" - I suspect there's a lot of folks who'd like to see actual production level examples
    - For example, the Bootstrap 4.1.3 basic template, with a button and a <script added to display "Hello World" nicely formatted in the font specified in the template - 
 - Printing Hello World isn't a useful example
 - However, a few dozen more words about even that would be useful
    - What does the response object look like, really? The idea that I should crawl through Chrome tool to learn that does't make me very interested 
       - If fact, it leads me to suspect that the author of the example doesn't know
    - What must be, should be , could be in the request object? Where is all that documented?

- Perhaps I have unreasonable expectations? I started building systems in 1965, when a computer was the size of an 18-wheeler, ran on kerosene and had waaaaayyy less power than the processor in my Nest thermostat
- However, the manuals that came with the system told how it worked - maybe I'm spoiled

 - I appreciate your response and look forward to more dialog, leading to a useful example for the docs.

**Comment by arhea** [comment]
@lesatdgl So you want to make a request then register a pop up with the data returned?

If so, it's import to keep in mind the contract of the API. The REST API is the contract between your web page and your backend. That API contract states that when you call `http://localhost:8080/` it will return some JSON called as such.

```json
{
    "hello": "world"
}
```

How that JSON is rendered, whether it is with Lambda or a Server, it doesn't matter. Therefore, I think the docs you are looking for exist. Chalice will help you build a backend that returns JSON which is one side of your contract. How you consume that contract depends on your frontend libraries. It is not feasible for us to write documentation for every library out there (jQuery, React, Vue.js, Ember.js, etc.)

The flow of your request will look something like this:

Browser, Phone, or other Client ---http request---> API Gateway ---trigger lambda--->lambda runs and generates json --- response to API Gateway ---> API Gateway ---API Gateway sends response to client---> Browser, Phone, or other Client. The client doesn't care how that JSON is rendered. 

Fetch is a native browser API in modern browsers (there are many ways of doing this as stated in this [StackOverflow](https://stackoverflow.com/questions/36975619/how-to-call-a-rest-web-service-api-from-javascript)). This replaces the need for jQuery Ajax like we used to use years ago.  The good news, you don't need all of those dependencies which will slow down your load time. I have included two examples below. What you do with the below examples can apply to any JSON based API.

Native Browser APIs:
```html
<button onClick="doSomething()">Click Me</button>
  
<div id="repsonse">Original</div>
<!-- After clicking the button the value would be "{ "hello": "world" }" -->
  
<script type="text/javascript">
    
    function doSomething() {
      fetch("http://localhost:8080").then(function(data) {
         var elem = document.getElementById("repsonse")
         elem.innerHTML = JSON.stringify(elem);
      });
    }
 </script>

jQuery APIs:
```html
<button onClick="doSomething()">Click Me</button>
  
<div id="repsonse">Original</div>
<!-- After clicking the button the value would be "{ "hello": "world" }" -->
  
<script type="text/javascript">
    
    function doSomething() {
      $.getJSON("http://localhost:8080", function(data) {
         var elem = document.getElementById("repsonse")
         elem.innerHTML = JSON.stringify(elem);
      });
    }
 </script>
```

I recommend doing more research on building REST APIs. REST APIs allow front end developers to program against the API Specification and backend developers to do the same. Chalice helps backend developers do just this. It doesn't dictate how the frontend should be architected.

**Comment by lesatdgl** [comment]
Thanks for all your effort and you get to the real point of all this:
```
How that JSON is rendered, whether it is with Lambda or a Server, it doesn't matter. 
Therefore, I think the docs you are looking for exist. 
Chalice will help you build a backend that returns JSON which is one side of your contract. 
How you consume that contract depends on your frontend libraries. 
It is not feasible for us to write documentation for every library out there (jQuery, React, Vue.js, Ember.js, etc.)
```
 - "It is not feasible for us to write documentation for every library out there (jQuery, React, Vue.js, Ember.js, etc.)" - RIGHT! 
 - That's why we have documentation of the interface - if there was a clear, complete and accurate documentation of the request and response objects that a Chalice lambda consumes/produces, we wouldn't be having this discussion - it would be language agnostic
 - You state "Therefore, I think the docs you are looking for exist" - you think or hope or believe?
 - I've spent a lot of time crawling through AWS docs and I haven't found them 
    - if you know where they are, please share.
    - One example of the inadequate docs is the "AWS Lambda Developer Guide"
       - It demonstrates
1. Why Chalice can be so valuable - by dragging one though cmdline hell to create a lambda
2. How an api should NOT be documented - by publishing console logs with comments
3. When I found a section, toward the back, labeled "Lambda" and a sub section labeled "Api", I thought "OH BOY! I found it" - however, what I found was a list of all the things one can say to the AWS cloud ABOUT a lambda and nothing about what one can say TO a lambda
 - Example: your code above 
```
var elem = document.getElementById("repsonse")
         elem.innerHTML = JSON.stringify(elem);
```
will fail if the lambda throws an exception - because, despite docs [ https://amzn.to/2lTHkqH] to the contrary, the error comes back as text/plain, not json 
 - I'm feeling that 1) I asked the wrong question and 2) that I have unexpected expectations
1. The proper question should have been "Where is the doc of the request expected by a [Chalice] lambda? And, where is the doc of the response returned; in the success and fail and exception cases?
2. How is someone new to Chalice expected to learn the answers to 1. above
- As you point out, this is, ostensibly, a REST API - that should mean that I could write code to use it with no knowledge of Chalice, lambda, ...
   - that is, a web developer should be able to write an html/jscript web app to utilize functions made available by lambdas, with no information beyond the querystring expected
    - this assumes, of course, that the perpetrator of the lambda implemented a REST API - not some approximation of it based on limited understanding
 - I saw / see Chalice as valuable because it reduced the aggravation of creating lambdas through other available methods. However, if there's an expectation that users of Chalice are willing to read all the Chalice code in order to use it, then that value goes away
 - What are your thoughts about how to discover how lambdas are supposed to work / behave / fail?
 - I'm starting to believe that this isn't the right forum for that discovery process????
   - A part of that process would be to understand how a Chalice-created lambda differs from one created by the other available methods - I don't know if the above mentioned return of a thrown exception is one such or not?

**Comment by arhea** [comment]
@lesatdgl I apologize for the confusion, this is all really good feedback! Can you share a little bit more about what you are trying to build?

For a

To your question about error handling; The docs in that link are referring to sending logs to CloudWatch not the user (or client), this admittedly is confusing. Chalice doesn't dictate how you handle errors. Some frameworks like Flask can define global error handlers but I like to handle errors on my own when building REST APIs. I have included an example below, that I have extended from [this section of the docs](https://github.com/aws/chalice/blob/master/docs/source/api.rst#response) how I would solve this problem:

```python
from chalice import Chalice, Response
# this is just an example import, this would be your application code
from myapp.db import find_user, UserNotFoundException 

# import the logging lbirary
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

app = Chalice(app_name='myapp')

@app.route('/user/{id}')
def user_handler():
    request = app.current_request
   
    try:
          # this could be calling the database or another api, just an example
          user = find_user(request.uri_params.id)
          
          # when we find the user return 200 (success) and convert the user to a dict
          return Response(body=user.to_dict(),
                    status_code=200,
                    headers={'Content-Type': 'application/json'})
    catch UserNotFoundException:
           return Response(body={ 'message': 'User not found!' },
                    status_code=404,
                    headers={'Content-Type': 'application/json'})
    catch Exception as err:
           # log the unknown error to cloudwatch so we can debug later
           logger.error(There was an error while searching for a user.')
           logger.error(str(err))
           # return a friendly error to the API client so that we don't expose any sensitive info
           return Response(body={ 'message': 'An unknown error occurred.' },
                    status_code=500,
                    headers={'Content-Type': 'application/json'})
```

Then in my frontend code I would do something like this:

```javascript
fetch("http://localhost:8080/user/1").then(function(data) {
  // data would be whatever the model of user data was
  // display the user information
}).catch(function(error) {
  // error would be the json returned by error handlers
  // handle the error with the client
});
```

I agree that Chalice can help you build and deploy your application faster on Lambda. Let me know if we are heading in the right direction, I want to make sure I get your questions answered! I will take a look at the documentation and I see how I can make it easier to follow.

**Comment by lesatdgl** [comment]
#### OK, as to what I'm doing: 
1. building a bunch of lambdas to handle requests from webpages 
  a. Think of landing pages and info requests
2. also building one lambda to handle a bunch of requests from webpages
  a. think of a single lambda handling a set of 3-4 kinds of requests  - info, register, ...

#### I feel silly, because I haven't looked at the Response, ... in the Chalice docs 
- I've been looking in the lambda docs - oh well, if you can't handle shame, you shouldn't mess with computers ;-)

 - you've answered a lot of my questions about the what's coming back - your answer seems to be whatever I want it to be
 - all the examples showed no such and I have been trying to find out what's expected
 - I know how to handle exceptions, I didn't know I needed to or what to expect to need to handle
### I want proper docs - where "proper" is a full, official, supported, blessed, guaranteed, ... definition of the required request object and the returned response object - for the success, failure and exception cases
 - where are such? The only object documented on the AWS sites is the context object - the one of least interest. Please do not respond - "it's just normal REST API request response" no, it's not and besides, there's no such thing 
- what I need it the definition of how AWS Lambda implements REST API request/response

### Thanks very much for this conversation. I"ll crawl through the parts of the docs you mentioned and then mess with it a bit

**Comment by jamesls** [comment]
Following up on old issue, this is all great discussion.  I'm going to go ahead and close out this issue, and track the doc updates over in #1254.  Thanks everyone!
