### ISSUE TITLE
Cannot register blueprints

### ISSUE THREAD

**Issue by mims92** [aws/chalice#1227]
Hello,

I'm trying to use blueprints. I'm following the tutorial but I get:

`ImportError: cannot import name 'myitem' from 'item.item' (/root/projects/lambda/main/item/item.py)`.

Any idea why?

Here is the folders tree:

```
 main
    ├── account
    │   ├── .chalice
    │   ├── account.py
    │   ├── __init__.py
    │   └── requirements.txt
    ├── authentication
    │   ├── .chalice
    │   ├── authentication.py
    │   ├── __init__.py
    │   └── requirements.txt
    ├── item
    │   ├── .chalice
    │   ├── __init__.py
    │   ├── item.py
    │   └── requirements.txt
    ├── .chalice
    ├── app.py
    ├── __init__.py
    └── requirements.txt

```

Content of app.py:

```
from chalice import Chalice
from item.item import myitem

app = Chalice(app_name='main')
app.experimental_feature_flags.update([
    'BLUEPRINTS'
])

app.register_blueprint(myitem)

```

Chalice version: v1.11.0

**Comment by katouyuta** [comment]
Please rewrite import section.

-from item.item import myitem
+from chalicelib.item.item import myitem

**Comment by mims92** [comment]
Hello,

This is what I get: 
```
from chalicelib.item.item import myitem
ImportError: cannot import name 'myitem'
```

Can you provide me with a working example? I really don't understand if the filename, import name must match in some extend.

Thank you

**Comment by mims92** [comment]
Any feedback?

**Comment by mims92** [comment]
When I'm running my chalice projects, I need to launch them separately with `chalice local --port 8001`, `chalice local --port 8002` for each services, which is very cumbersome. The goal is to have one lambda per service. So my initial question should be: is this architecture a good use case for Chalice?

**Comment by mims92** [comment]
Ok ,great news: I reimplemented my code from the example and it's working.

The only thing I did wrong was on the import:
```
from chalice import Chalice
from item.item import myitem <----

app = Chalice(app_name='main')
app.experimental_feature_flags.update([
    'BLUEPRINTS'
])

app.register_blueprint(myitem)
```

So `myitem` must be the name of the Blueprint instance in the `item.py` file.
