### ISSUE TITLE
Invoke with arguments from the CLI

### ISSUE THREAD

**Issue by alexei** [aws/chalice#1229]
Is there a way to invoke a Lamdba function with arguments from the CLI?

**Comment by earle** [comment]
`aws lambda invoke --function-name my-function --payload '{ "key": "value" }'`

**Comment by alexei** [comment]
Thanks @earle! I meant using Chalice.

**Comment by kyleknap** [comment]
You can use a payload by passing it in through standard input. So using this chalice app:
```python
from chalice import Chalice

app = Chalice(app_name='debug3')

@app.lambda_function()
def invoke(event, context):
    return event
```
I can then invoke it by passing in my event payload through stdin:
```
$ echo '{"hello": "world"}' | chalice invoke -n invoke
{"hello": "world"}
```
Looking over the help command and the documentation, I really could not find the information about being able to pass the event payload through stdin other than in workshops we have built. We should definitely add that information in the docs and the `chalice invoke --help` page.

Let us know if that clears things up.

**Comment by alexei** [comment]
Thanks for the help. Yeah, I guess that should be documented.

Otoh, is it possible to implement support for args in the invoke command in the future? E.g.
```
    $ chalice invoke -n hello -p '{"hello": "world"}'
```
That looks more intuitive than piping stdin or using the AWS CLI.

**Comment by kyleknap** [comment]
@alexei Yeah I could see us adding a payload flag in the future. I actually had it in my original proposal: https://github.com/aws/chalice/issues/900 but opted to just accepting input from stdin.
