### ISSUE TITLE
Unable to deploy multiple routes

### ISSUE THREAD

**Issue by Rubyj** [aws/chalice#1233]
@kyleknap @stealthycoin @jamesls 

When I deploy a lambda function with multiple routes, my lambda console only ever shows one route.

I can not seem to get multiple functions working. I even tried with a hello world example.

```
from chalice import Chalice

app = Chalice(app_name='helloworld')


@app.route('/')
def index():
    return {'hello': 'world'}

@app.route('/test')
def second():
    return {'test': 'test'}
```

```
{
  "version": "2.0",
  "app_name": "helloworld",
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}
```

For some reason this only ever ends up with one api (the second, test, route) route in my lambda  function once its deployed using `chalice deploy --stage dev`. What am I missing?

**Comment by studio3104** [comment]
Have you tested making a request to `/test` endpoint?
Once `chalice deploy` command runs successfully, you should be able to succeed the request. (You can easily test using `chalice url` command, such like `curl $(chalice url)`)
Functions decorated by `app.route` aren't deployed as individual Lambda functions for each, even if you implement multiple numbers of endpoints.
Instead, `app` object in a single Lambda function dispatches the request. The handler of the Lambda function should be `app.app`, just check it on your console.

**Comment by Rubyj** [comment]
@studio3104 The multiple endpoints seem to exist in the aws api gateway. However, on the lambda page in the aws console, I only see one endpoint. I am not sure why the endpoints od not exist under the api gateway section on the lambda page in the aws console when deployed with chalice

![Screenshot from 2019-09-06 15-18-50](https://user-images.githubusercontent.com/4855908/64454841-05202d00-d0ba-11e9-95e1-55971db0540f.png)


I would expect there to be multiple entries for API Gateway here, but there is only one. The lambda function has two endpoints as seen above.

**Comment by studio3104** [comment]
The `API endpoint` is the endpoint root, each endpoint path should be set properly into the associated API Gateway like the following image. You can check it on API Gateway console.

![image](https://user-images.githubusercontent.com/1546363/64476575-0f7e1c00-d1cb-11e9-8a18-8d7dc46b1de6.png)
