### ISSUE TITLE
Chalice logo

### ISSUE THREAD

**Issue by studio3104** [aws/chalice#1234]
Most popular OSS projects have their logo, why don't you make kinda cool logo for Chalice as well? WDYT!?

**Comment by jamesls** [comment]
It's happening 🎉 !  There's been some delays but it's in the works.

**Comment by jamesls** [comment]
https://github.com/aws/chalice/pull/1256

**Comment by studio3104** [comment]
Awesome! Cool!!

**Comment by jamesls** [comment]
Closing out old issue.
