### ISSUE TITLE
CloudFormation deployment fails on api_gateway_stage with dashes

### ISSUE THREAD

**Issue by johntmyers** [aws/chalice#1247]
When following this tutorial:

https://chalice.readthedocs.io/en/latest/topics/cfn.html?highlight=cloudformation%20deploy#example

Make the `api_gateway_stage` something like "api-dev" and the cloudformation deploy will fail with an error like this:

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [RestAPIapi-devStage] is invalid. Logical ids must be alphanumeric.

EDIT: looks like there's a pending fix for that here: https://github.com/awslabs/serverless-application-model/issues/1002

Just wanted to make a note of this as it is not a Chalice issue but some example stage names in Chalice docs have a "-" in them.

**Comment by stealthycoin** [comment]
Where in our examples do we use a dash in the name? I grepped our docs source and don't see any. Looks like we only use api/dev/prod:
```
$ rg api_gateway_stage
source/tutorials/websockets.rst
366:        "api_gateway_stage": "api",

source/upgrading.rst
64:      "api_gateway_stage": "api",
353:      "api_gateway_stage": "dev",

source/topics/configfile.rst
69:``api_gateway_stage``
332:        "api_gateway_stage": "dev"
360:    "api_gateway_stage": "api",
367:        "api_gateway_stage": "prod",
376:default to the top level ``api_gateway_stage`` key.
378:name of ``prod`` because the ``api_gateway_stage`` is specified
481:        "api_gateway_stage": "api",
```

**Comment by johntmyers** [comment]
Yes, sorry that is right, I was looking at the configuration file docs for `api_gateway_stage` where it uses this: `https://endpoint/prefix/your-api` but realized "prefix" is the is the setting that gets configured there.
