### ISSUE TITLE
Scheduled Lambda Timeout and never runs code.

### ISSUE THREAD

**Issue by subssn21** [aws/chalice#1249]
I have a very strange problem and have no idea what I am doing wrong. I have an application with several SQS Queues and many API Gateway routes all of which are running without issue.

However I added a scheduled Lambda Function today and every time it is supposed to run, it will attempt to run (The cloud watch event got scheduled and the lambda function gets invoked.) However nothing happens. It just sits there for the full time that the function has to run and then times out. There is no log output generated other than the start, end , report and timeout error:

> START RequestId: 2893a7b2-3265-4ca8-b6f2-8e0a203c8620 Version: $LATEST
> END RequestId: 2893a7b2-3265-4ca8-b6f2-8e0a203c8620
> REPORT RequestId: 2893a7b2-3265-4ca8-b6f2-8e0a203c8620 Duration: 60060.13 ms Billed Duration: 60000 ms Memory Size: 128 MB Max Memory Used: 128 MB
> XRAY TraceId: 1-5d854b58-9481fd2fea3cd4ab88e0bdc9 SegmentId: 39d7615d5884cd96 Sampled: false
> 2019-09-20T22:03:58.542Z 2893a7b2-3265-4ca8-b6f2-8e0a203c8620 Task timed out after 60.06 seconds

I have trimmed the code for the actual function down to the basic example and still the same thing.

    @app.schedule('rate(1 minute)')
    def check_messages(event):
        print(event.to_dict())
        #with conn:
        #    Message.needs_queued()

Am I missing a setting somewhere or an IAM permission on my role that I need?

**Comment by subssn21** [comment]
OK, So I have spent a bunch of time trying to debug this today. 

And After putting what feels like 100s of prints to figure out where it was stopping running at. It looks like it is the Dropbox API.

I removed the import dropbox and now it runs.

The weird thing is I use it without issue in my Rest API calls, It gets imported by my app all the time and is only causing an issue in the scheduled Lambda.

Is there something special about scheduled events?

**Comment by stealthycoin** [comment]
Sounds like something specific to what you are doing, likely the API call you are making with dropbox timing out? I don't have dropbox or use it for anything, so I just tried importing it which works fine:
```python
import dropbox

from chalice import Chalice

app = Chalice(app_name='dropbox-test')


@app.schedule('rate(5 minutes)')
def fn(event):
    print(dropbox)

```

Does the dropbox sdk have a debug mode you can turn on? I would start there. The only thing that should be different between the scheduled event and the route calls is that its a separate lambda function. Is it possible you configured your SQS/API Gateway lambda correctly and the scheduled event one is incorrect? I can't think of anything else.

**Comment by subssn21** [comment]
Thanks for trying that.

The thing is the scheduled function isn't even using dropbox. It's just part of the imports(because it's used by the API Gateway calls) and the act of importing it is where it freezes.

The thing that is weird is that in only freezes on the scheduled lambda and not the API Gateway or SQS Lambdas which is why I was wondering if there is something different that gets done when Chalice build the Lambda function for the scheduled function, or if there is something different inside of the Lambda system itself, but if you can import it fine outside of my environment, that clearly indicates it must be something in my environment that is causing the issue.

I wonder if it's an order issue. Can you try moving the import dropbox to after the import of Chalice?

The other possibility I can think of is it some weird interaction between the dropbox import and the other libraries I am using, but I would think if that's the case, it would freeze all the time.

**Comment by stealthycoin** [comment]
Swapping the order is fine as well for me. Any way you could cut this down to a minimal repro case with your configuration? I briefly started looking through what happens in the dropbox sdk when you just import it but it looks like a lot of stuff. Nothing obvious that would be causing it though.

**Comment by subssn21** [comment]
Built a minimum set of code to reproduce the issue.

Since you can't put subdirectories in gists, the chalicelib_test1.py belongs in the chalicelib dir

https://gist.github.com/subssn21/c6b9d59858153cc06c62d1ea729c168e

**Comment by stealthycoin** [comment]
I think there's gotta be something else in your code that's doing this, the repro works fine for me. I can curl the endpoint and all the scheduled events take around .3ms.

**Comment by subssn21** [comment]
Well I am going to go ahead and close this. I have a work around, as moving the import into the actual API Gateway call that is using it fixes the problem, not clean or pythonic, but it works.

It is still really weird, as I can reproduce on a clean Chalice, with very minimal anything else. So it must be something in my OS or Python? Weird.
