### ISSUE TITLE
Make blueprints no longer an experimental API.

### ISSUE THREAD

**Issue by jamesls** [aws/chalice#1250]
Blueprints were added in 1.7.0 (Feb 2019).  In that time, there haven't been any issues for blueprints that have required any API changes.  And while I don't have exact numbers, it does seem to be getting usage out in the wild.  I propose we mark this as a fully supported API.

**Comment by thulasi-ram** [comment]
Just bumping up. Would appreciate some update on this. About to start a project with blueprints which is going to be a used as a template in the org. 
Given that blueprints have been live for more than a year now I may actually go ahead even if it is experimental but it would be helpful to know if it would be considered an accepted feature.

**Comment by jamesls** [comment]
Given the +1s on this issue and the fact there have been no API changes to blueprints, I'm going to go ahead and mark this as an accepted feature.  I'll send a PR in a bit.
