### ISSUE TITLE
[proposal] Add 'dev' suite of CLI commands

### ISSUE THREAD

**Issue by jamesls** [aws/chalice#1257]
This proposal introduces a suite of subcommands under the `chalice dev`
namespace.  They help provide insight into how chalice deploys an application.
The target audience is developers contributing to chalice and users who want to
debug or better understand what chalice is doing.

As chalice continues to add more features, the deployer code continues to grow.
While the core deployer concepts seem to be holding up ok, each component of the
deployment system continues to add more and more functionality.  For example,
for new features we sometimes need to add new instructions to the planner, new
resources to the model definitions, the app graph builder now has conditional
logic based when constructing models, etc.

To understand how all this works, you typically have to modify the source code
and either insert print statements or step through it with a debugger.

To help with this, a new namespace ``chalice dev`` is added that allows
people to introspect the chalice deployment.  Initially, I propose adding two
new subcommands:

* `chalice dev appgraph`
* `chalice dev plan`

The `chalice dev appgraph` command pretty prints the output of the
`ApplicationGraphBuilder`.  This allows you to see how a chalice app maps to
the high level model representation.  The `chalice dev plan` pretty prints the
output of the planner.  This lets you see how a chalice app maps to concrete
instructions needed to deploy the app.

Now given that these commands are only meant for development/debug purposes,
and that these commands are surfacing implementation details of chalice, I also
propose that we clearly document (everywhere) that these commands should not
be relied on, that there are no guarantees for backwards compatibility.  This
applies to backwards compability of the commands and arguments themselves
under the `chalice dev` namespace, the output of these commands, and the
intrinsics exposed from these commands (e.g. the name of instructions in
the planner).

The goal of this is to help people better understand what chalice is doing,
as well as help us develop and review changes as new functionality is added.
Given there's no guarantee of backwards compatibility, I think these commands
are fairly low risk, and have potential to be really beneficial.

**Comment by kyleknap** [comment]
Looks fine to me on the caveat there is no backwards compatibility guarantees.

**Comment by jamesls** [comment]
Added in #1396, now available in the latest chalice release.
