### ISSUE TITLE
Slow performance using chalice framework render RDS data to UI

### ISSUE THREAD

**Issue by jlpl1999** [aws/chalice#1261]
We just refactor to current springboot apps into the chalice apps, and the back end connecting to RDS mysql via PeeWee for ORM.
Experience slowness to render data to front UI and currently small set of data. The same data which render via Sprintboot, has not problem.
Any suggestion for tuning on performance? Or any software plugin to diagnostic the current issues
Thank you

**Comment by kapilt** [comment]
using AWS X-ray may help here to understand the timings, or alternatively adding logging of timing information. you can also try adding more memory to the lambda function which gives additional cpu capabilities.

**Comment by stealthycoin** [comment]
Also depending on how many database connections you can make silmoltaniously, it would be good to check if you are creating a new connection per invocation (which would be very slow). Or keeping the connection alive in the container where it can be re-used between lambda invocations that are using the same container. Other than that I cannot think of anything that would be Chalice specific and causing these performance issues.
