### ISSUE TITLE
Packaging in chalice not using pip installed module

### ISSUE THREAD

**Issue by jamessugrue** [aws/chalice#1266]
I've done my setup as recommended, with a virtualenv, then installing chalice on the env. 
I have a python module that I forked and did some work on, and I gave it a newer version than that which is generally available 

If I run `pip list` I see my module with a newer version 

After running `chalice package out` and I look at the contents, it installs the generally available version. If I set the version in requirements.txt, even though it is available in `pip list` I get the following error: 
`chalice.deploy.packager.NoSuchPackageError: Could not satisfy the requirement:`

Have I made an incorrect assumption? 

Running `chalice local`, everything works as expected.

**Comment by subssn21** [comment]
What does the requirments.txt entry look like for your forked package?

Typically when I have needed to use a custom fork of a project, I fork it on github, push the fork to my local repo, then refer to it in my requirements.txt like:

`git+git://github.com/path/to/package-two@41b95ec#egg=package-two`

See this [stackoverflow question](https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source) for lots of details on specifying git references in requirements.txt

**Comment by jamessugrue** [comment]
That resolved it - thanks so much for your help there. Stupid question really now that I think about it.
