### ISSUE TITLE
Feature Request: Provide bash/zsh completion

### ISSUE THREAD

**Issue by brianredbeard** [aws/chalice#1269]
Chalice uses the Python [click] library which supports [bash completion][click-complete]. Generating the bash completion output via a verb on the utility would make it easier for users to work much more quickly.

[click]: https://github.com/pallets/click/
[click-complete]: https://click.palletsprojects.com/en/7.x/bashcomplete/

**Comment by jamesls** [comment]
Hi, can you clarify what you're asking for?  Given chalice uses click as you mention, you can configure auto-complete via:

```
$ eval "$(_CHALICE_COMPLETE=source chalice)"
```


Was there something more you'd like?

**Comment by ventz** [comment]
Just leaving it for anyone who is coming here looking for the ZSH equivalent:

```
eval "$(_CHALICE_COMPLETE=source_zsh chalice)"
```
