### ISSUE TITLE
SQLAlchemy can not be installed during chalice deploy

### ISSUE THREAD

**Issue by Rubyj** [aws/chalice#1278]
@jamesls @stealthycoin The SQLAlchemy package seems to be unable to installed during a chalice deploy with `sqlalchemy` in `requirements.txt` on manjaro/arch linux with `python3.7`.

```
Could not install dependencies:
sqlalchemy==1.3.10
You will have to build these yourself and vendor them in
the chalice vendor folder.
```
I can do this. but packages that then use sqlalchemy drivers do not even register it as being installed.

However, running on mac or ubuntu `chalice` can install `sqlalchemy` no problem with `python3.6`.

**Comment by stealthycoin** [comment]
Make sure you have a new enough version of wheel to properly install sqlalchemy. I had to upgrade it manually in a new 3.7 virtualenv I created before I could get sqlalchemy to install.

```
$ pip install -U wheel
```

**Comment by Rubyj** [comment]
> Make sure you have a new enough version of wheel to properly install sqlalchemy. I had to upgrade it manually in a new 3.7 virtualenv I created before I could get sqlalchemy to install.
> 
> ```
> $ pip install -U wheel
> ```

I believe I tried this already when I attempted to build the wheel manually. I will try again on arch with `python3.7` and make sure to explicitly upgrade `wheel`. I will post results here.

**Comment by stealthycoin** [comment]
Let me know if this doesn't resolve it for you. On arch you should even be able to build compatible C extensions so it really shouldn't be having issues on that platform if it can build the wheel at all.

**Comment by Rubyj** [comment]
@stealthycoin I think this solved the issue. I'll do some further testing tomorrow, but after making sure wheel was at the latest version with `python3.7` the deploy looked better at first glance.

**Comment by stealthycoin** [comment]
@Rubyj Good! I'm going to resolve the issue, if it isn't fixed please re-open.
