### ISSUE TITLE
How to call Chalice endpoint from Swift?

### ISSUE THREAD

**Issue by Pe-te** [aws/chalice#1284]
Trying to find a good example how to call a Chalice endpoint from Swift like described here:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-ios-lambda.html

The function-parameter is the name of the function, that works, but how do you build the jsonObject to call a specific route with path parameters and json bodies, headers, etc.?

**Comment by Pe-te** [comment]
Is there any reason all those fields in Chalice:__call__() are mandatory? I would expect everything other than httpMethod and resourcePath to be optional?

            event['multiValueQueryStringParameters'],
            event['headers'],
            event['pathParameters'],
            event['requestContext']['httpMethod'],
            event['body'],
            event['requestContext'],
            event['stageVariables'],
            event.get('isBase64Encoded', False)

AFAIU the last line with the get() access the field as optional and the brackets access it directly and raise an error if the value is missing.

**Comment by stealthycoin** [comment]
What are you asking exactly? None of those things you provide in the call those are all created by API Gateway from your HTTP request. You just make an HTTP request, as the link you posted shows.

**Comment by Pe-te** [comment]
We are working without API gateway and calling the Lambda directly with Lambda-Invoker, then you have to add all those fields even if they are not really needed.

**Comment by jamesls** [comment]
In that case I'd just use `@app.lambda_function()` instead of using the `@api.route()` decorator.  If you're not using API Gateway there's not much benefit in using the HTTP routing.
