### ISSUE TITLE
Backwards-incompatible change in query params in 1.9.0 and later

### ISSUE THREAD

**Issue by akurtz** [aws/chalice#1287]
Our project is trying to upgrade from Chalice 1.8.0 to 1.12.0, but we're finding that since the [move to MultiDict for query params](https://github.com/aws/chalice/pull/1132) in 1.9.0/1.9.1, passing a regular dict with params no longer seems to work.

[This line is the culprit.](https://github.com/aws/chalice/blob/e3b53f7a2125fe78c153ca8d2d474aaab6d7cfcf/chalice/app.py#L171)  It's expecting every query param value to be a list, but that isn't documented or enforced anywhere.

`MultiDict.__setitem__` does convert individual values to lists, so creating a MultiDict one param at a time works as expected:

```
params = MultiDict({})
params['p1'] = 'ABC'
params['p2'] = 123
# params is now MultiDict({'p1': ['ABC'], 'p2': [123]})
```

But the MultiDict _constructor_ does not perform this conversion, and I believe that's the most common way params are passed (as a dict).  So when we pass our usual dict of query params like `{'p1': 'ABC', 'p2': 123}` and those params are accessed, the `[-1]` is operating here on a string and integer, not lists.  So `params.get('p1')` returns `C` (last character of the string), and `params.get('p2')` raises a TypeError.

Passing `{'p1': ['ABC'], 'p2': [123]}` will cause it to work as expected.

I think the best solution would be to convert all non-list params to one-item lists in the constructor to maintain backwards compatibility in allowing regular dicts for query params.  Adding the following lines to `MultiDict.__init__` makes it work for our use case:

```
if isinstance(mapping, dict):
    mapping = {k: (v if isinstance(v, list) else [v]) for (k, v) in mapping.items()}
```

I'm not sure this will fix _all_ backwards compatibility issues, but at the very least it should only be an improvement and not a regression for anyone.

(This is not the first time 1.9.0 has caused a breaking change, see also: https://github.com/aws/chalice/issues/1158)

Thanks for your work on this project!

**Comment by stealthycoin** [comment]
That's a new Class in 1.9. There's no way for it to have a backwards incompatible change. Is something confusing about its usage? You have to provide a dict of lists to the constructor, which is mentioned in the class header, is that not clear enough? Its a new class though, and a new class constructor so its not a breaking change its just a new one, all your existing code should continue to work.

The only place where I see it automatically being plumbed into the initializer is from an API Gateway payload property which is in the right format already.

**Comment by akurtz** [comment]
> Its a new class though, and a new class constructor so its not a breaking change its just a new one, all your existing code should continue to work.

Here's the minimum code to demo the breaking change:

Install Chalice 1.8.0: `pip install -I chalice==1.8.0`

```python
from chalice.app import Request
request = Request(
    query_params={'p1': 'ABC', 'p2': 123},
    headers=None, uri_params=None, method='GET', body=None, context=None, stage_vars=None, is_base64_encoded=False
)
assert request.query_params.get('p1') == 'ABC'
assert request.query_params.get('p2') == 123
```

Tests pass.

Now install Chalice 1.9.0 (or later): `pip install -I chalice==1.9.0`

Tests now fail.  Fetching p1 returns `C`, fetching p2 raises `TypeError`.

**Comment by stealthycoin** [comment]
Why are you making a request object though. Those are created by Chalice, and the way it is currently I don't think there's any breaking change.
