### ISSUE TITLE
Handling API Key and Usage plan for API Gateway using Chalice and terraform

### ISSUE THREAD

**Issue by spicoflorin** [aws/chalice#1293]
Hi!
 Chalice support creating methods of API Gateway protected by API key (https://chalice.readthedocs.io/en/latest/api.html).
What I would like
1. is to use a generated API key and a correspoding already created Usage plan in config.json of the chalice.
2. chalice to generate both API key and  a correspoding already Usage plan
3. terraform to properly generate the plan for the above requests when using the command:
 `chalice package --pkg-format terraform pkg-app` 

 I found a similar issue here https://github.com/aws/chalice/issues/420, but unfortunately I don't know the status of this issue.
**Questions**
1. Can you please advise if you support these requests? 

2. If yes can you provide an example?

Thanks.

**Comment by jamesls** [comment]
This is not currently possible but something I'd like to add.  In general there's not great support for usage plans in Chalice.  #420 is track that, so I'm going to close out this issue.  Let's track the remaining work there.
