### ISSUE TITLE
chalice.app.Response is not JSON serializable when using Pure Lambda

### ISSUE THREAD

**Issue by nservidio** [aws/chalice#1294]
Hey all, love Chalice:

I have a "pure lambda" function for seeding my database:
```
@app.lambda_function()
    def seed(event, context):
```

The function returns a `chalice.app.Response` object:
```
return Response(body={"status": "seeded!"})
```

However, after deploying and triggering the lambda with the aws cli: 
```
aws lambda invoke --function-name my_function_name --cli-read-timeout 600 ~/Desktop/outfile.json 
```

I get the following error:
```
{
    "errorMessage": "Unable to marshal response: <chalice.app.Response object at 0x7f0d9c4ed090> is not JSON serializable",
    "errorType": "Runtime.MarshalError"
}
```

If I:
```
return {"status": "seeded!"}
```

The error goes away.

Also, I have no problem returning `Response` objects from `@app.route()`s.

I may be doing something dumb, so please let me know thanks!

**Comment by stealthycoin** [comment]
The `Response` class is for responding from a view function. That is a function decorated with `@route` and handling HTTP requests and responses. It doesn't really make sense in the context of a pure lambda function and isn't intended to be used there.

**Comment by nservidio** [comment]
Alright, thanks for the info!

**Comment by stealthycoin** [comment]
No problem, closing since I think its answered, feel free to open another one with further questions.
