### ISSUE TITLE
Implement HTTP Basic Authentication

### ISSUE THREAD

**Issue by 3dw1np** [aws/chalice#1301]
Any easy way to implement HTTP Basic Authentication in Chalice ?

**Comment by stealthycoin** [comment]
If by easy way you mean are there any abstractions or tools in Chalice to do this for you, there aren't currently anything for plain HTTP authentication.

Our authorization tools currently are :
https://chalice.readthedocs.io/en/latest/quickstart.html#tutorial-using-custom-authentication

From that list API Keys are probably the easiest to get working if you just want some form of auth on a route. You would need to hand out API keys in that case and use https://chalice.readthedocs.io/en/latest/quickstart.html#api-key.
