### ISSUE TITLE
SimpleJson release broke Chalice release

### ISSUE THREAD

**Issue by subssn21** [aws/chalice#1304]
I went to run a chalice release of my code this morning and it will deploy but not . run because of a 502 error.

I get this message during deploy:

> 
> Creating deployment package.
> 
> Could not install dependencies:
> simplejson==3.17.0
> You will have to build these yourself and vendor them in
> the chalice vendor folder.
> 
> Your deployment will continue but may not work correctly
> if missing dependencies are not present. For more information:
> http://chalice.readthedocs.io/en/latest/topics/packaging.html
> 

It ends up that last night a new release of simplejson was released and apparently it breaks the chalice deployment.

Not sure why we need simplejson as there is a built in json, (probably because simplejson is faster)

Also not sure why we are auto using the latest version. We should use specific version and test each new version before using it so this doesn't happen.

The package installs and works fine so I am not sure why it is failing to install during deployment

**Comment by subssn21** [comment]
You can work around this issue by adding

`simplejson==3.16.0`

to your requirements.txt

**Comment by KoreyPeters** [comment]
simplejson handles pushing JSON to DynamoDB better than the built in json package. Boto3 keeps throwing back integers as Decimal, which makes the built in json package barf.

**Comment by stealthycoin** [comment]
Thanks for the report I'll look into it.

**Comment by stealthycoin** [comment]
Relabled as bug and I have a PR to fix it up. I am surprised this didn't get reported sooner! I guess case 3 (from the commit message) is much less common than I would expect. Thanks for reporting this.
