### ISSUE TITLE
Chalice Package Pure Lambda

### ISSUE THREAD

**Issue by rajpdus** [aws/chalice#1305]
`chalice deploy` allows you to give a name to your lambda function by simply passing name=<FN_NAME> as a parameter to your `@app.lambda_function` decorator. You could invoke the same function by <app>-<env>-<FN_NAME> from aws cli. 

However, if one were to `chalice package` and bundle the template with other resources for deployment it does not retain the Function name. I figured out that during AWS template generation it does not add resource name to the cloud formation templating engine. 

Is it worth to have this fix?

**Comment by rajpdus** [comment]
<img width="604" alt="Screenshot 2019-11-19 at 10 15 22 PM" src="https://user-images.githubusercontent.com/54466596/69167184-82383b80-0b1a-11ea-8af8-39573f937a99.png">

This would solve the problem.

**Comment by stealthycoin** [comment]
So the name there is just the `chalice` name for it, like the command example where you use invoke it through the chalice CLI. In cloudformation its much better to let cfn pick the name, that way you can deploy multiple templates to the same account without a collision. I think if we made this "fix" it would actually result in a lot of issues.

In a CFN the name is given to the key of the lambda function itself in the resource block, since that is where it is supposed to be unique, and referenced by other resources that are a part of the application. The names are transformed to be compatible with CFN. This is currently considered a part of your API so you can depend on it.

**Comment by rajpdus** [comment]
True that it would allow deploying multiple templates through CFN. However, the name assigned while deploying such template automatically is an alpha numeric which renders its use as a callable in other function difficult. Every update to this lambda would change the name. This makes sense if the onus of naming resources using these templates rest on the user itself. May be a configuration item makes for a better suggestion than using the function name directly.

**Comment by stealthycoin** [comment]
Ah so I wouldn't ever really recommend just calling a function by name. I'd do some kind of system where it registers functions for certain roles and your application can discover or has a directory of which function goes to which role. Too many ways that can go wrong if you re-deploy, have multiple versions, change the name etc.

What I would do is use the [merge template feature](https://chalice.readthedocs.io/en/latest/topics/cfn.html#template-merge) and have a template that merges the name of your async lambda into the APIHandler lambda as an environment variable. For example.

app.py
```python
import os

import boto3

from chalice import Chalice

app = Chalice(app_name='example')

def get_env_var(name):
    return os.environ[name]


@app.route('/start-workflow')
def start():
    name = get_env_var('WORKFLOW_LAMBDA_NAME')
    # boto3.lambda_async_call_here(name=name... )
    return {'status': 'STARTED'}


@app.lambda_function(name='AsyncWorkflow')
def long_task(event):
    print('doing/starting some task...')

```

extras.json
```json
{
  "Resources": {
    "APIHandler": {
      "Properties": {
	"Environment": {
	  "Variables": {
	    "WORKFLOW_LAMBDA_NAME": {"Ref": "AsyncWorkflow"}
	  }
	}
      }
    }
  }
}

```

The extras.json merges an environment variable that references our `AsyncWorkflow` lambda function into the CFN template. The lambda function that is responsible for handling API Gateway requests is always in the CFN resource section under the key `APIHandler`.

```
$ chalice package out --merge-template extras.json
$ aws cloudformation package --template-file out/sam.json --output-template-file out/sam.yml --s3-bucket deployment-bucket
$ aws cloudformation deploy --template-file out/sam.yml --stack-name example --capabilities CAPABILITY_IAM
```

Now I have an APIHandler function that can reference the right function without knowing its name. Now you can rename it / have multiple stacks/ version it without worrying about the wrong one ever being referenced. The caveat is that you can't make a circular reference between the lambda functions. When I have a situation like that I usually wind up either 
1) Tagging my functions and using the tagging API to fetch them. Chalice already provides 1 tag by default that looks like this Key: `aws-chalice` Value: `version=1.12.0:stage=dev:app=example` that you can filter on. I usually add a `Purpose` tag as well to help sort them.
2) Use the CloudFormation API to get the outputs of the stack. Here you would use the `--merge-template` parameter again to add outputs for resources you want to reference, and give your lambda permissions to get the stack outputs. Every lambda can then use the [AWS::StackName pseudo parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackname) to get the list of outputs and cache the results.

Ideally in the future Chalice would have some sort of resource's API that lets you reference all resources by arn/identifier that were deployed as a part of the application. But we don't have that yet.

**Comment by rajpdus** [comment]
This is neat. Thanks.
