### ISSUE TITLE
Custome headers on API Gateway

### ISSUE THREAD

**Issue by Aamir010** [aws/chalice#1307]
How do we pass custom headers on API Gateway ?

I got into the issue where I am receiving "message": "Endpoint request timed out" because of API Gateway limitation.

And I found the doc where we can set the "X-Amz-Invocation-Type: true" to run the Lambda asynchronously

**Comment by stealthycoin** [comment]
There isn't a way to handle internal headers like that currently. If your goal is to kick off some kind of async workflow I would recommend you just boto3 in the API handler to kick off the job (step functions maybe, or just another lambda called asynchronously). This can get generate some kind of jobId on your backend to associated with the workflow, and return that to the caller. Then you can have some kind of other API to check on the status of a jobId or get the results if its complete.

**Comment by stealthycoin** [comment]
Let me know if I'm not understanding your use case.

**Comment by Aamir010** [comment]
@stealthycoin Thank you so much for taking sometime to responding on this thread. However, I have taken the same async approach for my use case
