### ISSUE TITLE
How to keep custom policy under version control?

### ISSUE THREAD

**Issue by brylie** [aws/chalice#1311]
We have a Chalice project that defines a lambda function. Inside the lambda, we need to access an S3 object in a secured bucket. To grant the lambda access to the bucket, we should define a custom policy document. 

Git ignores the policy document generated under `.chalice`. How can we keep the custom policy changes under revision control?

**Comment by brylie** [comment]
Ah, sorry. I assumed the .gitignore was ignoring all of .chalice.

**Comment by brylie** [comment]
Actually, no. For some reason, the `.chalice/policy.json` file is ignored by git until we explicitly add it `git add -f .chalice/policy.json`.

**Comment by stealthycoin** [comment]
You can put the policy file anywhere with `iam_policy_file` in the config file. Though when I try making a new project and adding a `.chalice/policy.json` file it picks it up right away. Maybe some global git config is conflicting in your case?

**Comment by brylie** [comment]
Ah, I think I recall how the file is being ignored. We are working with raw JSON data in the same project namespace, and have `*.json` in our `.gitignore` to prevent accidentally checking in data to GitHub.

**Comment by brylie** [comment]
Is the `iam_policy_file` approach documented? We pivoted back to using the Serverless Framework, for a second time, due to familiarity. 

It might have been easier to stick with Chalice, if it were more clear how to override parts of the Cloudformation stack (like specifying subnet) while letting Chalice automate some of the rough edges (like configuring permissions for S3 access).

**Comment by stealthycoin** [comment]
Yes it is documented here: https://chalice.readthedocs.io/en/latest/topics/configfile.html#iam-policy-file

**Comment by brylie** [comment]
Ah, yes. I did find that in my efforts. It seems like a loss to have to turn autogenerate to False, just to override a couple of specific permissions or configuration options. Is there a middle way, like an automatic merge approach to make this simpler?

**Comment by jamesls** [comment]
Not currently, but there is a feature request to support this.  Let's track that work over in https://github.com/aws/chalice/issues/1198
