### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by betacar** [aws/chalice#1312]
After I invoke a function using `boto3@1.10.8` through the following instruction,

```python
import json
import boto3
import src.config as config

client = boto3.client('lambda')

def send(payload: [dict]) -> None:
    """Invokes the lambda function"""
    client.invoke(FunctionName=config.ARN_NAME,
                  Payload=json.dumps(payload, default=str))
```
No exceptions are raised. However, the function is never executed and the following error is shown on CloudWatch logs with no further context:
```
[ERROR] AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1016, in __call__
    resource_path = event.get('requestContext', 
{}
).get('resourcePath')
```

Is this because chalice is expecting a dictionary instead of a list (as this case)? Or maybe because the function was declared as REST on Chalice? Or am I missing something?

**Comment by stealthycoin** [comment]
Are you calling an API endpoint function directly? How is that function decorated? Lambdas that serve API Gateway must be configured a certain way. If you want to be able to call that functionality separately (not from an API endpoint) I would suggest using `@app.lambda_function`. If you want to be able to call from both, I would suggest wrapping up the behavior in a `chalicelib/` function and having two handlers in Chalice:

```python
from chalicelib.handler import Handler
handler = Handler()


@app.route('/path')
def handle_from_api():
    handler.handle_request(app.current_request.body['somekey'])


@app.lambda_function()
def handle_directly(event, context): 
    handler.handle_request(event['somekey'])
```
