### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by jarretraim** [aws/chalice#1315]
I did some searching and didn't see an issue for this yet, so hopefully not a dupe.

AWS Lambda supports Python 3.8 as a target runtime as of Nov, 2019 (https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-now-supports-python-3-8/).

Chalice currently issues warnings on project creation, e.g:

```
...\chalice\cli\__init__.py:327: UserWarning: You are currently running python3.8, but the closest supported version on AWS Lambda is python3.7
Please use python3.7, otherwise you may run into deployment issues.
  validate_python_version(Config.create())
```

As well as documentation in the README:

```
Note: make sure you are using python2.7, python3.6, or python3.7. These are the only python versions currently supported by AWS Lambda so they are also the only versions supported by the chalice CLI and chalice python package. 
```

The code and documentation should be updated to support 3.8. Note that as of now, when creating a new function on AWS, Lambda defaults to 3.7 even when the local / dev interpreter is 3.8 and 3.8 is available.

**Comment by Senpos** [comment]
[Python 3.8.1 has arrived recently](https://www.python.org/downloads/release/python-381/) :)
So, 3.8 might get a bit more use soon.

**Comment by jamesls** [comment]
Fixed via https://github.com/aws/chalice/pull/1318

**Comment by nom3ad** [comment]
but  readme seems to be not updated.
