### ISSUE TITLE
Single lambda function for mutiple API endpoints

### ISSUE THREAD

**Issue by Aamir010** [aws/chalice#1323]
I have a multiple API endpoints in the app.py code. But when I look at AWS Console, it will only shows the single lambda function.

Is there any way, where I can have multiple lambda functions based on multiple endpoints?

**Comment by skwashd** [comment]
@Aamir010 Chalice defines a single entry point that all requests to the API gateway are routed through. The single entry point handles the routing. It looks up your route definitions and calls the right callback for the inbound request.

If you don't want this behavior you can ditch chalice and write standalone lambda functions. The downside is that you need to handle the wiring up of the API gateway.

**Comment by Aamir010** [comment]
Got it. Thanks for clarification. The real idea was to enable cloudwatch alarm for the endpoint and I did not found any specific parameters in config.json which enables the alarm. However, to hack we have to use the cloudwatch API's to enable.

**Comment by Aamir010** [comment]
The question is came up. Beacause I wants to provide timeout for each function definition. But there's only single endpoint define, how can we define the timeout and memory to the default endpoint? I can see the config.json keys for lambda to modify default timeouts and memory limits.

**Comment by johntmyers** [comment]
You can only provide a timeout for each lambda. Each route uses the same lambda and if you want to set memory and timeout for the Lambda that handle routes, you use `api_handler` as the lambda name.

From the docs:

```
There is one exception to this, which is any python function decorated with the @app.route() decorator. Chalice uses a single Lambda function for all requests from API gateway, and this name is api_handler. So if you have an app like this:

@app.route('/')
def index(): pass

@app.route('/foo/bar')
def other_handler(): pass
Then to specify configuration values for the underlying lambda function, which index() and other_handler() share, you would specify:

{
   "lambda_functions": {
     "api_handler": {
       "subnet_ids": ["sn-1", "sn-2"],
       "security_group_ids": ["sg-10", "sg-11"],
       "layers": ["layer-arn-1", "layer-arn-2"],
     }
   }
 }
```

**Comment by ricky-sb** [comment]
Related: https://github.com/aws/chalice/issues/1308

**Comment by jamesls** [comment]
Just following up here, this is not currently possible, but there's a proposal for how to enable this: https://github.com/aws/chalice/issues/1308.  Resolving as duplicate, let's track this over at https://github.com/aws/chalice/issues/1308
