### ISSUE TITLE
Lambda memory size in config

### ISSUE THREAD

**Issue by EgertM** [aws/chalice#1327]
Lambda memory size does not seem to change when changing the default value in config file for example from 128 to 256. 

I have it defined like this:
`"lambda_functions": {
    "index": {
      "lambda_timeout": 60,
      "lambda_memory_size": 256
    }
  }`
![image](https://user-images.githubusercontent.com/14824370/71093706-658f3200-21b2-11ea-90fe-2f3f80e4dffd.png)

**Comment by danil-smirnov** [comment]
It would be really helpful as well to define lambda performance params (memory size, which in turn defines cpu) _per method_.

In this case powerful lambdas could be assigned to heavy API methods only and one can save money on calls to lighter methods.

I suppose creation of different exemplars of api_handler lambda for every memory value detected.

**Comment by danil-smirnov** [comment]
@EgertM Are you sure you refer to your lambda correctly ("index")? For APIG lambda name should be ""api_handler".

**Comment by EgertM** [comment]
Yes, it´s the name of my lambda function ("index"), so that can´t be the issue.

**Comment by EgertM** [comment]
Does anyone else have an idea why it´s not working?

**Comment by isohrab** [comment]
I have the same problem. did you solve it?
