### ISSUE TITLE
Fix tests execution on local environment

### ISSUE THREAD

**Issue by carloshatch** [aws/chalice#1328]
First of, thanks for this framework. Second, I would like to report an issue I was having when running tests locally. I found two issues, the first is that the package `watchdog` isn't in the
`requirements-dev.txt`, so `make test` failed like this:

```ImportError while importing test module '/workspace/chalice/tests/integration/test_package.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/integration/test_package.py:9: in <module>
    from chalice import cli
chalice/cli/__init__.py:26: in <module>
    from chalice.cli import reloader
chalice/cli/reloader.py:34: in <module>
    from chalice.cli.filewatch.eventbased import WatchdogWorkerProcess
chalice/cli/filewatch/eventbased.py:4: in <module>
    import watchdog.observers
ImportError: No module named watchdog.observers
```

That could be fixed by installed the `watchdog` package. However, when trying to run `make prcheck`:

```# Run our custom linter on test code.
pylint --load-plugins tests.linter --disable=I,E,W,R,C,F --enable C9999,C9998 tests/
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/2.7.16/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/workspace/.pip-modules/lib/python2.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/workspace/.pip-modules/lib/python2.7/site-packages/pylint/lint.py", line 1274, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/workspace/.pip-modules/lib/python2.7/site-packages/pylint/lint.py", line 500, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/workspace/.pip-modules/lib/python2.7/site-packages/astroid/modutils.py", line 190, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/workspace/.pip-modules/lib/python2.7/site-packages/astroid/modutils.py", line 232, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
ImportError: No module named linter
make: *** [Makefile:22: pylint] Error 1
```

I believe the reason is because `pylint` isn't including the current working directory to the python path. That could be fixed by setting `PYTHONPATH` right before the command itself.

**Comment by jamesls** [comment]
Can you show the steps you used to set up your dev env?  When I walk through the steps in our contributing guide (https://github.com/aws/chalice/blob/master/CONTRIBUTING.rst#development-environment-setup), `make prcheck` is working for me.

Note that you might get a doccheck failure, which will be fixed in https://github.com/aws/chalice/pull/1330.

**Comment by carloshatch** [comment]
@jamesls You are right, I used an alternate path as I missed that guide. What I did was `python setup develop.py` and then tried to run `make test`, `make prcheck` also failed as described above. However,, by using `pip install -e ".[event-file-poller]"` everything worked as expected.

I can see advantage of `setup.py develop` over `pip install`, but definitely that's out of the scope here.

**Comment by jamesls** [comment]
Glad you were able to get it working!
