### ISSUE TITLE
Define lambda performance per method

### ISSUE THREAD

**Issue by danil-smirnov** [aws/chalice#1331]
It would be really helpful as to define lambda performance params (memory size, which in turn defines cpu) _per method._

In this case powerful lambdas could be assigned to heavy API methods only and one can save money on calls to lighter methods.

I think it can be implemented by creation of different exemplars of api_handler lambda for every memory value detected.

**Comment by ricky-sb** [comment]
You would need to deploy the routes to various Lambda functions (#1308) before you could do this.

**Comment by jamesls** [comment]
Yes, if https://github.com/aws/chalice/issues/1308 gets implemented you'd automatically get this "for free" given the way we let you configure different configurations per lambda.  Let's track that work over in #1308
