### ISSUE TITLE
Very large upstream traffic on deploy

### ISSUE THREAD

**Issue by vfilimonov** [aws/chalice#1332]
Hello,

First of all, many thanks to all of developers for such extremely useful framework!

I've noticed, that the upstream traffic is much larger than could be expected from the package size.

For example, in the package I have 2 pure lambda functions. Zipped deployment (from the "deployments" folder) is 44.4 MB. After deployment, AWS Lambda web console shows that each of them have code size of 42.3 MB. However during the deployment process almost 10-times more (396 MB) was transferred to `amazonaws.com`:

<img width="327" alt="Screenshot 2019-12-28 at 23 59 48 " src="https://user-images.githubusercontent.com/1324881/71550390-85eb9780-29cf-11ea-8fbc-c08b0d3efebb.png">

Is it an expected behavior? If so - what is the reason for such overhead?
And if not - maybe it could be the cause of slow deployments in some other issues (e.g. #1086)

Best regards
Vladimir

**Comment by kapilt** [comment]
till chalice does auto layers, then the package set is transferred for each function, which explains the additional transfer volume

**Comment by vfilimonov** [comment]
Hello @kapilt 
That's true. But 45*2 = 90 - much lower than ~400Mb transferred.

What I've noticed - the amount transferred is not always same for redeployment of the same chalice app. Sometimes it is equal to the `N_functions * package_size`, but sometimes exceeds it by 2x-4x times.

**Comment by jamesls** [comment]
I'd have to take a look at the debug logs, but you could also be hitting retries.  For example, if we're uploading our python package and lambda times out or the connection is closed, we'll retry, but we have to start the upload over (for a given lambda function).  If you run this `--debug` you should be able to see if this is the case.

**Comment by vfilimonov** [comment]
Thanks, @jamesls !

Retries make sense, though a bit surprising that it was taking roughly same number of retries on consecutive deployments.
 
I've switched to lambda layers so I don't have that big packages anymore. But if this issue happens again, I'll do `--debug` and post here. I guess I'll could it meanwhile will reopen it if needed.
