### ISSUE TITLE
passing iam_role_arn as per sam

### ISSUE THREAD

**Issue by iamajay** [aws/chalice#1333]
I am using template merge feature where my policy will be generated by the sam and I need to provide that arn to my .chalice/config.json file and I am doing like:
```
      "manage_iam_role": false,
      "iam_role_arn": {
          "Fn::GetAtt": [
            "MyRole",
            "Arn"
          ]
        }
```
But it is not working is there any way I can refer to this IAM role ARN into my final sam.json file.

**Comment by jamesls** [comment]
So there's not a straightforward way to do this yet, but what you can do for now:

* Change the `iam_role_arn` in your `.chalice/config.json` to be a placeholder string value, e.g:

```
      "iam_role_arn":  "PLACEHOLDER"
```

In the template that you merge in, override the `Role` value with the value you expect.  So for example, this will generate:

```
    "APIHandler": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Runtime": "python3.7",
        "Handler": "app.app",
        "CodeUri": "./deployment.zip",
        "Tags": {
          "aws-chalice": "version=1.12.0:stage=dev:app=bar"
        },
        "Timeout": 60,
        "MemorySize": 128,
        "Role": "foo"
      }
    },
```

So then, in the template you're merging, you'd add:


```
{
  "Resources": {
    "APIHandler": {
      "Role": {"Fn::GetAtt": ["MyRole", "Arn"]}
    }
  }
}
```

You'll have to add this for every lambda function you want to use this role for.

That being said, I do want to make this easier, I think this is a common use case.  Supporting any arbitrary type in `.chalice/config.json` is going to make it harder to validate the config file so perhaps there's some special way you can indicate you want to pass this value directly to the underlying packager?  I'd need to think about it for a bit.

**Comment by iamajay** [comment]
@jamesls thanks for the help, Although there is slight edit in your example it would be like I need to add in my template:
`{
  "Resources": {
    "APIHandler": : {"Properties": {"Role": {"Fn::GetAtt": ["MyRole", "Arn"]}}},
    }
  }
}`
`Role` should be inside `Properties`, 
One more query how will I make sure that my lambda in app.py file will come as under the merged confige? like as you took example of `APIHandler`, what will be the name of my other lambda in sam.json.

**Comment by jamesls** [comment]
Looks like I missed this last comment.  The names of the resources in sam.json will be the function name converted to camel case so `def my_function(...) -> "MyFunction"`.  You can also control this by specifying the `name=` parameter to the decorator if you want more control.

Let me know if you have any more questions.
