### ISSUE TITLE
Suggesion: remove boto3 from deployment package unless explicitly included

### ISSUE THREAD

**Issue by vfilimonov** [aws/chalice#1335]
It is related to #1043, but I think that this optionality could be rather beneficial, so I'll bring this to the discussion.

As it is discussed in the issue above - when some packages have a dependency on `boto3`, it will be included in the deployment package. And the package itself is quite heavy: 50MB uncompressed and ~7 MB compressed, which eats quite a lot from the 50MB limit of AWS Lambda.

At the moment there's no elegant way of removing it (`pip` with `requirements.txt` does not support `--no-deps` arguments). So the only reasonable way to get rid of it that I found is to fork the library of interest (e.g. `s3fs`), change the dependencies there and point Chalice to the forked version, rather than pypi. But indeed it is a huge workaround and makes a lot of pain in maintaining the lambda.

Would it be possible to have an option to remove boto3 from the deployment package: 
- either that could be a command line option
- or maybe remove it, unless `boto3`/`botocore` it is stated explicitly in the `requirements.txt`
- or ability to add packages not via `requirements.txt` but with an explicit `pip` commands?

**Comment by ricky-sb** [comment]
Tangentially related: https://github.com/aws/chalice/issues/1001

**Comment by jamesls** [comment]
I'd like to improve the issue of pulling in a large SDK, but I'm hesitant to have an option to exclude boto3 from the deps, especially if it's a required dependency as part of your requirements.txt (even if it's transitively through some other dependency).

The specific issue here is that the package name itself is only part of the problem.  We also have to make sure the version constraints match what's required, and we have no way of knowing what version of boto3/botocore is on the lambda function.  Even if we had a static mapping, Lambda occasionally upgrades the version of the SDK in the Lambda functions so this can change with no way for us to identify this.

I'm a strong advocate for specifying your dependency versions and in general I don't think you should rely on the version of the SDK on the Lambda function.

I'd rather have something that's smart about building a smaller SDK.  For example, most apps are only using a handful of services, and many services don't have a large surface API.

Almost all of the size of the SDK comes from the JSON files that define the service's API:

```
/tmp/testsize/out/packages $ du -hs botocore
 42M	botocore
/tmp/testsize/out/packages $ du -hs botocore/data/
 41M	botocore/data/
```

So instead if you had a way to say "only include operations A, B, C from service X", then Chalice could build that smaller SDK for you.  In theory, it could even use the AST walking code form the policy generator to see what API calls you're making and automatically do this for you.  I had a branch that did this a while ago, but the policy/AST code is too experimental to do this automatically right now.

The other feature that would make this possible (if you really, really wanted to do this) would be deployment hooks, which is essentially giving you hooks into the deployment/packaging process to allow you to run any code that you want.

Let me know what you think.
