### ISSUE TITLE
Authorizer with Identity Pool

### ISSUE THREAD

**Issue by drisme** [aws/chalice#1338]
Hi,
I am trying to set up an authorizer in chalice to integrate with firebase as an authentication provider via OpenId and cognito identity pools. To my understanding I don't need to create cognito user pools for this scenario, only an identity pool. But when trying to setup the authorizer I get the following error:

'my_pool': ProviderARNs need to be valid Cognito Userpools. Invalid ARNs-

arn:aws:cognito-identity:us-east-1:xxxxxxxxxxxx:identitypool/us-
 east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        Unable to put method 'GET' 

Do I need to set up a cognito pool in addition to the identity pool, even though my authentication provider is outside of AWS? Most of the docs say that only the identity pool is necessary, so I am a bit confused. The Identity Pool ARN I used is taken from the "Edit Identity Pool" page. Is this the right format, or do I need to add a suffix to the ARN?  

Thanks!

**Comment by subssn21** [comment]
I use an Identity Pool and have my Authorizer set as an IAM Authorizer.

An Identity Pool gives a user a temporary IAM credential to access the API, so all you need is the IAM role setup properly for the Identity Pool and set the Authorizer to IAMAuthorizer

**Comment by jamesls** [comment]
Thanks @subssn21!  

To add on to that answer, the cognito user pool authorizer is separate and requires that you use cognito user pools.  You can just use an IAM authorizer, and then use the temporary IAM credeential to access the API as mentioned in the comment above.

Let me know if you have any additional questions.
