### ISSUE TITLE
Single Chalice Lambda to support both Schedule and Route

### ISSUE THREAD

**Issue by yks0000** [aws/chalice#1346]
Hi,

I am finding this framework easy and useful. Thanks for building. However, I want to know if it is possible to have both `route` and `schedule` in single app. Currently we do this by processing `event`, however I see if we have both `route` and `schedule`, it creates two lambda, one with app.app and another with `app.<<function_name_of_schedule>>`.

One use case is, refreshing cache at regular interval and keep it in lambda local `/tmp` path or in memory, so that if a request comes and cache found in local /tmp memory, it will be returned from there instead of fetching it from actual source.

**Comment by jamesls** [comment]
No this is not currently possible.  In general, it's difficult to control this behavior as Lambda can scale up/down the number of lambdas you have based on a number of factors.  There's no guarantee that two successive invocations of a lambda function will go to the exact same instance.

I think the approach you have with two separate lambda functions will still accomplish the same thing.  Your scheduled lambda function will periodically make an HTTP request to whichever route you want to have updated cache info for, and if a request happens to go to that same instance, it will retrieve the cached data.  They don't need to be the same lambda function to achieve this.

Let me know if you have any other questions.
