### ISSUE TITLE
Query param cant handle escaped special character

### ISSUE THREAD

**Issue by paultop6** [aws/chalice#1349]
When passing a query param with a special character, that has been escaped correctly, on receiving of the call at the registered route, the special character has been handled unencoded.

E.g.
`GET /?param=a&b`
Encoded to
`GET /?param=a%26b`

On receiving from chalice, the query_params looks as follows:
`{'param': ['a'], 'b': ['']}`

As can be seen the ampersand is handled unescaped.

**Comment by jamesls** [comment]
I'm not seeing that behavior.  Here's what I tried:


```
$ cat app.py
from chalice import Chalice

app = Chalice(app_name='url')


@app.route('/')
def index():
    return app.current_request.query_params

$ chalice deploy
...

$ http 'https://abcd.execute-api.us-west-2.amazonaws.com/api/?param=a%26b'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 15
Content-Type: application/json
Date: Tue, 25 Feb 2020 17:23:26 GMT
...

{
    "param": "a&b"
}
```

Can you show me an example app that demonstrates the behavior you're seeing?
