### ISSUE TITLE
Docker support for Chalice Local command

### ISSUE THREAD

**Issue by malli1246** [aws/chalice#1351]
Hi,

When I tried a hello-world serverless api/lambda using chalice in windows, local execution is working fine. But when the same is pushed to Docker instance I am not able to access the same. Verified the docker connectivity using node.js app and it seems to be working fine. 

Whether chalice local has any restriction on accessing from docker or some container environment?

Background- I am working on a serverless app using Chalice and NodeJs. Part of the team working on Windows and another part on MAC. The setup requires multiple settings like setting up virtual env, using vault etc. As most of the commands are using Shell scripts written in mac and facing some permissions issues in Windows, we wanted to try using Docker for running in local.

**Comment by malli1246** [comment]
Looks like this is an issue with the listerner and host mapping. When I run `chalice local --port=4000` in my local PC, the server is actually running against my localhost. where as when I run the same command I am getting a `connection refused` error. After searching for days, just found an article specific to this connection refused error

**Comment by malli1246** [comment]
Closing this as not an issue with Chalice

**Comment by alfdnl** [comment]
Hi man, can I see how did you implement this in your dockerfile?
