### ISSUE TITLE
To what extent can a chalice project be ported to a generic cloud platform?

### ISSUE THREAD

**Issue by yassineim** [aws/chalice#1367]
First of all thank you for the great work. I'm thinking of using chalice for our company's next project, however the eventual vendor lock-in is making me have second thoughts. See the title for my question. Thank you for any insights.

**Comment by jamesls** [comment]
The internals of chalice can be made cloud agnostic, as there's nothing specific about AWS except for the backend deployer creating an execution plan that specifies API calls, but it would take a considerable amount of work.

The API would need some updates as the names are AWS specific, e.g. `on_sqs_message`.

In general though, I suggest having the core parts of your application completely isolated from the integration with the cloud specific parts.  That way the bulk of the work in migrating only requires rewriting the integration points.

Hope that helps, let me know if you have any more questions.

**Comment by yassineim** [comment]
OK this does make sense. Thank you.
