### ISSUE TITLE
How does Chalice handle external or shared dependencies?

### ISSUE THREAD

**Issue by LBWright** [aws/chalice#1376]
If I were using MongoDB for my database instead of DynamoDB, how is that handled in each lambda instance? If I wanted to create a connection outside of the lambda, how would that be maintained inside of the Lambda? 

I'm having trouble understanding how Chalice handles general global or shared Python modules and the documentation is not super clear on this.

If I write my app with the following:
```
from libs import UserModel
app = Chalice(...)
db = MongoClient(...)

@app.route('/)
def get_items():
  return db.some_method()

@app.route('/an-entirely-different-route')
def get_different_things():
  user = UserModel(...)
  user.do_something()
  return db.some_different_method()
```

How are these db connections shared? If I were to add a Model that has the database instantiations, how would I need to handle that? I'm assuming the same is for redis, or for anything else that's thirdparty that might need to pool connections.

In addition, if I have code inside of my libs, how is that shared between Lambdas? Would the `user` above be packaged inside of each Lambda? How does each Lambda know the difference?

**Comment by jamesls** [comment]
When a lambda function is invoked for the first time, it will import your python module so any code at the module level will be run.  The specific function in your python module is then invoked.  If your lambda function is invoked again, this function "instance" can be reused.  This means that the module level code isn't rerun (the module is already imported) so only the python function code is run.  There's no specific details on specifically how many times this function instance will be reused.

There's also cases where additional function instances will be spun up, for example if your function is being invoked and a concurrent request comes in, then an additional instance will be created, which in turn will run your module level code again.  You can control this level of concurrency (docs [here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html#configuration-concurrency-provisioned)).

> How are these db connections shared?

They're not, but they will be reused as long as a specific function instance is being reused.

Let me know if you have any more questions.

**Comment by LBWright** [comment]
If I'm reading this correctly, any Lambda invoked will contain all of the code from the entire application? 

The rest makes sense, it would seem to operate the same as any other handler.

**Comment by jamesls** [comment]
> If I'm reading this correctly, any Lambda invoked will contain all of the code from the entire application?

Yes that's correct.
