### ISSUE TITLE
Select lambda functions to be deployed in config.json

### ISSUE THREAD

**Issue by vfilimonov** [aws/chalice#1380]
Maybe it is already discussed in issues, or already supported, but I could not find the reference. Please point me into right way in this case.

I think it would be useful if there was some way of choosing which functions should be deployed. As I understand, the only way to do this at the moment - is to comment out decorators (e.g. `@app.lambda_function`) prior to deploy.

The use case: When package has many functions (and maybe some heavy dependencies / triggers to create), when developing or debugging one specific lambda, it would be good to be able to deploy only it to `dev`, but not all of them. Beyond a simple saving deployment time and upstream traffic, you might not want other functions to be triggered accidentally.

**Comment by jamesls** [comment]
Hi, this is not possible and likely not something we'd want to do.  Think of this more like a "cloudformation deploy" where the entire set of resources/lambda functions is deployed as a single unit.

That does mean that if you have a lot of lambda functions, it can take some time to deploy.  There is some ongoing work on trying to cut down deployment times with lots of lambda functions by automatically using layers, which should drastically help (#1179, #1176).

Let me know if you have any more questions.

**Comment by vfilimonov** [comment]
Sounds reasonable. Thanks for the response, @jamesls
