### ISSUE TITLE
misleading error message when queue name in @app.on_sqs_message has invalid chars

### ISSUE THREAD

**Issue by alexramos1** [aws/chalice#1388]
When using @app.on_sqs_message, I'm unexpectedly receiving "The provided execution role does not have permissions to call ReceiveMessage on SQS".

After a lengthy investigation I determined the error occurred because I had specified the full queueUrl instead of just the queue name.

Chalice framework should validate the queue name in order to avoid generating this incorrect error message.

**Comment by jamesls** [comment]
Thanks for reporting.  I agree we should add additional validation here.
