### ISSUE TITLE
Chalice package generates invalid resource property type for AWS Lambda function 

### ISSUE THREAD

**Issue by vrinda1410** [aws/chalice#1397]
Hi @jamesls , @stealthycoin 

While using chalice's @app.schedule() decorator in the code & deploying that through chalice package, the following property is generated in SAM template
`Events:`
        `FunctionHandlerEvent:`
         ` Type: Schedule`
         ` Properties:`
         ` Schedule: rate(5 minutes)`
     ` FunctionName:function_handler`

Refer: https://github.com/aws/chalice/blob/6dc35c7ae590733e6d6a98d357bc8d28f7fbfa29/chalice/package.py#L158

**Based on these, AWS Cloudformation doesn't support this property for lambda function but AWS SAM does for functions as per**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-events

Can someone please suggest a resolution or a temporary workaround until this is fixed if it's a known issue. 

Awaiting response. Thanks !

**Comment by jamesls** [comment]
Can you clarify what problem you're running into?  The `package` command generates a SAM template, not a cloudformation template:

https://github.com/aws/chalice/blob/6dc35c7ae590733e6d6a98d357bc8d28f7fbfa29/chalice/package.py#L129

What happens when you try to deploy this?

**Comment by vrinda1410** [comment]
I know the SAM template generated supports this property type but when I try to deploy my code through these commands:
1. chalice package 
2. aws cloudformation package 
3. aws cloudformation deploy
mentioned here : https://chalice.readthedocs.io/en/latest/topics/cfn.html

CFN deployment fails with the following error:
--
Encountered unsupported property Events
--

**Comment by jamesls** [comment]
I'm not able to repro this issue.

We generate a template that specifies that the template is a SAM template so the `aws cloudformation deploy` shouldn't fail because cloudformation is treating it as a SAM template, not a CFN template. Can you give me an exact set of steps (commands + sample code) that you took that demonstrates this problem.  If I can repro this issue I'll be able to dive into why this is failing.

But just to reiterate again, this should be something that's fully supported and should work for you, so I'm curious what's going on here.

**Comment by vrinda1410** [comment]
I was able to get down to the underlying issue with this. The problem that SAM transform is not supported in cloudformation stacksets.

Ref: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/207

I am able to work with scheduled events when using normal cloudformation stacks with AWS Chalice but the deployment pipeline recently switched to cloudformation stacksets and that broke the existing setup.

Is there any way Chalice can handle this scenario until cloudformation starts supporting this ?

**Comment by jamesls** [comment]
Ah, good to know.

One option that might work for you is to run the sam translator locally to convert it to a cloudformation template using the sam-translate.py script https://github.com/awslabs/serverless-application-model/blob/develop/bin/sam-translate.py .  You'd have to make sure your app deployment is already uploaded to s3 (the `aws cloudformation package` part).

**Comment by vrinda1410** [comment]
Thanks for the input @jamesls 
I'll try it out using this python script.
