### ISSUE TITLE
Chalice app.websocket_api.send() is not working.

### ISSUE THREAD

**Issue by Justicism15** [aws/chalice#1406]
I have been using Chalice Websocket API and deployed in AWS API Gateway. The problem is that I always get a connection timeout once app.websocket_api() is called. It is not sending the message back to the connection_id. Please help me. Here are sample messages I received in my front-end:

Message {"message": "Endpoint request timed out", "connectionId":"Llf4ceE2NjMCF7w=", "requestId":"Llf7PFSNNjMFZeA="}

For my backend code (for debugging purpose, i set the on connect event to resend the message but it still produces the same error and not sending it to the websocket):

app = Chalice(app_name="dev-websocket")
app.websocket_api.session = Session()
app.experimental_feature_flags.update([
    'WEBSOCKETS'
])

@app.on_ws_connect()
def connect(event):
    app.websocket_api.send(event.connection_id, "Messsage fetched!")

**Comment by jamesls** [comment]
It looks like those are the API gateway logs.  Can you share the lambda logs for that handler?  You can also set `app.debug = True` to get more info.
