### ISSUE TITLE
blueprints and event handlers bug

### ISSUE THREAD

**Issue by beugene-orcher** [aws/chalice#1409]
I've tried to use the feature Blueprint and found that if you declared event handlers out of app.py, you get an incorrect deploying in AWS. The function will raise "Unable to import module `chalicelib.{module}`". The official doc (https://chalice.readthedocs.io/en/latest/topics/blueprints.html) described that "Blueprints support any decorator available on an application object". 

Example for reproducing:

```
# app.py
from chalice import Chalice
from chalicelib.views import mgmt

app = Chalice(app_name='test')
app.experimental_feature_flags.update([
    'BLUEPRINTS'
])

app.register_blueprint(mgmt.bp, url_prefix='/mgmt')

# chalicelib.views.mgmt
bp = Blueprint(__name__)
@bp.on_sns_message(topic='test_topic')
def test_sns(event):
    print('test')
```
Run `chalice deploy`.

The function's handler will be chalicelib.views.mgmt.test_sns. Test of the function returns
{
  "errorMessage": "Unable to import module 'chalicelib.views.mgmt'"
}

If declare a route in Blueprint, then it works good because it will deployed as a function with entry point in app.app.

**Comment by jamesls** [comment]
I'm not seeing that issue.  Are you sure you've made the `chalicelib` and `views` directories packages by adding an `__init__.py`?  Here's what I had:

```
.
├── app.py
├── chalicelib
│   ├── __init__.py
│   └── views
│       ├── __init__.py
│       └── mgmt.py
└── requirements.txt
```

When I deploy this I'm able to see the test message when I publish to my SNS topic:

```
$ aws sns publish --topic-arn arn:aws:sns:us-west-2:12345:TestTopic --message TestMessage

$ chalice logs -n test_sns
2020-04-28 12:29:26.261000 29722e test
```

**Comment by beugene-orcher** [comment]
@jamesls Yes, you're right! I missed `__init__.py` on `chalicelib` level. Thank you!
