### ISSUE TITLE
Error Handling - Exception message contains Exception code

### ISSUE THREAD

**Issue by M4rk3tt0** [aws/chalice#1411]
I don't know if this is a bug or an intended feature, but in the built-in exceptions the message contains the exception code + the message. 

This is the example retrieved from the documentation:
`{
    "Code": "BadRequestError",
    "Message": "This is a bad request"
}`

Instead the result of the operation is:
`{
    "Code": "BadRequestError",
    "Message": "BadRequestError: This is a bad request"
}`

**Comment by jamesls** [comment]
Unintended, originally reported in https://github.com/aws/chalice/issues/1339.  I'm fine removing it if someone wants to send a PR.  Let's track this over in #1339
