### ISSUE TITLE
documentation issue w.r.t to 'chalice generate-pipeline' and python 3.8

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1412]
Even though I have used 'chalice deploy' successfully with python 3.8, 'chalice generate-pipeline' will not work because AWS CodeDeploy does not yet support python 3.8.

It would help if the docs mentioned this and maybe put a timeline for when CodeDeploy plans to add that support.

It would also help if there were instructions to set up a pipeline using github actions. I have found this: https://github.com/marketplace/actions/chalice-extended-action

But I am not sure if it is reliable and in heavy use.

**Comment by devangmehta123** [comment]
I have read the documentation more closely and I think that that a good way forward is to use the 'chalice package' command to generate a terraform config and it works quite well. 

I have been able to create and destroy my environment several times this way.

But I want to configure some more things. For example, I added my own main.tf file to create a VPC and terraform seems to do the right thing by making the lambda function inside this new VPC.

My annoyance now seems to be the setting of certain parameters for terraform. For example, chalice correctly assumes that region should not be hardcoded in the 'aws' provider. But that forces 'terraform plan' and 'terraform apply' to ask this question on the command line. 

Ideally, to be able to run terraform without console input. I want to keep chalice.tf.json in source control along with my main.tf which further customizes the environment. Ideally, I should never have to hand edit or merge chalice.tf.json.

I can add the region inside chalice.tf.json but I wish there was a way to override the provider settings from my main.tf file. That way, chalice.tf.json will always be a generated file which is only changed by chalice.

**Comment by devangmehta123** [comment]
I have made some more progress on this. Terraform cloud integrates very well with github actions. I have been able to trigger the formation of the infrastructure quite easily. At this point, maybe this issue becomes a feature request. What would be helpful is for `chalice package --pkg-format terraform --s3-key s3://..... tf-dev`. It is still helpful to put generate the TF config file to put inside source control. But the package.zip is probably better off in s3 with the TF file having a link to that object.

**Comment by jamesls** [comment]
Awesome, thanks for the feedback.  I like the idea of adding an `--s3-key` where we can upload the package.zip for you.  I'll also look into updating the docs about 3.8.

FWIW, I've not seen https://github.com/marketplace/actions/chalice-extended-action before.  It's not something we've created or maintain, but it does look interesting.

**Comment by jamesls** [comment]
Closing out old issue, there's a new v2 version of the `generate-pipeline` command that addresses this (along with updated docs).
