### ISSUE TITLE
Authorizer for on_ws_connect

### ISSUE THREAD

**Issue by fernandoflorez** [aws/chalice#1413]
Hello,

I'd like to work on a PR to have the option to have an authorizer for the on_ws_connect handler.

Any guidance on where should i start? Have tried to place logs everywhere in order to understand the code flow but I don't even see the messages on cloudwatch after a deployment.

Since the $connect is just a route it should be possible to extend the decorator to pass the extra param to the registration handler, right?

Thanks,

**Comment by fernandoflorez** [comment]
Got it!

**Comment by jamesls** [comment]
Hi, sorry for the delay on this.  It'll depend on [what type of authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-control-access.html) you want to support.  For a Lambda authorizer you'd have to create the additional lambda function and then pass that that arn when creating the $connect route.  More info here: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-lambda-auth.html.  Let me know if you have any more questions, I can help with the PR.
