### ISSUE TITLE
Multiple origin CORS with IAMAuthorizer

### ISSUE THREAD

**Issue by 3dw1np** [aws/chalice#1418]
I tried to set up multiple CORS origins with the example given in the documentation but with an authorizer, it didn't work as expected. I received a 403 error response.

```
from chalice import Chalice, Response

app = Chalice(app_name=config.API_NAME)
authorizer = IAMAuthorizer()

@app.route('/auth/me', methods=['POST', 'OPTIONS'], authorizer=authorizer)
def auth_me():
	method = app.current_request.method
	if method == 'OPTIONS':
		headers = {
			'Access-Control-Allow-Method': 'POST,OPTIONS',
			'Access-Control-Allow-Origin': ','.join(config.ALLOWED_ORIGINS),
			'Access-Control-Allow-Headers': ['Authorization', 'Content-Type', 'X-Amz-Date', 'X-Amz-Security-Token', 'X-Api-Key']
		}

		origin = app.current_request.headers.get('origin', '')	
		if origin in config.ALLOWED_ORIGINS:
			headers.update({'Access-Control-Allow-Origin': origin})

		return Response(
			body=None,
			headers=headers,
		)

	elif method == 'POST':
		return 'Foo'
```

```
STATUS: 403 Forbidden
{
  "message": "Missing Authentication Token"
}
```

**Comment by jamesls** [comment]
That error message is tricky because it can either mean you're not making it past the authorizer *or* you're accessing a route that doesn't exist.

Can you share the client code you're using to make the authorized request?

**Comment by 3dw1np** [comment]
I am using the Amplify API lib to do the request who manage signed requests against Amazon API Gateway when the API Gateway Authorization is set to AWS_IAM, right ?

Just to let you know, if I setup the Cors=True, it's working so I am sure that the route exists.

Many thanks for your help !

**Comment by jamesls** [comment]
So I'm not as familiar with the specifics of how the amplify lib is making requests, but if the browser is the one making the preflight OPTIONS request, then I don't think it would be signed with sigv4.  I'd check the network calls being made and verify that the OPTIONS request has the appropriate Auth headers included.  Although I'm not sure if you'd actually want an auth'd OPTIONS call.

**Comment by 3dw1np** [comment]
I don't see the OPTIONS request it seems to be remove in the newest version of chrome. 
I will try with firefox.

[https://httptoolkit.tech/blog/chrome-79-doesnt-show-cors-preflight](https://httptoolkit.tech/blog/chrome-79-doesnt-show-cors-preflight)

**Comment by jamesls** [comment]
Just following up on this, were you able to see the pre-flight request in chrome?
