### ISSUE TITLE
proposal for documenting recipes

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1420]
I would like to ask if there is an existing proposal to document various recipes. For example, in order to make Terraform cloud work, I had to do some heavy discovery myself (granted that I am still learning about infra as code)).

I am now on a similar journey w.r.t. to fully local testing, for example, with localstack.

I have recently tested serverless framework. 

It is great but I could not see it having a definitive advantage over Chalice in any way unless you really needed to be multi-language or multi-cloud at some point.

Most micro-services are by definition small fits of functionality. I think micro-frameworks tuned to a particular language and cloud and which allow clutter are inherently better for that.

But we should make it easy for individuals to become productive, rather than having to discover these integrations all by themselves.

I could contribute my recipes to Chalice if there was some kind of section in the documentation for it. Still quite new to the open source separate repo + PR process and don't quite understand the structure of the document generation yet.

Maybe you could help me there.

**Comment by jamesls** [comment]
Sure no problem, thanks for the interest.

I think for recipes that are common to Chalice, it makes sense to have them as part of the core Chalice documentation.  For example, if there's anything you think we could improve for the terraform documentation (https://chalice.readthedocs.io/en/latest/topics/tf.html) that would be great).

We're working on some improvements to local testing now, so I'd probably hold off on the localstack integration documentation for the time being.

For contributing, there's general information in our [contributing guide](https://github.com/aws/chalice/blob/master/CONTRIBUTING.rst), but for docs specifically, once you have your dev environment set up, you'd just run `make doccheck` to generate the docs (we use sphinx for our docs if you're familiar with that).  If also runs some basic linting on the docs to ensure there's no syntax errors.

All of the docs are stored under the `docs/source/` directory here: https://github.com/aws/chalice/tree/master/docs/source

Let me know if you have any more questions.
