### ISSUE TITLE
Make POST calls within chalice apps

### ISSUE THREAD

**Issue by vrinda1410** [aws/chalice#1421]
Hi.
I have a use case where I need to send post data to another another service but I can't find any library within chalice to do so? 
Please suggest solution on how can I make POST call with chalice ?

Thanks!

**Comment by jamesls** [comment]
Do you mean from within an `@app.route()` function you want to make a POST call to another service?  If so, I'd use whichever http library you prefer to do so.  The [requests library](https://requests.readthedocs.io/en/master/) is the most popular and you'd just do `requests.post('https://my/api')`.

If you're talking about making a POST request directly form an API gateway route bypassing Lambda entirely, then that's something that Chalice doesn't support.

**Comment by vrinda1410** [comment]
I'm using python requests module but there's a problem with that too.
Making post to an API gateway which uses resources policies, the request has to be signed which isn't supported by requests library. Now to do that, I've to use yet another 3rd party library just for signing it with AWS signature. 
All of it not only makes the code logic complex but also bloats up the package size.

I believe, chalice should address this in some manner.

**Comment by jamesls** [comment]
I agree that it should be easier to do this, but I think making sigv4 signed HTTP requests makes more sense in the python SDK (boto3), which already makes signed HTTP requests to AWS services.  It would be a few small tweaks to enable making requests to arbitrary endpoints.

**Comment by vrinda1410** [comment]
@jamesls - Right now, I'm making a cross-account POST call from lambda in AccountA using python requests module to lambda in AccountB & it's failing at whitelisted resource policy at API Gateway in AccountB.
The error that I get -
Exception: "MissingAuthenticationTokenException"
Message: "Missing Authentication Token"

Only solution I could find to address this ^ is signing requests with https://github.com/DavidMuller/aws-requests-auth

Is there another way to address this problem ? If yes, can you point me to that.

Awaiting response. Thanks!

**Comment by jamesls** [comment]
Yes, you should be able to use that module in order to generate an signed request.  If you're already using the requests library it's a good choice because it integrates with the auth system in requests.
