### ISSUE TITLE
Lambda execution fails while using scheduled event (Rate & Cron class)

### ISSUE THREAD

**Issue by vrinda1410** [aws/chalice#1436]
My lambda function is running into invocation errors while using scheduled events. I'm nowhere trying to refer event object in my code. Also this is happening with both Rate & Cron events
Here's the error details:
`[ERROR] KeyError: 'version' `
`Traceback (most recent call last):`
  `File "/var/task/chalice/app.py", line 1428, in __call__`
    `event_obj = self.event_class(event, context)`
 `File "/var/task/chalice/app.py", line 1456, in __init__`
      `self._extract_attributes(event_dict)`
 `File "/var/task/chalice/app.py", line 1467, in _extract_attributes`
    `self.version = event_dict['version']`

Lambda function structure is as follows:
`@app.schedule(Cron('0/15', '*', '*', '*', '?', '*'))`
`def func_name(event,context):`
    `try:`
       ` // Post call to an endpoint using requests.post()`
    `except: `

**If I change the signature of my function, the error changes**
Lambda function structure is as follows:
`@app.schedule(Cron('0/15', '*', '*', '*', '?', '*'))`
`def func_name():`
    `try:`
       ` // Post call to an endpoint using requests.post()`
    `except: `

Changed error details:
`[ERROR] TypeError: rds_info_handler() takes 0 positional arguments but 1 was given `
`Traceback (most recent call last):`
`File "/var/task/chalice/app.py", line 1429, in __call__`
   `return self.func(event_obj)`

Any suggestions why this might be happening ?

**Comment by vrinda1410** [comment]
@jamesls, @stealthycoin - Can you guys please look into this ? 

Thanks!

**Comment by jamesls** [comment]
Hi, the function takes a single argument `event`.  Here's the docs with more info: https://aws.github.io/chalice/topics/events.html#scheduled-events

Can you try this:

```python
app = chalice.Chalice(app_name='foo')

@app.schedule(Rate(1, unit=Rate.HOURS))
def every_hour(event):
    print(event.to_dict())
```

**Comment by vrinda1410** [comment]
It worked as expected. Thanks
