### ISSUE TITLE
1.15 update broke packaged wheels

### ISSUE THREAD

**Issue by griff4594** [aws/chalice#1437]
Since the update from yesterday to 1.15.0 our team is getting a new error from packaged modules in the vendors directory:

`[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'pyrsistent'`

**Comment by jamesls** [comment]
Taking a look, is there a set of steps I can follow to setup a similiar vendors directory that demonstrates the problem?

**Comment by griff4594** [comment]
![Screen Shot 2020-06-16 at 10 11 03 AM](https://user-images.githubusercontent.com/4130905/84799678-dc6a8380-afb9-11ea-8f28-f7b8eab1e570.png)

**Comment by jamesls** [comment]
Just to clarify, are you saying the package/deploy commands ran without any errors, but you're seeing this when you try to invoke your lambda function?  I'm having trouble reproducing this issue, but this might be related to https://github.com/aws/chalice/pull/1435 (not in the 1.15.0 release) which was introduced from this PR which did make it in the 1.15.0 release https://github.com/aws/chalice/pull/1425/files.

Looking over your vendor directory there should also be a `pyrsistent/` directory that seems to be missing, which suggests that wheel wasn't built.

**Comment by jamesls** [comment]
I just pushed a release that should fix this, 1.15.1.  Could you retest and let me know if that fixes the problem for you?

**Comment by griff4594** [comment]
its fixed

**Comment by griff4594** [comment]
thx for the update!!
