### ISSUE TITLE
CognitoUserPoolAuthorizer is not supporting the client credentials local

### ISSUE THREAD

**Issue by muriloviana** [aws/chalice#1447]
Hello everyone,

Recently support was added to run `CognitoUserPoolAuthorizer` locally (https://github.com/aws/chalice/blob/master/CHANGELOG.rst#1131). However, when running it with the client credentials auth flow, the following error raises:

```shell
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55311)
Traceback (most recent call last):
  ...
  File "/Users/muriloviana/.virtualenvs/chalice/lib/python3.7/site-packages/chalice/local.py", line 324, in authorize
    "principalId": claims["cognito:username"]}
KeyError: 'cognito:username'
----------------------------------------
```

Everything works fine when we use the code grant flow to authenticate. As we are using machine-to-machine communication, client credentials are the best approach for us.

Possible solution for now: ignore the client credentials in local mode.

**Comment by jamesls** [comment]
Resolved via #1448.
