### ISSUE TITLE
Issue with Blueprint and Pure Lambda Functions

### ISSUE THREAD

**Issue by madhavmehta1** [aws/chalice#1451]
I am using Blueprint for API endpoints and Pure lambda functions. I am able to successfully register my endpoints and hit them, but the lambda functions that interact with these endpoints are not being registered because I get an error message that says this:
`"errorMessage": "Handler 'function_name'  missing on module 'app'","errorType": "Runtime.HandlerNotFound"`

In the chalicelib directory, I have:
`__init__.py`
`api_endpoints.py`
`pure_lambdas.py`

The app.py is setup like this:

    from chalicelib.api_endpoints import api_endpoints
    from chalicelib.pure_lambdas import pure_lambdas
    app = Chalice(app_name='app-name')
    app.experimental_feature_flags.update(['BLUEPRINTS'])
    app.register_blueprint(api_endpoints)
    app.register_blueprint(pure_lambdas)

The pure_lambdas.py is setup like this:

    pure_lambdas = Blueprint(__name__)

    @pure_lambdas.lambda_function(name='NAME')
    def function_name(event, context):
            [code]

    @pure_lambdas.lambda_function(name='NAME1')
    def function_name1(event, context):
            [code]

When I keep the lambda functions within app.py, everything runs properly. I just can't get it to work when I use Blueprint.

**Comment by rajpdus** [comment]
Hey Madhav,

Blueprints are meant to only augment and arrange your URL routes just like Flask and not pure lambdas. Documentation [here](https://aws.github.io/chalice/topics/blueprints.html).

I would suggest one of two things either move your pure lambdas to `app.py` or do this in `pure_lambdas.py`

```
from app import app as pure_lambda

@pure_lambdas.lambda_function(name='NAME')
def function_name(event, context):
        [code]

@pure_lambdas.lambda_function(name='NAME1')
def function_name1(event, context):
        [code]
```

**Comment by jamesls** [comment]
> but the lambda functions that interact with these endpoints are not being registered

@madhavmehta1 Can you clarify what you mean here?  How are the lambda functions interacting with the endpoints?  By making HTTP requests to the specific routes?

The configuration you have should work here, and when I try to repro this issue it's working for me.
I used the same setup you have, and I also added a basic rest API for the ``api_endpoints`` file:

```
$ cat chalicelib/api_endpoints.py
from chalice import Blueprint

api_endpoints = Blueprint(__name__)


@api_endpoints.route('/')
def index():
    return {'hello': 'api'}
```

I also added boiler plate code in the lambda functions you had:

```
$ cat chalicelib/pure_lambdas.py
from chalice import Blueprint

pure_lambdas = Blueprint(__name__)

@pure_lambdas.lambda_function(name='NAME')
def function_name(event, context):
    return {'foo': 'bar1'}


@pure_lambdas.lambda_function(name='NAME1')
def function_name1(event, context):
    return {'foo': 'bar2'}
```

When I deploy the app, it seems to be working fine for me:

```
$ chalice deploy
Creating deployment package.
Creating IAM role: bplambda-dev
Creating lambda function: bplambda-dev-NAME
Creating lambda function: bplambda-dev-NAME1
Creating lambda function: bplambda-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-east-1:12345:function:bplambda-dev-NAME
  - Lambda ARN: arn:aws:lambda:us-east-1:12345:function:bplambda-dev-NAME1
  - Lambda ARN: arn:aws:lambda:us-east-1:12345:function:bplambda-dev
  - Rest API URL: https://abcd.execute-api.us-east-1.amazonaws.com/api/

```

Verify the REST API works:

```
$ http https://39g3wqnnoc.execute-api.us-east-1.amazonaws.com/api/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 15
Content-Type: application/json
Date: Wed, 15 Jul 2020 18:52:24 GMT
Via: 1.1 27eb501c8caff149895f88cac34554af.cloudfront.net (CloudFront)
X-Amz-Cf-Id: emrvvA5B2FEJFQoSnYqjJXUewjMUxmlPS7Rp8rpgmE9SmR63m5vsgw==
X-Amz-Cf-Pop: IAD89-C2
X-Amzn-Trace-Id: Root=1-5f0f5068-11b05d981e6504664010a9c2;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: PumATG9nIAMF1Lg=
x-amzn-RequestId: 43dedfc5-ebb3-4245-81d1-73b4fc4f937f

{
    "hello": "api"
}

```

Verify we can invoke our lambda functions:

```
$ chalice invoke -n NAME
{"foo": "bar1"}
$ chalice invoke -n NAME1
{"foo": "bar2"}
```

Do you see that same behavior with that sample code?

**Comment by madhavmehta1** [comment]
@jamesls One of the lambda functions was meant to handle API requests - however, I no longer need it. I still have one pure lambda function that I need as part of the project, but it does not interact with my API.

I ran the sample code you provided,  and I get an error saying this when invoking the lambda functions:
    Error: could not find lambda function named NAME.

Do I need to run app.register_lambda_function() and pass parameters to that? I am currently registering it as a blueprint. If so, what should the code look like?

**Comment by madhavmehta1** [comment]
@rajpdus The documentation says the concept is extended to ALL Chalice resources:
```
Note
The Chalice blueprints are conceptually similar to Blueprints in Flask. Flask blueprints allow you to define a set of URL routes separately from the main Flask object. This concept is extended to all resources in Chalice. A Chalice blueprint can have Lambda functions, event handlers, built-in authorizers, etc. in addition to a collection of routes.

**Comment by jamesls** [comment]
@madhavmehta1 I used the same app.py you had in your original comment.  For completeness this is the app.py file:

```
$ tree
.
├── app.py
├── chalicelib
│   ├── __init__.py
│   ├── api_endpoints.py
│   └── pure_lambdas.py
└── requirements.txt
```

```
$ cat app.py
from chalice import Chalice
from chalicelib.api_endpoints import api_endpoints
from chalicelib.pure_lambdas import pure_lambdas

app = Chalice(app_name='app-name')
app.experimental_feature_flags.update(['BLUEPRINTS'])
app.register_blueprint(api_endpoints)
app.register_blueprint(pure_lambdas)
```


My `api_endpoints.py` and  `pure_lambdas.py` are exactly what was shown in my [previous comment](https://github.com/aws/chalice/issues/1451#issuecomment-658942974).

**Comment by madhavmehta1** [comment]
@jamesls I don't understand what is wrong with my configuration then. I will try to replicate the basic code and post what the function invocation results in
