### ISSUE TITLE
New version 1.15.1 && scopes

### ISSUE THREAD

**Issue by Ph4rell** [aws/chalice#1452]
Hi, 

I updated my Chalice version to 1.15.1 with pip, to get the last updates, specially scopes integration.

I updated my code with scopes and got errors like `AttributeError: 'CognitoUserPoolAuthorizer' object has no attribute 'with_scopes'`

I checked in my venv, sites-packages where chalice is install, in the `app.py` i'got the `__version__ = '1.15.1'`, but the code about scopes is not here. 

Someone can explain me if i did something wrong ?

MyCode:
```
authorizer = CognitoUserPoolAuthorizer(
    'API-DNS-UserPool', header='Authorization',
    provider_arns=[environ['cognito']])
```
```
@app.route(
    '/dns/public/records', 
    methods=['POST'], 
    authorizer=authorizer.with_scopes(["DNS/post"]))

```
`chalice --version
chalice 1.15.1, python 3.6.1, darwin 19.5.0`

Regards,
Pierre

**Comment by jamesls** [comment]
The `with_scopes` method is not part of a release yet.  It was merged a few weeks ago (https://github.com/aws/chalice/pull/1444).  Is it possible you're installing from the latest master branch somehow?

**Comment by Ph4rell** [comment]
The pip method install the latest master version or the latest release ?

**Comment by jamesls** [comment]
It should install the latest release.  I double checked the 1.15.1 tag and you can see that there's no `with_scopes` method: https://github.com/aws/chalice/blob/1.15.1/chalice/app.py#L222.

I also downloaded the latest chalice release from pip via `pip download chalice` and verified that the `with_scopes()` method is not there.  I'm not sure how you pulled in the latest code from the master branch.  It might be easiest to just recreate your virtualenv again.

**Comment by Ph4rell** [comment]
OK thank you !
