### ISSUE TITLE
Problem with big images processing with rasterio/gdal.

### ISSUE THREAD

**Issue by samveljanvelyan** [aws/chalice#1456]
Hi all,

The main goal of my lambda is to have my final Geotiff uploaded to s3. The function under the hood receives a message from SQS then is making a request to a tile server using rasterio assembling tiles in memory by using a Window function. In the end, I have the GeoTIFF which in order needs to be uploaded to S3. 

Locally it works fine. After deploying when I send sqs message with small size raster it works on lambda as expected, but when I increase the size I get the following error.

[
![Screenshot from 2020-07-17 17-30-26](https://user-images.githubusercontent.com/50568658/87792101-755c1b00-c854-11ea-9884-c9336857d243.png)
](url)

I have provided a destination_profile in the following way.

`{
        'driver': "GTiff",
        'count': 3,
        'height': image_height,
        'width': image_width,
        'dtype': "uint8",
        'nodata': 0,
        'crs': "epsg:3857",
        'transform': geo_transform,
        'bigtiff': "YES"
    }`
Here is the full list of my requirements.txt

requests
boto3
numpy
mercantile
rasterio==1.0.24
GDAL==2.4.4
affine
tqdm
Pillow
nap

Can you please provide some hints how to cope with this?

**Comment by jamesls** [comment]
Can you show me the specific error you're getting from Lambda?  Does it exit before it's finished?  If you get a "Process exited before completing request" this could be due to the timeout or memory limits being hit, which you can configure to larger values (https://aws.github.io/chalice/topics/configfile.html#lambda-memory-size).

**Comment by samveljanvelyan** [comment]
The message sent from SQS keeps remaining in in flight stage and the lamba function keeps invoking permanently. The specific error is the one whic is being shoen on the screenshot at my previous comment. After some time cloudwatch says that the limit of error messages exceeded 1000 and it will not show it anymore. The raster that I'm trying to process is just 209 MB, I configured my lambda to have 1024 MB of RAM and it has been mounted to the EFS.

I guess that my lambda somehow misses some gdal depencdencies which I cant figure out. Because locally irlt works just fine. 

![Screenshot_20200718-105228_Chrome](https://user-images.githubusercontent.com/50568658/87846926-d4697080-c8e4-11ea-9a14-7dca66a74acb.jpg)

**Comment by jamesls** [comment]
Cool, glad you were able to figure it out.
