### ISSUE TITLE
How to get lambda context with websockets?

### ISSUE THREAD

**Issue by rafagan** [aws/chalice#1458]
Using routes, I can access a context in this way:
`app.current_request.context['authorizer']['user_id']`

But with websockets the `current_request` is null. How can I achieve that?

**Comment by jamesls** [comment]
If should be available via the `event.context` in the arg that's passed to the handler:

```python
@app.on_ws_message
def handler(event):
    context = event.context
```

Let me know if that doesn't work for you, although based on your code we'll need to add support for authorizers to websockets first.
