### ISSUE TITLE
Broken click dependency

### ISSUE THREAD

**Issue by crawforde** [aws/chalice#1462]
Chalice: 1.16.0
Python: 3.7.7

After installing dependencies and running `chalice --version`, I got the following error:
```
Traceback (most recent call last):
  File ".chalice/venv/bin/chalice", line 7, in <module>
    from chalice.cli import main
  File ".chalice/venv/lib/python3.7/site-packages/chalice/cli/__init__.py", line 530, in <module>
    type=click.Choice(['json', 'yaml'], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
```

Upgrading the `click` package to major version 7 fixed the issue. Seems that the one installed by default (version 6) is broken.

**Comment by jamesls** [comment]
Thanks for reporting.  It looks like our version range allows for v6 (https://github.com/aws/chalice/blob/master/setup.py#L10) so if something else was already pulling in v6 of click it wouldn't upgrade click.  I'll update Chalice to lock to major version 7.
