### ISSUE TITLE
Add ARM64 support to Chalice

### ISSUE THREAD

**Issue by odidev** [aws/chalice#1464]
Hi Team,

Currently, Chalice is running on the x86_64 platform. There are ‘wheels’ binaries being downloaded, which are available for x86_64, but are unavailable for ARM64. It will be very helpful if we have ARM64 wheels available. May I know, if you are planning on releasing ARM64 wheels?

**Comment by jamesls** [comment]
Chalice doesn't provide any binary wheel files as part of its release assets.  It doesn't have any native dependencies so we're able to release a single wheel file that's compatible on all platforms, as you can see on our downloads page here: https://pypi.org/project/chalice/#files.

You should be able to use the wheel we publish on pypi on ARM platforms.
