### ISSUE TITLE
Chalice- CORS issue when using Custom Authorizers and accessing from multiple domains

### ISSUE THREAD

**Issue by RahulChowdaryN** [aws/chalice#1472]
Thank you for the wonderful framework. It's helping me and my team a lot.

I deployed chalice app using custom authorization. And then when I try to hit the api from different domains it's giving me the cors issue. Here are the details

This is my simple cors config:

cors_config = CORSConfig(
    allow_origin='*',
    max_age=600,
    allow_credentials=True
)

API Method-1:
@app.route('/custom_cors', methods=['GET'], cors=True)
def supports_custom_cors():
    return {'cors': True}
The error for this method is 

**Access to XMLHttpRequest at 'https://------amazonaws.com/api/custom_cors_test' from origin 'https://www.google.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

API Method-2:

@app.route('/custom_cors_test', authorizer=jwt_auth, methods=['GET'], cors=cors_config)
def test_custom_cors():
    return {'cors': True}

The error for this method is

**Access to XMLHttpRequest at 'https://---------amazonaws.com/api/custom_cors' from origin 'https://www.google.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.**

As far as I understand this is because I'm using the credentials for custom authorization.

I've tried few alternatives and  It worked when I passed a single domain in cors_config instead of * and access from that domain. But, **I want to access from multiple domains without any cors issue.**

**I also tried to enable in api-gateway and redeploy but it didn't work.**

Is there a way to handle this in Chalice.

**Comment by RahulChowdaryN** [comment]
while going through the documentation I found this

```
from chalice import Chalice, Response

app = Chalice(app_name='multipleorigincors')

_ALLOWED_ORIGINS = set([
    'http://allowed1.example.com',
    'http://allowed2.example.com',
])

@app.route('/cors_multiple_origins', methods=['GET', 'OPTIONS'])
def supports_cors_multiple_origins():
    method = app.current_request.method
    if method == 'OPTIONS':
        headers = {
            'Access-Control-Allow-Method': 'GET,OPTIONS',
            'Access-Control-Allow-Origin': ','.join(_ALLOWED_ORIGINS),
            'Access-Control-Allow-Headers': 'X-Some-Header',
        }
        origin = app.current_request.headers.get('origin', '')
        if origin in _ALLOWED_ORIGINS:
            headers.update({'Access-Control-Allow-Origin': origin})
        return Response(
            body=None,
            headers=headers,
        )
    elif method == 'GET':
        return 'Foo'
```
Any suggestions on integrating this with all my existing routes would be helpful.

**Comment by jamesls** [comment]
Ideally there'd be a way to do this with middleware (which isn't supported yet) but for now you'd have to explicitly decorate every route that needs this behavior (i.e extract out the multiple origin code into a separate decorator that you then add to every route).  That's probably your best option.
