### ISSUE TITLE
Add REST API ID to Terraform outputs

### ISSUE THREAD

**Issue by jrbeilke** [aws/chalice#1477]
Attempting to integrate a Chalice app with other parts of an application which has already been terraformed.

It would be very helpful to have the REST API ID available as a Terraform output so we can manage other resources with Terraform such as custom domains, usage plans, etc which are not currently supported within Chalice.

**Comment by jamesls** [comment]
Seems reasonable to me.  I've merged your PR for this, https://github.com/aws/chalice/pull/1478
