### ISSUE TITLE
Need help with chalice local with Cognito

### ISSUE THREAD

**Issue by harshavardhangsv** [aws/chalice#1479]
I am creating apigateway endpoint with cognito authorizer. I want to test that locally using `chalice local` . 
can someone help me on where to find the documentation on how to provide test data for it to work locally? I did browse through `https://aws.github.io/chalice` but I didn't find anything regarding this.

thanks in advance

**Comment by jamesls** [comment]
The local mode only supports the [builtin authorizers](https://aws.github.io/chalice/topics/authorizers.html#built-in-authorizers).  If you're using the cognito user pool auth it will always succeed (and log a warning that it's not supported).  You just need to provide a JWT token in the Authorization header with a `cognito:username` claim.  Let me know if you're still having trouble with this.

**Comment by harshavardhangsv** [comment]
@jamesls thanks for the reply. yes, it worked for me. I also went through the code and figured it out. I used the the IDToken generated after the authentication from cognito and it worked
