### ISSUE TITLE
Chalice deploy required policies  

### ISSUE THREAD

**Issue by usmandap** [aws/chalice#1481]
I am using administrator IAM user for running chalice as I am unable to find the required managed policies for chalice. I believe giving administrator access to IAM user responsible for chalice deployment is a good idea. Could anyone please guide me what I am missing or if I could get the required managed policies that will allow me to run chalice deploy. Thanks

**Comment by jamesls** [comment]
We could try and generate minimal policies for what's needed to deploy a chalice application, the only complication is that 1) it depends on what features you're using, for example if you're not using `@app.on_s3_event` then we don't need any S3 permissions, so the policy would depend on your application and 2) if we included a list of all the service needed by chalice that list might change over time as we add support for more features/services.

There's some work on this over in https://github.com/aws/chalice/issues/59.
