### ISSUE TITLE
Terraform + stages

### ISSUE THREAD

**Issue by joriskoris-emburse** [aws/chalice#1489]
Hi,

I am struggling to figure out a decent way to deploy various stages while using Terraform packaging.

Problems I run into are:

1. Deploying a single stage is just fine - but adding a second stage and interpolating stage variable, will inevitably have Terraform thinking it needs to destroy/recreate resources, making it impossible to have gateway with different stages.
2. Do the above, but with different state files (or workspaces). However, then reusing the gateway is also impossible, since new gateway will just be created.

Any suggestions?

**Comment by jamesls** [comment]
How are you intending to use chalice stages?  I don't fully understand what the first problem you're talking about.  Could you give me more information?

**Comment by joriskoris-emburse** [comment]
Sure - suppose we want to avoid Cloudformation deploys and want to instead just use Terraform. How would you go about setting up 1 api gateway + several api gateway stages using Terraform outputs?

**Comment by jamesls** [comment]
Ah, it sounds like you're asking if we support multiple API gateway stages so you might have one API gateway but different lambda functions on the backend based on the stage.

If that's the case then you are correct, it's not possible in Chalice.  We have a 1:1 mapping with an API Gateway API and an API Gateway stage.

**Comment by joriskoris-emburse** [comment]
Gotcha, thanks for confirming!
