### ISSUE TITLE
PEP 561 support (consume Chalice's mypy types outside of Chalice)

### ISSUE THREAD

**Issue by wimax-grapl** [aws/chalice#1499]
Hi there!

PEP 561 is an accepted proposal that would allow programs that consume Chalice to use its mypy types. This would be greatly appreciated addition to Chalice, and relatively low-hanging fruit. 

https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages

I've created a fork of this that I'll add as a PR :)

**Comment by jamesls** [comment]
Sounds good!  Reading over the pep, it sounds like all that's need is to create a `py.typed` file and add it to the package data in the `setup.py`.

**Comment by wimax-grapl** [comment]
Yep! I've added a PR :)

**Comment by jamesls** [comment]
Merged, thanks for adding this.

**Comment by wimax-grapl** [comment]
Thanks for acting so quickly :)
