### ISSUE TITLE
Binary data is returned base64 encoded 

### ISSUE THREAD

**Issue by andy-imt** [aws/chalice#1501]
I am attempting to use Chalice to return a PDF file.  It works fine with `chalice local`, but when live, all the content returned is base64 encoded instead of returning raw bytes.  I believe I am following all of the guidelines to get this to work: I am setting the Content-Type header, that type is added to binary_types, and the data I am providing is of type 'bytes'.

I have built a minimal test case, using a PDF file in /vendors/test.pdf:

* app.py
```python
from chalice import Chalice, Response, NotFoundError

from pprint import pprint

app = Chalice(app_name='pdf-download-test-case')

app.api.binary_types.append('application/pdf')

@app.route('/')
def index():
    with open('./test.pdf', 'rb') as pdf:
        content = pdf.read()

    pprint(type(content))
    pprint(app.api.binary_types)

    return Response(body=content,
                    status_code=200,
                    headers={'Content-Type': 'application/pdf'})
```

* output (verifying my data is the correct type, and the MIME type was added)
```
2020-08-28 13:46:13.685000 fea9ad <class 'bytes'>
2020-08-28 13:46:13.685000 fea9ad ['application/octet-stream',
2020-08-28 13:46:13.685000 fea9ad 'application/x-tar',
2020-08-28 13:46:13.685000 fea9ad 'application/zip',
2020-08-28 13:46:13.685000 fea9ad 'audio/basic',
2020-08-28 13:46:13.685000 fea9ad 'audio/ogg',
2020-08-28 13:46:13.685000 fea9ad 'audio/mp4',
2020-08-28 13:46:13.685000 fea9ad 'audio/mpeg',
2020-08-28 13:46:13.685000 fea9ad 'audio/wav',
2020-08-28 13:46:13.685000 fea9ad 'audio/webm',
2020-08-28 13:46:13.685000 fea9ad 'image/png',
2020-08-28 13:46:13.685000 fea9ad 'image/jpg',
2020-08-28 13:46:13.685000 fea9ad 'image/jpeg',
2020-08-28 13:46:13.685000 fea9ad 'image/gif',
2020-08-28 13:46:13.685000 fea9ad 'video/ogg',
2020-08-28 13:46:13.685000 fea9ad 'video/mpeg',
2020-08-28 13:46:13.685000 fea9ad 'video/webm',
2020-08-28 13:46:13.685000 fea9ad 'application/pdf']
```

Is this a bug, or is there configuration that I am missing?

**Comment by jamesls** [comment]
Can you show what the client request looks like?  Just want to confirm you're adding the `Accept` header as well (docs [here](https://aws.github.io/chalice/topics/views.html#binary-content)).

**Comment by andy-imt** [comment]
I guess that's probably my problem, as I want this to be available via a browser which would be sending '*/*' in Accept. Is there a way to make the one endpoint return binary data regardless of the client's Accept header while the others return JSON?

**Comment by msm-publicgood** [comment]
I've just run into this exact problem myself. Banged my head on it for a day and I think at least I know what's happening.

I believe this is something going wrong when the Response object is serialized to a dictionary and there's a check being done of the Response's `Content-Type` header against the app's api gateway object's `binary_types` array. The Response isn't recognized as a binary response, so the `isBase64Encoded` flag isn't set in the Lambda's JSON response to the API Gateway. However, the `bytes` in the body does get base64 encoded, so that's what API Gateway returns, as text.

You don't see this happen, best I can tell, when served locally because that JSON serialization for API Gateway doesn't happen with the local server.

The content type matching appears to be failing unless you set the `binary_types` array to `['*/*']` (which makes for other problems if you have other functions in the app returning text). See #1095 for some earlier discussion on a related problem.

I will try to put together a minimal example that illustrates the issue, and I'll see if I can trace the problem in `Response.to_dict()`.

**Comment by msm-publicgood** [comment]
@msm-publicgood (I) said:

> I've just run into this exact problem myself. Banged my head on it for a day and I think at least I know what's happening.

I was incorrect. This is not a problem in Chalice, but a problem of my misunderstanding of how API Gateway works with Lambda Proxy responses and Accept headers in determining binary content. API Gateway assumes a well-behaved HTTP client, which browsers surely aren't.

@andy-imt asked:

>  Is there a way to make the one endpoint return binary data regardless of the client's Accept header while the others return JSON?

The only way I found to make this work at the moment is:

- Make sure the app adds `*/*` to its binary types: ```app.api.binary_types = ['*/*']``` or ```app.api.binary_types.append('*/*')```
- Endpoint view functions that need to return binary content should set their `Content-Type` header to an explicit binary type.
- Endpoint view functions that need to return JSON should not just return an arbitrary data structure to be serialized as JSON by Chalice. Instead, return an explicit `Response` object with the data already serialized and converted to `bytes`:

```python
@app.route('/healthcheck', methods=['GET'], content_types=['*/*'])
def healthcheck():
    """ healthcheck returns the service's current status """
    body = {'pixel_service_ok': pixels_service.ok(), 'pixel_service_state': pixels_service.state()}
    return Response(
        status_code=200,
        headers={
            'Content-Type': 'application/json',
        },
        body = json.dumps(body).encode('UTF-8')
    )
```

There's code in Chalice in `app.py` that explicitly handles the case where you've had to treat JSON as a binary response type and does the right thing in the Lambda Proxy response back to the API Gateway.

**Comment by andy-imt** [comment]
@msm-publicgood: Thanks for your work-arounds, they are helpful.

What I guess I don't understand from a Chalice stand-point is if a client specifies they accept '*/*', why wouldn't a binary type be returned as binary?  Is this a limitation of the link between API Gateway and Lambda, or is this a behavior in Chalice that could be changed?

**Comment by msm-publicgood** [comment]
> What I guess I don't understand from a Chalice stand-point is if a client specifies they accept '*/*', why wouldn't a binary type be returned as binary? Is this a limitation of the link between API Gateway and Lambda, or is this a behavior in Chalice that could be changed?

I'm still learning how this works, but I believe this is a consequence of how API Gateway handles the intersection of the list of binary types for your API, the `Accepts` header of the incoming request, and the `Content-Type` header of the outgoing response.

Routed Chalice view functions are treated as though they return Lambda Proxy responses. Chalice does the right thing when assembling that response: If the `binary_types` dictionary contains a match to the `Content-Type` header of your `Response` object, Chalice sets the `isBase64Encoded` flag properly on the response and does the right thing with your body bytes or string. If you have `*/*` included as a binary type, all content types match as binary, but Chalice has some logic to handle `application/json` properly when preparing a binary response, too.

Chalice always returns the response body data to the API gateway as text, either a UTF-8 string for text types, or a base-64 encoded string, with `isBase64Encoded` true in the response.

Chalice packaging and deployment configures an API Gateway Integration for your API that explicitly sets all of the binary types set in the app, and it sets a `contentHandling` flag on the API Gateway with a value of `CONVERT_TO_TEXT`. Why this is important is if you look at the "API Gateway response content type conversions" table in [this documentation page](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-workflow.html).

I'm still uncertain what the conditions are per that table, but it appears that if the gateway is not set up with '*/*' as a binary type and your client request comes in with `Accept: */*` the gateway assumes it should return a text response even if the content type of the response is a binary type.

There's another caveat with returning binary responses to '*/*' in Chalice: Best I can tell, you also cannot just raise a ChaliceViewError error type as a response:

```python
raise ChaliceViewError("Pixel Service Not OK: %s" % (err))
```

That will result in an encoding error. Instead, you must assemble an explicit error response with the appropriate HTTP error code and JSON body. 

I imagine there must be some better way to handle this case where our API client is dumb, like most browsers, and doesn't set a proper `Accept` header, when we're trying to mix text and binary responses from our APIs, but this seems like a case that API Gateway itself has an opinion on that doesn't meet (at least my) expectations.

**Comment by andy-imt** [comment]
@msm-publicgood Thanks for your response.  That clarifies quite a few things for me.

From your documentation link, it seems also that part of the challenge is that API Gateway only recognizes the first Content-Type provided in the Accept, so the fact that it contains '\*/\*' from the browser is irrelevant.

Trying to deliver content to browsers is kind of fighting against the way that API Gateway and Chalice were designed.  It's unfortunate though, because it would be very useful to be able to use them in this manner.

**Comment by msm-publicgood** [comment]
> Trying to deliver content to browsers is kind of fighting against the way that API Gateway and Chalice were designed.

That's correct, IMO. API Gateway is, surprise, meant for implementing HTTP APIs for well-behaved API clients. I suspect the more reasonable thing to do -- at least for my use case -- from a Chalice view function is to respond with an HTTP redirect to binary content on some server that expects to be accessed by browsers, like S3, or even possibly redirect to a `data:` URL.

Editorial: What would be even better for my use case is online advertising to drop the use of "pixels" for tracking events and start using the `sendBeacon()` API that every modern browser implements. But I don't have the energy to tilt at that windmill.

**Comment by jamesls** [comment]
Thanks everyone for the detailed explanations of the current behavior.  I think the best options we have at the moment is documenting the behavior with browsers and the options you have for working with HTTP clients that can't set Accept headers.  Also, I think it should be a safe change to support having `*/*` as a binary type and still allow you to return a python dictionary directly instead of requiring you to use the `Response(body=json.dumps(...), ...)` workaround.  Right now, doing so is an error condition, so we should make be able to add a fallback in that case (e.g. try to serialize as utf-8 first if we try to base64 encode a string/unicode type).
