### ISSUE TITLE
SwaggerGenerator should capture documention for query and cookie parameters

### ISSUE THREAD

**Issue by straz** [aws/chalice#1513]
In [chalice/deploy/swagger.py](https://github.com/aws/chalice/blob/master/chalice/deploy/swagger.py), `SwaggerGenerator` generates swagger doc strings for `path` and `header` parameters.

There should be a standard way to declare `query` and `cookie` parameters for chalice routes, too.
Perhaps these should be declared inside function docstrings, see https://github.com/aws/chalice/pull/681/

From https://swagger.io/docs/specification/describing-parameters/:
> Query parameters are the most common type of parameters.

**Comment by jamesls** [comment]
There's a proposal on how to model inputs in Chalice: https://github.com/aws/chalice/issues/1224.  That would include things like query params as well.  The benefit of modeling it is that you can get not only documentation but also validation for free.  We can track that work there.
