### ISSUE TITLE
Issue with 'chalice deploy' of pymysql[rsa]

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1515]
Hi,

This is a nagging issue with chalice deploy. I decided to switch from mysqlclient to pymysql to bypass C code being included as part of the deploy.

That allowed 'chalice deploy' to work because the code became pure python but it created a new problem where the code cannot authenticate with an RDS Maria DB instance.

To get around that, I looked at the pymysql documentation which signalled that I might need to put pymysql[rsa] in my requirements.txt file.

That then gives me this problem while deploying. I am using chalice from inside a docker linux image which is not exactly Amazon Linux and maybe that is the problem (python:3.8.2-slim-buster). Or it could be that the deploy size is too large or a layer is being installed. 

I can't make out from this error and I am not that familar with Chalice internals to dig deeper.

My requirements.txt is very simple: pymysql[rsa] and SQLAlchemy

'Connection was closed before we received a valid response from endpoint URL'

**Comment by jamesls** [comment]
When I try to include the packages and import them in my app it works as I'd expect.  Is there anything else I can try that might demonstrate this problem (do you have any layers specified in your .chalice/config.json file)?  Another thing you can check is run `chalice package out` and then check the size of the packaged app via `du -hs out/`.  You can check if it's over the 50MB limit.

Here's what I tried:

```python
from chalice import Chalice

app = Chalice(app_name='testpackage')


@app.route('/')
def index():
    import pymysql
    return {'pymysql': pymysql.__file__}
```

requirements.txt:

```
pymysql[rsa]
SQLAlchemy
```

```
$ chalice deploy
Creating deployment package.
Creating IAM role: testpackage-dev
Creating lambda function: testpackage-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:12345:function:testpackage-dev
  - Rest API URL: https://abcd.execute-api.us-west-2.amazonaws.com/api/
```

```
$ http https://abcd.execute-api.us-west-2.amazonaws.com/api/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 43
Content-Type: application/json
Date: Mon, 14 Sep 2020 19:30:18 GMT
...

{
    "pymysql": "/var/task/pymysql/__init__.py"
}
```

**Comment by devangmehta123** [comment]
@jamesls , sorry for not coming back to you earlier. If there is a 50MB limit, that might explain the problem. And there have been notes on the internet that such problems are general Lambda problems, than something specific to Chalice.

I think that to accurately reproduce it, you might need my Dockerfile which at the time, contained a whole bunch of dependencies for the cryptography package to work. I probably should use an Amazon Linux image designed for Lambda to come closest to that environment. 

As it turns, out, I did not need pymysql[rsa] at all. Just simple pymysql with any cryptography seemed to work.

I am using Windows and I don't use virtualenv's. I just have my Chalice run inside Docker and I have PyCharm configured for that workflow.

With the new Chalice test client, everything seems to run locally just fine and I can have some elaborate tests.

I will ask for a feature request in config.json soon which helps with my flow. Thanks.

**Comment by devangmehta123** [comment]
There is another issue related to `chalice deploy`. I thought that I might be able to improve the deploy by using automatic_layer = true.

But that created a different problem (orjson deploys and works perfectly with automatic_layer = false)

```
root@47c9f60673b4:/app# chalice deploy
Creating shared layer deployment package.

Could not install dependencies:
orjson==3.4.0
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://aws.github.io/chalice/topics/packaging.html
```

**Comment by devangmehta123** [comment]
And the above problem was fixed by using a different version of orjson, i.e. 3.3.0. So I can use automatic_layers and that does improve the experience. 

But I discovered that it is not that simple to clear all the existing deploys, so quite often even after the above failure, it would still continue to use the existing zip files. I manually deleted all the zip files under to get around that.

**Comment by jamesls** [comment]
Thanks for clarifying.  It might be worth adding a `--force` option to the package/deploy commands that would clear all the existing zip files to ensure we repackage everything fresh.

**Comment by devangmehta123** [comment]
@jamesls , some more observations on the the original report above. I am now trying to add sentry_sdk[chalice] to the deploy.

And I see the same problem as pymysql[rsa]. 

And I have checked the package size. They are quite small. The managed layer is about 11MB and application code is about 35KB.

It does not feel like the size is the problem. But I don't understand why the deploy loses connection.

**Comment by devangmehta123** [comment]
@jamesls , FWIW, and I understand that I might be creating noise for you, it might actually be worthwhile having a page like 'known annoyances and recommended hacks'. I mean it as a joke but the issue I am facing is probably an unresolved bug in AWS CLI or all the strange network issues that can happen.

As it stands, I have a workflow where 'chalice deploy' can be executed through github actions on merge to master. So, I might be able to get around this problem.

https://github.com/aws/aws-cli/issues/3842

**Comment by devangmehta123** [comment]
And then, just to confirm, github actions managed to deploy successfully. I am quite sure that if I tried with pymysql[rsa] through github actions, that might be resolved.

Which is all great but the error reporting within my PC left a few things to be desired. All in good humour, but I am hoping that these notes will make it easier for everyone in the future.

**Comment by jamesls** [comment]
> it might actually be worthwhile having a page like 'known annoyances and recommended hacks'.

I agree, I have an issue tracking the creation of a troubleshooting page here: https://github.com/aws/chalice/issues/1455, let's track that work over there.

Thanks again for the feedback.
