### ISSUE TITLE
Deploy lambda functions only for given stage

### ISSUE THREAD

**Issue by arsalasif** [aws/chalice#1518]
My config file looks like this:
```json
{
  "version": "2.0",
  "app_name": "chalice",
  "environment_variables": {
    "REGION": "us-west-2"
  },
  "stages": {
    "stage": {
      "environment_variables": {
        "ENV": "stage"
      },
      "lambda_functions": {
      }
    },
    "prod": {
      "environment_variables": {
        "ENV": "prod"
      },
      "lambda_functions": {
        "create_snapshot": {
          "autogen_policy": false,
          "iam_policy_file": "./policy/rds-snapshot-policy.json",
          "manage_iam_role": true,
        },
        "delete_snapshot_periodically": {
          "autogen_policy": false,
          "iam_policy_file": "./policy/rds-snapshot-policy.json",
          "manage_iam_role": true
        }
      }
    }
  }
}
```

Is there an option to deploy functions given under a specific stage?
This should deploy `create_snapshot` and `delete_snapshot_periodically` when I run `chalice deploy --stage prod`.
It shouldn't deploy either of those methods on `chalice deploy --stage stage` since they are only declared under `prod` stage.

Is this possible?

**Comment by jamesls** [comment]
No this is not currently possible.  The stages in the `.chalice/config.json` file allow you to specify configuration for Lambda functions in different stages, but the configuration is optional (there's reasonable defaults if no config is provided).  So you don't have to specify your Lambda function in the `.chalice/config.json` in order for us to deploy it.  We assume the same set of resources across all your stages.

**Comment by arsalasif** [comment]
Thanks. But in case of event based lambdas, it'll create duplicates on all stages? That wastes resources and compute time, even when you don't need it.

**Comment by jamesls** [comment]
Yes, that's the intent of [stages](https://aws.github.io/chalice/topics/stages.html).  A completely separate, independent set of resources.  You don't want to be mixing Chalice stages (e.g. your "dev" and "prod" resources should be separate).  It sounds like for your scenario, stages isn't the right feature for you.  You could have separate apps, and add in shared pieces via [Blueprints](https://aws.github.io/chalice/topics/blueprints.html)
