### ISSUE TITLE
terraform http api support

### ISSUE THREAD

**Issue by kapilt** [aws/chalice#1520]
terraform added in http api support, it would be good to flush out chalice pkg gen support to support the same.

**Comment by jamesls** [comment]
Nice, though we'll still need to support HTTP APIs first (https://github.com/aws/chalice/issues/1321), which is a planned feature.  I would assume terraform support would be included as part of that change.

**Comment by kapilt** [comment]
well really s/http/apigatewayv2 .. or put another way this is also intended to support tf gen for websockets endpoints support already extant in chalice w/ cf.
