### ISSUE TITLE
getting `GLIBC_2.18' not found error  in aws api gateway

### ISSUE THREAD

**Issue by kuabhish** [aws/chalice#1521]
I am writing an Api in aws chalice. 
My code is working good in local.

But I am getting the following respnse:
`{
  "message": "Internal server error"
}
` 
My requirements.txt file contains:

```
wcwidth==0.1.7
boto3==1.13.7
botocore==1.15.49
cashfree-sdk==0.1.1
web3==5.10.0
pycryptodome==3.9.8
```

On checking in aws api gateway. Found the following error:

Error Message:

```
{"errorMessage": "Unable to import module 'app': /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/rusty_rlp.cpython-37m-x86_64-linux-gnu.so)", "errorType": "Runtime.ImportModuleError"}
Fri Sep 18 13:47:33 UTC 2020 : Lambda execution failed with status 200 due to customer function error: Unable to import module 'app': /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/rusty_rlp.cpython-37m-x86_64-linux-gnu.so). Lambda request id: b8a849f9-2982-49a6-a010-f6a2dbe1655e
```

**Comment by jamesls** [comment]
In this case, it looks like some of the C dependencies you're using are building correctly.  You'll best option is to manually build these either in docker or on Amazon Linux, and then include them in the `vendor/` directory, as shown [here](https://aws.github.io/chalice/topics/packaging.html#cryptography-example)

**Comment by kuabhish** [comment]
Hey @jamesiri , I deployed these codes few days back and it was working good. Something happened with AWS lambda. I am sure of it. 

Earlier I was deploying only with 

`chalice deploy`

What happened to  Lambda ?

I will try the link you mentioned and see. Thanks

**Comment by kuabhish** [comment]
Hey @jamesls 

I am not seeing this error when I am deploying

```
Could not install dependencies:
cryptography==1.9
You will have to build these yourself and vendor them in
the chalice vendor folder.
```

**Comment by jamesls** [comment]
Not sure what happened with Lambda, but if you can use a newer version of cryptography (`>=2.0`) we'll be able to pull in the manylinux1 wheel file and you won't run into this problem of having to build it manually.
