### ISSUE TITLE
schedule function error KeyError: 'version'

### ISSUE THREAD

**Issue by lxhnt** [aws/chalice#1524]
Function:
@app.schedule(Rate(30, unit=Rate.MINUTES))
def periodic_task(event):
    print(event.to_dict())
    pass

Function trigger:
chalice invoke -n periodic_task

Error trace:
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1458, in __call__
    event_obj = self.event_class(event, context)
  File "/var/task/chalice/app.py", line 1486, in __init__
    self._extract_attributes(event_dict)
  File "/var/task/chalice/app.py", line 1497, in _extract_attributes
    self.version = event_dict['version']
KeyError: 'version'
Error: Unhandled exception in Lambda function, details above.

**Comment by jamesls** [comment]
For the decorators that are bound to a specific event (`.schedule, on_s3_event, on_sns_message`, etc), they all require a specific event payload.  This payload is automatically generated by the corresponding AWS service.  If you want to manually invoke the function, you'll need to provide an event payload that matches the schema expected by that event handler.

```
echo '{
  "id": "53dc4d37-cffa-4f76-80c9-8b7d4a4d2eaa",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "2019-10-08T16:53:06Z",
  "region": "us-east-1",
  "resources": [ "arn:aws:events:us-east-1:123456789012:rule/MyScheduledRule" ],
  "detail": {}
}' | chalice invoke -n periodic_task
```

**Comment by camiloromers** [comment]
I have literally the same issue .. I coded a lambda func (example in the documentation) that has a scheduler decorator and got the same error. How can I solve it?

**Comment by owlwalks** [comment]
@camiloromers this works for me:

```
echo '{
  "id": "53dc4d37-cffa-4f76-80c9-8b7d4a4d2eaa",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "2019-10-08T16:53:06Z",
  "region": "us-east-1",
  "resources": [ "arn:aws:events:us-east-1:123456789012:rule/MyScheduledRule" ],
  "detail": {},
  "version": ""
}' | chalice invoke -n periodic_task
```
(added "version" field)

**Comment by alfdnl** [comment]
> @camiloromers this works for me:
> 
> ```
> echo '{
>   "id": "53dc4d37-cffa-4f76-80c9-8b7d4a4d2eaa",
>   "detail-type": "Scheduled Event",
>   "source": "aws.events",
>   "account": "123456789012",
>   "time": "2019-10-08T16:53:06Z",
>   "region": "us-east-1",
>   "resources": [ "arn:aws:events:us-east-1:123456789012:rule/MyScheduledRule" ],
>   "detail": {},
>   "version": ""
> }' | chalice invoke -n periodic_task
> ```
> 
> (added "version" field)

For the id parameter, can you help me where to find the id? sorry Im abit confused

**Comment by theist** [comment]
There's something I do not understand, why chalice perform validation over the event contents for an event instead of let the responsibility on the user's code?  I was hit by this and the error puzzled me because I don't really care about the event contents, I only need the lambda fired at a certain point in time. And in case I will require some validation on the event's content I will have performed it in my code.

**Comment by forgebench** [comment]
I had the same issue and found this thread. 

The issue stems from the fact that chalice wants to validate a very specific schema, and if it isn't all there then it'll toss the error. In this case when you test from AWS Lambda using their built in CloudWatch scheduled event it does not include the "version" key in the JSON. 

To properly set your CloudWatch event scheduler you'll need to set the JSON yourself from CloudWatch. As others said above simply add the version key into the JSON payload.

**Comment by maor-gh** [comment]
For someone coming in with this issue.

The way I solved it for running lambda payloads in a scheduled lambda is to pass all params the CloudWatchEvent validator expects, and add the params I need to run the lambda.
```
{
      "custom_param1": X,
      "custom_param2": X,
                      "version":"",
                      "account":"",
                      "region":"",
                      "detail":{},
                      "detail-type":"",
                      "source":"",
                      "time":"",
                      "id":"",
                      "resources":[]
                  }
```
Then, the only way to get access to these params in the function is when using `event.to_dict()`
