### ISSUE TITLE
Blueprint.route() no longer retains __doc__

### ISSUE THREAD

**Issue by nayaverdier** [aws/chalice#1525]
Code snippet below succeeds on chalice `v1.19.0` and fails on chalice `v1.20.0`. This does not seem to affect `Chalice` objects (the snippet succeeds if `b = Chalice(__name__)` on both versions)

```python
from chalice import Blueprint

b = Blueprint(__name__)

@b.route("/test", methods=["POST"])
def x():
    """a"""
    pass

assert x.__doc__ == "a"
```

**Comment by jamesls** [comment]
Confirmed bug, thanks for reporting, I'll get that fixed.
