### ISSUE TITLE
Enable use of CDK cloudformation_include in cdk-chalice by bumping maximal attrs version

### ISSUE THREAD

**Issue by alexpulver** [aws/chalice#1528]
I am trying to make [cdk-chalice](https://github.com/alexpulver/cdk-chalice/) use the recently implemented CDK [`cloudformation_include`](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html) module. It allows to import an existing CloudFormation template and cast resources to CDK types. Any modifications made to these resources will be reflected in the resulting CDK template. This will allow CDK users easily customize resources generated by Chalice. See [Сustomizing resources generated by Chalice (and cdk-chalice respectively)](https://github.com/alexpulver/cdk-chalice/issues/15) for example of such a request.

`cdk-chalice` users can package the Chalice app either in current environment (using subprocess) or using Docker container. When packaging in current environment, Chalice library should be installed in order for `chalice` executable to be available for packaging the app.

`cloudformation_include` module entered developer preview in CDK 1.64.0. This CDK version requires (through [`jsii`](https://github.com/aws/jsii/blob/master/packages/@jsii/python-runtime/setup.py#L33)) `attrs~=20.1`. On the other hand, Chalice requires `attrs>=19.3.0,<20.0.0`. Hence both CDK and Chalice cannot be installed in the same environment due to conflict in dependencies.

Is there a reason that Chalice can't work with `attrs<=20.1.*`?

https://github.com/aws/chalice/blob/96c8bded3e0936df42d49eb9fb3b2226e60848d2/setup.py#L16

**Comment by jamesls** [comment]
> Is there a reason that Chalice can't work with attrs<=20.1.*?

I think this should be ok.  Looking over their changelog, the breaking changes don't seem relevant to us.  Assuming it passes travis, I'll upgrade this.
