### ISSUE TITLE
Lambda only allows  deployment packages that are 50.0 MB or less in size

### ISSUE THREAD

**Issue by thosieucoi** [aws/chalice#1542]
I'm trying to develop and deploy an AWS Chalice application using CircleCI. I have tried to run command
`chalice deploy`

But I got error: **This is likely because the deployment package is 124.8 MB. Lambda only allows deployment packages that are 50.0 MB or less in size. To avoid this error, decrease the size of your chalice application by removing code or removing dependencies from your chalice application.**

This is my requirements.txt

```
boto3==1.14.63
chalice==1.21.0
pyarrow==0.17.1
pandas==1.0.5
python-dotenv==0.14.0
snowflake-connector-python==2.3.3
```

Would anyone guide me how to deploy AWS Chalice application using CircleCI?

Thank you so much.

**Comment by jamesls** [comment]
The 50MB limit is a restriction of the AWS Lambda service, so there's not much Chalice can do to work around that.  I've seen people store additional dependencies at S3 and then on Lambda function initialization they download all the dependencies to their Lambda function and add it to their `sys.path`, which is probably your best option if you are unable to remove dependencies.

**Comment by thosieucoi** [comment]
@jamesls Thank you so much. I will try to download all dependencies to /tmp

**Comment by josiahcoad** [comment]
But if the lambda is downloading dependencies upon every initiation, what that make initiation take a lot longer? @jamesls
