### ISSUE TITLE
integration of the current new relic agent into Chalice handlers

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1544]
I wonder if there is anyone currently writing a library which might automaticcally integrate the new relic layer into Chalice handlers in app.py.

A Lambda can be instrumented based on this documentation. There is a small amount of wrapper code to be written around each Lambda, which seems to be a case for building a decorator to wrap it.

And this needs to work with automatic layering so that all the new relic dependencies are availalbe. 

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-using-lambda-layer

I am looking for something similar to what Sentry has done. The amount of code to add was minimal.

Something like this:

```
from sentry_sdk.integrations.chalice import ChaliceIntegration

sentry_sdk.init(
    dsn=ParamContainer.SENTRY_DSN,
    integrations=[ChaliceIntegration()]
)
```

**Comment by jamesls** [comment]
I'm not super familiar with new relic (and I don't have access to an account), but I'm also curious if anyone else is working on this.  FWIW the sentry one was written before [middleware](https://aws.github.io/chalice/topics/middleware.html) was added to Chalice so supporting new types monitoring handlers should be much safer and not require monkeypatching.

**Comment by devangmehta123** [comment]
That's an interesting idea. I started using middleware maybe 2 days after you released to introduce a status code and standard message format to the response. That might just make this intrumentation much simpler.

This might then become a documentation ticket in one of the guides.

**Comment by devangmehta123** [comment]
@jamesls , is there any way in config.json to add an existing layer. The new relic documentation recommends doing something like this but I would rather have it in the chalice configuration.

`newrelic-lambda layers install --nr-account-id YOUR_NR_ACCOUNT_ID --function my-function --upgrade`

**Comment by jamesls** [comment]
Yes, via the `layers` config options: https://aws.github.io/chalice/topics/configfile.html#layers

**Comment by ShahBinoy** [comment]
@jamesls  Even after Using extension and layer, NewRelic instrumentation requires that we set the main starter function to be the function of NewRelic layer and pass in the actual lambda handler function name as an environment variable. This way the control passes through the NewRelic Handler and then gets forwarded to the actual Lambda function call. We need an ability to invoke NewRelic Layer function instead of main chalice function
