### ISSUE TITLE
'chalice package' does not deploy all stages into API Gateway found in '/.chalice/config.json'

### ISSUE THREAD

**Issue by danieltensoriot** [aws/chalice#1548]
chalice 1.21.0, python 3.7.3, windows 10

Executing CloudFormation stack produced from `chalice package`  does not deploy all stages found in `/.chalice/config.json`

Based on the sample `config.json` below, the only stage produced in API gate way is `dev'.

```json
{
  "version": "2.0",
  "app_name": "project",
  "tags": {
    "project": "project"
  },
  "stages": {
    "dev": {
      "api_gateway_stage": "dev",
      "tags": {
        "environment": "dev"
      },
      "environment_variables": {
        "USER_TABLE": "dev-project-user"
      }
    },
    "test": {
      "api_gateway_stage": "test",
      "tags": {
        "environment": "test"
      },
      "environment_variables": {
        "USER_TABLE": "test-project-user"
      }
    }
  }
}
```

**Comment by jamesls** [comment]
The `stages` key in the `.chalice/config.json` file are for Chalice stages which are different from API Gateway stages (https://aws.github.io/chalice/topics/stages.html).  To package for a different stage you can run `chalice package --stage STAGE_NAME`.
