### ISSUE TITLE
lambda proxy integration blocks me from allowing x-www-form-urlencoded in request

### ISSUE THREAD

**Issue by mowliv** [aws/chalice#1555]
I'm trying to get a twilio callback into my chalice code working. So far, I've been using json data in the requests, but am not seeing that option in twilio for the callback. It's sending media type application/x-www-form-urlencoded. I would map it in AWS API UI but since that's auto-generated by chalice, I'm not able to turn off proxy integration in AWS API console so I allow. As a result, I'm getting this error in twilio that AWS is rejecting the callback:

"Got HTTP 415 response to https://[redacted].execute-api.us-west-1.amazonaws.com/dev/outbound_call_callback"
statusCallback | "https://[redacted].execute-api.us-west-1.amazonaws.com/dev/outbound_call_callback"
.
.
.
Response body:
{
    "Code": "UnsupportedMediaType",
    "Message": "Unsupported media type: application/x-www-form-urlencoded; charset=utf-8"
}

Please advise. Wishing there was a config option in chalice to either specify to allow this or to specify another option than proxy integration. Open to other solutions, of course.

Would also appreciate a pointer to the best forum for chalice Q&A - is it stack exchange?

Thanks!
Michael

**Comment by jamesls** [comment]
You can set the `content_types` parameter in a route to indicate the acceptable types, e.g.:

```
@app.route('/', content_types=['application/x-www-form-urlencoded'])
def myroute():
    # Body contents as byte() type.
    bytes_body = app.current_request.raw_body
    # Assuming it's utf-8
    str_body = bytes_bode.decode('utf-8')
```

**Comment by mowliv** [comment]
Thank you, I will try that!

**Comment by mowliv** [comment]
Any suggestion appreciated for how best to parse it from there. I get:

Called=%2B12135551212&ToState=CA&CallerCountry=US&Direction=outbound-api&Timestamp=Fri%2C%2016%20Oct%202020%2002%3A13%3A09%20%2B0000&CallbackSource=call-progress-events&SipResponseCode=200&CallerState=CA&ToZip=90210&SequenceNumber=0&To=%2B12135551212&CallerZip=94001&ToCountry=US&CalledZip=90210&ApiVersion=2010-04-01&CalledCity=VENTURA&CallStatus=completed&Duration=1&From=%2B15559141111&CallDuration=8&CalledCountry=US&CallerCity=VENTURA&ToCity=VENTURA&FromCountry=US&Caller=%2B15559191111&FromCity=VENTURA&CalledState=CA&FromZip=94001&FromState=CA

**Comment by mowliv** [comment]
Never mind, I found this for how to parse it:
https://stackoverflow.com/questions/21584545/url-query-parameters-to-dict-python

Thanks!

Would also appreciate a pointer to the best forum for chalice Q&A - is it stack exchange?

**Comment by jamesls** [comment]
> Would also appreciate a pointer to the best forum for chalice Q&A - is it stack exchange?

Yeah, stackoverflow with the question tagged with chalice.  There's also a [gitter channel](https://gitter.im/awslabs/chalice) where people in the Chalice community hang out and can answer questions.

**Comment by mowliv** [comment]
Awesome, thanks!
