### ISSUE TITLE
Chalice api_gateway_custom_domain error after code updates

### ISSUE THREAD

**Issue by mato2** [aws/chalice#1569]
After Configuring custom domain names with AWS Chalice, I got an error after running chalice deploy for code changes. 
Error: Resource does not exist: api_gateway_custom_domain.

[Container] 2020/11/01 01:10:38 Running command chalice deploy --stage development
--
161 | Traceback (most recent call last):
162 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/config.py", line 482, in resource_values
163 | return self._deployed_values_by_name[name]
164 | KeyError: 'api_gateway_custom_domain'
165 |  
166 | During handling of the above exception, another exception occurred:
167 |  
168 | Traceback (most recent call last):
169 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 40, in resource_deployed_values
170 | return self._deployed_resources.resource_values(
171 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/config.py", line 484, in resource_values
172 | raise ValueError("Resource does not exist: %s" % name)
173 | ValueError: Resource does not exist: api_gateway_custom_domain
174 |  
175 | During handling of the above exception, another exception occurred:
176 |  
177 | Traceback (most recent call last):
178 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/cli/__init__.py", line 631, in main
179 | return cli(obj={})
180 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
181 | return self.main(*args, **kwargs)
182 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
183 | rv = self.invoke(ctx)
184 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
185 | return _process_result(sub_ctx.command.invoke(sub_ctx))
186 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
187 | return ctx.invoke(self.callback, **ctx.params)
188 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
189 | return callback(*args, **kwargs)
190 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
191 | return f(get_current_context(), *args, **kwargs)
192 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/cli/__init__.py", line 206, in deploy
193 | deployed_values = d.deploy(config, chalice_stage_name=stage)
194 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 354, in deploy
195 | return self._deploy(config, chalice_stage_name)
196 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 365, in _deploy
197 | plan = self._plan_stage.execute(resources)
198 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 164, in execute
199 | result = handler(resource)
200 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 1164, in _plan_restapi
201 | custom_domain_plan = self._add_custom_domain_plan(
202 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 1178, in _add_custom_domain_plan
203 | api_mapping_plan = self._add_apimapping_plan(
204 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 236, in _add_apimapping_plan
205 | deployed = self._remote_state.resource_deployed_values(
206 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 43, in resource_deployed_values
207 | return self._dynamically_lookup_values(resource)
208 | File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/chalice/deploy/planner.py", line 55, in _dynamically_lookup_values
209 | raise ValueError("Deployed values for resource does not exist: %s"
210 | ValueError: Deployed values for resource does not exist: api_gateway_custom_domain

https://aws.amazon.com/blogs/developer/configuring-custom-domain-names-with-aws-chalice/

**Comment by jamesls** [comment]
This is related to your other issue https://github.com/aws/chalice/issues/1570, specifically that the state file used by `chalice deploy` is local, which means that if deploying through a CI system that wipes files every time, Chalice won't know about what's deployed or not.  Let's track this in #1570, I'll update that issue with a few suggestions.
