### ISSUE TITLE
Environment variable values must be strings, got 'type' unicode for key 'ENV'

### ISSUE THREAD

**Issue by 3dw1np** [aws/chalice#1573]
I am using the version 1.21.4 of chalice and I am getting this error below during the deployment:
```Environment variable values must be strings, got 'type' unicode for key 'ENV'```

I am still using python 2.7 on my local computer but it was working fine on chalice 1.21.2

**Comment by jamesls** [comment]
Thanks for reporting, this is a bug introduced while fixing #1543.  We'll get this fixed.
