### ISSUE TITLE
Knowing inside the handler if the invocation is a test invocation or regular invocation

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1576]
This may seem a confusing header but let me explain the use case below.

I have been using unit tests to my database set/get logic. I rely heavily on seed data. The unit tests are always repeatable because every set/get function takes the database connection as input and every unit test simply does a `trans.rollback()` at the end of each test.

The actual set/get function is not concerned with the rollback. The handler (through a common decorator) creates the connection. The nice pattern in sqlalchemy is that the transaction will be committed if no exception happens. So, the code inside this decorator is quite clean. 

I just want to add one last piece of logic in this decorator. Something like:

```
   if test_mode:
       trans.rollback()
```

This really helps with testing the full API using the Chalice Test Client. I really like using the Test Client in my unit tests because it tests the API endpoints thoroughly.

But ATM, I am restricted to read-only endpoints. If I used the Test Client in read-write endpoints, I would change the state of my database.

I am wondering if there is any way to detect inside the handler if it has been invoked by the test client or by the actual API gateway.

Thanks.

**Comment by jamesls** [comment]
There's not a direct way to check if you're using the test client.  The closet thing you can do is check the sourceIp on the request context and see if it's 127.0.0.1 (which it will be when using either `chalice local` or the Chalice test client).  

```
if app.current_request.context['identity']['sourceIp'] == '127.0.0.1':
    # Running in local or test mode.
else:
    # Running in lambda

```
The other option is to set your own env var when you run your tests (e.g `MYAPP_TEST_MODE=true` or something).  Hope that helps.

**Comment by devangmehta123** [comment]
Thanks @jamesls 

I am testing everything inside a container. Setting an env var coming into the container inside docker-compose was a one liner. 

And obviously, it will just not be set inside the production Lambda. 

A bit sheepish that I did not think of it myself!

**Comment by jamesls** [comment]
Glad to see you found a solution that works for you!
