### ISSUE TITLE
is it possible to generate terraform with the provider credentials?

### ISSUE THREAD

**Issue by chimon2000** [aws/chalice#1577]
I have not found a way to run `terraform plan/apply` without defining credentials as default or setting them as environment variables.  It would be nice if this could be generated for me.

**Comment by jamesls** [comment]
Do you mean that you'd want the access_key/secret_key included in the terraform template chalice generates?  If so, that's usually [not a recommended practice](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#static-credentials) so I'm not sure we'd want to support that.  In order for us to do that we'd need to pull those credentials from some underlying source anyways (environment variables, config file, etc) so you'll still need to use some other source to configure creds.

You can also use the `~/.aws/config` and `~/.aws/credentials` along with an AWS profile if you don't want to use environment variables.

**Comment by chimon2000** [comment]
I actually want to be able to set them.  My use case is that chalice can build an app using an AWS profile but it can't generate that same package if you specify the profile.  It also might make sense that you'd be able to specify the profile in the chalice config.

**Comment by jamesls** [comment]
Can you tell me more about the "but it can't generate that same package if you specify the profile."  I'm not opposed to setting the `profile` in the Chalice config if that would help out.  I'm interested in exploring other options where we wouldn't have to hardcode credentials in the terraform templates.

**Comment by kalpaitch** [comment]
Hi, opening this up to see if you have a suggestion on how to configure the root provider when also using the chalice.tf.json template which also specifies a provider config block:

```
A default (non-aliased) provider configuration for "aws" was already given at
chalice.tf.json:230,12-13. If multiple configurations are required, set the
"alias" argument for alternative configurations.
```

One way would be to always export the packaged chalice template to a separate module, but my current setup would prefer to include this with other terraform configuration. And yet the provider block in chalice.tf.json cannot be overridden, all I need to add/merge is the provider.aws.region as per the comment https://github.com/aws/chalice/issues/1412#issuecomment-624614144

**Comment by kalpaitch** [comment]
For example when configuring with localstack I'd like my provider configuration to be:

```
provider "aws" {
  access_key                  = "mock_access_key"
  s3_force_path_style         = true
  secret_key                  = "mock_secret_key"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway      = "http://localhost:4566"
    cloudwatch      = "http://localhost:4566"
    xray            = "http://localhost:4566"
    ec2             = "http://localhost:4566"
    ...
    sts             = "http://localhost:4566"
  }
}
```

**Comment by hobochild** [comment]
@kalpaitch, I've just run into the same issue - did you find a way to achieve this?

**Comment by kalpaitch** [comment]
Only by not exporting chalice to the root module. Not ideal as it means I need an extra abstraction, but it works well enough.

**Comment by hobochild** [comment]
Cool :thinking:  but you set the `endpoints` config for localstack in the auto-generated chalice aws provider?

**Comment by kalpaitch** [comment]
I didn't, I put them in the root module and then called the chalice auto-generated config in a sub module.
