### ISSUE TITLE
Chalice should return an Allow header with the list of allowed methods in a 405 response

### ISSUE THREAD

**Issue by jrbeilke** [aws/chalice#1583]
Looks like the initial work was done in #160 to return an error with a 405 status code when an unsupported method is used, but Chalice should also include an `Allow` header in the response with a list of the supported methods.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow

```
The Allow header lists the set of methods supported by a resource.

This header must be sent if the server responds with a 405 Method Not Allowed status code to indicate which request methods can be used. An empty Allow header indicates that the resource allows no request methods, which might occur temporarily for a given resource, for example.
```

**Comment by jamesls** [comment]
Thanks for reporting, I'll take a look at your PR later today.

**Comment by jamesls** [comment]
Fixed via https://github.com/aws/chalice/pull/1584
