### ISSUE TITLE
Using chalice deploy with Localstack

### ISSUE THREAD

**Issue by tyagow** [aws/chalice#1585]
I am trying to use chalice-local to install chalice on localstack, but when doing chalice-local deploy I get errors on localstack related with chalice trying to delete some functions.

chalice-local - https://github.com/localstack/chalice-local

Here is the error:
```
deployer.py", line 378, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (405) when calling the DeleteFunctionConcurrency operation: 
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not 
 Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for 
 the requested URL.</p>
```
On localstack I get:
```
2020-11-20T12:56:52:INFO:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:ftg_chalice-local-handle_sqs_message
2020-11-20T12:56:52:INFO:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:ftg_chalice-local
```
Checking localstack logs
```
╰─± aws --endpoint-url=http://0.0.0.0:4566 lambda list-functions
{
    "Functions": []
}

```
I know this is not related 100% to chalice itself, but having more knowledge on chalice deployment would be helpful.

Why chalice is trying to delete a function that I don't have implemented - `function:ftg_chalice-local` ? 
I only have handle_sqs_message.

app.py:

```
app = Chalice(app_name="ftg_chalice")
app.log.setLevel(logging.INFO)

@app.middleware("http")
def http_middleware(request, get_response):
    if request.headers.get("x-chalice-secret") != CHALICE_SECRET:
        return Response(
            status_code=401,
            headers={"content-type": "text/plain"},
            body=json.dumps({"code": "UnauthorizedError", "message": "Unauthorized"}),
        )

    response = get_response(request)

    if response.status_code != 200:
        body = response.body
        if not isinstance(body, dict):
            body = json.loads(body)
        response.body = json.dumps({"code": body["Code"], "message": body["Message"]})

    return response

@app.on_sqs_message(queue='my-queue', batch_size=1)
def handle_sqs_message(event):
    for record in event:
        app.log.debug("Received message with contents: %s", record.body)
```

here are the services up on localstack:

```
{"services": {"cloudformation": "running", "cloudwatch": "running", "iam": "running", "sts": "running", "lambda": "running", "logs": "running", "sqs": "running", "ssm": "running", "apigateway": "running"}}
```

**Comment by tyagow** [comment]
If I comment out this, the deployment works:

![image](https://user-images.githubusercontent.com/700778/99837982-2a764b00-2b47-11eb-8568-1fc2cd8856d8.png)

**Comment by jamesls** [comment]
Thanks for reporting.  Browsing through the localstack [source code](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py), it looks like they don't implement the `delete_function_concurrency` API call (though they do implement the `put_concurrency`).  This is why the chalice deploy is failing.  If that is the case, I'm not sure what we can do on Chalice's side.

**Comment by tyagow** [comment]
> Thanks for reporting. Browsing through the localstack [source code](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py), it looks like they don't implement the `delete_function_concurrency` API call (though they do implement the `put_concurrency`). This is why the chalice deploy is failing. If that is the case, I'm not sure what we can do on Chalice's side.

Thank you for your response, I will add this to the issue I've created in localstack github.
