### ISSUE TITLE
Add `application/x-www-form-urlencoded` to _DEFAULT_BINARY_TYPES

### ISSUE THREAD

**Issue by binamkayastha** [aws/chalice#1589]
👋  I was wondering why `application/x-www-form-urlencoded` in this default list? And if it could be added?

https://github.com/aws/chalice/blob/8c48771ef0fe2ae97a00e337ca5828e709b132d3/chalice/app.py#L572-L577

I couldn't find an explanation of this in the docs anywhere, and I didn't need to do anything special in API Gateway to get my app to work with this type (when adding it to the `content_types` list in the `app.route` decorator)

**Comment by aparsekar** [comment]
From the docs - https://chalice.readthedocs.io/en/stable/api.html#APIGateway.default_binary_types

You could append to this list - 
`app.api.binary_types.append('application/my-binary-data')
`
or the list can be reassigned -
```
app.api.binary_types = [
    'application/octet-stream',
    'application/my-binary-data',
]
```

**Comment by jamesls** [comment]
Thanks @aparsekar for chiming in!

@binamkayastha The reason it's not in the default list of binary types is that it's a plain text encoding, and you generally wouldn't send binary content with the `application/x-www-form-urlencoded` content type (non alphanumeric content is percent encoded).  Let me know if you have any more questions.
