### ISSUE TITLE
ERROR: chalice 1.21.4 requires pip<20.3,>=9, but you'll have pip 20.3 which is incompatible

### ISSUE THREAD

**Issue by denis-ryzhkov** [aws/chalice#1590]
Another iteration of https://github.com/aws/chalice/issues/1344 and https://github.com/aws/chalice/issues/1085

**Comment by malaney** [comment]
Yes, the PIP upgrade and Chalice's dependency on it broke our build.  We've had to pin our pip version down in order to mitigate.  Unfortunate.

**Comment by jamesls** [comment]
Not sure why dependabot didn't catch this for us, I'll get this updated.
