### ISSUE TITLE
VPC is not getting configured with lambda while doing chalice deployment

### ISSUE THREAD

**Issue by saravanaemis** [aws/chalice#1597]
VPC is not getting configure with lambda though I supplied valid subnet_ids & security_group_ids to the chalice config.json file.
 
This is how my config file looks like,

"lambda_functions" : {
          "cohort_submit_to_compiler" : {
            "lambda_timeout": 600,
            "autogen_policy": false,
            "subnet_ids":["xxx-1","xxx-2"],
            "security_group_ids" : ["YYYY"],
            "iam_policy_file": "policy-dev.json"
          }
}

And also with my policy-dev.json, I provided mandatory access permission to the EC2 resource to create VPC configuration, And this is how my policy-dev.json looks like,
{
              "Action": [
                  "ec2:CreateNetworkInterface",
                  "ec2:DescribeNetworkInterfaces",
                  "ec2:DetachNetworkInterface",
                  "ec2:AttachNetworkInterface",
                  "ec2:DescribeInstances",
                  "ec2:DeleteNetworkInterface"
              ],
              "Resource": "*",
              "Effect": "Allow"
          }

**Note**: Deployment is getting success but VPC is not configured to my Lamba. 

Could someone please help me with this?

**Comment by jamesls** [comment]
Can you provide the output of the `chalice dev appgraph` command.  This will ensure that the lambda functions have the correct config options.

**Comment by saravanaemis** [comment]
Hi @jamesls 

Here's my project appgraph plan,
```
Application
├── SQSEventSource(resource_name=submit_to_compiler-sqs-event-source,
│   │              queue=sqs-lambda-compiler-queue,
│   │              batch_size=1,)
│   ├── LambdaFunction(resource_name=submit_to_compiler,
│   │   │              function_name=core_chalice-dev-submit_to_compiler,
│   │   │              environment_variables=ENVIRONMENT_VARIABLES,
│   │   │              runtime=python3.7,
│   │   │              handler=chalicelib.blueprints.execute.submit_to_compiler,
│   │   │              tags=TAGS,)
│   │   ├── ManagedIAMRole(resource_name=submit_to_compiler_role,
│   │   │   │              role_name=core_chalice-dev-dev-submit_to_compiler,
│   │   │   │              trust_policy=TRUST_POLICY,)
│   │   │   ├── FileBasedIAMPolicy(document=Placeholder.BUILD_STAGE,
│   │   │   │   │                  filename=/Users/xxxx/yyyy/zzzz/.chalice/policy-dev.json,)
│   │   ├── DeploymentPackage(filename=Placeholder.BUILD_STAGE,)
├── SQSEventSource(resource_name=submit_to_runtime-sqs-event-source,
│   │              queue=sqs-lambda-runtime-queue,
│   │              batch_size=1,)
│   ├── LambdaFunction(resource_name=submit_to_runtime,
│   │   │              function_name=core_chalice-dev-dev-submit_to_runtime,
│   │   │              environment_variables=ENVIRONMENT_VARIABLES,
│   │   │              runtime=python3.7,
│   │   │              handler=chalicelib.blueprints.runtime.submit_to_runtime,
│   │   │              tags=TAGS,)
│   │   ├── ManagedIAMRole(resource_name=submit_to_runtime_role,
│   │   │   │              role_name=core_chalice-dev-dev-submit_to_runtime,
│   │   │   │              trust_policy=TRUST_POLICY,)
│   │   │   ├── FileBasedIAMPolicy(document=Placeholder.BUILD_STAGE,
│   │   │   │   │                  filename=/Users/xxxx/yyyy/zzzz/.chalice/policy-dev.json,)
│   │   ├── DeploymentPackage(filename=Placeholder.BUILD_STAGE,)
├── RestAPI(resource_name=rest_api,
│   │       swagger_doc=Placeholder.BUILD_STAGE,
│   │       api_gateway_stage=api,
│   │       endpoint_type=EDGE,)
│   ├── LambdaFunction(resource_name=api_handler,
│   │   │              function_name=core_chalice-dev,
│   │   │              environment_variables=ENVIRONMENT_VARIABLES,
│   │   │              runtime=python3.7,
│   │   │              handler=app.app,
│   │   │              tags=TAGS,)
│   │   ├── ManagedIAMRole(resource_name=api_handler_role,
│   │   │   │              role_name=chalice-dev-api_handler,
│   │   │   │              trust_policy=TRUST_POLICY,)
│   │   │   ├── FileBasedIAMPolicy(document=Placeholder.BUILD_STAGE,
│   │   │   │   │                  filename=/Users/xxxx/yyyy/zzzz/.chalice/policy-dev.json,)
│   │   ├── DeploymentPackage(filename=Placeholder.BUILD_STAGE,)
```

Note: With the same subnet and security group id I can able to configure VPC manually with the AWS console for the same lambda. But with chalice deployment, it's not getting configured.

**Comment by saravanaemis** [comment]
Hi @jamesls,

Could you please look into the project app graph plan, I can't figure out any wrong with my policy or app graph plan?

**Comment by jamesls** [comment]
Based on your app graph output, it doesn't look like there's any VPC configuration being applied.  You should see something like this (note the subnet_ids and security_group_ids):

```
Application
├── LambdaFunction(resource_name=test_function,
│   │              function_name=my-app-dev-test_function,
│   │              environment_variables=ENVIRONMENT_VARIABLES,
│   │              runtime=python3.7,
│   │              handler=app.test_function,
│   │              tags=TAGS,
│   │              security_group_ids=SECURITY_GROUP_IDS,
│   │              subnet_ids=SUBNET_IDS,)
```

I would double check the names of your functions that match the names in your config file.  Not sure if it's just the sanitized output, but your appgraph has a function named `submit_to_compiler` and the function name in the config file is `cohort_submit_to_compiler`.

**Comment by saravanaemis** [comment]
Thanks for the inform, I figured out the problem. 

The problem was, I have name mismatched with the method I used for on_sqs_event with the config file.
