### ISSUE TITLE
Chalice Lambda Versions and Alias

### ISSUE THREAD

**Issue by Gladiator7640** [aws/chalice#1600]
Hi 

We are using Chalice for a big project, and we want to deploy many Lambda versions along with Lambda Alias, Canary releases is another important issue that we must consider into account. Unfortunately, I couldn't find anything regarding Lambda Versions or Alias using Chalice. In other words, we want to deploy Serverless applications gradually. AWS SAM has provided us with the following features:

If you use AWS SAM to create your serverless application, it comes built-in with CodeDeploy to provide gradual Lambda deployments. With just a few lines of configuration, AWS SAM does the following for you:

Deploys new versions of your Lambda function, and automatically creates aliases that point to the new version.
Gradually shifts customer traffic to the new version until you're satisfied that it's working as expected, or you roll back the update.
Defines pre-traffic and post-traffic test functions to verify that the newly deployed code is configured correctly and your application operates as expected.
Rolls back the deployment if CloudWatch alarms are triggered.

My question is that can I combine AWS Chalice CloudFormation Support with AWS SAM to achieve this goal?

I will be grateful for any help you can provide.

**Comment by jamesls** [comment]
Chalice doesn't support versions or aliases directly.  You can combine the generated cloudformation with additional configuration that can add these values.  For example:

```
$ cat deployment-prefs.yml
Global:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Linear10PercentEvery10Minutes
````

```
$ chalice package --merge-template deployment-prefs.yml out
```

And then from there you'd deploy your SAM template in the `out/` directory.

**Comment by Gladiator7640** [comment]
Thanks James :) 👍
