### ISSUE TITLE
Environment Variables not applied Properly

### ISSUE THREAD

**Issue by loesak** [aws/chalice#1602]
New to Chalice so forgive me if I am mistaken.

I am using Chalice to generate Terraform configuration.

It seems that environment variables may not be applied properly in certain circumstances. Or they are and it's not intuitive and leads to misconfiguration.

I have two lambdas; one that is triggered via a CloudWatch event (cron scheduled)
```python
_CRON = os.environ.get('CRON')
app.schedule(_CRON)
def kick_off_batch_job(event):
```

and one that is triggered off an S3 event
```python
_BUCKET = os.environ.get('BUCKET')
@app.on_s3_event(bucket=_BUCKET, events=['s3:ObjectCreated:*'])
def persist_data(event: S3Event):
```

Using the following configuration:
```json
{
  "version": "2.0",
  "app_name": "my-app",
  "tags": {
    "Terraform": "yes"
  },
  "autogen_policy": false,
  "stages": {
    "dev": {
      "environment_variables": {
        "ENV": "dev"
      },
      "tags": {
        "Environment": "dev"
      },
      "lambda_functions": {
        "kick_off_batch_job": {
          "iam_policy_file": "policy/dev/kick_off_batch_job.json",
          "environment_variables": {
            "CRON": "cron(0, 6, *, *, ?, *)"
          }
        },
        "persist_data": {
          "iam_policy_file": "policy/dev/persist_data.json",
          "environment_variables": {
            "BUCKET": "my-bucket"
          }
        }
      }
    }
  }
}
```

and running the command
```shell
AWS_DEFAULT_REGION=us-east-1 chalice package --stage dev --pkg-format terraform terraform/
```

results in the following stack
```shell
Creating deployment package.
Traceback (most recent call last):
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/chalice/cli/__init__.py", line 656, in main
    return cli(obj={})
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/chalice/cli/__init__.py", line 575, in package
    packager.package_app(config, out, stage)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/chalice/package.py", line 1216, in package_app
    template = self._templater.generate(resources)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/chalice/package.py", line 817, in generate
    self.dispatch(resource, template)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/chalice/package.py", line 137, in dispatch
    handler(resource, template)
  File "/home/aloes/Development/git/chalice/.venv/lib/python3.8/site-packages/chalice/package.py", line 882, in _generate_s3bucketnotification
    if '{aws_s3_bucket.' in resource.bucket:
TypeError: argument of type 'NoneType' is not iterable
```

Debugging the Chalice process, I determined it was not finding the value for my bucket from the environment when defined in the lambdas `environment_variables` configuration section. Moving the value to the `stages` environment variable configuration allowed the build to work... 
```json
{
  "version": "2.0",
  "app_name": "my-app",
  "tags": {
    "Terraform": "yes"
  },
  "autogen_policy": false,
  "stages": {
    "dev": {
      "environment_variables": {
        "ENV": "dev",
        "BUCKET": "my-bucket",
        "CRON": "cron(0, 6, *, *, ?, *)"
      },
      "tags": {
        "Environment": "dev"
      },
      "lambda_functions": {
        "kick_off_batch_job": {
          "iam_policy_file": "policy/dev/kick_off_batch_job.json"
        },
        "persist_data": {
          "iam_policy_file": "policy/dev/persist_data.json"
        }
      }
    }
  }
}
```

but now both lambdas had both environment variable set. 
```json
{
  ... snip ...
  "resources": {
    "aws_lambda_function": {
      "kick_off_batch_job": {
        ... snip ...
        "environment": {
          "variables": {
            "ENV": "dev",
            "CRON": "cron(0, 6, *, *, ? *)",
            "BUCKET": "my-bucket"
          }
        },
        ... snip ...
      },
      "persist_data": {
        ... snip ...
        "environment": {
          "variables": {
            "ENV": "dev",
            "CRON": "cron(0, 6, *, *, ? *)",
            "BUCKET": "my-bucket"
          }
        },
        ... snip ...

      }
    }
    "aws_cloudwatch_event_rule": {
      "kick_off_batch_job-event": {
        "name": "kick_off_batch_job",
        "schedule_expression": "cron(0, 6, *, *, ?, *)",
        "description": ""
      }
    }
  }
  ... snip ...
}
```

Not very clean but works. However, I wondered what would happen if the variable was set in both places (stage and lambda) with different values.
```json
{
  "version": "2.0",
  "app_name": "my-app",
  "tags": {
    "Terraform": "yes"
  },
  "autogen_policy": false,
  "stages": {
    "dev": {
      "environment_variables": {
        "ENV": "dev",
        "BUCKET": "not-my-bucket",
        "CRON": "cron(0, 6, *, *, ?, *)"
      },
      "tags": {
        "Environment": "dev"
      },
      "lambda_functions": {
        "kick_off_batch_job": {
          "iam_policy_file": "policy/dev/kick_off_batch_job.json",
          "environment_variables": {
            "CRON": "cron(30, 4, *, *, ?, *)"
          }
        },
        "persist_data": {
          "iam_policy_file": "policy/dev/persist_data.json",
          "environment_variables": {
            "BUCKET": "my-bucket"
          }
        }
      }
    }
  }
}
```

The result was a bit confusing
```json
{
  ... snip ...
  "resources": {
    "aws_lambda_function": {
      "kick_off_batch_job": {
        ... snip ...
        "environment": {
          "variables": {
            "ENV": "dev",
            "CRON": "cron(30, 4, *, *, ? *)",
            "BUCKET": "not-my-bucket"
          }
        },
        ... snip ...
      },
      "persist_data": {
        ... snip ...
        "environment": {
          "variables": {
            "ENV": "dev",
            "CRON": "cron(0, 6, *, *, ? *)",
            "BUCKET": "my-bucket"
          }
        },
        ... snip ...

      }
    }
    "aws_cloudwatch_event_rule": {
      "kick_off_batch_job-event": {
        "name": "kick_off_batch_job",
        "schedule_expression": "cron(0, 6, *, *, ?, *)",
        "description": ""
      }
    }
  }
  ... snip ...
}
```

Here you can see that the cloudwatch event is triggered with the schedule expression `cron(0, 6, *, *, ?, *)`, however the lambda is given the expression `cron(30, 4, *, *, ? *)`. For anyone reviewing the code and chalice configraiton (not terraform) in the aws console, or in their IDE could reasonably and incorrectly assume that the used cron expression would be `cron(30, 4, *, *, ? *)`.

I assume Chalice is not inspecting the environment variables of the individual lambdas when deciding how the infrastructure should be built, which makes sense to some degree when i think about it.

I could not find anything in the documentation about where environment variables need to be set for different use cases. I think for now, I'll have to assume that environment variables used for the decorators have to be defined in the top level or stage level `environment_variables` configuration and not at the lambda level and just deal with the fact that some lambdas are going to get environment variables that they just don't need set.

**Comment by jamesls** [comment]
Thanks for the detailed write up.

> I assume Chalice is not inspecting the environment variables of the individual lambdas when deciding how the infrastructure should be built, which makes sense to some degree when i think about it.

The environment variables that are set during build/package time only come from the global or stage-specific env vars, not from function specific env vars.  Although these environment variables will be set properly for each function when the function is invoked on Lambda.

The reason it's this way is that Chalice imports your app in order to see what resources it needs to generate.  So we have to pick one set of environment variables that we set before we import your app.  It's not clear what the expected resolution should be if two functions define the same env vars with different values.  We'd have to essentially reload the app.py file for each Lambda function with a new set of environment variables each time, which I'm not sure is a good idea.

The documentation should be updated to reflect this, I don't believe we document this behavior.

Somewhat related is the idea of application parameters (https://github.com/aws/chalice/issues/608#issuecomment-345391098), which would let you specify config values without having to use lambda environment variables (assuming you don't need access to the `CRON` value inside your lambda function).  It didn't generate a whole lot of interest, but I'm not opposed to adding it.

**Comment by jamesls** [comment]
Documented in #1603.  Tracking app params in #608.
