### ISSUE TITLE
Support for resource policy

### ISSUE THREAD

**Issue by lucagherardi** [aws/chalice#1604]
Hi everyone,

I'm writing an application where I want to use SES to store emails on a bucket.
To do that I have a rule that first invokes a lambda to do some filtering on the email and then stores the data in a bucket.

What is the best way of creating the policies for lambda and bucket in a programmatic way?

The lambda function needs the following policy:

```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "allowSesInvoke",
      "Effect": "Allow",
      "Principal": {
        "Service": "ses.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:eu-west-1:************:function:my-lambda-function",
      "Condition": {
        "StringEquals": {
          "AWS:SourceAccount": "************"
        }
      }
    }
  ]
}
``` 

While the bucket needs the following policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowSESPuts-1607719263506",
            "Effect": "Allow",
            "Principal": {
                "Service": "ses.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::my-bucket/*",
            "Condition": {
                "StringEquals": {
                    "aws:Referer": "************"
                }
            }
        }
    ]
}
```

I thought about using boto3 to do that, but how do I make sure that the policy are applied only at deployment time (chalice deploy) and when it is the right time to do so? At the end of the app file? Is there an environment variable set by chalice deploy to detect the process?

Any better idea? :-)

Thanks in advance,
Luca

**Comment by jamesls** [comment]
You can specify your own policy to be used for your lambda functions in the `.chalice/` directory.  You can use the default name of `.chalice/policy-<stage>.json` or you can specify your own file via `iam_policy_file` (docs https://aws.github.io/chalice/topics/configfile.html#iam-roles-and-policies).  Chalice doesn't manage S3 bucket policies you'd have to add that as a separate step in your deployment after you run `chalice deploy`.   Or you can use either terraform/SAM so you can deploy everything as a single stack (https://aws.github.io/chalice/topics/cfn.html).  Let me know if you have any more questions.
