### ISSUE TITLE
Cognito User Pool Authorized route throwing CORS error 

### ISSUE THREAD

**Issue by dellysoul** [aws/chalice#1609]
I'm following the available documentation and having trouble using the cognito authorizer with the following set up and 2 test routes:

``` 
authorizer = CognitoUserPoolAuthorizer('careercloudusers', provider_arns=[CORRECT_POOL_ARN])

cors_config = CORSConfig(
    allow_origin='http://localhost:8080',
    allow_headers=['X-Special-Header'],
    max_age=600,
    expose_headers=[''],
    allow_credentials=True
)

@app.route('/dash-data', methods=['GET'], cors=cors_config)
def my_dashboard():
    try:
        return {"message": 'yo'}
    except Exception as e:
        return {"message": str(e)}


@app.route('/me', methods=['GET'], authorizer=authorizer)
def me():
    try:
        user_id = _get_authenticated_username()
        return {"message": user_id}
    except Exception as e:
        return {"message": str(e)}
```

I have no issues connecting to the actual cors enabled route /dash-data from localhost:8080, but when pinging /me I get the usual blocked by CORS error.
``` from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. ```

Querying from POSTman using the same Authorization bearer token that's sending from localhost, I'm able to connect to localhost:8080/me which ensures that the authorizer is working

Seems like adding authorizer to the route is injecting some OPTIONS that is causing the rejection. Not sure what to do here, so opening this ticket. 

Thanks!

**Comment by dellysoul** [comment]
Closing as this turned out to be an issue with the user pool config, and nothing with this framework itself.

**Comment by csm-kb** [comment]
@dellysoul What in your user pool config was causing this preflight issue, for reference?
