### ISSUE TITLE
Event handlers cannot access chalice app instance when registered via Blueprints

### ISSUE THREAD

**Issue by yvnbunag** [aws/chalice#1615]
Consider the following project (Files and code not related are stripped off)
```
├── app.py
├── chalicelib
│   ├── services
│   │   ├── DailyLoginReport.py
├── ...  
```
**app.py**
```
import logging
from chalice import Chalice

from chalicelib.services.DailyLoginReport import dailyLoginReport

services = [ dailyLoginReport ]

app = Chalice()

for service in services:
    app.register_blueprint(service)
```
**chalicelib/services/DailyLoginReport.py**
```
from chalice import Blueprint, Cron

dailyLoginReport = Blueprint(__name__)

@dailyLoginReport.schedule(Cron(0, 7, '*', '*', '?', '*'))
def emailDailyLoginReport(event):
    dailyLoginReport.current_app.log.info('EVENT HANDLER')

    return True

@dailyLoginReport.route('/daily-login-report', methods=['POST'])
def emailDailyLoginReportTrigger():
    dailyLoginReport.current_app.log.info('ENDPOINT HANDLER')

    return True
```
I recently tried out the blueprints feature to improve the modular structure of the project. In the previous implementation, I am importing the Chalice app instance in the service files to be able to use its logger instance when handling endpoint requests and events - and is working as intended.

In the refactored implementation, we could obtain the app instance [thru the blueprint's current_app property](https://github.com/aws/chalice/issues/1094). I am able to use its logger on the endpoint handlers (emailDailyLoginReportTrigger method in the given example). However, when the method is triggered thru an event (schedule, on_sqs_message, emailDailyLoginReport method in the given example) it results in an error (from Cloudwatch log):
```
[ERROR] RuntimeError: Can only access Blueprint.current_app if it's registered to an app.
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1544, in __call__
    return self.handler(event_obj)
  File "/var/task/chalicelib/services/DailyLoginReport.py", line 22, in emailDailyLoginReport
    print(dailyLoginReport.current_app)
  File "/var/task/chalice/app.py", line 1922, in current_app
    "Can only access Blueprint.current_app if it's registered "
```

This is related to [Blueprints and lambda function inconsistency #1566](https://github.com/aws/chalice/issues/1566), as I have experienced it as well and it seems to be the same reason for the bug in this issue - event handlers are being invoked directly so the Chalice app is not being instantiated.

**EDIT:**
Chalice version is 1.21.7.

**Comment by jamesls** [comment]
Yeah, it's the same root cause as #1566.  We're trying to work out the best option here which is likely going to require all the handlers (and blueprints) to go through a central routing method.  Let's track that work over in #1566.

**Comment by yvnbunag** [comment]
Alright, thanks. Hoping a fix will be rolled out soon.
