### ISSUE TITLE
Segmentation Fault when using auto-generated layers

### ISSUE THREAD

**Issue by onurmatik** [aws/chalice#1616]
I am using "automatic_layer" and because the generated layer is > 50 MB, I am uploading the generated `managed-layer-...-python3.7.zip` manually to s3 and create a Lambda layer. Then I re-deploy with chalice, removing the `automatic_layer` option and setting the `layers` to the generated ARN of the layer I manually created. 

The function deployed this way worked OK for a couple of times, then started failing occasionally with "Segmentation Fault". The error rate increased shortly and now it is failing 100%.

Traceback:

> OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
> START RequestId: 3b98bd4b-6cda-4d21-8090-1a49b17c06fc Version: $LATEST
> OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
> END RequestId: 3b98bd4b-6cda-4d21-8090-1a49b17c06fc
> REPORT RequestId: 3b98bd4b-6cda-4d21-8090-1a49b17c06fc Duration: 7165.04 ms Billed Duration: 7166 ms Memory Size: 128 MB Max Memory Used: 41 MB
> RequestId: 3b98bd4b-6cda-4d21-8090-1a49b17c06fc Error: Runtime exited with error: signal: segmentation fault (core dumped)
> Runtime.ExitError

My environment requirement is ´awswrangler´. Because it itself requires boto3 & botocore, and they are already in the Lambda environment, I suspected that there might be a conflict of different versions of boto. I tried the same flow by explicitly including boto3 and botocore in the requirements but I am still receiving the segmentation fault.

**Comment by jamesls** [comment]
Hmm, not sure about boto3 and botocore causing the segfaults.  They don't have any C dependencies so the worst case I'd expect is a python level exception if there were incompatibilities between the two.  Looking over the dependencies of `awswrangler`, there seems to several C extensions used by those libraries that might be causing issues, it's especially weird that everything seemed to work ok but started failing more over time.

Are you seeing the same issues when you use the lambda layers they publish? https://github.com/awslabs/aws-data-wrangler/releases

**Comment by onurmatik** [comment]
It is working fine with the lambda layer they published. Thank you for the pointer!

**Comment by jamesls** [comment]
Glad it's working for you!  I'm guessing there's something specific about how that library needs to be built.
