### ISSUE TITLE
Alternatives for Flask modules like WTForms?

### ISSUE THREAD

**Issue by tvb** [aws/chalice#1617]
Hi,

Now this looks to be an interesting project! 

I have a Flask app for which I would like to determine if a rebuild to Chalice is possible. It uses a few Flask modules like Sessions, Babel (i18n), Toastr (pretty alerts), and WTForms (HTML forms builder) alongside of the Jinja2 template engine and some other python extensions like upcountry. I have found that Jinja2 can be integrated into Chalice, but am I right to assume none of these Flask module are supported in Chalice, nor are there any alternatives available for it?

And if not, will there be support in any form for these kind of extensions?

**Comment by jamesls** [comment]
Hi, there's no built-in support for flask modules/extensions, but you should be able to use the underlying libraries such as WTForms/Jinja2 directly in Chalice.  Another thing to keep in mind is a common usage of Chalice is for the underlying JSON api that's combined with a client side front end framework (react, vue, etc), but you still have the option of generating HTML server side as well if you prefer.

**Comment by tvb** [comment]
I see, I am using Flask now for my frontend hence my question. Thanks!

**Comment by lpwm** [comment]
https://github.com/marshmallow-code/marshmallow
