### ISSUE TITLE
Deploy lambda function without APIG

### ISSUE THREAD

**Issue by akranga** [aws/chalice#162]
Api Gateway support is very nice, however it should be possible to deploy AWS Lambda function with chalice that has not been exposed to the user (without API gateway). 

Appreciate any workaround

**Comment by byumark** [comment]
+1

**Comment by frob** [comment]
+1

**Comment by dimo3d** [comment]
+1 if I can connect it to a SQS or SNS event.

**Comment by frob** [comment]
First step should be to make deployments work without decorators.

**Comment by khatiba** [comment]
+1

**Comment by jamesls** [comment]
Marking as feature request, I'd like to add support for this.

**Comment by lucamezzalira** [comment]
+1

**Comment by boosh** [comment]
I'd like this for scaling images when they're uploaded to S3, so would need to respond to S3 events.

**Comment by jamesls** [comment]
Quick update on this.  This is now partially possible using the `@app.lambda_function()` (docs http://chalice.readthedocs.io/en/latest/topics/purelambda.html).  There's still a limitation that you have to have at least one route defined (so this would be to create *additional* lambda functions), but this is a limitation I plan on removing soon.

**Comment by manojtr** [comment]
> Quick update on this. This is now partially possible using the `@app.lambda_function()` (docs http://chalice.readthedocs.io/en/latest/topics/purelambda.html). There's still a limitation that you have to have at least one route defined (so this would be to create _additional_ lambda functions), but this is a limitation I plan on removing soon.

Hello @jamesls, I am just wondering, have you removed the above limitation yet? I could see any doco without the API GW component. I am keen to use chalice for my multiple lambda services that doesn't have anything to do with API GW. Please let me know if it is possible. Thank you, Manoj
