### ISSUE TITLE
Chalice package process stops picking up custom packages

### ISSUE THREAD

**Issue by iandesj** [aws/chalice#1621]
A little background...
I was writing my application with chalice version 1.21.4 and everything was well. The project has several custom python packages that we wrote and include in our requirements.txt file like so:
```
file:../mypackage
file:../myotherpackage
```

I noticed that after I upgraded from 1.21.4 to 1.21.8 that these custom packages were not getting brought in anymore and bundled in the deployment package. This was causing the `app` module to error on import because these were missing.

I didn't have time to check the other versions between x.x.4 and x.x.8, so I couldn't tell you if that change was made in x.x.8 or prior.

**Comment by jamesls** [comment]
Looking through our CHANGELOG, the only packaging related changes in that version range was related to supported manylinux2014 wheels (#1551) which I wouldn't expect to cause the issue you're seeing.  A couple of questions:

* Does your custom python package require building any C extensions/dependencies?
* What OS are you developing on?

If possible, could you post a sanitized version of the debug logs for the package command?  (Something like `chalice --debug package out 2>&1 | grep chalice`)
