### ISSUE TITLE
Can chalice create two lambda functions belongs to same cloudwatch event

### ISSUE THREAD

**Issue by vumdao** [aws/chalice#1623]

**Comment by jamesls** [comment]
You'd have to configure them separately and have them call out to the same underlying function:

```python
@app.on_cw_event({"source": ["aws.codecommit"]})
def first(event):
    return real_handler(event)

@app.on_cw_event({"source": ["aws.codecommit"]})
def second(event):
    return real_handler(event)

def real_handler(event):
    # Actual shared logic goes here
    ....
```

**Comment by vumdao** [comment]
@jamesls Thanks for your help but it does not work for my case

`def hello():
    app.log.debug("Say hello!")
    send_slack("hello")


def goodbye():
    app.log.debug("Say goodbye!")
    send_slack("goodbye")


def handle_event(event):
    if event == 'hello':
        hello()
    elif event == 'goodbye':
        goodbye()
    else:
        print("Wrong event")


@app.schedule('cron(* * ? * * *)')
def lamdba_hello(event):
    return handle_event('hello')


@app.schedule('cron(* * ? * * *)')
def lamdba_goodbye(event):
    return handle_event('goodbye')`

It create two cloudwatch rules instead of one
![image](https://user-images.githubusercontent.com/37215642/105373930-c0a71a00-5c39-11eb-8491-0a73a761101e.png)
