### ISSUE TITLE
pip version lock is not compatible with the latest version (21.0)

### ISSUE THREAD

**Issue by seratch** [aws/chalice#1627]
Chalice has its compatible version range for pip: `pip<20.4`.

The latest pip version is 21.0 now. Is there any chance to change this range to accept 20.4 and higher? If it's fine to loosen this limit, I am happy to send a pull request.

>ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chalice 1.22.0 requires pip<20.4,>=9, but you have pip 21.0 which is incompatible.

**Comment by jamesls** [comment]
Yeah, let's bump that up to accept the latest version of pip.

**Comment by jamesls** [comment]
Ah, I think dependabot didn't pick this up because of the migration to native-github.  I believe after upgrading their config file (https://github.com/aws/chalice/pull/1629) we should start automatically picking up these version updates going forward (https://github.com/aws/chalice/pull/1630).

**Comment by seratch** [comment]
Thanks! It seems https://github.com/aws/chalice/pull/1630 fixes this :+1:
