### ISSUE TITLE
Can you deploy Lambda@Edge functions with chalice?

### ISSUE THREAD

**Issue by kortina** [aws/chalice#1632]
I was looking through https://aws.github.io/chalice/topics/events.html to see if there was support for Lambda@Edge (my guess was there might be a CloudFront Event section) but didn't see one.

I'm curious if it is possible to somehow use chalice to deploy Lambda@Edge functions. AWS docs on the Event Structure here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html

Is the only necessary step to hook into the correct Event types as a trigger for the lambda, or do you think I would have to do any other configuration to use chalice to manage a [Lambda@Edge Function](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html)?

**Comment by jamesls** [comment]
Chalice does not support lambda@edge functions right now.  There's a few more steps involved with the lambda@edge functions, you'll need to ensure that cloudfront->lambda have the appropriate permissions and then set up the configuration in your cloudfront distribution.

**Comment by brianmingus2** [comment]
@jamesls I am interested in lambda@edge support, to achieve lower latency. Do you know the level of effort for this task might be?

**Comment by tedmiston** [comment]
@jamesls @brianmingus2 Do you know if there's a ticket we can follow on the roadmap for lambda@edge support?  I'm very interested in this feature as well.
