### ISSUE TITLE
Generated resource-based policy when deploying an on_s3_event is not secure

### ISSUE THREAD

**Issue by szamarin** [aws/chalice#1635]
When deploying an app with a on_s3_event Chalice automatically generates a policy that gives invoke permissions to the specified bucket. However the bucket names is not tied to the account, so if the bucket is deleted it potentially exposes the lambda function to confused deputy attacks. An "AWS:SourceAccount" condition should be added to restrict permissions.

**Comment by jamesls** [comment]
Thanks for reporting, we'll get that updated.
