### ISSUE TITLE
requirements.txt is not being packaged into deployment.zip in 1.2.0

### ISSUE THREAD

**Issue by lvenki94** [aws/chalice#1642]
`chalice package`  is not packaging the requirements.txt into deployment.zip

**Comment by jamesls** [comment]
Can you give me a specific example (including a sample `requirements.txt` file)?  `chalice package` should be automatically packaging your requirements file.  Also if you're using `1.2.0` I'd suggest upgrading to the latest version and trying again.  That version came out almost 2 years ago, and there's been numerous improvements and fixes to the packager since that time.

**Comment by lvenki94** [comment]
Context:

**Deployment Scenario 1:**
Chalice version: **1.12.0**
Command: `chalice package --merge-template extras.json out`
requirements.txt file:

`attrs==19.3.0
boto3==1.14.43
botocore==1.17.43
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
docutils==0.15.2
enum-compat==0.0.3
idna==2.10
Jinja2==2.11.2
jmespath==0.10.0
MarkupSafe==1.1.1
mypy-extensions==0.4.3
numpy==1.19.1
phonenumbers==8.12.10
psycopg2-binary==2.8.5
python-dateutil==2.8.1
python-dotenv==0.14.0
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
s3transfer==0.3.3
six==1.15.0
structlog==20.1.0
urllib3==1.25.10`

**Deployment Scenario 2:**

Chalice version: **1.2.0**
Command: `chalice package --merge-template extras.json out`
requirements.txt file:

`attrs==19.3.0
boto3==1.14.43
botocore==1.17.43
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
docutils==0.15.2
enum-compat==0.0.3
idna==2.10
Jinja2==2.11.2
jmespath==0.10.0
MarkupSafe==1.1.1
mypy-extensions==0.4.3
numpy==1.19.1
phonenumbers==8.12.10
psycopg2-binary==2.8.5
python-dateutil==2.8.1
python-dotenv==0.14.0
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
s3transfer==0.3.3
six==1.15.0
structlog==20.1.0
urllib3==1.25.10`


When I download the deployment package from the Lambda, I don't see the all the required packages in Scenario 2.
I see all the required packages in scenario 1. 

Scenario 1 - is a a local deployment. where I've been using chalice version 1.12.0 for a long without any issue.
Scenario 2 - is pipeline run when code is pushed so a new chalice is downloaded every time the pipeline is run.

Once I fixed the pipeline to download to chalice version 1.12.0. The issue was fixed.

**Comment by jamesls** [comment]
Glad to hear you got it working!
