### ISSUE TITLE
Chalice Deploy CLI Command Failed to Recognize "autogen_policy" = "False" Configuration

### ISSUE THREAD

**Issue by samuelkhtu** [aws/chalice#1643]
Hello, I tried to follow [AWS Chalice Document](https://aws.github.io/chalice/topics/configfile#iam-policy-file) to deploy a custom policy but the ```chalice deploy``` cli won't pick up the ```"autogen_policy" : "False" ``` parameter. 

.chalice/config.json
```json

{
    "version": "1.0",
    "app_name": "aws-chalice-template",
    "stages": {
        "dev": {
            "api_gateway_stage": "dv",
            "environment_variables": {
                "ENV_LOG_LEVEL": "INFO"
            },
            "autogen_policy": "False"
        }
    }
}

```

I have the "policy-dev.json" located in .chalice folder. 

.chalice/policy-dev.json

```json

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": ["apigateway:POST", "apigateway:GET"],
            "Resource": "*"
        }
    ]
}


```

I reviewed the Chalice code and I think the issue is located at line 418 in ```chalice/deploy/appgraph.py.``` 

```python

if not config.autogen_policy:

```

The condition expect ```config.autogen_policy``` as Boolean type but unfortunately ```chalice/config.py``` (line 335) property actually return string type instead.

```python
 @property
    def autogen_policy(self):
        # return False
        # type: () -> bool
        return self._chain_lookup('autogen_policy',
                                  varies_per_chalice_stage=True,
                                  varies_per_function=True)

```

Therefore, the ```if not config.autogen_policy``` won't work as expected.

I patched the code locally and the chalice deploy works as expected.

```python

from distutils.util import strtobool
...
if not bool(strtobool(config.autogen_policy)):
...

```

Can someone help and confirm this issue?  Do you think converting the property value to Boolean for this condition is a bit overkill? I am more than happy to submit a pull request to fix this issue.

I also reviewed the code in other area, I believe other properties (e.g. config.py line 305 automatic_layer) have the same issue.

Thanks

**Comment by jamesls** [comment]
I'll update the docs here, but the value is expected to be a boolean type, not a string, so the config value should be:

```
            "autogen_policy": false
```

There's some examples in the [IAM Roles and Policies](https://aws.github.io/chalice/topics/configfile#iam-roles-and-policies) section, but I'll clarify that section as well.

**Comment by samuelkhtu** [comment]
Thanks @jamesls It works.
