### ISSUE TITLE
subnet, security group ids in config not being recognized per lambda function

### ISSUE THREAD

**Issue by johnkeep** [aws/chalice#1689]
**Background:** We have a RDS database in a VPC that we want some chalice functions to use to read and write to the database. We have many function/chalice route endpoints. They all seem to get packaged under one function so we can't manually change VPC settings for each chalice route endpoints.

**Problem:** Setting subnet, security group ids in chalice.config for specific lambda function is not updated at all upon deployment.

_config.json_
```

{
  "version": "2.0",
  "app_name": "test",
  "autogen_policy": true,
  "stages": {
    "dev": {
      "environment_variables": {
        "STAGE": "dev",
        "DB_NAME": "database"
      },
      "api_gateway_stage": "dev",
      "lambda_functions":{
        "read": {
          "subnet_ids": ["subnet-123","subnet-1231"],
          "security_group_ids": ["sg-1234"]
        },
        "write":{
          "subnet_ids": ["subnet-123","subnet-1231"],
          "security_group_ids": ["sg-1234"]
        }
      }
    }
}
```

According to the documentation: _"A list of subnet ids for VPC configuration. This value can be provided per stage as well as per Lambda function. In order for this value to take effect, you must also provide the security_group_ids value. When both values are provided and autogen_policy is True, chalice will automatically update your IAM role with the necessary permissions to create, describe, and delete ENIs. "_

**Expected:** above but in reality that was never happening. Running `chalice dev appgraph` shows below.

**Actual:** subnet, security group not updated. 

```
Application
├── RestAPI(resource_name=rest_api,
│   │       swagger_doc=Placeholder.BUILD_STAGE,
│   │       api_gateway_stage=api,
│   │       endpoint_type=EDGE,
│   │       authorizers=AUTHORIZERS,)
│   ├── LambdaFunction(resource_name=api_handler,
│   │   │              function_name=test,
│   │   │              environment_variables=ENVIRONMENT_VARIABLES,
│   │   │              runtime=python3.8,
│   │   │              handler=app.app,
│   │   │              tags=TAGS,)
│   │   ├── ManagedIAMRole(resource_name=default-role,
│   │   │   │              role_name=test,
│   │   │   │              trust_policy=TRUST_POLICY,)
│   │   │   ├── AutoGenIAMPolicy(document=Placeholder.BUILD_STAGE,)
│   │   ├── DeploymentPackage(filename=Placeholder.BUILD_STAGE,)
```

`LambdaFunction` is missing the security group, subnet ids specified from the config file.

Chalice Version: 1.22.2

**Comment by jamesls** [comment]
Hi johnkeep,

Due to historical reasons, Chalice uses a single Lambda function for your rest API.  All the other event decorators (e.g. `on_s3_event`, `schedule`, `on_sns_message`, etc.) all result in a new lambda function being created.  If you want to configure the lambda function for the rest api you'd use the `api_handler` name in the Chalice config file.  There's more details in the docs [here](https://aws.github.io/chalice/topics/configfile.html#lambda-specific-configuration).

> There is one exception to this, which is any python function decorated with the @app.route() decorator. Chalice uses a single Lambda function for all requests from API gateway, and this name is api_handler.

There is an existing feature request to allow multiple Lambda functions for a REST API, but that has not been implemented yet.  Let me know if you have any more questions.
