### ISSUE TITLE
Cloudwatch scheduled event naming conflicts with multiple stages

### ISSUE THREAD

**Issue by jrbeilke** [aws/chalice#1691]
Have a Chalice app with multiple stages deployed to the same AWS account and running into an issue where scheduled events from one stage of the app are conflicting with events for another stage.

ie.
dev stage lambda is `api-dev-work_request_notifier` and is tied to a `work_request_notifier-event` event in cloudwatch

then we deploy our prod stage and end up with

prod stage lambda is `api-prod-work_request_notifier` and is tied to the same `work_request_notifier-event` event in cloudwatch which clobbers the event for the dev lambda

Seems like Chalice should include the stage name when generating Cloudwatch events to avoid conflicts just like when naming the lambda functions

**Comment by jamesls** [comment]
Can you give me more details/steps to repro this issue?  I'm not seeing this behavior when deploy a scheduled event to multiple stages.  Here's what I tried:

```python
from chalice import Chalice

app = Chalice(app_name='testsched')


@app.schedule('rate(5 minutes)')
def foo(event):
    return {'hello': 'world'}
```


```
$ chalice deploy --stage dev
...
$ chalice deploy --stage prod
```

Then confirm they're multiple events configured.

```
 $ aws events list-rules
{
    "Rules": [
        {
            "Name": "testsched-dev-foo-event",
            "Arn": "arn:aws:events:us-west-2:12345:rule/testsched-dev-foo-event",
            "State": "ENABLED",
            "ScheduleExpression": "rate(5 minutes)",
            "EventBusName": "default"
        },
        {
            "Name": "testsched-prod-foo-event",
            "Arn": "arn:aws:events:us-west-2:12345:rule/testsched-prod-foo-event",
            "State": "ENABLED",
            "ScheduleExpression": "rate(5 minutes)",
            "EventBusName": "default"
        }
    ]
}
```

I also am seeing the stage name being added to the event rule names.  Were you running into something else?

**Comment by dhay** [comment]
I have this same issue.  My scheduled event handler is defined like so:
```python
@app.schedule(Rate(1, unit=Rate.HOURS))
def send_call_reminders(event):
     pass
```
When I package up my project `chalice package --pkg-format terraform --stage dev .`, I get the following resource created in my `chalice.tf.json` file:
```json
  "resource": {
    "aws_lambda_function": { ... },
    "aws_lambda_event_source_mapping": { ... },
    "aws_cloudwatch_event_rule": {
      "send_call_reminders-event": {
        "name": "send_call_reminders-event",
        "schedule_expression": "rate(1 hour)",
        "description": ""
      }
    },
```
I would have exepcted the cloudwatch event rule to have a name that includes the current stage.  To get around this, for now, I have to manually configure my lambda name like so:
```python
@app.schedule(Rate(1, unit=Rate.HOURS), name=f"send_call_reminders-{ENV}")
def send_call_reminders(event):
    pass
```
