### ISSUE TITLE
Custom Excpetions in chalice

### ISSUE THREAD

**Issue by Vikash082** [aws/chalice#1693]
Is there a way that we can use our own Custom Exception with Chalice?

I am writing a REST API handler. It was using custom exception (AdminRequestError). Sample code.

```
@app.route('/customers', methods=['GET'])
def list_customers():
    if client.is_admin_req(app.current_request):
        return client.list_customers()
    raise InvalidRequest("Only admin can do that")
```

I see client gets InternalServerError with status code 500. Is there a way, client can get custom exceptions. I see one way specified in doc is catch the exception and use Response() to send the response back. But this can't be done in middleware. It only works with ChaliceUnhandledError and not any other exception.

Is this a limitation ? If yes, is there any workaround this ?

**Comment by jamesls** [comment]
It depends on what you want the behavior of the custom exception to be.  In your code example snippet, what would you want Chalice to send back to the user if you raise your `InvalidRequest` object?

You'd have to either subclass from `ChaliceViewError` or `ChaliceUnhandledError` in order to customize what the error response should be for the user.

**Comment by Vikash082** [comment]
I have a sample logging middleware like this:

```
@app.middleware('http')
def log_req(event, get_response):
    try:
        logger.info("Request processing started.")
        return get_response(event)
    except InvalidRequest as ir:
        logger.error(str(ir))
    logger.info("Request successfully processed")

@app.route('/customers', methods=['GET'])
def list_customers():
    if client.is_admin_req(app.current_request):
        return client.list_customers()
    raise InvalidRequest("Only admin can do that")

class InvalidRequest(ChaliceViewError):
    pass

```

The issue which I am trying to raise here is that the below two lines doesn't gets executed. There is no traceback on server side. 

```
    except InvalidRequest as ir:
        logger.error(str(ir))
```

The output only shows:

`127.0.0.1 - - [02/Apr/2021 10:12:30] "GET /customers HTTP/1.1" 500 -`

I want to log the traceback in middleware at time of error. May be I have used middleware incorrectly. If that's the case, kindly let me know the correct way of achieving the  same.

**Comment by Vikash082** [comment]
I think, instead of **ChaliceViewError** , I need to use **ChaliceUnhandledError** . If that's the correct approach, we can close this issue.
