### ISSUE TITLE
Types in chalice.deploy.models not available in Lambda runtime

### ISSUE THREAD

**Issue by crawforde** [aws/chalice#1694]
I'm using the type `CloudWatchEvent` to provide type hints for some of my functions:
```
from chalice.deploy.models import CloudWatchEvent

def run(event: CloudWatchEven) -> int:
{ ... }
```
Everything works when running locally, but in the Lambda runtime environment, I'm seeing the following error:
`Unable to import module 'app': No module named 'chalice.deploy'`

It seems that the chalice package command does not include this module in the deployment package. Is there a workaround for this? It's nice for development purposes to be able to provide type hints.

**Comment by jamesls** [comment]
The `chalice.deploy.models.*` classes are only used during the deployment process.  The types used by the event handler are in `chalice.app` so you should be able to use `from chalice.app import CloudWatchEvent`.

**Comment by crawforde** [comment]
Oh awesome, thank you.
