### ISSUE TITLE
packager - osx - wheel download broken 

### ISSUE THREAD

**Issue by kapilt** [aws/chalice#1696]
two separate issues

afaics chalice's attempts to download linux many wheels have been broken for a while on Mac OSX, this is due to not passing --python-version to pip download in packager.py. ie in one of our chalice applications attempting to package on osx, results in the following message

```
Creating shared layer deployment package.
Could not install dependencies:
pyrsistent==0.17.3
pygit2==1.5.0
cffi==1.14.5
You will have to build these yourself and vendor them in
the chalice vendor folder.
```

pygit2 and cffi packages maintain osx wheels, so should be downloaded without issue. Digging in chalice attempts to execute pip with effectively the follow command
```
$ pip download  --only-binary=":all:" --no-deps --platform "manylinux2014_x86_64" --implementation="cp" --abi="cp38" . pygit2==1.5.0
Processing /Users/kapilt/projects/myapp
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Could not find a version that satisfies the requirement pygit2==1.5.0
ERROR: No matching distribution found for pygit2==1.5.0
```

The issue is that chalice never set the --python-version for the target lambda runtime, so pip doesn't know which version to download, simply passing in explicitly the python version we want results in success.
```
$ pip download  --python-version 38 --only-binary=":all:" --no-deps --platform "manylinux2014_x86_64" --implementation="cp" --abi="cp38" . pygit2==1.5.0

Processing /Users/kapilt/projects/myapp
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pygit2==1.5.0
  Using cached pygit2-1.5.0-cp38-cp38-manylinux2014_x86_64.whl (3.1 MB)
Saved ./pygit2-1.5.0-cp38-cp38-manylinux2014_x86_64.whl
Successfully downloaded myapp pygit2
```

oddly this does work on linux, but its definitely broken on osx, for reference my local python version on both is 3.9

second issue, currently chalice has issues working with pip 21, due to a constraint in compat.py in determining entry point for
pip, simple fix is another clause to the table for compat.py pip_import_string
```
    elif (21, 0) <= pip_major_minor < (22, 0):
        return 'from pip import main'
```

**Comment by jamesls** [comment]
I'll need to keep digging into what's going on with pyrsistent but I'm not seeing the behavior you're describing for the other two dependencies when I try this on macOS Catalina.  It might be specific to a python version/pip version.

```
$ python --version
Python 3.7.8

$ pip --version
pip 21.0 from /Users/jamessar/.virtualenvs/chalice-37/lib/python3.7/site-packages/pip (python 3.7)

$ cat requirements.txt
pygit2==1.5.0
cffi==1.14.5

$ chalice package out
Creating deployment package.

$ unzip -l out/deployment.zip  | grep so$
   856392  01-01-1980 00:00   _cffi_backend.cpython-37m-x86_64-linux-gnu.so
   942480  01-01-1980 00:00   pygit2/_libgit2.abi3.so
  1043480  01-01-1980 00:00   pygit2/_pygit2.cpython-37m-x86_64-linux-gnu.so
```

**Comment by jamesls** [comment]
Also tried this on python 3.8 and with the latest version of pip and not seeing any errors.  I'll send a PR for a fix for pyrsistent (we just need to allow the package to use the mac specific .whl when it's built without the optional C extension because we know it's safe).

> second issue, currently chalice has issues working with pip 21, due to a constraint in compat.py in determining entry point for
pip, simple fix is another clause to the table for compat.py pip_import_string

Can you give me more details on this?  Both imports work for me, and the only difference seems to be that the `pip.main` version prints a warning to stderr.

```
$ python
Python 3.8.5 (default, Oct  6 2020, 13:54:57)
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> pip.__version__
'21.0.1'
>>> from pip import main
>>> from pip._internal.cli.main import main
```

**Comment by kapilt** [comment]
pyrsistent doesn't package wheels, fwiw

**Comment by kapilt** [comment]
my test env was from big sur, 11.2.. part of the issue i suspect is you have to cross version boundaries from your osx py to lambda target py version.


re second issue, just noticed we're not on latest chalice release :/ user err, as latest compat.py look good, will retry original issue as well.

**Comment by kapilt** [comment]
```
(chalice-check) ➜  chalice new-project check
/Users/kapilt/.pyenv/versions/3.9.4/envs/chalice-check/lib/python3.9/site-packages/chalice/cli/__init__.py:424: UserWarning: You are currently running python3.9, but the closest supported version on AWS Lambda is python3.8
Please use python3.8, otherwise you may run into deployment issues. 
  validate_python_version(Config.create())
Your project has been generated in ./check
(chalice-check) ➜  cd check 
(chalice-check) ➜  ls
app.py           requirements.txt
(chalice-check) ➜  nano requirements.txt && cat requirements.txt
(chalice-check) ➜  check chalice package out
Creating deployment package.

Could not install dependencies:
cffi==1.14.5
pygit2==1.5.0
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://aws.github.io/chalice/topics/packaging.html

No region configured. Either export the AWS_DEFAULT_REGION environment variable or set the region value in our ~/.aws/config file.
(chalice-check) ➜  check chalice --version
chalice 1.22.3, python 3.9.4, darwin 20.3.0
(chalice-check) ➜  check python --version
Python 3.9.4

**Comment by kapilt** [comment]
the fix incidentally is to pass per initial issue comment is to pass `--python-version 38` when building with version corresponding to lambda target.
