### ISSUE TITLE
Cannot find reference 'SNSEvent' in 'app.pyi

### ISSUE THREAD

**Issue by swapnil1994** [aws/chalice#1701]
after an upgrade to 1.22.4 all the SNSEvent used classes gives error

**Comment by jamesls** [comment]
Thanks for reporting, there's a few extra types missing in the app.pyi file even after https://github.com/aws/chalice/pull/1685.  I'll go through another pass and add the missing types.

**Comment by kislyuk** [comment]
Thanks for fixing this @jamesls. Looking forward to this being released.
