### ISSUE TITLE
Type hint for `Request.query_params` does not match documentation

### ISSUE THREAD

**Issue by jmullercuber** [aws/chalice#1708]
The API documentation for the `Request` class indicates the `query_params` may be `MultiDict` or `None`: https://aws.github.io/chalice/api.html#Request.query_params

However, the type hint associated with the class definition does not match the above: https://github.com/aws/chalice/blob/8df8b59aa759292ec065dae54a074731b11fa28e/chalice/app.pyi#L77-L78

The impact of this issue is that the mismatch makes it more difficult for developers to use the API as their IDE will suggest one thing about `query_params` (they don't need to check for `None` values) while in reality they do.

A minimal example of such is below, with comments.
```py
from chalice import Chalice, Response

DEFAULT_NAME = "world"

app = Chalice(app_name="hello-world")


@app.route("/", methods=["GET"])
def hello_world():
    # This part is not obvious given chalice's current type hints
    # `or {}` is a work-around to ensure params is Dict type if chalice sets it as None
    params = app.current_request.query_params or {}

    # works for Dict/MultiDict, but not NoneType
    name = params.get("name", DEFAULT_NAME)
    
    return {"message": f"hello {name}"}
```

This is an issue on the latest release `1.22.3`

**Comment by jmullercuber** [comment]
Related PRs/issues: https://github.com/aws/chalice/pull/1132 , https://github.com/aws/chalice/issues/1055

**Comment by jamesls** [comment]
We should update the type hint associated with the class definition.  I would like to change the value to always be a dict type, but we'd have to wait for a major version bump to make that change.
