### ISSUE TITLE
Warning: Version constraints inside provider configuration blocks are deprecated

### ISSUE THREAD

**Issue by kalpaitch** [aws/chalice#1717]
terraform v0.14 (latest version is now 0.15), chalice version 1.22.4

When packaging for terraform output:
```
Warning: Version constraints inside provider configuration blocks are deprecated
  on ../chalice.tf.json line 234, in provider.template:
 234:       "version": "~> 2"
```

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

**Comment by kalpaitch** [comment]
I'd say this is quite critical now, it's blocking my deployments.

**Comment by soloradish** [comment]
workaround, use jq modify generated json file. idea from: https://samuelmurillo.xyz/2021/07/27/AWS-Chalice-Terraform/
```
# snippet in our makefile
chalice package \
		--pkg-format terraform $(DIST_DEV_DIR)
# remove generated aws provider
jq 'del(.provider.aws)' $(DIST_DEV_DIR)/chalice.tf.json > $(DIST_DEV_DIR)/chalice.tf.json.tmp && \
    mv $(DIST_DEV_DIR)/chalice.tf.json.tmp $(DIST_DEV_DIR)/chalice.tf.json
```

**Comment by jamesls** [comment]
https://github.com/aws/chalice/pull/1867 has been merged which fixes this issue.  We'll get a release out with this fix shortly.
