### ISSUE TITLE
example of using stages when deploying with CDK 

### ISSUE THREAD

**Issue by brno32** [aws/chalice#1719]
Are there any examples of how to deploy by stages (environments) when deploying with the CDK, as spelled out here? https://aws.github.io/chalice/tutorials/cdk.html

I found https://aws.github.io/chalice/topics/stages.html, but can't find any reference to CDK

**Comment by tfotis** [comment]
Maybe this can help https://stackoverflow.com/questions/67330632/how-to-deploy-by-stage-with-chalice-using-cdk

**Comment by brno32** [comment]
Haha I'm the one who made that SO post 😆 

This question stems from my misunderstanding of apigateway stages vs. using different cloud formation stacks to represent different deployment environments. I've done the following in my own scripts to achieve this, without really making use of chalice/apigateway stages

```python
import os

from aws_cdk import (
    core as cdk,
)
from chalice.cdk import Chalice

STAGE = os.getenv("STAGE")
CHALICE_SOURCE_DIR = os.path.join(os.path.dirname(__file__), os.pardir)


class MyStack(cdk.Stack):
    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)
        self.chalice = Chalice(
            self,
            "chalice-app",
            source_dir=CHALICE_SOURCE_DIR,
            stage_config={
                "environment_variables": {
                    "STAGE": STAGE
                }
            },
        )


app = cdk.App()

MyStack(app, f"my-stack-{STAGE}")

app.synth()
```

This let's me pivot on stage in the way I'm used to.
