### ISSUE TITLE
Trigger Pure Lambda from API call - Locally (support request)

### ISSUE THREAD

**Issue by jowan** [aws/chalice#1741]
I have a Chalice API function, and I want to invoke a Lambda within it, using Boto3.

I would like to define that Lambda in my Chalice project as a Pure Lambda, to keep it all in one place. They share code/db connections etc.

If it is deployed, then the Pure Lambda exists in my AWS account, and I can refernce it's ID and test the Chalice API function locally using $ chalice local - great !

However, I would really like to test this *all* locally, including the Pure Lambda

**Question**: _How do I call a Chalice Pure Lambda function from within a Chalice API function 'locally' for testing ?_

Building on the Chalice hello world, I want something like the following, and to be able to run it with $ chalice local:

```python
from boto3 import client as boto3_client
from datetime import datetime
import json

lambda_client = boto3_client('lambda')

app = chalice.Chalice(app_name='foo')

@app.route('/')
def index():
    response = lambda_client.invoke(FunctionName="MyFunction",
                                           InvocationType='Event',
                                           Payload={}
    return {'hello': response}


@app.lambda_function(name='MyFunction')
def pure_lambda_function(event, context):
    return 'world'
```

**Comment by areeves87** [comment]
For a 3rd party solution checkout https://github.com/localstack/chalice-local where you can deploy your chalice project locally to mocked aws services running inside a container.
