### ISSUE TITLE
AWS Chalice adds support for the AWS CDK v2

### ISSUE THREAD

**Issue by vumdao** [aws/chalice#1742]
I ran `pip install chalice[cdk]` and it crashed my cdk construct version. Hope aws chalice support for aws cdk v2 soon.

**Comment by brno32** [comment]
If Chalice is a whole major version behind CDK version 2, that could hurt adoption

**Comment by jamesls** [comment]
We do plan to support CDK v2.  Right now CDK v2 is in [developer preview](https://aws.amazon.com/blogs/developer/announcing-aws-cloud-development-kit-v2-developer-preview/), so I think what we might do is add an additional tag that lets you install cdk v2, e.g. `pip install chalice[cdkv2]`.  Then we'd need to have new app templates for CDK v2.

**Comment by henrysingleton** [comment]
Now that [CDK 2.0 is released](https://github.com/aws/aws-cdk/releases/tag/v2.0.0), is there an approximate timeline for support?

**Comment by sloppycoder** [comment]
i'm waiting for this too...any update?

**Comment by baotran2207** [comment]
Looking for this also

**Comment by baotran2207** [comment]
> We do plan to support CDK v2. Right now CDK v2 is in [developer preview](https://aws.amazon.com/blogs/developer/announcing-aws-cloud-development-kit-v2-developer-preview/), so I think what we might do is add an additional tag that lets you install cdk v2, e.g. `pip install chalice[cdkv2]`. Then we'd need to have new app templates for CDK v2.

Any progress for CDK v2

**Comment by jpascoe** [comment]
Any updates?

**Comment by jamesls** [comment]
Implemented in https://github.com/aws/chalice/pull/1909
