### ISSUE TITLE
Reference APIGateway RestApi from chalice in CDK

### ISSUE THREAD

**Issue by brno32** [aws/chalice#1765]
I'd like to generate an api key for my chaliceapp in my cdk script. Can anyone provide an example of how to get the ApiGateway RestApi resource that chalice provisions? 

e.g., in the same way you can do `self.chalice.get_function()`, I'd like to do

```python
class ChaliceApp(core.Stack):
    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)
        self.chalice = Chalice(
            self,
            "chalice",
            source_dir=CHALICE_SOURCE_DIR,
        )

        api = self.chalice.get_api()
```

I've tried

```python
cfn_api: sam.CfnApi = self.chalice.get_resource("RestAPI")
```

which seems to work, but I can't seem to go from this to the `IRestApi`-based instance of the rest api which I need to do the sort of stuff you see here

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_apigateway/README.html#usage-plan-api-keys

such as:

```python
# where api is the rest api resource generated by chalice
plan = api.add_usage_plan("UsagePlan",
    name="Easy",
    throttle=apigateway.ThrottleSettings(
        rate_limit=10,
        burst_limit=2
    )
)

key = api.add_api_key("ApiKey")
plan.add_api_key(key)

plan.add_api_stage(
    stage=api.deployment_stage,
)
```

**Comment by tsabat** [comment]
We have this issue too.  Please provide advice.

**Comment by aburk3** [comment]
I'd also like to know how to do this.

**Comment by xavierbuspatrol** [comment]
We'd like to do it too.

**Comment by jamesls** [comment]
The approach we've taken for other resources is to use the various `from_*` static methods to create the L2 objects.  However they implement the various `I*` interfaces but they're not the same as if you've instantiated the L2 construct yourself.  So for example, for rest apis you could do something like this to get an `IRestApi`:

```python
            cfn_rest_api = self.chalice.sam_template.get_resource('RestAPI')
            self._rest_api = apigateway.RestApi.from_rest_api_id(
                self, 'RestAPI', cfn_rest_api.ref)
```

But you'd still run into issues depending on what methods you try to call (the object created is technically a `_RestApiBaseProxy`).  For example, this will work to add a usage plan:

```
        plan = self._rest_api.add_usage_plan("UsagePlan",
            name="Easy",
            throttle=apigateway.ThrottleSettings(
                rate_limit=10,
                burst_limit=2
            )
        )

```

But this will fail with a "Can't read property `stageName` of undefined":

```
        key = self._rest_api.add_api_key("ApiKey")
```

You would either have to figure out how to populate a `deployStage` attribute (not sure if that would actually work) or you may have to resort to using the low level `Cfn*` resources to create the Api Key, e.g. `CfnApiKey`.
