### ISSUE TITLE
on_sqs_message missing parameter for MaximumBatchingWindowInSeconds

### ISSUE THREAD

**Issue by skuechlin** [aws/chalice#1778]
This prevents us from using batch sizes > 10, since deploy fails with
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: Maximum batch window in seconds must be greater than 0 if maximum batch size is greater than 10

**Comment by kmbotts** [comment]
This doesn't appear to be too difficult to implement, but it does change a lot of existing constructors which could affect users going forward. I'm just starting Python (coming from Java), so maybe there is an optional field or we can simply overload a new constructor. 

With that said, I was able to make the change in several places to capture the new attribute with updated unit tests to assert on the field. If there are any areas of concern, please let me know. I'll continue working through the functional and integration tests.

**Comment by kmbotts** [comment]
There is also the support for streams (kinesis and dynamodb come to mind).

**Comment by skuechlin** [comment]
thanks for looking into this!
