### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by mvermaes** [aws/chalice#1787]
I redeployed a Chalice project using Python 3.9 after [support was added to Lambda](https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/) recently. ~The deployed API seems to work fine with 3.9~ After checking the Lambda Console, I can see that the functions remain on 3.8.

Chalice issues the below warning:
> .../lib/python3.9/site-packages/chalice/deploy/validate.py:46: UserWarning: You are currently running python3.9, but the closest supported version on AWS Lambda is python3.8
> Please use python3.8, otherwise you may run into deployment issues. 
>   validate_python_version(config)
> Creating deployment package.
> ...

It looks like this is due to the default version being set to 3.8 in `lambda_python_version`:
https://github.com/aws/chalice/blob/dd14f8dc038c05729d108df132c8c40251c8c1fa/chalice/config.py#L160-L166

**Comment by jamesls** [comment]
Thanks for reporting, we'll get that updated.

**Comment by manmartgarc** [comment]
I think #1793 should could close this issue?

**Comment by mvermaes** [comment]
Yes, it's all working good now after your PR was merged. Thanks!
