### ISSUE TITLE
pip 21.2.4 support

### ISSUE THREAD

**Issue by tekumara** [aws/chalice#1791]
With the latest version of pip:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chalice 1.23.0 requires pip<21.2,>=9, but you have pip 21.2.4 which is incompatible.
```

**Comment by jamesls** [comment]
Looks like you're on version 1.23.0 which is an older version of Chalice.  The latest version of Chalice (currently 1.24.1) supports the latest pip version, so if you upgrade this error should go away.
