### ISSUE TITLE
Accessing a database hosted on an EC2 from a Chalice app without exposing it publicly.

### ISSUE THREAD

**Issue by jmizgajski** [aws/chalice#1805]
Hi there,

I was hoping you could give me a hint on how to solve the following problem.

- I have a custom (not available as a service) database that I am running on an EC2 instance I can assign an elastic ip to it so it remains constant. 
- I would like the chalice app to access this database
- I would like the database to not be visible publicly

Thanks in advance.

**Comment by jamesls** [comment]
The best way to do that would be to have your database run in a private subnet in your VPC.  You can then set the [subnet_ids](https://aws.github.io/chalice/topics/configfile.html#subnet-ids) and the [security_group_ids](https://aws.github.io/chalice/topics/configfile.html#security-group-ids) to run your lambda in a VPC.

More high level info here: https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html .

Let me know if you have any more questions.
