### ISSUE TITLE
Lambda function state support

### ISSUE THREAD

**Issue by reikje** [aws/chalice#1819]
AWS recently announced the [expansion of state](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) to all Lambda functions. 

When rolling out a function to AWS Lambda, the deployment mechanism needs to support state changes for the function during its deployment. The AWS CLI, SDK, as well as some IaC tools like Terraform or the Serverless Framework do already have support for this change.

I am curious if any changes in Chalice are needed to support this change by AWS?

**Comment by jrothman** [comment]
Chalice v1.26 + is now handling the latest AWS lambda state changes. I was running v1.24 not so long ago and ran into errors at lambda deployment time which read: "An error occurred (ResourceConflictException) ...".  - apparently an error arising as a result of AWS's lambda state change. Upgrading Chalice addressed the issue.

**Comment by jamesls** [comment]
Yep thanks for following up here.  This was addressed in #1732 which was first released in Chalice v1.23.0 I believe so as long as you're using the latest version of Chalice you shouldn't see any issues.
