### ISSUE TITLE
Mypy broken for CustomAuthorizer

### ISSUE THREAD

**Issue by darlev91** [aws/chalice#1831]
`app.pyi` doesn't have correct list of arguments for `CustomerAuthorizer.__init__`.
It breaks mypy running with next errors:

```
error: Too many arguments for "CustomAuthorizer"
error: Unexpected keyword argument "authorizer_uri" for "CustomAuthorizer"
error: Unexpected keyword argument "header" for "CustomAuthorizer"
```

**Comment by jamesls** [comment]
Ah, thanks for sending the PR, I'll take a look.

FWIW, now that we don't have to support py2.7 we don't need to maintain a separate .pyi file, but it's taking a while to port everything over (https://github.com/aws/chalice/issues/1802).  Once that works done we shouldn't run into these issues anymore.

**Comment by jamesls** [comment]
Closing out issue, the linked PR has been merged/released.
