### ISSUE TITLE
Log is not working after upgrade to  chalice~=1.26.2 from 1.26.0

### ISSUE THREAD

**Issue by m-thirumal** [aws/chalice#1845]
Logging is not working after upgrade to  chalice~=1.26.2 from 1.26.0

```
import logging

app = Chalice(app_name='lambda_returnAppSyncResponse', debug=True, configure_logs=False)

def handler(event, context):
    logging.debug("hey I am printing log")

```

**Comment by jamesls** [comment]
Can you elaborate on what's not working?  Looking over the diff from 1.26.0 to 1.26.2 ([diff](https://github.com/aws/chalice/compare/1.26.0...1.26.2)) there weren't any changes to logging.

You also have `configure_logs=False` which means that Chalice won't configure the stream handler for you, so the example you gave won't print anything unless you set `configure_logs=True`.
