### ISSUE TITLE
Generate API key with Chalice

### ISSUE THREAD

**Issue by brno32** [aws/chalice#1851]
Is there a way to generate an API key for ApiGateway via Chalice? Right now I'm having to do it all in the console

```python
@app.route("/", methods=["POST"], api_key_required=True)
def index():
    return app.current_request.json_body
```

For example, I'm specifying `api_key_required` but it doesn't have any affect on the provisioned resources

**Comment by jamesls** [comment]
Chalice currently does not have any CLI commands for generating an API key / Usage plans for API Gateway.  You'd have to do that through the console/CLI/SDKs.

**Comment by brno32** [comment]
Got it. Thanks for confirming! Could an example be provided as to how to generate the an API key for the rest api chalice generates? I asked this question here

https://github.com/aws/chalice/issues/1765

**Comment by jamesls** [comment]
Yep, I'll add an example of how to generate these with the CDK.

**Comment by xavierbuspatrol** [comment]
@brno32 Did you find an elegant solution?

**Comment by brno32** [comment]
I have not. I'm eagerly awaiting to see what @jamesls produces

**Comment by jamesls** [comment]
Just wanted to follow up here.  I commented on the earlier issue (https://github.com/aws/chalice/issues/1765#issuecomment-1013495429) about how you can potentially get a reference to the L2 `RestApi`, but you'll run into issues invoking specific methods.  Honestly, if you want an API key as part of your rest api, I'd probably just use the escape hatch in the CDK to specify the relevant SAM template snippet needed.  The issue I ran into trying to make this work with the L1 `Cfn*` resources is you need to add a `DependsOn` on the generated API Gateway deployment resource which is auto generated as part of the SAM transform and has a SHA added to the logical resource ID so there doesn't seem to be a good way to calculate what this name would be.

Something like this worked for me:

```python
class ChaliceApp(cdk.Stack):

    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)
        self.chalice = Chalice(
            self, 'ChaliceApp', source_dir=RUNTIME_SOURCE_DIR,
            stage_config={},
        )
        self._cfn_rest_api = self.chalice.sam_template.get_resource('RestAPI')
        self._cfn_rest_api.add_override(
            'Properties.Auth.UsagePlan', {
                'CreateUsagePlan': 'PER_API',
                'Quota': {'Limit': 500, 'Period': 'MONTH'},
                'Throttle': {
                    'BurstLimit': 100,
                    'RateLimit': 50,
                }
            }
        )
```

You can't get the API key value from cfn, so you'd need to use an CDK/CLI to get the actual value:

```
YOUR_STACK_NAME="yourstacknamehere"

api_key_id=$(aws cloudformation describe-stack-resources --stack-name ${YOUR_STACK_NAME} --logical-resource-id RestAPIApiKey --query StackResources[0].PhysicalResourceId --output text)
api_key_value=$(aws apigateway get-api-key --api-key ${api_key_id} --include-value --query value --output text)

$ curl -vvv -H "x-api-key: ${api_key_value}" https://rest-api-id.execute-api.us-west-2.amazonaws.com/api/apikey-needed
```

Hope that helps.
