### ISSUE TITLE
Setting handler to something other than app.app

### ISSUE THREAD

**Issue by des-moines** [aws/chalice#1866]
Is there a way to have Resources.APIHandler.Properties.Handler be something other than app.app in the sam.yaml file that chalice generates? It doesn't appear to be configurable, but I'm wondering if I'm missing something.

**Comment by jamesls** [comment]
No, it's not configurable.  Not for any particular reason, just that that use case hasn't come up.

**Comment by des-moines** [comment]
Thanks for the confirmation. This has come up for me since I need to integrate some lambdas with New Relic which involves changing the handler to be newrelic_lambda_wrapper.handler.

**Comment by jamesls** [comment]
Ah I see: https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/python/template.yaml#L20

Interesting.  The only real way to do that if you're using `chalice package` and SAM/CFN to deploy your app is the template merge feature where you'd have to override each `Handler` value: https://aws.github.io/chalice/topics/cfn.html#template-merge
