### ISSUE TITLE
Runtime.MarshalError: Unable to marshal response: 'utf-8' codec can't decode byte 0x9c in position 1808

### ISSUE THREAD

**Issue by leobragatti** [aws/chalice#1871]
Hi everyone,
I'm trying to merge PDFs in my lambda and return the content, but I'm getting this error:
```
[ERROR] Runtime.MarshalError: Unable to marshal response: 'utf-8' codec can't decode byte 0x9c in position 1808: invalid start byte
```

I get the files from S3, like this:
```
merger = PdfFileMerger()
for file_name in payload:
    resource = client.get_object(Bucket=bucket, Key=file_name)
    file_content = resource['Body'].read()
    buffer = BytesIO(file_content)
    merger.append(buffer)

response_data = BytesIO()
merger.write(response_data)
merger.close()
```

Then I return this in my lambda:
```
return Response(
    body=response_data.getvalue(),
    status_code=HTTPStatus.OK,
    headers={
        'Content-Type': 'application/pdf',
        'filename': 'file.pdf'
    }
)
```

I'm using [PyPDF2](https://pythonhosted.org/PyPDF2/) to merge the PDFs
I made some tests just returning one PDF content and I had the same issue

Any ideas?

**Comment by jamesls** [comment]
API Gateway's particular about calling out which content types are binary types.  You may need to add `application/pdf` to the list of binary types (https://aws.github.io/chalice/api.html?highlight=binary#APIGateway.binary_types)

**Comment by leobragatti** [comment]
I did that. And if understood well, it'll always return a base64 content, right?
Just to be sure, because I read this article (https://aws.amazon.com/blogs/developer/chalice-version-0-9-0-is-now-available/) and it seems it can return the binary data

**Comment by jamesls** [comment]
> I did that. And if understood well, it'll always return a base64 content, right?

Not always.  API Gateway has specific requirements on what you have to do to get binary content.  There's more details in the Chalice docs here:  https://aws.github.io/chalice/topics/views.html#binary-content , but to summarize, if you want to *return* binary content, the client has to send an Accept header, and if you want to *send* binary content to API Gateway you have to set the Content-Type in the request.  So in your example, to get binary content returned you'd have to make a request like:

```
curl -H 'Accept: application/pdf' https://myapi.execute-api.us-west-2.amazonaws.com/api/my-view-name > my.pdf
```
