### ISSUE TITLE
reopening #1872 chalice deploy command failing with ResourceConflictException UpdateFunctionConfiguration exception

### ISSUE THREAD

**Issue by kraj007** [aws/chalice#1873]
Reopening previous issue again 
https://github.com/aws/chalice/issues/1872
@jamesls 

This is blocking for me. I am already using the latest chalice version 1.26.4 , still getting this issue. I saw similar kind of issue for claudiajs.
https://github.com/claudiajs/claudia/issues/226 

Also checked , https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

one of the options suggested is to use "aws:states:opt-out" in description but in case of chalice it internally creating lambda and then tries to update. How can I pass description in chalice deploy command.

We are in kind of similar situation of https://github.com/claudiajs/claudia/issues/226  where we deployed the stack on one environment and next deployment onwards its continuously failing. 
also to confirm , I had discussion with AWS premium support ,  they suggested to check with you guys on this.

**Comment by kraj007** [comment]
Hello Team,

Can anybody please help me on this issue ?

**Comment by kraj007** [comment]
we got one workaround from AWS support to update the lambda description and add "aws:states:opt-out" as mentioned here 
https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

This workaround worked as of now as in first attempt our lambda got created however next time we ran our jenkins pipelines it was failing. 
We do not have option to provide the lambda description in chalice deploy command. So not sure if this workaround will work every time.

Also @jamesls  can you please check once here 
https://github.com/aws/chalice/blob/61f43459a078524b4d80cbb816bb4d5d67884a47/chalice/awsclient.py#L913

if this getting evaluated ? I think we need to check like " inside ' for condition
if if result['LastUpdateStatus'] != '"Successful"'

**Comment by kraj007** [comment]
@jamesls  I have added logging to check the chalice version and found that jenkins instance while chalice deploy command using older chalice version 1.22.1. This is strange issue in our case as all our requirements files have explicitly using chalice .26.4 version.

We have now explicitly doing pip install before chalice deploy again with latest version and I can confirm this issue is solved as of now. Meanwhile our devops team checking why older version is present in jenkins instances.

**Comment by jamesls** [comment]
Awesome, glad you were able to get everything working for you!
