### ISSUE TITLE
Bug: Chalice raises RuntimeError when pip >=22.0.0

### ISSUE THREAD

**Issue by luqasz** [aws/chalice#1887]
Versions of pip >=22.0.0 won't work with chalice.
```python
File "/home/runner/work/SOME_DIR/lambda/.venv/lib/python3.9/site-packages/chalice/compat.py", line 34, in pip_import_string
    raise RuntimeError("Unknown import string for pip version: %s"
RuntimeError: Unknown import string for pip version: (22, 0)
```
https://github.com/aws/chalice/blob/master/chalice/compat.py#L31 Missing elif for newer pip.

**Comment by jamesls** [comment]
Thanks for reporting.  We bumped the pip version to support v22.1 of pip (https://github.com/aws/chalice/pull/1883), but it looks like the CI pulled in v21.3.1 so all the tests passed (https://github.com/aws/chalice/runs/5006199735?check_suite_focus=true#step:4:154).

We'll get this fixed.
