### ISSUE TITLE
[question] purpose of policy-dev.json?

### ISSUE THREAD

**Issue by MustafayMustafa** [aws/chalice#1925]
In the sample ToDo app https://github.com/aws/chalice/blob/master/docs/source/samples/todo-app/code/.chalice/policy-dev.json

Auto generate policy is false and a developer policy json file is provided, what is the reasoning for this? Why are we not able to use auto generating policies in this example? Furthermore, how might this policy differ for deploying to prod stage?

**Comment by jamesls** [comment]
The main thing is that the policy generation doesn't handle scoping the statements to the appropriate Resources, so providing your own policy file allows it to be more specific.
