### ISSUE TITLE
Allow usage of version 4.x of AWS Terraform Provider

### ISSUE THREAD

**Issue by loesak** [aws/chalice#1951]
The `required_providers` configuration locks the aws provider at versions with the constraint `>= 2, < 4`. The latest version of the AWS Terraform provider is 4.22.0. For projects that generate additional Terraform configuration around the Terraform generated by Chalice, this is limiting.

For example, RDS Aurora Serverless V2 support was added in version 4.12.0

Request that the constraint change to `>= 2, < 5`

**Comment by jamesls** [comment]
Fixed in #1953
