### ISSUE TITLE
@app.schedule No longer supports Rate/Cron object expression

### ISSUE THREAD

**Issue by dhay** [aws/chalice#1967]
A recent commit (afd23d7d729f8383033fe3851bc1de5effd1f22f), added types to the various decorators.  In particular, the `@app.schedule` decorator requires `expression` to be a `str`, which means that it no longer accepts the object type `Rate` or `Cron`.

I used to be able to do this (and the [Chalice documentation shows this example as well](https://aws.github.io/chalice/topics/events.html#scheduled-events))
```python
@app.schedule(Rate(1, unit=Rate.HOURS), name=f"send_call_reminders-{ENV}")
```
Now, I have to add a `to_string()` call as follows:
```python
@app.schedule(Rate(1, unit=Rate.HOURS).to_string(), name=f"send_call_reminders-{ENV}")
```

I'm thinking the type for the `schedule` decorator should probably be `Union[str, ScheduleExpression]`.

**Comment by jamesls** [comment]
Good catch, that should be a union type, we'll get that updated.
