### ISSUE TITLE
update does not change version

### ISSUE THREAD

**Issue by mjk-313-muto-riho** [aws/chalice#1971]
I updated to chalice1.27.2, but when I run "chalice --version" it says "chalice 1.27.1".
When I was checking the update status, I found that the 25th line below in app.py, which was rewritten in version 1.27.1, was chalice 1.27.1.Is it related?
https://github.com/aws/chalice/blob/d0faf162a09dfc7f5ffd2e9902cd685345f2e5fa/chalice/app.py#L25

**Comment by jamesls** [comment]
Thanks for reporting, looks like this is a regression introduced in #1932.  I'll get this updated.
