### ISSUE TITLE
How do Lambda functions scale when using websockets with Chalice?

### ISSUE THREAD

**Issue by gusgordon** [aws/chalice#1973]
Can't find any information in the docs about this. Any insight would be appreciated!

**Comment by jamesls** [comment]
There's nothing specific that Chalice does to scale websockets, it's all in the Lambda service itself.  More Lambdas will be created as you receive more concurrent websocket messages, so it's possible that there will be multiple instances of your `on_ws_message` websocket handler if needed.  Hope that helps!
