### ISSUE TITLE
Chalice CDK template depends on version of attrs incompatible with aws-cdk-lib

### ISSUE THREAD

**Issue by tdwright** [aws/chalice#2020]
When following the [Chalice CDK guide](https://aws.github.io/chalice/tutorials/cdk.html), a requirement is added for `aws-cdk-lib>2.0,<3.0`. This indirectly depends on `attrs` v22.2.0. 

Chalice [depends](https://github.com/aws/chalice/blob/master/setup.py#L29) on `attrs<21.5.0,>=19.3.0`. Since v22.2.0 isn't within this (oddly narrow) range, no version can exist that satisfies both requirements.

This came to light when I was converting the generated project to use `pip-tools`. To do this:
1. Renamed the `requirements.txt` files to `requirements.in`
2. Added `chalice` to the `runtime/requirements.in` file (since I want to be able to run `chalice local` after `pip-sync`)
3. Ran `pip-compile` on the `infrastructure` directory, then in `runtime`, then in the project root.

When I completed this final step, I was presented with the following exception:

```
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches attrs==21.4.0,==22.2.0 (from -r runtime/requirements.txt (line 11))
Tried: 15.0.0, 15.1.0, 15.1.0, 15.2.0, 15.2.0, 16.0.0, 16.0.0, 16.1.0, 16.1.0, 16.2.0, 16.2.0, 16.3.0, 16.3.0, 17.1.0, 17.1.0, 17.2.0, 17.2.0, 17.3.0, 17.3.0, 17.4.0, 17.4.0, 18.1.0, 18.1.0, 18.2.0, 18.2.0, 19.1.0, 19.1.0, 19.2.0, 19.2.0, 19.3.0, 19.3.0, 20.1.0, 20.1.0, 20.2.0, 20.2.0, 20.3.0, 20.3.0, 21.1.0, 21.1.0, 21.2.0, 21.2.0, 21.3.0, 21.3.0, 21.4.0, 21.4.0, 22.1.0, 22.1.0, 22.2.0, 22.2.0
Skipped pre-versions: 15.0.0a1
There are incompatible versions in the resolved dependencies:
  attrs==22.2.0 (from -r infrastructure/requirements.txt (line 7))
  attrs==21.4.0 (from -r runtime/requirements.txt (line 11))
```

Using the backtracking resolver (as suggested) does not help. All it does is produce a slightly different exception that boils down to the same thing.

Since these requirements all come from the Chalice project, it feels like they ought to agree.

**Comment by jamesls** [comment]
Yep, now that we require python 3.7, I think we can avoid this altogether and just update Chalice to use dataclasses from the stdlib instead of attrs, it's essentially an identical API.  Should be a straightforward change.
