### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by n-primeau** [aws/chalice#2037]
[Lambdas now support 3.10](https://aws.amazon.com/fr/about-aws/whats-new/2023/04/aws-lambda-python-3-10/). The request is to support 3.10 in chalice. 

There's an existing PR that accomplishes this: https://github.com/aws/chalice/pull/2036

**Comment by devinmatte** [comment]
This is currently blocking our upgrade to Python 3.10, hopefully this can be resolved soon!

**Comment by bobcolner** [comment]
also ran into this issue. looks like lambda does now support 3.10: 

https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/#:~:text=AWS%20Lambda%20now%20supports%20Python,code%20more%20readable%20and%20maintainable.

**Comment by priamai** [comment]
Same here, I was surprised to see the console error.
```
 UserWarning: You are currently running python3.10, but the closest supported version on AWS Lambda is python3.9
Please use python3.9, otherwise you may run into deployment issues. 
  validate_python_version(Config.create())
Your project has been generated in ./lcservice
```
