### ISSUE TITLE
Support Graviton2 Deployments

### ISSUE THREAD

**Issue by ojhilt** [aws/chalice#2042]
It would be great to get configuration support for Graviton2 processors by selecting arm64 Architecture in the runtime environment.  Combined with Python 3.10 support this would really help us bring all our lambda deployments up to date.  Cheers!

**Comment by jamesls** [comment]
Thanks for the feature request.  Let's track the progress for this over in https://github.com/aws/chalice/issues/1808.  I'll put together an initial estimate for the work involved and go from there.

**Comment by ojhilt** [comment]
sounds good, cheers!
