### ISSUE TITLE
Aws lambda unzipped size error - aws chalice

### ISSUE THREAD

**Issue by dewirizki** [aws/chalice#2081]
I think it my deployments packages less than 250 mb, but i still got an error likes this
 An error occurred (InvalidParameterValueException) when calling the 
 CreateFunction operation: Unzipped size must be smaller than 53642504 bytes

**Comment by tareshss** [comment]
Can you share your requirements.txt and any layers you are using? 

"This quota applies to all the files you upload, including layers and custom runtimes."

[Source](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html)

50 MB (zipped, for direct upload)

250 MB (unzipped)

**Comment by dewirizki** [comment]
size of my zipped file just 4x.xx MB, and this one a requirements.txt that i used on this project and I add a layer in configuration file
![image](https://github.com/aws/chalice/assets/81002911/ff1c1d0a-14ab-4f77-b9b5-1cfff3b96b10)

**Comment by tareshss** [comment]
my guess is that the layer along with fastparquet pushes you over the 250 MB unzipped size.

the list of requirements for fastparquet is pretty hefty

numpy
pandas
cython >= 0.29.23 (if building from pyx files)
cramjam
fsspec

I would recommended researching how to use pandas, etc for aws lambda with another layer aws chalice project or googling how to import pandas in aws lambdas.
