### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by devinmatte** [aws/chalice#2086]
AWS announced today support for Python 3.12 in Lambda

https://aws.amazon.com/about-aws/whats-new/2023/12/aws-lambda-support-python-3-12/

It would be great to see Chalice support this new version as well 😄

Thanks!

**Comment by jamesls** [comment]
Nice, I'll look into adding this today.

**Comment by eatsleepdeploy** [comment]
Just trying out chalice and looks like neither 3.11 or 3.12 are supported via the terraform packager. Is it just missing from the MR for now, or is this going to be added as part of [this ticket](https://github.com/aws/chalice/issues/2066) - or is terraform support being deprecated?

**Comment by markbenepass** [comment]
I don't think this is actually completed due to the Terraform dependency?
