### ISSUE TITLE
After-Request Callbacks

### ISSUE THREAD

**Issue by mlioo** [aws/chalice#315]
It'd be great to have the ability to call something similar to flasks app.after_request function to trigger the execution of a function at the end of a request for running jobs or tasks after requests.

**Comment by jamesls** [comment]
Marking as feature request.  I'd like to add this.  There was an initial PR for this: https://github.com/awslabs/chalice/pull/181

I think it was just missing tests and needed to get the travis build passing.

**Comment by jamesls** [comment]
Closing out issue, this is now possible with Chalice middleware.
