### ISSUE TITLE
using jinja2 to load template files

### ISSUE THREAD

**Issue by Mil0R** [aws/chalice#469]
works when `chalics local` but  raise exception like ` jinja2.exceptions.TemplateNotFound: t.html` after `chalice deploy`, it looks like the default folder *templates* was not packaged when deploy.

**Comment by achautha** [comment]
@Mil0R , did you package your template file into `chalicelib` directory ? 

Check this out [multifile support](http://chalice.readthedocs.io/en/latest/topics/multifile.html)

**Comment by Mil0R** [comment]
@achautha thanks it works now.
