### ISSUE TITLE
chalice deploy: charmap codec can't encode character 0x81

### ISSUE THREAD

**Issue by schnitzelK1ng** [aws/chalice#509]
Getting this on chalice deploy /w python 3.6.2 (64bit), windows and chalice 1.0.1
Issue does not exist in 0.9.0, havent tried 1.0.0 yet.

**Comment by jamesls** [comment]
Can you give us sample code and set of steps that demonstrate the issue?  Does this happen with the auto-generated `app.py` created from `chalice new-project`?

**Comment by schnitzelK1ng** [comment]
will look into it.

**Comment by schnitzelK1ng** [comment]
Cannot repro with the auto-generated app.py.. gonne be a tough hunt to find what it is..

**Comment by jamesls** [comment]
Thanks for looking into this.  I'm going to go ahead and close this out for now.  If you're able to hunt down what this is, let us know and we'll take another look.

**Comment by RowlandZero** [comment]
I'm experiencing the same error. perhaps this can be reopened.
On chalice deploy:
'charmap' codec can't decode byte 0x81 in position 191: character maps to <undefined>

I'm on windows 64, python 3.6.1
dead simple hello world testing the scheduler

from chalice import Chalice

app = Chalice(app_name='demoapp')


@app.route('/')
def index():
    return {'hello': 'world'}

@app.schedule('rate(5 minutes)')
def handler(event: CloudWatchEvent):
    pass

**Comment by jamesls** [comment]
Reopening.

**Comment by jamesls** [comment]
I believe this is now fixed in https://github.com/aws/chalice/pull/560
