### ISSUE TITLE
Select lambda_memory_size based on route(/resource)

### ISSUE THREAD

**Issue by siggi84** [aws/chalice#510]
It would be great to be able to select container type based on the route. These containers could then have different lambda_memory_size and different timeouts. This would be helpful where there is large difference in computational intensity between API calls.

Is there a simple work-around for this that I am missing?

**Comment by jamesls** [comment]
This isn't possible right now because the API handler is a single lambda function.

At this point, it's going to be difficult to change this because there's a lot of baked in assumptions about all the API calls being handled by a single lambda function.  I'm inclined to call this out of scope.

**Comment by kyleknap** [comment]
Closing this issue for now. If enough interest gets generated related to this, we will reopen the feature request.
