### ISSUE TITLE
What is the best way to store credentials like AWS RDS password

### ISSUE THREAD

**Issue by zhenchaochen** [aws/chalice#512]
Seems like the right place to save password is the environment variable in .chalice/config.json, however, config.json will be pushed to code base. 

I can think of another way is saving the password in S3, and then lambda can access the file with correct IAM role permission, but it is ugly and not efficient. 

What you you think?

Thanks.

**Comment by JordonPhillips** [comment]
There may be several ways for you do handle this, though Chalice doesn't currently have a bundled in way of deploying such things. One option would be to use SSM. Another would be to use KMS as described [here](https://github.com/aws/chalice/issues/481#issuecomment-323178711).

Closing out this issue in favor of the existing feature request linked above.
