### ISSUE TITLE
Setting debug level not working

### ISSUE THREAD

**Issue by pyvotal-cguers** [aws/chalice#523]
Setting the debug level this way

`app.log.setLevel(logging.DEBUG)`

(see http://chalice.readthedocs.io/en/latest/topics/logging.html#examples) does not work. What does work is

`app.debug = True`

(see http://chalice.readthedocs.io/en/latest/quickstart.html#tutorial-error-messages)

**Comment by stealthycoin** [comment]
What do you mean "not working". Can you give specific repro steps and explain what you mean not working? I tried this and it works as expected:

app.py
```python
import logging
from chalice import Chalice

app = Chalice(app_name='test-nested-chalicelib')
app.log.setLevel(logging.DEBUG)
print(app.log.getEffectiveLevel())


@app.route('/')
def index():
    app.log.debug('foobar')
    return app.log.getEffectiveLevel()
```

Logs from chalice local when making a request:
```
$ chalice local
10
Serving on localhost:8000
test-nested-chalicelib - DEBUG - foobar
127.0.0.1 - - [08/Sep/2017 12:35:49] "GET / HTTP/1.1" 200 -
```

Logs from curling:
```
$ curl localhost:8000
10
```
Note that 10 is `logging.DEBUG`.

**Comment by pyvotal-cguers** [comment]
Using `app.log.setLevel(logging.DEBUG)` did not show any debug messages, while using `app.debug = True` did. I have not tried this in 1.0.2, but this was the behavior I saw with 1.0.1.

**Comment by stealthycoin** [comment]
You would need to give me repro steps then, there have been no changes that touch `app.log` between 1.0.1 and 1.0.2 and the above sample I gave works as expected.

**Comment by stealthycoin** [comment]
Also tried this is `1.0.1` and it works as expected. Feel free to reopen this if you can provide repro steps.

**Comment by pyvotal-cguers** [comment]
You are correct. It was a syntax mistake on my part. I was doing `import chalicelib.Module1`where "Module1" was a folder containing a file `Module1.py`, which contained a function `myfunc()`. I was trying to use `Module1.myfunc()` when I should have been using `chalicelib.Module1.myfunc()`.

After correcting the syntax I have since been able to even reference _text files_ stored in `chalicelib` without any issues.

(Sorry for reopening this, but for completeness sake I wanted to share with others in case they had a similar experience)
