### ISSUE TITLE
Sub folders in chalicelib/ are not included in the deployment package

### ISSUE THREAD

**Issue by pyvotal-cguers** [aws/chalice#524]
It does not seem that "anything in that [chalicelib/] directory  is recursively included in the deployment package" is not working (see http://chalice.readthedocs.io/en/latest/topics/multifile.html#multifile-support). It seems that only the files inside chalicelib/ are included but no sub-folders.

**Comment by stealthycoin** [comment]
Can you give me specific repro steps? This worked for me:
```
$ tree .
.
├── app.py
└── chalicelib
    ├── __init__.py
    └── nested
        └── secondlevel
            └── data.txt
$ chalice deploy
...
...
$ unzip -lq .chalice/deployments/d41d8cd98f00b204e9800998ecf8427e-python3.6.zip
 Length     Date   Time    Name
 --------    ----   ----    ----
    33485  09-06-17 14:03   chalice/app.py
      431  08-01-17 12:20   chalice/__init__.py
      180  09-07-17 15:56   app.py
      266  09-07-17 15:58   chalicelib/__init__.py
      432  09-07-17 15:58   chalicelib/__pycache__/__init__.cpython-36.pyc
        7  09-07-17 15:50   chalicelib/nested/secondlevel/data.txt
```

Looks like its all there. I also tried loading a data file and returning its contents which worked fine.

**Comment by pyvotal-cguers** [comment]
This is working now in 1.0.2
