### ISSUE TITLE
Chalice doesn't delete CloudWatch rule created for Scheduled lambda-function

### ISSUE THREAD

**Issue by pshirbhate** [aws/chalice#535]
Hello,

While developing the scheduled lambda-function, I figured out that chalice doesn't delete the CloudWatch rules it has created during the deploy.

```
from chalice import Chalice
from chalice import Rate

app = Chalice(app_name='test')

@app.route('/')
def index():
    return {'hello': 'world'}

@app.schedule(Rate(1, unit=Rate.MINUTES))
def every_minute(event):
    print event.to_dict()

```
While deletion, Chalice deletes the REST API endpoint, lambda-function: test-dev, scheduled lambda-function: test-dev-every_minute and role: test-dev EXCEPT cloud watch rule: test-dev-every_minute

Kindly look into this.

**Comment by stealthycoin** [comment]
Thanks for reporting this. We will get it fixed.

**Comment by kyleknap** [comment]
Looks like the PR got merged. Should be fixed now. Closing issue.
