### ISSUE TITLE
Why am I getting "Endpoint request timed out" at the end instead of returned JSON?

### ISSUE THREAD

**Issue by pyvotal-cguers** [aws/chalice#537]

**Comment by pyvotal-cguers** [comment]
I have a function that completes successfully and even saves to the CloudWatch log the resulting JSON structure, but it seems that returning that structure is not working. It **timesout**.

**What am I doing wrong?**

My Chalice code:
```
from __future__ import print_function
import boto3, os, json, time
from chalice import Chalice
from chalice import BadRequestError         # 400
from chalice import NotFoundError           # 404
from chalice import ChaliceViewError        # 500

app = Chalice(app_name='myFunc')
@app.route('/ec2/new', methods=['POST'])
def newEC2():
    ...
    item = {'instance':newEC2instance.instance, 'users':finalUsers}
    app.log.debug("newEC2: Done: %s" % json.dumps(item))
    return item
```
My app's `config.json` file has `"lambda_timeout": 300` and `"lambda_memory_size": 384` (and I confirmed in Lambda that these values are set).

CloudWatch shows:
```
18:25:50 myFunc - DEBUG - newEC2: Done: {"instance": {...
18:25:50 END RequestId: 3acxxxxx-9a5c-11e7-8cef-370e466251c2
18:25:50 REPORT RequestId: 3xxxxxed-9a5c-11e7-8cef-370e466251c2	Duration: 93110.83 ms	Billed Duration: 93200 ms Memory Size: 384 MB	Max Memory Used: 57 MB
```
... so the resulting `item` json is available and it is being logged in Cloudwatch.

The result when called from the command line, via `httpie`:
```
$ cat testData.txt | http --timeout=300 POST https://xxxxxxxxxx.execute-api.us-east-2.amazonaws.com/dev/ec2/new
HTTP/1.1 504 Gateway Timeout
Connection: keep-alive
Content-Length: 41
Content-Type: application/json
Date: Fri, 15 Sep 2017 21:24:46 GMT
Via: 1.1 a0d2fxxxxxxxxx255448d1a4c773a5fe.cloudfront.net (CloudFront)
X-Amz-Cf-Id: azJt3alQRxxxxxxxxxbzSyTLMEv04J9jf6ZVE-HaSmQe-Pr11r1YDw==
X-Cache: Error from cloudfront
x-amzn-RequestId: 3ac9c5ab-9a5c-11e7-847e-xxxxxxf53000

{
    "message": "Endpoint request timed out"
}
```

BTW, the **total execution time is 93 seconds**... well below the configured 300s limit.

**Comment by stealthycoin** [comment]
Hmmm so this seems like the same issue as the other one I just commented on but has a little more information. The fact that it logs to cloudwatch logs and then has a timeout issue seems to support my suspicion in the other thread about the size being too large for one of the service payload limits. I think the fact that the timeout happens before the configured timeout and the HTTP timeout that you supplied makes sense since it is probably timing out reading data from lambda -> api gateway which is not subject to any of the settings about timeouts. I'm going to close this issue in favor of #536.

**Comment by pyvotal-cguers** [comment]
No. This is totally different. HTTPIE gets a timeout even when specifying a bigger timeout period. I am getting a timeout even though my resulting Lambda function does complete the process successfully.

However, I believe I know the reason.

It turns out that with Chalice you can set the timeout for the Lambda function (up to 300 seconds) and in HTTPIE you can specify its timeout. However, API Gateway has a hardcoded timeout of 30 seconds, so a timeout longer than 30 seconds in Chalice has no real effecting API Gw. The Lambda function will continue to work (up to the timeout set in Chalice <= 300), but API Gateway will return a timeout at 30 seconds.

Unless the API Gateway timeout can be set via a parameter (like I said, it seems to be hardcoded today), working with Chalice calls longer than 30 seconds will always timeout. It kind of defeats the purpose of being able to set a longer timeout in Chalice.

**Comment by hannes-ucsc** [comment]
> It kind of defeats the purpose of being able to set a longer timeout in Chalice.

Except that Chalice also lets you trigger lambdas with SQS or CloudWatch event rules and in those scenarios timouts longer than 30s make sense.

Anyways, the max. timeout API gateway timeout is actually 29s. It seems to be configurable between 50ms and 29s. I find it odd that 1) Chalice doesn't let me configure the API Gateway timeout and 2) that Chalice lets me specify a lambda timeout that is greater than the API Gateway timeout for a lambda that is fronted by API Gateway.
