### ISSUE TITLE
Add before_request functionality

### ISSUE THREAD

**Issue by mickzer** [aws/chalice#553]
Add a similar feature to before_request as is provided in Flask: http://flask.pocoo.org/docs/0.12/api/#flask.Flask.before_request

This allows a function to be run before the actual route function is called. It is very useful for doing request parameter validation, user identification and permission verification etc.

**Comment by joguSD** [comment]
Marking as a feature request.
A PR for this functionality is in progress here: #181

**Comment by VitorFalcao** [comment]
@joguSD Has this feature been implemented yet? I not, I would like to work on it. Do you have any pointers, please?

**Comment by jamesls** [comment]
Closing out old issue, this is now possible with Chalice middleware.
