### ISSUE TITLE
Config. exception: "str expected, not int" - Missing details

### ISSUE THREAD

**Issue by jonasao** [aws/chalice#568]
Attempting to run my chalice project locally, i received the error-message:
`str expected not int`

After fiddling around a bit, I recalled entering an int-value in the `./chalice/config.json` file in one of my environment variables. Making this value a string instead fixed my problem. 

In my opinon this is a bug:
1. JSON accepts int-values
2. The exception message should be improved. E.g. stating that the application failed to parse the config. file or similar in addition to the existing message.

**Comment by jamesls** [comment]
Thanks for reporting, we should get that error message improved.  I agree it's not very clear.

**Comment by jamesls** [comment]
Closing out old issue, improved error messaging via https://github.com/aws/chalice/pull/1561
