### ISSUE TITLE
Deploying environment variables from dev to stage

### ISSUE THREAD

**Issue by Xyleroth** [aws/chalice#589]
Hey, I've been able to successfully add environment credentials to my dev, but now when I construct a new stage in prod, the prod lambda is unable to use the same environment variables. I followed the steps laid out in Issue #481 . 
I made a config:
```
{
  "version": "2.0",
  "app_name": "chalice_clearinghouse",
  "stages": {
      "dev": {
        "api_gateway_stage": "api",
        "environment_variables": {
          "CHALICE_USER": ="<SOME VALUE>",
          "CHALICE_PASSWORD": "<SOME VALUE>",
          "CHALICE_HOST": "<SOME VALUE>",
          "CHALICE_PORT": "<SOME VALUE>"
        },
      "prod":{
        "api_gateway_stage": "api",
        "environment_variables":{
          "CHALICE_USER": "<SOME VALUE>",
          "CHALICE_PASSWORD": "<SOME VALUE>",
          "CHALICE_HOST": "<SOME VALUE>",
          "CHALICE_PORT": "<SOME VALUE>"

        }

      }
    }
  }
}
```
However, when I use chalice deploy --stage prod and attempt to access one of the environment variables, it hasn't been set. I get the following error:
```
{
    "Code": "ChaliceViewError",
    "Message": "ChaliceViewError: Key / Keys do not exist in os.environ on the lambda. Please 
      examine lambda config"
}
```
The same process works fine in dev though.

I tried removing prod and reinitializing the lambda to no avail. Any suggestions? Is there a command I can run to ensure the config has been set correctly?

**Comment by Xyleroth** [comment]
I forgot to say that the chalice view error is my own exception I throw when a call to os.environ['SOME KEY'] does not succeed. I'll keep updating this with additional details as I go. Thanks ahead of time!

**Comment by Xyleroth** [comment]
My chalice version is 1.04, awscli is 1.11.170

**Comment by stealthycoin** [comment]
I can't repro this by copying your config file and deploying two stages. It sets up the environment variables just fine for both.

Below is what I Tried.

config.json
```
{
  "version": "2.0",
  "app_name": "test-env-vars",
  "stages": {
    "dev": {
      "api_gateway_stage": "api",
      "environment_variables": {
        "CHALICE_USER": "<SOME VALUE>",
        "CHALICE_PASSWORD": "<SOME VALUE>",
        "CHALICE_HOST": "<SOME VALUE>",
        "CHALICE_PORT": "<SOME VALUE>"
      }
    },
    "prod": {
      "api_gateway_stage": "api",
      "environment_variables": {
        "CHALICE_USER": "<SOME VALUE>",
        "CHALICE_PASSWORD": "<SOME VALUE>",
        "CHALICE_HOST": "<SOME VALUE>",
        "CHALICE_PORT": "<SOME VALUE>"
      }
    }
  }
}
```

app.py route
```python
@app.route('/')
def index():
    user = os.environ['CHALICE_USER']
    pwd = os.environ['CHALICE_PASSWORD']
    host = os.environ['CHALICE_HOST']
    port = os.environ['CHALICE_PORT']
    return {
        'user': user,
        'password': pwd,
        'host': host,
        'port': port
    }
```

commands run
```
$ chalice deploy
...
$ http $(chalice url)
...
{
    "host": "<SOME VALUE>",
    "password": "<SOME VALUE>",
    "port": "<SOME VALUE>",
    "user": "<SOME VALUE>"
}
```
```
$ chalice deploy --stage prod
...
$ http $(chalice url --stage prod)
...
{
    "host": "<SOME VALUE>",
    "password": "<SOME VALUE>",
    "port": "<SOME VALUE>",
    "user": "<SOME VALUE>"
}
```

The only modifications I made were that the config you provided was not valid as it had a stray `=` in it. 

If you check the lambda function manually are the variables there?

**Comment by Xyleroth** [comment]
It might be an issue with the config I had. I'll go through what you put up and see if I can get it working. I appreciate you taking the time to help with this.

**Comment by Xyleroth** [comment]
If you're able to get it working it has to be something on my end.

**Comment by Xyleroth** [comment]
Just got it working. It was an issue with the json. My apologies for causing an issue with this. I thought I had validated the json beforehand. Thanks alot!

**Comment by stealthycoin** [comment]
No problem. Glad you got it working!
