### ISSUE TITLE
HTTP Response for images

### ISSUE THREAD

**Issue by BigChief45** [aws/chalice#592]
I am migrating a web service that would serve an image blob in the HTTP response into AWS Lambda with Chalice.

However, after reading the [documentation](http://chalice.readthedocs.io/en/latest/api.html#response) I get the idea that Chalice does not support this:

```python
return Response(body=image_blob,
                    status_code=200,
                    headers={'Content-Type': 'image/jpeg'})
```

> body
The HTTP response body to send back. **This value must be a string**.

Is there any way around this?

**Comment by dstufft** [comment]
I believe the documentation there is using string in a more general sense, rather than literally ``str`` on Python 3. A quick look at the code suggests that ``bytes`` objects are also supported.

**Comment by BigChief45** [comment]
@dstufft Yes, after reading more through the documentation and [this issue](https://github.com/aws/chalice/issues/348), I found how to serve binary data in the response. Yet I am experiencing this error when I test it using `'Accept': 'image/jpg'` header:

```json
{
    "Code": "UnsupportedMediaType",
    "Message": "Unsupported media type: application/json"
}
```

Here is an simplified excerpt of my code:

```python
@app.route('/my_route', content_types=['image/jpg'])
def serve_img():
    with open('/tmp/{0}-{1}.jpg'.format(book_id, page_number), 'rb') as img:
        img_data = img.read()

    if not img_data:
        raise BadRequestError('Error')

    return Response(body=img_data,
                    status_code=200,
                    headers={'Content-Type': 'image/jpg'})
```

I am at a completely loss on why this isn't working and keeps mentioning Media Type of `application/json` in the error response. Help is greatly appreciated.

**Comment by BigChief45** [comment]
Found the problem. I thought that specifying the content types in the decorator was for allowing the `Accept` header through API Gateway.

To make it work I simply removed that and use my requests with the `Accept` header.

**Comment by shreyashag** [comment]
Thank you @BigChief45 for your input!
