### ISSUE TITLE
query params default to different values when running locally V.S. running in lambda

### ISSUE THREAD

**Issue by nplutt** [aws/chalice#593]
Hey,

When running an application locally the `current_request.query_params` defaults to `{}` if there are no query params. This can be very misleading when running locally because when the lambda is deployed `current_request.query_params` defaults to `None`.

In order to fix this I would propose changing the local development server so that the  `current_request.query_params` also defaults to `None`.

Thanks,
Nick

**Comment by dstufft** [comment]
Marking this as an enhancement, thanks!
