### ISSUE TITLE
Specify bind address for local dev server

### ISSUE THREAD

**Issue by BigChief45** [aws/chalice#596]
A custom port can be specified when running the local development server. I couldn't find anything in the docs about being able to specify a custom bind address (i.e `--host 0.0.0.0`). Is this possible? Would be happy to provide a PR if it's not.

**Comment by joguSD** [comment]
This is not currently possible. Could you explain your use case for needing to be able to choose a custom bind address?

**Comment by BigChief45** [comment]
@joguSD Some cloud development environments (such as [Cloud 9](https://c9.io/), acquired by Amazon by the way) only allow specific interfaces (such as `0.0.0.0`) for running development servers.

**Comment by joguSD** [comment]
Cool, sounds reasonable to me. Marking as a feature request.
