### ISSUE TITLE
Please check it... I need this 

### ISSUE THREAD

**Issue by doublekw** [aws/chalice#600]
Hi
I'm using chalice to build cloud for collecting data.
My cloud MUST support multipart/form-data. 
But, It's difficult because chalice's binary media types doesn't invlove "multipart/form-data"
I think if you add multpart/form-data, It'll be greater than now.... Please consider it : )

**Comment by BigChief45** [comment]
You can add your own binary media types to the list of binary media types that Chalice will handle by adding them to the `binary_types` list. You can read more in the documentation [here](http://chalice.readthedocs.io/en/latest/api.html#APIGateway.binary_types)

**Comment by joguSD** [comment]
As @BigChief45 mentioned it is possible to receive the raw body and parse the multipart form manually currently. If this were a feature in chalice what would you expect the interface to look like?

**Comment by jamesls** [comment]
Closing out issue due to inactivity.  Let me know if you have any more questions.
