### ISSUE TITLE
CTRL+C takes too long to terminate "chalice local" process

### ISSUE THREAD

**Issue by byrro** [aws/chalice#601]
On Windows 8.1 command line:

When I run:
`chalice local --port=8080`

If I immediately press `CTRL+C`, it interrupts the script right after.

When I run:
`chalice local --port=8080`
Then open http://localhost:8080/ on my browser and after that press `CTRL+C` on the command prompt, the script only gets interrupted after 1-2 minutes. The only way to interrupt it quickly is killing the Python process.

Expected behavior:
Have the script run by `chalice local` terminated immediately after pressing `CTRL+C`, regardless of having made an HTTP request or not before that.

I'm experiencing the issue with the windows 8.1 command prompt. Same issue happens when using Console2 and ConEmu.

**Comment by joguSD** [comment]
I've reproduced this on windows 10. Closing the browser (tried both firefox and IE) seems to allow `chalice local` to close. Not sure if this is an issue with `HTTPBaseServer` on windows or an issue with our `ChaliceRequestHandler`.

**Comment by wollerman** [comment]
Potentially related is #628 where the browser seems to interfere with other requests.

**Comment by noelmccrory** [comment]
This happens to me also when running chalice local from a Powershell terminal inside VS Code (Win 10). As a workaround, I typically add a new terminal, run chalice local, test, then kill the terminal when I'm finished. CTRL-C seems to have no effect at all.

**Comment by byrro** [comment]
@noelmccrory I'm using [ConEmu](https://conemu.github.io/). Instead of killing the entire terminal, you can configure a shortcut in ConEmu to kill just the Python process within the terminal. Instead of using CTRL+C, I configured CTRL+Q to kill Python and quit the Chalice local process without having to close the Terminal window every time.

Open ConEmu settings, go to "Keys & Macro" and search for this shortcut: "Terminate (kill) active process in the current console". Then set the key combination of your preference.

**Comment by variable** [comment]
Just had the same problem

**Comment by leason** [comment]
On Windows 10 you can `ctrl+c`, then just send a request to chalice.  The interrupt isn't picked up until another request is sent.  That causes the local process to quit, and then you can restart it.  I don't know how to implement it, but having an automatic reload when files change similar to how React does this when you run `npm start` would be awesome.

**Comment by byrro** [comment]
Flask also has a similar functionality, automatically restarting the local server when it identifies changes in any python file in the project directory. One drawback is that sometimes it reloads when I'm still making changes and a syntax error prevents the server from starting, requiring a manual start later. But anyway, I like the feature.

**Comment by atagar** [comment]
Thanks Renato! Great catch, sent them a fix...

https://github.com/aws/chalice/pull/675

**Comment by duaneking** [comment]
This is still happening, only now it doesn't seem to respond to Control-C at all.
