### ISSUE TITLE
Pure lambda creation, IAM role not created initially

### ISSUE THREAD

**Issue by johntmyers** [aws/chalice#602]
When creating a pure lambda function using `@app.lambda_function` when you first deploy you'll see the `Creating lambda function: ... ` message but the new IAM execution role for this function is *not* created when the actual function is initially created.

When I deploy immediately again, the IAM execution role is finally created and associated with the Lambda function.

I feel like the IAM role should be created and associated on the initial creation of the new lambda function.

Version: 1.0.4

**Comment by joguSD** [comment]
This is a known issue and the deployer is currently under going a re-write to help address issues like these. I've created a place-holder issue for tracking issues related to deployment. 

Related #604

**Comment by jamesls** [comment]
Consolidating issues over in #604.
