### ISSUE TITLE
Create multiple AWS APIs

### ISSUE THREAD

**Issue by gldavis3000** [aws/chalice#603]
Is it possible to create multiple APIs?  For instance, my first API has about 20 endpoints that are specifically created to be used by an ios/android app or javascript browser page.  Now I need another API with a different app_name.  I have many more APIs planned for creation as time goes on and I want them to be separate APIs so I don't end up with a single API containing 100 or more endpoints.
To try to accomplish this I created another chalice folder, but when I did "chalice deploy" it deleted the first API from AWS API Gateway and added the new one.  I need to have the ability to create multiple APIs in Gateway.  Is this possible with chalice and how do I accomplish it?
Thanks

**Comment by joguSD** [comment]
That's strange. How did you create the second chalice folder? If you copied over the folder from your first application it's possible you also copied the `.chalice` folder which keeps track of the deployed resources which might have caused the the old API to be deleted.

**Comment by gldavis3000** [comment]
I believe that's what happened.  I just created a new chalice folder to try and debug an issue that popped up in the original folder.  When I did the new folder from scratch (with no deployed.json) and deployed it I got a new api in AWS instead of it replacing the original one and the deployed.json file was automatically created.  Thanks for the help
