### ISSUE TITLE
Automate vendor packages installation 

### ISSUE THREAD

**Issue by rajasimon** [aws/chalice#616]
For the sake of cut copy paste I tried to automate the vendor package. I have private library which is need to be included in vendor folder.  I understand that just placing the .whl file in vendor folder is enough to deploy the private python package. Tried below...

    pip wheel -w vendor git+ssh://git@bitbucket.org/team/repo@v0.0.1#egg=egg-name --build-option="--plat-name=linux_x86_64"

This download all the whl files into vendor folder which is great. But after the `chalice deploy` my application still throws error. After inspecting the deployments folder I found that my repo package shown like .whl file not the folder repo. 

```
 app.py
 repo.0.0.1-py3-none-linux_x86_64.whl
 __init__.py
requests
requests-2.18.4.dist-info
requests-2.18.4-py2.py3-none-linux_x86_64.whl
```

My question is why chalice not install my private repo. ?

**Comment by joguSD** [comment]
Does you vendor directory include the wheel directly? As in `vendor/repo.0.0.1-py3-none-linux_x86_64.whl`? It should include the contents of the wheel as shown in the [example here](repo.0.0.1-py3-none-linux_x86_64.whl).

**Comment by rajasimon** [comment]
Thanks turns out I can pip install into vendor/ directory using target command. 

    pip install git+ssh://git@bitbucket.org/team/repo@v0.0.1#egg=egg-name -t vendor/ --no-deps

Right now I'm looking into custom pip post install script that can do above with ease. Thanks for your help.
