### ISSUE TITLE
Assigning policies for each generated role

### ISSUE THREAD

**Issue by BigChief45** [aws/chalice#620]
When I deploy with Chalice, a role is automatically created for API Gateway and every Lambda function in my project. Currently, I am manually assigning the required policies for these roles after deploying with Chalice, through the AWS Console.

However I would like to assign specific policies for specific roles in some config file so that Chalice can assign them automatically after deploying. 

Is this currently possible?

**Comment by joguSD** [comment]
It is currently only possible to specify a single manual policy (that will be attached to all of the roles).
http://chalice.readthedocs.io/en/latest/topics/configfile.html#examples

This will be addressed in the new [deployer rewrite](https://github.com/aws/chalice/issues/604).

**Comment by BigChief45** [comment]
@joguSD Thanks. Is there any place where I can see a list of all the new changes the deploy rewrite will contain?
