### ISSUE TITLE
Add UnprocessableEntityError for HTTP status 422

### ISSUE THREAD

**Issue by dmulter** [aws/chalice#621]
I use HTTP status code 422 for responses like POST when the entity already exists. This is a very common practice. I created a new class for this in my own code, but it would be better directly in Chalice.

**Comment by joguSD** [comment]
Opened up a PR for this in #625

**Comment by dmulter** [comment]
👍

**Comment by dmulter** [comment]
Just got around to trying to replace my code with this, but it doesn't work for some reason. Reproduce using:

```bash
(venv) test $ pip install chalice
(venv) test $ python
Python 3.6.3 (default, Nov 23 2017, 20:47:31)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from chalice import UnprocessableEntityError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'UnprocessableEntityError'
```

**Comment by dmulter** [comment]
This was not resolved for a few reasons:

- The error was not added to chalice/__init__.py
- There were no tests added so the new code was never checked to see that it didn't work
- The new error was not added to the README.rst along with the list of other errors

**Comment by joguSD** [comment]
Sorry about that, I tested the import directly from chalice.app previously. Also good catch on the documentation. We did have tests based on the errors previously but we ended up removing them. I'll see if I can add some static analysis to ensure all subclasses of errors are exposed via `__init__.py` as well.

**Comment by dmulter** [comment]
Would love to see this make it into a release sometime. I'm hoping this project isn't foundering due to lack of a maintainer...
