### ISSUE TITLE
Custom app path or config path

### ISSUE THREAD

**Issue by variable** [aws/chalice#622]
Hi Guys,

Having a bit of issue trying to fit Chalice into existing project template. I have asked on Stackoverflow but no answers so far, so maybe asking here will get some luck.

https://stackoverflow.com/questions/47253464/aws-chalice-using-custom-config-path-or-custom-app-path

Cheers.

James

**Comment by nplutt** [comment]
Hey, so your issue is that the `.chalice` folder needs to be at the same level as the app.py file.

**Comment by variable** [comment]
Is there a way to configure it so `.chalice` can sit somewhere else?

**Comment by nplutt** [comment]
No not currently.

**Comment by joguSD** [comment]
Yeah this isn't possible currently. I'm not sure if this is something we would want to add either. Is there any issue with pushing your `.chalice` directory down into your `src` directory?

**Comment by variable** [comment]
Thanks guys, I started to create a chalice project within the src folder and go from there.
