### ISSUE TITLE
Sending two responses for one request

### ISSUE THREAD

**Issue by fromneo** [aws/chalice#624]
I am writing a slack slash command and want to use the delayed response functionality.
When a slack command is sent, it requires a response within 3 seconds.

Since I want to make a call to a database, I need to first provide a response of 200, and then POST to a response URL with my data.

Chalice has a Response object that handles responses well. But I have to `return` from the function.
I'm not sure how I can use this to return a 200 first, and then make another POST request with my data later on. Any thoughts?

**Comment by rajasimon** [comment]
I suggest you to invoke another lambda function for the POST request.

**Comment by joguSD** [comment]
Unfortunately this isn't possible currently. There is a feature request for an [after_request](https://github.com/aws/chalice/issues/315) decorator. You should give that a +1. Let me know if you have any other questions.

**Comment by fromneo** [comment]
@rajasimon so do you mean by using AWS SNS to post messages between 2 lambda functions? That seems doable but harder to maintain as well. Since I would need to maintain two instances of chalice.

**Comment by joguSD** [comment]
@fromneo It's possible to have chalice manage pure lambda functions within the same project. Docs for this are [here](http://chalice.readthedocs.io/en/latest/topics/purelambda.html). Closing this out in favor of the existing feature request.

**Comment by fromneo** [comment]
Thank you @joguSD i'll give it a shot!
