### ISSUE TITLE
Allow pipeline creation with Python 3.6 (custom image)

### ISSUE THREAD

**Issue by ericfrederich** [aws/chalice#627]
I'm on Linux Mint 18.2 which is based on Ubuntu 16.04.  This comes with Python3.5 so I installed Python3.6 via the [deadsnakes ppa](https://askubuntu.com/a/865569).

When I run this...
```bash
python3.6 -m venv /tmp/my_chalice_env
source /tmp/my_chalice_env/bin/activate
pip install chalice
cd /tmp
chalice new-project my_chalice_project
cd my_chalice_project
chalice generate-pipeline pipeline.json
CodeBuild does not yet support python version 'python3.6'.
```
... I get the following error:

```
CodeBuild does not yet support python version 'python3.6'.
```

Maybe I'm doing something wrong?

**Comment by joguSD** [comment]
Chalice currently detects what version of python you're using (in this case v3.6) and will not generate a pipeline if you're using a version of python that is not currently supported by codebuild (they only have python containers up to v3.5). That being said, we are considering removing this restraint and allowing a custom container image to be specified when creating the codebuild resources. Let me know if you have any more questions.

**Comment by jamesls** [comment]
This is now available in v1.1.0 of chalice.  You can run `chalice generate-pipeline --codebuild-image python:3.6.1` to use the 3.6.1 python docker image (or any custom codebuild image you want).

**Comment by ericfrederich** [comment]
@joguSD it is confusing because the docs for Chalice mention *"make sure you are using python2.7 or python3.6"*

But it clearly doesn't work with 3.6 out of the box.  What is the expected workflow here?

**Comment by wutachih** [comment]
chalice generate-pipeline --codebuild-image python:3.6.4
Usage: chalice generate-pipeline [OPTIONS] FILENAME
