### ISSUE TITLE
Environment variables not being found while deploying

### ISSUE THREAD

**Issue by vyscond** [aws/chalice#635]
Hi. So i just notice that we will get an error if we try to use the `chalice deploy` command while accessing environment variables to fill up the `CognitoUserPoolAuthorizer` object. I think this happens because chalice import the `app.py` file while doing the actual deploying.

I've tried to wrap the authorizer with a function call but got the same error saying that the env var was not found. Than i wrapped it on a lambda but it complained that the object returned didn't had an `name` property.

Finally the only solution i got was to access the environment using the `.get` to handle a fallback value. Sadly i cannot also put something like `.get('AWS_ARN')` because the authorizer class will complain about the empty value. The only way i had to overpass it was to hard code my dev ARN as a fallback value.

What i'm missing is some sort of lazy evaluation on this scenario. I think.

**Comment by vyscond** [comment]
Related to https://github.com/aws/chalice/issues/584

**Comment by joguSD** [comment]
Sorry this took a while to get to, but you're correct that this is the same issue as #584. Closing out in favor of the existing issue.
