### ISSUE TITLE
Missing token validation property from custom authorizer

### ISSUE THREAD

**Issue by msam6444** [aws/chalice#642]
I have setup my custom authorizer using Auth0 and i have to adjust `Token Validation` parameter to  `^Bearer [-0-9a-zA-z\.]*$`. Currently the system doesn't utilizing the `identityValidationExpression` which results in empty `Token Validation` after each chalice deploy.

E.g: I have created following authorizer from aws console:

<img width="465" alt="screen shot 2017-12-20 at 4 24 17 pm" src="https://user-images.githubusercontent.com/1429432/34204930-5c375f32-e5a2-11e7-8bc0-ea6f8edc7684.png">

After running `chalice deploy` my custom `Token Authorization` get vanished:
<img width="470" alt="screen shot 2017-12-20 at 4 12 43 pm" src="https://user-images.githubusercontent.com/1429432/34204987-8155833e-e5a2-11e7-9c0e-99a5deda45a7.png">

My code for Custom Verification was:

```py
auth0 = CustomAuthorizer(
    name='jwt-rsa-custom-authorizer',
    header='Authorization',
    ttl_seconds=3600,
    authorizer_uri=('uri' )
)
```

**Comment by mabdullah353** [comment]
A quick fix in above merge request will allow users to set Token Validation as following:

```
auth0 = CustomAuthorizer(
    name='jwt-rsa-custom-authorizer',
    header='Authorization',
    ttl_seconds=3600,
    token_validation='^Bearer [-0-9a-zA-z\.]*$',
    authorizer_uri=('uri' )
)
```

@jamesls can you review it ?

**Comment by joguSD** [comment]
Thanks for the pull request. Marking this as a feature request until we get a chance to look at it.
