### ISSUE TITLE
async function support (or at least better error message)

### ISSUE THREAD

**Issue by getaaron** [aws/chalice#646]
I have a working lambda function and am trying to migrate to _chalice_. This lambda function includes a Python async function:

```python
async def fetch(session, url):
```

When I run `chalice deploy`, the deploy fails cryptically:

```bash
$ chalice deploy
Loading function
Regen deployment package.
'xml_request'
$
```

(`xml_request` is a variable in my lambda function, not sure if that's a coincidence or if chalice has a similar variable name.)

If I comment out the `async def` function, the deploy goes smoothly.

- IMO, chalice should support async functions since lambda supports them (despite the comments in https://github.com/aws/chalice/issues/637)
- if chalice doesn't support them, this should be (1) a documented limitation, and (2) there should be a friendly explanation that the function as written is incompatible with chalice and to either rewrite it or find another deployment solution

CC @rajasimon

**Comment by joguSD** [comment]
This is actually a bug in the policy generation analyzer. It's definitely not our intention to prohibit the use of async in general.
