### ISSUE TITLE
How to hookup coverage.py to projects done using chalice ? 

### ISSUE THREAD

**Issue by voltagreen** [aws/chalice#649]
Is it possible to provide a hook to measure the code coverage using coverage.py for projects done using chalice or is there any other way to achieve the same objective? 

I want to make sure that I have enough code coverage for the projects that I'm doing using chalice. 

I'm sorry but I looked everywhere but unable to find the related materials on this subject.

**Comment by jamesls** [comment]
Are you wanting to measure code coverage from running your test suite?  If so, there's nothing special you need to do to get that working for chalice.  `py.test` and all the various test runners should just work, e.g `py.test --cov ...` (https://pytest-cov.readthedocs.io/en/latest/)

Let me know if you have any more questions.

**Comment by voltagreen** [comment]
thanks. but I'm bit confused about the procedure. I have written my test cases using postman and currently using "chalice local" to test those test cases via Newman. I need to test the coverage of those test cases.

**Comment by voltagreen** [comment]
without testing the API output as is I have short circuited the functions called from the app.py and wrote test cases to test those functions. This is not ideal but it serve the purpose. 

I'm closing this ticket
