### ISSUE TITLE
Can't access parameters passed with a hash

### ISSUE THREAD

**Issue by leason** [aws/chalice#652]
Examining current_request.to_dict() for a request that looks like:
`https://my-api/api/authenticate#token_id=abcd&access_token=efgh` doesn't appear to make it possible to get to token_id or access_token.  Here is what the to_dict() result looks like:
```json
{
   "query_params":null,
   "headers":{
      "accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "accept-encoding":"gzip, deflate, br",
      "accept-language":"en-US,en;q=0.9",
      "cache-control":"max-age=0",
      "cloudfront-forwarded-proto":"https",
      "cloudfront-is-desktop-viewer":"true",
      "cloudfront-is-mobile-viewer":"false",
      "cloudfront-is-smarttv-viewer":"false",
      "cloudfront-is-tablet-viewer":"false",
      "cloudfront-viewer-country":"US",
      "host":"<redacted>.execute-api.us-east-1.amazonaws.com",
      "referer":"https://<redacted>.auth.us-east-1.amazoncognito.com/login?response_type=token&client_id=<redacted>&redirect_uri=https://<my-api>/api/authenticate",
      "upgrade-insecure-requests":"1",
      "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
      "via":"2.0 <redacted>.cloudfront.net (CloudFront)",
      "x-amz-cf-id":"<redacted>",
      "x-amzn-trace-id":"Root=<redacted>",
      "x-forwarded-for":"<redacted>",
      "x-forwarded-port":"443",
      "x-forwarded-proto":"https"
   },
   "uri_params":null,
   "method":"GET",
   "context":{
      "requestTime":"01/Jan/2018:17:04:49 +0000",
      "path":"/api/authenticate",
      "accountId":"<redacted>",
      "protocol":"HTTP/1.1",
      "resourceId":"<redacted>",
      "stage":"api",
      "requestTimeEpoch":1514826289919,
      "requestId":"<redacted>",
      "identity":{
         "cognitoIdentityPoolId":null,
         "accountId":null,
         "cognitoIdentityId":null,
         "caller":null,
         "sourceIp":"162.238.214.37",
         "accessKey":null,
         "cognitoAuthenticationType":null,
         "cognitoAuthenticationProvider":null,
         "userArn":null,
         "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
         "user":null
      },
      "resourcePath":"/authenticate",
      "httpMethod":"GET",
      "apiId":"<redacted>"
   },
   "stage_vars":null
}
```
This is the URL structure AWS Cognito uses if you utilize their UI for the login/register form.  What I'm trying to do is create an API endpoint that takes in those tokens, validates them, creates a local user if necessary, and then redirects to my front end with an application specific JWT that will be used by the frontend for future API calls.  

Maybe I'm just going about this whole thing all wrong.  I want to create my own JWT and include the application specific UserId to speed up future requests.

**Comment by jamesls** [comment]
I'm able to repro this as well.  It looks like those values just aren't forwarded by API gateway using the lambda proxy integration.  It is possible to just use query string parameters instead in your scenario?  Those will definitely work, e.g `https://my-api/api/authenticate?token_id=abcd&access_token=efgh`

**Comment by leason** [comment]
Hey James, thanks for the response.  The problem is that I don't think I have any control over how those parameters are passed by the Cognito Login Page UI.  When you set that up in AWS they don't let you choose how to pass the parameters.  You can choose to use "token" or "code" for the login page which dictates which parameters are passed, but not how to pass them.  That seems to be a hard coded thing on the AWS side.  See: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html

I'm trying to use the AWS hosted login page to keep things as simple as possible for my web application.  This removes a lot of user management complexity from my source code.

The work around I'm going to use for now will mean implementing this flow:

1. React app route to serve as the callback handler from Cognito's login page
2. React app passes AWS JWT to a chalice managed handler which will validate it, create an application user if necessary, and return an application specific JWT back to the frontend to be used in future API calls.
3. If the JWT expires, redirect the user back to the AWS login page

I think that will work.  I plan to try and test that out this week.  Glad I'm not going crazy at least.

**Comment by kevinpaulconnor** [comment]
@leason  for your #2, I think that this is what the cognito javascript library is made for, https://github.com/aws/amazon-cognito-identity-js. So instead of having a chalice endpoint to perform your #2, manage identity registration/login/refresh client-side, including username, and then reference your application-specific cognito pool in your chalice code on the endpoints that require authentication.

**Comment by leason** [comment]
Hey Kevin, thanks for the link.  We're actually using a react-redux wrapper around that library now.  Handling #2 server side is necessary for us because we need to create an application specific user record that we'll use to relate to lots of other things.  I didn't want to just pass the cognito user id around in the DB layer because joins against string based columns are generally slower than integers, and I didn't want to make my model layer dependent on something so AWS specific if I could avoid it.  This way our app is a bit more portable.

We're actually up and running now and it's working well.  Just had to figure out all the moving parts.  Thanks, again!

**Comment by kevinpaulconnor** [comment]
That makes some sense, thanks for walking me through it. If you don't mind indulging me though, what advantage does cognito provide at all in your case, since you're rolling your own JWT/application specific user id anyway? I'm assuming that you aren't benefiting from cognito security for your application-specific JWT and have to continue to perform validation on API calls with that token. You said that using the AWS login form is desirable and your trouble came partially from the desire to use it. But I don't think of writing a front end login form as a heavy task.

Not academic for me since I have an in-progress app that is passing around cognito strings for id, just thinking about tradeoffs. For my thinking, I can let cognito do the auth and forget about it. But if I wasn't satisfied with what cognito was providing to the degree that I wanted my own JWT for routine calls, I don't know why I'd be using cognito at all.

**Comment by leason** [comment]
Kevin, first up I'll be the first to say it's very possible I'm doing something stupid here, so please take what I say here with a grain of salt and if you have suggestions on how I can do it better I'm all ears.

Originally I started building my own login form but then I realized I actually needed registration, verification, login, MFA, forgot password, and forgot username workflows.  Allowing Cognito to manage all that takes some burden off us white we're building out the MVP.  To me that stuff is not a huge value add right now - I want my team focused on building the app and user management stuff is not key to that.  Not having to deal with storing people's passwords is pretty nice as well - the less of those kinds of problems I have to solve the better.  

Doing it this way also keeps things open for using more than just Cognito.  If I want to integrate with Azure AD, Auth0, or something else it would be pretty easy to add them now.  I don't see us doing that soon, but it's doable.

If we were replacing the authentication system for an existing app and I needed a lot of control over those experiences then clearly I wouldn't use their hosted pages.

**Comment by kevinpaulconnor** [comment]
That makes a ton of sense. And indeed, I have many of those workflows that you mention fleshed out on my app but am behind on the actual (allegedly) valuable parts, so your prioritization strategy seems wise to me.

Thanks for taking the time to walk me through your thinking!

**Comment by leason** [comment]
No problem at all, Kevin!

@jamesls - so to be clear I've worked around the problem.  I think a potential fix is just making the chalice Cognito authenticator a bit more flexible.   I've also noticed it can't deal with the standard "Bearer " or "bearer=" preamble that many frameworks like to use in the Authentication header.  Chalice has to get that token on it's own with no preamble.

**Comment by stealthycoin** [comment]
Closing this since it looks like the pressing issue was resolved. I would remark as a feature request for more flexible parameters for `CognitoUserPoolAuthorizer` but I think this thread is too noisy. If you have any particular requests can you open a new issue and we can mark it as a feature request from there and discuss those specific features.
