### ISSUE TITLE
Chalice not working and throwing Required parameter name not set

### ISSUE THREAD

**Issue by mabdullah353** [aws/chalice#669]
I was previously using Ubuntu machine to deploy the code and it's working perfectly fine. Now i switched on Mac osHigh, and getting the following error:

```bash
$chalice deploy --stage development
Required parameter name not set
```

To me it's look like boto3 issue. I have doubled checked my ~/.aws credentials files also i tried to export AWS credentials into environment variables. But no luck.

My installation steps were

```
$ python --version
Python 2.7.14

$ virtualenv venv
source venv/bin/activate

$ pip install -r requirements-dev.txt

$chalice local --port=8080
Required parameter name not set
```

Any help on it ?

**Comment by BigChief45** [comment]
If I am not mistaken, you need **Python 3.6** to use Chalice.

**Comment by mabdullah353** [comment]
It tooks me some while to identify the issue, 
I was using dynamodb on my app.py  and getting the name of the table from environment variable the shortcode looks like following:

```py
table = dynamodb.Table(os.environ.get('TABLE_NAME'))
```

The error i was receiving does not make any sense to me so the way i have debugged this issue is by removing the global exception over here https://github.com/aws/chalice/blob/master/chalice/cli/__init__.py#L370 then it throws me the stack trace of my app. 

What is the best way to get stack trace back from such situations ?

**Comment by kyleknap** [comment]
I actually sometimes remove that except statement as well when I am debugging an error that I don't understand. Chalice does have the `--debug` flag that you can try but the Chalice library does not have too many logging statements in the codebase so it can be hit or miss. What does the output look like when you run `chalice --debug deploy`? Would you be able to debug from that?

**Comment by mabdullah353** [comment]
The output is same using --debug parameter 
```bash
$ chalice --debug deploy --stage development 
Required parameter name not set
```

It would be great if we add a traceback call when --debug is true while capturing the global exception as well.

Thanks

**Comment by stealthycoin** [comment]
The current master branch of Chalice now spits out a full stacktrace by default when it runs into an error. I'll close this issue since it looks like you managed to figure out the problem anyway, should be easier with the next release of Chalice though.
