### ISSUE TITLE
Testing against dynamic path fails

### ISSUE THREAD

**Issue by soimafreak** [aws/chalice#671]
Hi, Not sure if this is entirely the right place for this... 

I have a simple app with a dynamic path. When using `chalice local` it works as expected. 
When using the unit tests though it claims the path can not be found, I'm assuming because it's not explicit. Obviously, if I make an explicit path it then works and the tests pass but this is not ideal.
I'm using the same test framework defined here https://github.com/aws/chalice/issues/289 but I'm not sure if I've done something wrong or not.

The specific error I am getting is this:
`chalice.app.ChaliceError: No view function for: /world`

I've created this simple gist that shows the working/failure case: https://gist.github.com/soimafreak/5f3aec2b68964a7344b953f2b53cb57b

Any help appreciated.
Matt

**Comment by atagar** [comment]
Hi Matt, no problem. Missing tidbit is that your event's uri needs to exactly match the @app.route. If you change your test from...

```
def test_index(sample_app, create_event):
    event = create_event(
        uri='/world',
        method='GET'
    )   
    response = sample_app(event, context=None)
    assert_response_body_is(
        response,
        {"hello": "world"}
    )
```

... to...

```
def test_index(sample_app, create_event):
    event = create_event(
        uri='/{hello}',
        method='GET',
        path={'hello': 'world'},
    )   
    response = sample_app(event, context=None)
    assert_response_body_is(
        response,
        {"hello": "world"}
    )
```
... it passes. Here's a similar test you can base it on...

https://github.com/aws/chalice/blob/master/tests/unit/test_app.py#L241

**Comment by kyleknap** [comment]
Yep. I agree with what @atagar suggested. Let us know how that works out.

**Comment by soimafreak** [comment]
Thanks @atagar and @kyleknap, That is now working as expected for what I'm doing :)
