### ISSUE TITLE
URL query parameter not decoding variable

### ISSUE THREAD

**Issue by mabdullah353** [aws/chalice#688]
API Defination.
```py
@app.route('/user/{name}')
def user_name(name):
    return name
```

now the following Get request will return. visiting the `/user/first|last` will assign the variable `name` to `first%7Clast` instead of `first-last`

Is this intentional or you have to plan to return the decoded value from url ?

**Comment by joguSD** [comment]
This is intentional and we can't decode by default without it being a backwards incompatible change. There's more discussion here #511. Closing in favor of the existing issue.
