### ISSUE TITLE
When deploying, if config is incorrect, make Chalice error instead of hang

### ISSUE THREAD

**Issue by owenbrown** [aws/chalice#709]
If a user does "chalice deploy" and the config is set up incorrectly, the deployment hangs forever. 

It would be better for, especially for new users, if there was instead an error message.

An easy example is, if the config file references a policy-prod.json file and the policy-prod.json is missing, it just hangs forever.
Instead, it should error out.

**Comment by owenbrown** [comment]
Hi, this is still important to me.
For example, right now, I'm trying to deploy. Maybe there's an issue with my config. Maybe it's unhappy because the ARN role already exists. Or doesn't exist.
Either way, instead of giving me an error messages, the system simply says;:
"Creating lambda function: ExampleApp"
And sits there forever. This is really problematic, especially for new users.

The specific issue might be, if you specify and iam_role_arn, and that role doesn't exist, deploying hangs.

This is the config that causes this conditions:

```
{
  "version": "2.0",
  "app_name": "WebhookTemplate",
  "manage_iam_role": true,
  "iam_policy_file": "policy-dev.json",
  "environment_variables": {
    "GOOGLE_PROJECT_ID": "webhooktemplate-f873e",
    "GOOGLE_API_CONFIG_FILE_NAME": "WebhookTemplate-4f13adca72b4.json"
  },
  "stages": {
    "dev": {
      "api_gateway_stage": "api",
      "iam_role_arn": "arn:aws:iam::865862963382:role/WebhookTemplate-dev",
      "environment_variables": {
        "AGENT_NAME": "WebhookTemplate",
        "CHALICE_STAGE": "dev",
        "FACEBOOK_PAGE_ACCESS_TOKEN": "",
        "FACEBOOK_VERIFY_TOKEN": ""
      }
    },
    "prod": {}
  }
}

```

**Comment by owenbrown** [comment]
Hi, this is still important to me.
For example, right now, I'm trying to deploy. Maybe there's an issue with my config. Maybe it's unhappy because the ARN role already exists. Or doesn't exist.
Either way, instead of giving me an error messages, the system simply says;:
"Creating lambda function: ExampleApp"
And sits there forever. This is really problematic, especially for new users.

The specific issue might be, if you specify and iam_role_arn, and that role doesn't exist, deploying hangs.

This is the config that causes this conditions:

```
{
  "version": "2.0",
  "app_name": "WebhookTemplate",
  "manage_iam_role": true,
  "iam_policy_file": "policy-dev.json",
  "environment_variables": {
    "GOOGLE_PROJECT_ID": "xxxxxxx",
    "GOOGLE_API_CONFIG_FILE_NAME": "xxxxx"
  },
  "stages": {
    "dev": {
      "api_gateway_stage": "api",
      "iam_role_arn": "arn:aws:iam::xxxxxxxxx:role/WebhookTemplate-dev",
      "environment_variables": {
        "AGENT_NAME": "WebhookTemplate",
        "CHALICE_STAGE": "dev",
        "FACEBOOK_PAGE_ACCESS_TOKEN": "",
        "FACEBOOK_VERIFY_TOKEN": ""
      }
    },
    "prod": {}
  }
}

```

**Comment by owenbrown** [comment]
Investigating further, (on of) the issues is, if there's an error with the code, chalice won't deploy.
Simply running "app.py" or doing some sort of error check would catch the issue. 
I know now that the work-around is to always run "app.py" prior to pushing, to make sure everything works. But, this should still produce and error when running "chalice deploy".

**Comment by ivica-k** [comment]
I may be experiencing the same thing
```
$ chalice deploy

The following actions will be added to the execution policy:

cognito-idp:ListUsers

Would you like to continue?  [Y/n]: 
Updating IAM policy for role: helloworld-dev
Creating deployment package.
Creating lambda function: helloworld-dev
```

Looking into network traffic, I can see there is an upload happening, but it will eventually fail with
```
ERROR - While sending your chalice handler code to Lambda to create function 
"helloworld-dev", received the following error:

 Connection aborted. Timed out sending your app to Lambda.
```

My deployment package (`7554820bf6b05ff14124c65c7217a168-python3.6.zip`) is 6.2MBs so it should be uploaded fairly quickly.

**Comment by stealthycoin** [comment]
I have not managed to replicate this @owenbrown is there any more information you can give me about your setup? Chalice version maybe? I used the most recent version and tried both python versions. Everything deployed without hanging. Are you sure its not an actual networking issue?

**Comment by ivica-k** [comment]
A quick fix was to increase the timeout in [botocore/endpoint.py](https://github.com/boto/botocore/blob/develop/botocore/endpoint.py#L40) in my virtual environment. 

The proper solution is discussed here https://github.com/aws/chalice/issues/344
