### ISSUE TITLE
Add full stack trace for chalice deploy errors

### ISSUE THREAD

**Issue by owenbrown** [aws/chalice#711]
Please add a --verbose flag for "chalice deploy", so that if the deploy fails, the user can debug the issue, by receiving the full stack trace of the error.

Is it stands, the user only receives the final line of the error. Though sending test events to the routes in app.py is a work-around, sometime the error isn't triggered by a route.

**Comment by jamesls** [comment]
I agree, I'd like this as well.

**Comment by akravetz** [comment]
related to #662
