### ISSUE TITLE
Chalice with RDS postgresql?

### ISSUE THREAD

**Issue by iashanmugavel** [aws/chalice#714]
Hi,
Our application is developed on Ruby on Rails and RDS postgresql as database.  I am building the serverless API using Chalice(API gateway+ Lambda). But unfortunately I am not getting much references to connect RDS from lambda functions. 

I found this plugin http://initd.org/psycopg/docs/ to connect postgresql but it is not helping much in terms of ORM layer.

Is it possible to configure/connect RDS using Chalice?

Thanks,
Shan

**Comment by stealthycoin** [comment]
Yes it should work fine using the `psycopg2` python package. Which hopefully answers the Chalice specific part of your question.

As for setting up RDS and Lambda Im afraid I am not particularly experienced so I can't offer any advice. I would suggest looking either on the stackoverflow/lambda forums/RDS forums.
