### ISSUE TITLE
Automate Documentation

### ISSUE THREAD

**Issue by UnderSampled** [aws/chalice#716]
It would be great to be able to automatically document the API based on inline comments. Also useful would be a way to set the "operationId" for swagger based on the View Function's name. I'm not sure how that works with the API Gateway, but it would be amazing if the SDKs I generate from it's exported Swagger file could have the functions named and documented correctly, without having to redo the swagger-file.

**Comment by stealthycoin** [comment]
Do you mean using the docstrings for each route function as the documentation that gets set for the API Gateway documentation for that route? That sounds useful to me if thats what you are referring to.

**Comment by kadrach** [comment]
See https://github.com/aws/chalice/issues/574 and https://github.com/aws/chalice/issues/574, there are probably more :)

**Comment by jamesls** [comment]
This is addressed via https://github.com/aws/chalice/pull/681
