### ISSUE TITLE
Help me to correct chalice staging url configuration

### ISSUE THREAD

**Issue by rajasimon** [aws/chalice#734]
I've deploy my project to AWS using chalice. In the end chalice spit out the url which look like this...

    https://<xxx>.execute-api.us-east-1.amazonaws.com/api/

When I access this throws below error but the `local` is fine.

> {"message":"Missing Authentication Token"}

This is my view function...

```
@app.route('/{day}')
def index(day=None):
    if not day:
        day = datetime.today().strftime('%Y-%m-%d')
    
    # Using the date to get the DynamoDb post information.
    return query_posts(day)
```

The error is gone after put /dev in the end but then throws error if I'm accessing by date 

    https://fvilt4qxqj.execute-api.us-east-1.amazonaws.com/api/dev/2018-03-01

> {"message":"Missing Authentication Token"}

But then again the error is gone if I remove `dev` from the url. What  I want is to standard url like without dev to use the Api.

**Comment by dstufft** [comment]
I believe that is the error you get if that url isn't registered in lambda. Your route requires a date, so ``/api/`` isn't valid, it needs to be ``/api/<SOMETHING>``.
