### ISSUE TITLE
How use the same API gateway with different stages and functions? 

### ISSUE THREAD

**Issue by iboobel** [aws/chalice#739]
How use the same API gateway with different stages and functions? 
Fox exemple: 
`chalice deploy --stage prod --api-gateway-stage prod `
will create my-app-prod (function) and some gateway with stage prod. 
But if I run:
`chalice deploy --stage dev--api-gateway-stage dev` 
I'll get new pair of function and api entrypoint. 
Can I create something like this
API_ID.execute-api.us-east-1.amazonaws.com/prod/
API_ID.execute-api.us-east-1.amazonaws.com/dev/ with the same API_ID?

**Comment by nplutt** [comment]
Hey, so you could do something like this, you would deploy both API Gateways just like you're doing now.
From there you can use API Gateway's custom domain name feature and add both api's under their respective base path mappings of `dev` and `prod`.

**Comment by stealthycoin** [comment]
@nplutt is correct. Sorry I missed this before.
