### ISSUE TITLE
app.current_request is not thread safe

### ISSUE THREAD

**Issue by edwinevans** [aws/chalice#759]
I'm running into a problem when testing using chalice local and making calls to my service at almost the same time. It seems like app.current_request could get overwritten by a later request by the time I finish handling an earlier one so my current handler is working with a request object with context for the later request (i.e. I'm handling Request 1, Request 2 comes in, Request 3 comes in, my handler for request 2 uses app.current_request and gets the context for request 3). 

Would it be better to pass the request object in to the route?

Is this a potential problem when running in lambda or does each handler get a separate process?

**Comment by stealthycoin** [comment]
`app.current_request` makes the assumption that only 1 is going to be executed at a time since that is how it functions in Lambda and makes everything simpler. We could play with switching to ForkingMixIn to separate them by a process boundary.

**Comment by edwinevans** [comment]
Thanks for your response. Does Lambda with api gateway only execute one request at a time? I have seen something that looks similar now when running in AWS. In one case I got a Chalice error of "invalid_request" with description "invalid concurrent request". What does this mean?

**Comment by edwinevans** [comment]
Is there any way to workaround/force the requests to come in sequentially? I don't see how I can make something reliable if I can't assume that the request body corresponds to the request function and that request bodies won't get lost.

**Comment by edwinevans** [comment]
Regarding "invalid concurrent request" I can't find the complete response any more. I'll let you know if I see it again.

Regarding the originally described issue it's possible to reproduce it by having the browser make multiple requests in parallel using Promise.All. (I'm not doing this any more so the issue will happen less frequently for me but may be worse when it does happen since I won't be expecting it.)

Thanks for looking into this.

**Comment by clarsen** [comment]
> Only one can execute in Lambda at a time, so this is not an issue with production Chalice, it is an issue with local mode properly emulating the production service. The local mode uses threads since browsers can hog the connection and was causing local mode to hang after a request from a browser. 

Hi there, I noticed this issue in my local development too, but attached a PR with a simple fix that has been working well for me over the last few weeks in local mode operation.
