### ISSUE TITLE
500 error running locally and hitting a non-CORS endpoint from a different localhost port

### ISSUE THREAD

**Issue by BenMusch** [aws/chalice#761]
## Context

I am running `chalice local` on my machine and hitting the local chalice app (running on port 8000) from a front-end running on `localhost:8080`. I do not get this error when hitting the API from Postman or other http clients.

Here is the request made via my front-end (doesn't work):

```
curl 'http://localhost:8000/translate' -X OPTIONS \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Origin: http://localhost:8080' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36' \
  -H 'Access-Control-Request-Headers: content-type' --compressed
```

Here is a request made via Postman (works):

```
curl -X POST \
  http://localhost:8000/translate \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:8080' \
  -H 'Postman-Token: 66936da1-a61c-adb8-11c7-7e4ee0e27fd7' \
  -d '{
	"text": "My name is Ben",
	"numTranslations": "1"
}'
```

## Actual response

500 error with no content

#### Traceback

```
  File "/Users/bmuschol/.pyenv/versions/2.7.13/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/bmuschol/.pyenv/versions/2.7.13/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/bmuschol/.virtualenvs/translate/lib/python2.7/site-packages/chalice/local.py", line 529, in __init__
    self, request, client_address, server)  # type: ignore
  File "/Users/bmuschol/.pyenv/versions/2.7.13/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/Users/bmuschol/.pyenv/versions/2.7.13/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/bmuschol/.pyenv/versions/2.7.13/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/bmuschol/.virtualenvs/translate/lib/python2.7/site-packages/chalice/local.py", line 550, in _generic_handle
    body=body
  File "/Users/bmuschol/.virtualenvs/translate/lib/python2.7/site-packages/chalice/local.py", line 471, in handle_request
    options_headers = self._autogen_options_headers(lambda_event)
  File "/Users/bmuschol/.virtualenvs/translate/lib/python2.7/site-packages/chalice/local.py", line 497, in _autogen_options_headers
    cors_headers = cors_config.get_access_control_headers()
AttributeError: 'NoneType' object has no attribute 'get_access_control_headers'
```

## Expected response

403 response with the `missing auth token` message given when hitting a non-CORS endpoint on prod _or_ don't consider different localhost ports to be cross-origin

## Environment

Chalice 1.1.1
Python 2.7.13

**Comment by stealthycoin** [comment]
Yea looks like this needs to be smoothed out a bit. Marking as an enhancement.

**Comment by ogrodnek** [comment]
I'm getting this same error against a CORS endpoint in local mode.

**Comment by ogrodnek** [comment]
I'm getting this same issue hitting a CORS endpoint running chalice local.

**Comment by adamklaff** [comment]
Is there a workaround for this? I can't seem to make post requests using Axios, my Chalice local server keeps crashing with the above error.

In Chalice (app.py):
```
cors_config = CORSConfig(
    allow_origin='*'
)
@app.route('/submit', methods=['POST'], cors = cors_config)
```

index.js

 ```
let axiosConfig = {
            headers: {
                'Access-Control-Allow-Origin': '*'
            },
            params: {
                name: this.name,
                email: this.email
            }
	      };
        axios.post('http://localhost:8000/dividend', null, axiosConfig)
```

**Comment by vladimirze** [comment]
Had the same issue with this code:
```python
from chalice import Chalice


app = Chalice(app_name='chalicedemo')


@app.route('/', methods=['GET'])
def get():
    return {}


@app.route('/', methods=['POST'], cors=True)
def post():
    return {}
```

Note that the first view does not have CORS enabled. If I change the order of functions -- it will not crash.

When OPTIONS response is autogenerated, there is an attempt to access cors configuration for current served route
but since not all methods/routes have to support CORS (like in example above) then `cors_config` will be None.
The reason why it is sensitive to order is because the cors configuration is always read from the first declared view -- https://github.com/aws/chalice/blob/1.20.1/chalice/local.py#L552

I've filtered out methods that do not have CORS enabled for them. Here is the PR: https://github.com/aws/chalice/pull/1534.

**Comment by jamesls** [comment]
Fixed via https://github.com/aws/chalice/pull/1534
