### ISSUE TITLE
Chalice local mode drops query string params with blank vlaues

### ISSUE THREAD

**Issue by brianjbeach** [aws/chalice#765]
When running Chalice in local mode it, incorrectly parses query string parameters dropping parameters that have no value. This is inconsistent with how Lambda/API gateway performs.  For example, given the following URL http://example.com?a=1&b=&c=3 the resulting query string param collection will not include b in local mode, but would include it when running in Lambda. The correct implementation of parse_qs should include the keep_blank_values=True flag as described [here](https://docs.python.org/2/library/urlparse.html#urlparse.parse_qs)

https://github.com/aws/chalice/blob/c1c918c31c7e77272f6f2edd68355cd8ac441dc3/chalice/local.py#L126

**Comment by stealthycoin** [comment]
I see you have a PR for this so I am going to close this issue.
