### ISSUE TITLE
Sub module could not be found defined under chalicelib

### ISSUE THREAD

**Issue by kyeljmd** [aws/chalice#769]
My directory structure is as follows

```
.
├── app.py
├── chalicelib
│   └── __init__.py
│      ├──users 
│            └── __init__.py
│            └── routes.py
└── requirements.txt
```

I have a directory called users under it is the following routes
```
from app import app

CITIES_TO_STATE = {
    'seattle': 'WA',
    'portland': 'OR',
}


@app.route('/')
def index():
    return {'hello': 'world'}


@app.route('/cities/{city}')
def state_of_city(city):
    return {'state': CITIES_TO_STATE[city]}

```

and within my app.py 

I have this defined
```

from chalice import Chalice

app = Chalice(app_name='redqchaliceimpl')

from chalicelib import users
from users import routes
```

However, whenever I run chalice deploy this error occurs

`No module named 'users'
`

Did I miss anything?

**Comment by kgutwin** [comment]
This looks like a Python circular import dependency problem. Look here for some discussion and possible solutions: https://stackoverflow.com/questions/1556387/circular-import-dependency-in-python

**Comment by stealthycoin** [comment]
@kgutwin is correct. Since this isn't a chalice specific problem I'm going to close it out.
