### ISSUE TITLE
CodeBuild failure

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#773]
http://chalice-workshop.readthedocs.io/en/latest/part2/02-pipeline.html#creating-a-pipeline
Following the instruction above, the build failed. Has it been fixed?

[Container] 2018/04/02 19:25:27 Phase context status code: Message: 
[Container] 2018/04/02 19:25:27 Entering phase INSTALL
[Container] 2018/04/02 19:25:27 Running command sudo pip install --upgrade awscli
sh: 1: sudo: not found

[Container] 2018/04/02 19:25:27 Command did not exit successfully sudo pip install --upgrade awscli exit status 127

**Comment by stealthycoin** [comment]
I can't replicate this I just followed those instructions and it builds and deploys a beta stage without any issue. I don't think this is an issue with chalice or the pipeline cloudformation it emits.

**Comment by wutachih** [comment]
After I removed 'sudo' in the buildspec.yml, the pipeline worked.

**Comment by stealthycoin** [comment]
Glad you got it working.
