### ISSUE TITLE
The REST API doesn't contain any methods

### ISSUE THREAD

**Issue by jhw** [aws/chalice#789]
I have a Chalice app which is 100% pure functions, but when I try and deploy it complains about the above. I can solve this by adding a simple index function (non- pure) but is there any way to configure the deployment to not create an API so as to avoid this ? Thanks!

**Comment by BigChief45** [comment]
Make sure to upgrade to the latest version of Chalice (1.2.0).

**Comment by stealthycoin** [comment]
@BigChief35 is correct :). Fixed in 1.2.0
