### ISSUE TITLE
package.py creates AWS::Serverless::Function Environment Variables property incorrectly

### ISSUE THREAD

**Issue by earchibald-lv** [aws/chalice#795]
`AWS::Serverless::Function` implements environment variables as

```
{ "Properties": {
  "Environment": {
    "Variables": { ... } } }
```

(see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html)

However, `package.py` is defining the structure as:

```
{"Properties: {
  "EnvironmentVariables": {
    "Variables": { ... } } }
```

**Comment by stealthycoin** [comment]
Thanks for reporting it. I'll get this fixed.
