### ISSUE TITLE
Terrible Lambda performance for CPU- bound function

### ISSUE THREAD

**Issue by jhw** [aws/chalice#800]
Hi, I have a Chalice project with a number of endpoints/functions, working fine, no problem. I recently added an extra function which performs a calculation on the server - POST a JSON request, perform calculation, return JSON response. The calculation is totally stateless, ie lambda function doesn't call any third party URLs or datastore or anything. On my laptop the calculation takes ~1 second. On lambda the average time is ~14 seconds!  This isn't going to work for me. I don't think it's the API Gateway or the startup time at fault as all the other functions in the project (non- CPU bound) return nice timely results. It feels to me like the calculation is being run on a tiny machine or maybe there is limited memory. I have tried setting "memory_size" in .chalice/config.json to 512, but makes no difference. Can anyone suggest how I might improve performance of the calculation, possibly by increasing memory (perhaps I am doing it wrong ?) or somehow specifying a larger machine (is that possible ?) - Thx!

**Comment by kadrach** [comment]
I don't believe AWS publishes official performance characteristics for Lambda functions, but only state that Lambda function "cpu" performance scales with provisioned memory. So "more memory" means more horsepower. There are a large number of blog posts you can find on this topic.

Aside from that, you can try profiling the application to see where the bottleneck is. Hard to tell. This is unlikely to be related to Chalice.

**Comment by jhw** [comment]
OK this article suggests increasing the memory should fix the issue.

https://serverless.zone/my-accidental-3-5x-speed-increase-of-aws-lambda-functions-6d95351197f3

But I can't seem to increase memory size! I have changed `.chalice/config.json` to read as follows

```
{
    "stages": {
	"dev": {
	    "api_gateway_stage": "api"
	}
    },
    "version": "2.0",
    "app_name": "XXXX",
    "memory_size": 1536
}
```
but when I deploy and run the function again, the CloudWatch logs still reference 'Memory Size: 128MB' (the default) and the function takes the same amount of time to run.

Am I trying to increase memory_size the wrong way ?

**Comment by jhw** [comment]
Fixed. The attribute is `lambda_memory_size`, not `memory_size`. `memory_size` was specified in the original proposal, but the docs say `lambda_memory_size`. Anyway it works, execution down to 1-2 secs :-). 

It might be nice to have  `config.json` tested against a schema prior to deployment, my `memory_size` field was obviously being silently ignored :-/
