### ISSUE TITLE
Continuation of processing after response sent.

### ISSUE THREAD

**Issue by soimafreak** [aws/chalice#804]
I've had a look at the documentation and code but I could not see anything built in for this.

What I want to do is receive a request on an API endpoint and immediately send a response object to the client. After sending the response object I want to then continue processing the request I received. 

I Have tried to create a thread and split the response and work I believe this will work locally but Lambda will terminate the process due to a response being sent. 
When using the pure lambda route, the method terminates when the response is returned  (locally)

So with that in mind...
Am I overlooking an obvious way to solve this using chalice?
Could I use the pure lambda mechanism to achieve this or will it also terminate its request early as it did locally?

The only way I have seen this work is to use the pure_lambda route but then generate a SNS topic to execute the pure lambda in the background, which seems cumbersome to me.

**Comment by soimafreak** [comment]
I did a little more digging and created some prototypes. It looks like there is no way of doing it without creating another interaction. I think this would be a nice addition to chalice; but for now, I'll have to create that new interaction.
I'll close this, but still interested how others solved this, especially if it was done without creating another interaction with lambda by say SNS

**Comment by tahaykACF** [comment]
In my case the solution was to make a call to an endpoint with 1s timeout (no wait for response)
so I can return a response and continue processing the request
I don't know if it is the best way to do it but it works for me
