### ISSUE TITLE
"The security token included in the request is invalid" on Cloud9

### ISSUE THREAD

**Issue by rosskarchner** [aws/chalice#807]
From a brand-new Cloud9 environment  (as an IAM user with [this custom policy](https://github.com/aws/chalice/issues/59#issuecomment-239640739), and I'm getting the following when I try to deploy the default app (the one you get along with new-project):

```
ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (InvalidClientTokenId) when calling the CreateRole 
 operation: The security token included in the request is invalid
```
Is that IAM policy incomplete?

**Comment by kadrach** [comment]
At first glance, that policy does not grant `iam:CreateRole`. However I would expect to see a permission denied error rather than a security token error. Are you manually setting credentials, or letting chalice (boto) pick up credentials?

**Comment by rosskarchner** [comment]
I'm letting Chalice pick them up automatically

**Comment by rosskarchner** [comment]
I should also not that the policy I linked to is not the only one in place-- some of these are needed for Cloud9, and some were just added while attempting to troubleshoot.

![screenshot from 2018-04-22 18-41-50](https://user-images.githubusercontent.com/235397/39100766-06a55a9e-465d-11e8-8cf5-5dd441804775.png)

**Comment by rosskarchner** [comment]
some googling indicates that there is an incompatibility between API's that use tokens, and service-linked roles. For now, I've set my credentials in environment variables, and things seem to be working OK.
