### ISSUE TITLE
deploy fails with pip 10.0.0

### ISSUE THREAD

**Issue by dmulter** [aws/chalice#808]
I'm running a venv with Python 3.6.3 and just upgraded PIP from 9.0.3 to the 10.0.0 and get the following error for chalice deploy:

```
chalice.deploy.packager.PackageDownloadError: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pip' has no attribute 'main'
```

I downgrade back to 9.0.3 and all works fine.

**Comment by dstufft** [comment]
There is a version pin for ``pip<10`` in our ``setup.py``, however we should update chalice to handle pip 10 and drop that pin.

**Comment by jamesls** [comment]
Yeah I ran into this myself.  I wonder if it's worth having (assuming it's feasible) the range be >9,<11 or if we should just only support 10.x.

**Comment by dstufft** [comment]
It *should* be pretty easy to support both.

**Comment by dmulter** [comment]
FYI, the same thing is happening again when upgrading to the latest pip v18.0.

**Comment by ricky-sb** [comment]
Looks like the new pip version broke chalice again. Getting the same error.
