### ISSUE TITLE
Cloudformation deploy

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#814]
Can I use 'cloudformation deploy' for different stages like chalice deploy? A pointer or example will be appreciated.

**Comment by kyleknap** [comment]
It should not be much different than `chalice deploy`. The main difference is that you have to run `chalice package` with the `--stage` argument, and follow the instructions from [this guide]( http://chalice.readthedocs.io/en/latest/topics/cfn.html?highlight=cloudformation%20deploy#example) to actually deploy the CloudFormation stack. It is also worth noting if you are deploying separate stacks, you would likely want to use a different CloudFormation stack name and S3 bucket when running the `aws cloudformation deploy` and `aws cloudformation package` commands respectively.

Let us know if you have any more questions.
