### ISSUE TITLE
Auth is enabled for all routes in chalice local

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#815]
Once some routes are enabled with the authorizer, all routes are required to pass the token in the chalice local. But the endpoint works appropriately per route. Is this expected?

**Comment by kyleknap** [comment]
Could you clarify what you are seeing from your side (i.e. provide a sample app and sample HTTP requests sent to the local server)? For example, I have not been able to reproduce this. Here is what my `app.py` looks like:
```python
from chalice import Chalice, AuthResponse

app = Chalice(app_name='demoauth1')


@app.authorizer()
def demo_auth(auth_request):
    token = auth_request.token
    # This is just for demo purposes as shown in the API Gateway docs.
    # Normally you'd call an oauth provider, validate the
    # jwt token, etc.
    # In this exampe, the token is treated as the status for demo
    # purposes.
    #if token == 'allow':
    return AuthResponse(routes=['/'], principal_id='user',
                        context={'allow': token})


@app.route('/', authorizer=demo_auth)
def index():
    return {'context': app.current_request.context}


@app.route('/noauth')
def unauth():
    return {'no': 'auth'}
```
So when I make a request to `/`, it requires auth:
```
$ http 127.0.0.1:8000/ 'Authorization: allow'
HTTP/1.1 200 OK
Content-Length: 164
Content-Type: application/json
Date: Mon, 30 Apr 2018 22:39:12 GMT
Server: BaseHTTP/0.3 Python/2.7.10

{
    "context": {
        "authorizer": {
            "allow": "allow", 
            "principalId": "user"
        }, 
        "httpMethod": "GET", 
        "identity": {
            "sourceIp": "127.0.0.1"
        }, 
        "path": "/", 
        "resourcePath": "/"
    }
}

```
But when I make a request to `/noauth`, it is able to handle the request just fine:
```
$ http 127.0.0.1:8000/noauth
HTTP/1.1 200 OK
Content-Length: 14
Content-Type: application/json
Date: Mon, 30 Apr 2018 22:39:19 GMT
Server: BaseHTTP/0.3 Python/2.7.10

{
    "no": "auth"
}

```

**Comment by stealthycoin** [comment]
What version of Chalice is this? the /dev/ makes me think that this is not a recent version.

**Comment by wutachih** [comment]
chalice 1.2.2

**Comment by wutachih** [comment]
I ran into the similar issue. I have two deployments, /dev and /prod, with an identical route. Something isn't right.

@app.route('/upgrade_controllers/{secret}', methods=['POST'])
def send_mails(secret):
....

(api-env) $ http post https://api.aviatrix.io/dev/upgrade_controllers/xxxxxx
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 21
Content-Type: application/json
Date: Fri, 11 May 2018 04:48:26 GMT
Via: 1.1 ae162f6796e551002447afd7c07ec67a.cloudfront.net (CloudFront)
X-Amz-Cf-Id: HObY3vI9PAfFuSzXjSxdHwmNPesvJccLwhDOU8tZZCWtZf50Ylak3A==
X-Amzn-Trace-Id: Root=1-5af52096-a5116c9f04029276781135fd
X-Cache: Miss from cloudfront
x-amz-apigw-id: GtIHhGUsPHcFb6g=
x-amzn-RequestId: 888915c7-54d6-11e8-a275-dbe0316fe42c

{
    "Status": "Success"
}

(api-env) $ http post https://api.aviatrix.io/prod/upgrade_controllers/xxxxxx
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Fri, 11 May 2018 04:58:29 GMT
Via: 1.1 2d6b915af011d536a849b277ab1ac8b4.cloudfront.net (CloudFront)
X-Amz-Cf-Id: TY92xxzdFvFnlQLz8AjkZi-qNTotBsvw2edBswZ4poOmrrY0kDCerQ==
X-Cache: Error from cloudfront
x-amz-apigw-id: GtJmbH45vHcF-OA=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: f294f443-54d7-11e8-a3cd-1f073cecc505

{
    "message": "Missing Authentication Token"
}

**Comment by stealthycoin** [comment]
Missing authentication token can also just mean the route wasn't found. It doesn't necessarily mean auth is involved. I'll take a look at replicating this.

**Comment by stealthycoin** [comment]
Looks like you just have the `/dev/` prefix in there for local mode which is causing the issue. Local mode doesn't do any deployments and there are no prefixes. Just the API routes themselves. I have no issues running this code:

```python
from chalice import Chalice

app = Chalice(app_name='local-test')


@app.authorizer()
def jwt_auth(auth_request):
    token = auth_request.token
    if token == 'allow':
        return AuthResponse(routes=['/'], principal_id='user')
    else:
        return AuthResponse(routes=[], principal_id='user')


@app.route('/happy')
def hello():
    return {"Hello": "Happy"}


@app.route('/test-token', cors=True, authorizer=jwt_auth)
def test_token():
    return {"Hello": "Testing"}
```

```
$ curl -vvv localhost:8000/happy
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /happy HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: BaseHTTP/0.6 Python/3.6.4
< Date: Mon, 21 May 2018 19:29:44 GMT
< Content-Length: 18
< Content-Type: application/json
<
* Connection #0 to host localhost left intact
{"Hello": "Happy"}
```

The other issue you added to this is separate since it doesn't have anything to do with local mode, and we would need more information to help debug it. Most likely there is no /prod/ prefix in api gateway.
