### ISSUE TITLE
Is it possible to use scheduled event function with lambda timeout set?

### ISSUE THREAD

**Issue by hustshawn** [aws/chalice#821]
I have a scheduled event function needs to run, but it may take little bit more time, which may be over than the default 60 seconds of lambda functions. Is there any way I can set the timeout to the target function?

This is my schedule function below.
```
@app.schedule(Rate(5, unit=Rate.MINUTES))
def per_five_minutes(event):
   # This function may take almost 2 minutes, but it timeout in 60 seconds, and rerun...
    main()
    print(event.to_dict())
```

**Comment by stealthycoin** [comment]
Yes, it is in the documentation for configuration: http://chalice.readthedocs.io/en/latest/topics/configfile.html#configuration-file as `lambda_timeout`.

**Comment by hustshawn** [comment]
@stealthycoin Thanks a lot. It helps to me.
