### ISSUE TITLE
How should I enable compressed response from my API using Chalice

### ISSUE THREAD

**Issue by irr** [aws/chalice#822]
Hi,

  Is there any configuration or steps that I should do to get my compressed response?

```python
from chalice import Chalice, Response
import json

app = Chalice(app_name='chapp')

@app.route('/')
def index():
    return Response(body=json.dumps(app.current_request.to_dict()),
                    status_code=200,
                    headers={'Content-Type': 'application/json'})
```
   I tried using this sample code and it is not working. After deployed I use the following command to enable compression:

aws apigateway update-rest-api --rest-api-id 2z.... --patch-operations op=replace,path=/minimumCompressionSize,value='0'

<-----------------------  begin (output)
{
    "apiKeySource": "HEADER", 
    "name": "chapp", 
    "endpointConfiguration": {
        "types": [
            "EDGE"
        ]
    }, 
    "minimumCompressionSize": 0, 
    "version": "1.0", 
    "createdDate": 1524781284, 
    "binaryMediaTypes": [
        "application/octet-stream", 
        "application/x-tar", 
        "application/zip", 
        "audio/basic", 
        "audio/ogg", 
        "audio/mp4", 
        "audio/mpeg", 
        "audio/wav", 
        "audio/webm", 
        "image/png", 
        "image/jpg", 
        "image/jpeg", 
        "image/gif", 
        "video/ogg", 
        "video/mpeg", 
        "video/webm"
    ], 
    "id": "2z..."
}
<----------------------- end (output)

   Is it possible to enable compression in .chalice/config.json?

   Thanks in advance.

**Comment by joguSD** [comment]
This isn't currently possible through the config.json. There's an open feature request for this here: #672.
Closing as duplicate.
