### ISSUE TITLE
The endpoint for SNS sub

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#823]
I tried to subscribe a route to the SNS as a HTTPS endpoint. But it can't see any body data when the SNS posts a confirmation request to the route. I can tell the route is triggered from the log, but it can't see any data from current_request. Is it this a known limitation?

**Comment by sedden** [comment]
The content type for requests sent to SNS HTTPS endpoints is text/plain. This works for me:

```
@app.route('/sns', methods=['POST', 'GET', 'PUT'], content_types=['text/plain'])
def sns():

    try:
        message = json.loads(app.current_request.raw_body)
    except:
        pass

    headers = app.current_request.to_dict()['headers']
    message_type = headers.get('x-amz-sns-message-type')

    # handle subscribtion confirmation
    if message_type == 'SubscriptionConfirmation' and 'SubscribeURL' in message:
        pass

    # handle notifications
    elif message_type == 'Notification':
        pass

    return 'OK\n'
```
