### ISSUE TITLE
helloworld chalice deploy : InvalidParameterValueException

### ISSUE THREAD

**Issue by sanjivsoni** [aws/chalice#824]
I am trying to deploy Chalice (chalice 1.2.2) hello world project on AWS. I am using python3.6 in virtual env on a mac. 
This is how app.py looks like

```
from chalice import Chalice  
   app = Chalice(app_name='helloworld')
   
   @app.route('/')
   def index():
       return {'hello': 'world'}

```

requirement.txt is empty
When I run `chalice deploy`,
Creating deployment package.
Updating policy for IAM role: helloworld-dev
Creating lambda function: helloworld-dev
Traceback (most recent call last):
...
...
 I get this error `botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.`

In AWS IAM console, I can see the helloworld-dev role created.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        }
    ]
}
```

Chalice config.json file
```
 {
  1   "version": "2.0",
  2   "app_name": "helloworld",
  3   "stages": {
  4     "dev": {
  5       "api_gateway_stage": "api"
  6     }
  7   }
  8 }
```

**Comment by kadrach** [comment]
>  Updating policy for IAM role: helloworld-dev

At a quick glance, you have a pre-existing role. Chalice "updates" this role with a `put_role_policy` call.

Was this role created by Chalice initially? The error message suggests that the trust policy is incorrect. It should look like [this](https://github.com/aws/chalice/blob/ac3bee4830fb0d6acfa326c3d04c13ff2cfcdd6f/chalice/constants.py#L59:1).
