### ISSUE TITLE
Working with Swagger ?

### ISSUE THREAD

**Issue by jhw** [aws/chalice#825]
Apologies but I am having trouble finding this in the docs; but what are the recommended ways of working with Swagger and Chalice ? I have a team of devs building stateless Chalice POST apps/APIs - JSON in, JSON out - and need a sensible documentation solution. I mention Swagger because it seems to be what everybody uses. Ideally I would like devs to write simple docs as part of their Chalice projects (maybe in YAML form ? maybe annotated source code ?), have them deployed to AWS via Chalice and then have a nice set of generated HTML docs available at the Chalice endpoint. Does anything nice and simple like this exist ? Assuming Chalice supports Swagger could someone point me to the docs and maybe describe the workflow in very simple terms ? Asking because Swagger seems like a beast with multiple different products and its very hard to know where to start. Thanks in advance :-)

**Comment by stealthycoin** [comment]
Chalice does not have any explicit integrations with swagger from an API definition perspective. The point of Chalice is to define your API in the python code itself so using swagger for this would run counter to one of the main selling points of Chalice. 

The only place Chalice currently uses swagger is as an implementation detail in how it deploys the API Gateway interface. Once the API Gateway has been deployed you can always fetch the API definition in swagger format using the [Export](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html) API Gateway API. 


If you are just asking for a feature to get documentation into API Gateway itself then there is a PR up right now for sourcing the API documentation from the docstrings of the chalice route functions. You can go give a thumbs up if you are interested in this feature: https://github.com/aws/chalice/pull/681
