### ISSUE TITLE
Body response - PDF File (with weasyprint)

### ISSUE THREAD

**Issue by 3dw1np** [aws/chalice#831]
I am using Response for a pdf file rendered with weasyprint lib.
Locally works, but in lambda, I have an error "JSON serialization of response: 'utf8' codec can't decode byte 0xe2 in position 10"

```
return ChaliceResponse(body=pdf_file,
				status_code=200,
				headers={
					'Content-Type': 'application/pdf',
					'Content-Disposition': 'inline; contract.pdf'
				}
			)
```

Also in the declaration of the route, I had put that : 
```
@app.route('/me/contract', content_types=['application/pdf'], methods=['GET'], cors=True)
```

**Comment by kadrach** [comment]
I think that's because `application/pdf` is not part of Chalice's [default binary types](https://github.com/aws/chalice/blob/2fa53f6b50de5bc29092b92fd9dffbd5edec5d59/chalice/app.py#L406).

> Chalice supports binary payloads through its app.api.binary_types list. Any type in this list is considered a binary Content-Type. Whenever a request with a Content-Type header is encountered that matches an entry in the binary_types list, its body will be available as a bytes type on the property app.current_request.raw_body.
