### ISSUE TITLE
Importing requests breaks the app

### ISSUE THREAD

**Issue by javrllerenas** [aws/chalice#847]
I am trying to make a GET request to an external api using `requests.get()`, however, by importing `requests` the app breaks.

I could not find a similar module/function in `chalice` that offers the same functionality.

### Environment
* Python 3.6

**Comment by BigChief45** [comment]
I am using requests without any problems in my Chalice project. Can you post details of the errors?

**Comment by stealthycoin** [comment]
We will need more details than this. I regularly use requests in Chalice apps so that isn't it.

Try setting `app.debug = True` as the first line under `app = ...` and see what logs come out.

**Comment by marcelo-bn** [comment]
Hello @stealthycoin and @aalvrz I am having the same problem than @javillerenas 

The `requests` module cannot be found. Which version of the chalice and orders are you using?
