### ISSUE TITLE
Chalice Package File Permissions

### ISSUE THREAD

**Issue by bvallelunga** [aws/chalice#853]
Hey guys, when I run `chalice deploy` on my laptop everything works great but when I run it on a Heroku instance it creates this error when calling the function.

```
START RequestId: 520c9d03-617b-11e8-bedb-6bcc2dc21d2d Version: $LATEST
module initialization error: [Errno 13] Permission denied: '/var/task/app.py'

END RequestId: 520c9d03-617b-11e8-bedb-6bcc2dc21d2d
REPORT RequestId: 520c9d03-617b-11e8-bedb-6bcc2dc21d2d    Duration: 293.22 ms    Billed Duration: 300 ms     Memory Size: 128 MB    Max Memory Used: 21 MB    
module initialization error
[Errno 13] Permission denied: '/var/task/app.py'
```

I am guessing this is a permissions error. So I tried `chmod -R 777` on the repo and it partially fixed the problem by granting permissions to existing files in the repos. Now the problem is that all the other files like the `chalice` folder and `vendor` folder all do not have proper permissions because the heroku instance default permissions do now allow `rwx`. 

```
START RequestId: 520c9d03-617b-11e8-bedb-6bcc2dc21d2d Version: $LATEST
module initialization error: [Errno 13] Permission denied: '/var/task/chalice/__init__.py'

END RequestId: 520c9d03-617b-11e8-bedb-6bcc2dc21d2d
REPORT RequestId: 520c9d03-617b-11e8-bedb-6bcc2dc21d2d    Duration: 293.22 ms    Billed Duration: 300 ms     Memory Size: 128 MB    Max Memory Used: 21 MB    
module initialization error
[Errno 13] Permission denied: '/var/task/chalice/__init__.py'
```

Would it be possible to chmod everything that goes into the package zip the chalice library creates. This way all the files have the same permissions and should run on AWS lambda?

**Comment by bvallelunga** [comment]
This hack worked for me:

Adding it between lines 99 & 100: https://github.com/aws/chalice/blob/master/chalice/deploy/packager.py#L100

```
with self._osutils.tempdir() as clone_dir:
    self._osutils.extract_zipfile(package_filename, clone_dir)
    self._osutils.remove_file(package_filename)
    
    os.system('chmod -R 777 {}'.format(clone_dir))
    shutil.make_archive(package_filename[:-4], 'zip', clone_dir)
```

**Comment by kadrach** [comment]
What do the file permissions prior to packaging look like?

**Comment by kyleknap** [comment]
I have a similar question to what @kadrach asked.
