### ISSUE TITLE
chalice local test error <response 403>

### ISSUE THREAD

**Issue by iamecong** [aws/chalice#861]
when I test my chalice project locally, the response return <response 403> and {"message": "Missing Authentication Token"}???
The tutorial says,"The chalice local command does not assume the role associated with your lambda function, so you'll need to use an AWS_PROFILE that has sufficient permissions to your AWS resources used in your app.py."
what dose this mean?

**Comment by kyleknap** [comment]
@iamecong could you provide code from the Chalice app that you are running and provide the command you are running to query the API running locally? Often times, I get this error because I had typo in the command that I ran to query the API. More specifically a typo in the API's route.
