### ISSUE TITLE
Does not pick the current Python version

### ISSUE THREAD

**Issue by Gsantomaggio** [aws/chalice#863]
Hi,
I am trying to deploy an AWS lambda function, the problem is that chalice does not pick the current Python version.
I'd like to deploy it using Python 2.7, but for some reason it uses Python 3.6

OS:
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
```

Deploy:
```bash
(env) ➜  hello_chalice git:(master) ✗ chalice --version
chalice 1.3.0

(env) ➜  hello_chalice git:(master) ✗ python --version
Python 2.7.10
(env) ➜  hello_chalice git:(master) ✗ pip --version
pip 9.0.1 from /hello_chalice/env/lib/python2.7/site-packages (python 2.7)
(env) ➜  hello_chalice git:(master) ✗
(env) ➜  hello_chalice git:(master) ✗ chalice --debug deploy

.....
aws-chalice/1.3.0 Python/3.6.5 Darwin/16.7.0 exec-env/AWS_Lambda aws-chalice/1.3.0 Botocore/1.10.31'},  
....

Resources deployed:
  - Lambda ARN: arn:aws:lambda:xxxxxxxxx:function:hello_chalice-dev-square
```

But the result is:
![opera snapshot_2018-06-05_153815_console aws amazon com](https://user-images.githubusercontent.com/386987/40979675-bc395b26-68d6-11e8-8db2-0eff449c7506.png)

The package:
```
chalice package cloudformation 
```

gets
```
"Sqrt": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Runtime": "python3.6",
        "Handler": "app.sqrt",
```

Is there a way to specify the python version during the deploy?
Thanks

**Comment by kyleknap** [comment]
Thanks for the information. I suspect based on the debug logs:
```
aws-chalice/1.3.0 Python/3.6.5 Darwin/16.7.0 exec-env/AWS_Lambda aws-chalice/1.3.0 Botocore/1.10.31'},
```
the chalice executable that you are using may be installed under a Python3 runtime. In general `chalice` will use the python version that is being used to run the `chalice` executable. Could, you run: `which chalice`? That should hopefully point to where the executable lives and help detemine why Python3 is being used to run the `chalice` CLI.

**Comment by jamesls** [comment]
As a side note, perhaps we could update `chalice --version` to also print the python version, similar to `aws --version`.

**Comment by kyleknap** [comment]
+1. I was thinking the same thing after I posted the response. I opened another issue to track that: https://github.com/aws/chalice/issues/865

**Comment by Gsantomaggio** [comment]
Here:
```
(env) ➜  hello_chalice git:(master) ✗ which chalice
/usr/local/bin/chalice
```

**Comment by kyleknap** [comment]
Yeah it looks like it is getting installed system-wide. I would recommend uninstalling the system wide installation and instead rely on the version installed in the virtualenv that you activated. Let us know if that helps.

**Comment by Gsantomaggio** [comment]
@kyleknap yes it worked. 

```
$ which chalice
hello_chalice/env/bin/chalice
```

Thanks for your help. I should have thought about it, sorry.

**Comment by kyleknap** [comment]
No worries. Glad you got it working!
