### ISSUE TITLE
chalice and aws-sam-cli cross dependency issue (click) 

### ISSUE THREAD

**Issue by gjmveloso** [aws/chalice#872]
**Description:**

**Steps to reproduce the issue:**
1. Install `chalice` - https://github.com/aws/chalice
2. Install `aws-sam-cli`
3. `click` package warning

**Observed result:**

While installing `chalice`--
aws-sam-cli 0.3.0 has requirement click~=6.7, but you'll have click 6.6 which is incompatible.

While installing `aws-sam-cli` --
chalice 1.3.0 has requirement click==6.6, but you'll have click 6.7 which is incompatible.

**Expected result:**

No cross dependencies issues

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

macOS 10.13.5
pip 10.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)

**Output of `sam --version`**:

SAM CLI, version 0.3.0

**Comment by gjmveloso** [comment]
Related to https://github.com/awslabs/aws-sam-cli/issues/488

**Comment by jamesls** [comment]
Thanks for reporting, I think we can relax the version constraint and lock to a major version.
