### ISSUE TITLE
Do Errors accept json messge?

### ISSUE THREAD

**Issue by xplorld** [aws/chalice#882]
In README we know about using Chalice-defined Errors.

```py
from chalice import BadRequestError

@app.route('/cities/{city}')
def state_of_city(city):
    try:
        return {'state': CITIES_TO_STATE[city]}
    except KeyError:
        raise BadRequestError("Unknown city '%s', valid choices are: %s" % (
            city, ', '.join(CITIES_TO_STATE.keys())))
```

The problem is that, can I use a JSON object, instead of `str` as message of `BadRequestError`?

```py
raise BadRequestError({"error":"MyError", "timestamp": 12345, "some_meta": [{"key":"value"}]})
```
Will this work and send a proper JSON to the client?

**Comment by stealthycoin** [comment]
You can put anything you like there, it will be serialized to a string [here](https://github.com/aws/chalice/blob/master/chalice/app.py#L79)  before being passed along to the ChaliceError where it will eventually wind up in the `Message` [field of the response](https://github.com/aws/chalice/blob/master/chalice/app.py#L718-L720).
