### ISSUE TITLE
Can't connect to via network IP

### ISSUE THREAD

**Issue by freaker2k7** [aws/chalice#885]
I'm using now chalice==1.3.0 and I've updated my code to work with python3.
I updated it from chalice==0.7.0 and python2.

Now when I access the local website on http://localhost:3000 everything works (as formally),
But when I try to access it from http://192.168.1.101:3000 I get:

"This site can’t be reached" in chrome

And if I add the --host argument, then it's not accessible from http://localhost

Please help.

**Comment by stealthycoin** [comment]
That would be a routing issue with your network, nothing to do with Chalice itself. Probably just need to set up port forwarding on your router.

**Comment by freaker2k7** [comment]
I'll test it again, just to make sure, but it all seemed to work fine under chalich==0.7.0 and when I updated it, things stopped working... so there was no change in my router.
