### ISSUE TITLE
Deploying to "private" API Gateway with dedicated VPC endpoint

### ISSUE THREAD

**Issue by arnaudsj** [aws/chalice#897]
Hi,

I have created a dedicated VPC endpoint in order to be able to deploy a Chalice micro-service to a private API Gateway instance (meaning only accessible on a particular VPC within AWS), but I am not seeing anything in the document, nor issues which outlines how it is possible or not to specify the API Gateway resource policy (where you normally specify the VPC endpoint). I am following AWS's documentation here: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html#apigateway-private-api-set-up-resource-policy

Thank you in advance for any pointers or guidance.

**Comment by dhruvsakalley** [comment]
Currently creating open API endpoints causes internet traversals adding network latency ~100ms on top of lambda execution, also a lot of our API's are internal facing and not exposed to public endpoints. This is feature if implemented will increase chalice usage to a great extent for anyone who's developing micro-services which are consumed internally VPC's and would be able able to do so with low latency.

**Comment by mtslzr** [comment]
Would also love to see this added. As-is, `chalice deploy` wipes any existing resource policy, forcing us to trigger a second deploy to add the policy and re-deploy the API after Chalice does its thing. This would be incredibly useful for any internally-used APIs.

**Comment by schwartzie** [comment]
Just fixing the issue that @mtslzr noted with `chalice deploy` clearing out an existing API Gateway Resource Policy would allow us to manually make an API Gateway private while still getting the convenience of the rest of `chalice deploy`.

**Comment by dhruvsakalley** [comment]
Bump, I'm wondering if this can be marked important, an identical issue on SAM was https://github.com/awslabs/serverless-application-model/issues/480 increased in priority. If this is going to take a lot of time to get done, I would appreciate some workarounds. Currently it's a showstopper for adoption of chalice in our deploy pipeline.

**Comment by markwatson** [comment]
After digging through the code, it looks like adding this would require swagger support for this functionality. Or are there options in the code for setting custom ApiGateway options? Sorry, I'm still learning the codebase!

**Comment by HarryCaveMan** [comment]
After a little more digging, tit seems this might be added to `chalice package` by adding `EndpointConfiguration` to the config and properly applying it in the `_generate_restapi` method in `package.py` I will dig a little more to find out how it could be added to `chalice deploy`

**Comment by HarryCaveMan** [comment]
Tagged this in #976 because we will need the ability to add a resource policy for the VPCE

**Comment by kapilt** [comment]
added a pr that will allow deploying to private api endpoints (api endpoint configuration type), however this won't configure a vpc endpoint as that resource is shared across multiple apis and has variance for vpc/subnet/security groups independent of chalice configuration.
