### ISSUE TITLE
`reserved_concurrency` not working for lambdas

### ISSUE THREAD

**Issue by aarnold** [aws/chalice#912]
When I set the reserved_concurrency value for a function it is not used on the lambda function. I have tried both creating and updating the lambda from chalice with zero and non-zero values and nothing seems to update the "Reserve concurrency" in AWS.

chalice==1.6.0

My config.json
```
{
  "version": "2.0",
  "app_name": "xxx",
  "api_gateway_stage": "api",
  "manage_iam_role": false,
  "iam_role_arn": "arn:aws:iam::xxx",
  "stages": {
    "prod": {
      "lambda_functions": {
        "single_executing_function": {
          "reserved_concurrency": 1
        }
      }
    }
  }
}
```

**Comment by gallmerci** [comment]
Maybe you can post your config file to see whether everything is fine there? Did you try to package your chalice app using `chalice package <dir>` and check the sam.json for the ReservedConcurrentExecutions parameter?

**Comment by aarnold** [comment]
After running `chalice package <dir>`, the ReservedConcurrentExecutions parameter was correct in the sam.json. Running a deploy again showed the `reserved_concurrency` applied. Must have been a mistake when I was upgrading from 1.3.0 to 1.6.0.
