### ISSUE TITLE
Deploy fails with InvalidSignatureException

### ISSUE THREAD

**Issue by onurmatik** [aws/chalice#916]
I am using Chalice version 1.6.0. I have 100 MB of python packages in the `/vendor` directory, because of the `matplotlib` that my app depends on. The zipped deployment package is 30 MB, below the 50 MB AWS package size limit. 

My ISP's upload speed is low, slightly below 1 mbps. The deployment takes longer than 5 minutes and fails with the following message:

> ChaliceDeploymentError: ERROR - While sending your chalice handler code to Lambda to update function 
"create_report-dev-create_report", received the following error:
>  An error occurred (InvalidSignatureException) when calling the 
 UpdateFunctionCode operation: Signature expired: 20180727T161712Z is now 
 earlier than 20180727T162142Z (20180727T162642Z - 5 min.)

This I think, is due to the low tolerance of v4 signature. Is there a way around it? Is another signing / authentication method is available? Or, can chalice create timestamp at a later stage to save time?

**Comment by kadrach** [comment]
Check that this is not clock skew by synchronizing your clock to an NTP server.

As a workaround, you can try to use the [CloudFormation](https://chalice.readthedocs.io/en/latest/topics/cfn.html) deployment flow. This separates the S3 upload and the "Lambda update".

**Comment by onurmatik** [comment]
Thanks, I didn't know about the CloudFormation deployment flow. And, no, it is not a clock skew.
