### ISSUE TITLE
Question: How to get parameters from chalice command-line arguments?

### ISSUE THREAD

**Issue by behappycc** [aws/chalice#923]
I am currently trying app.py to get parameters from chalice deploy --stage dev. app.py need to know which stage and connect to different dynamoDB region. Is there a specific way to get parameters from chalice command-line arguments?

**Comment by gallmerci** [comment]
Did you have a look at [stage specific configuration](http://chalice.readthedocs.io/en/latest/topics/configfile.html#stage-specific-configuration)? There you can define environment variables depending on your stage which you then can use in your app.py.
