### ISSUE TITLE
Logging when using Chalice local

### ISSUE THREAD

**Issue by expertcoder** [aws/chalice#927]
I'm running `chalice local` and would like to have some kind of logging. The documentation refers to using CloudWatch logs, which I don't think makes much sense when running locally.

I have tried code like

```
logging.basicConfig(
   filename='myfile.log',
   level=logging.DEBUG
)

@app.route('/mytest', methods=['GET'])
def mytest():
   logger = logging.getLogger()
   logger.error('This is my log message')
   return {"some":"data"}
```

Nothing is be logged to the log file. This is the similar to other code which I use is other python programs and it usually works. Not sure why its not working, is Chalice interfering in some way

Either way, is there some preferred practises when logging with Chalice local? Maybe it would be worth updating the documentation to mention this.

Thanks.

**Comment by expertcoder** [comment]
I noticed this in a comment in the logger module code

```
def basicConfig(**kwargs):
   """This function does nothing if the root logger already has handlers
   configured...."""
```

So I guess that is why my code was not logging.

I am now using something like

```
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

file_handler = logging.FileHandler('./myfile.log')
file_handler.setFormatter(formatter)

logger = logging.getLogger()
logger.addHandler(file_handler)
logger.setLevel(logging.ERROR)


@app.route('/mytest', methods=['GET'])
def mytest():
   logger.error('This is my log message')
   return {"some":"data"}
```

**Comment by whatsdis** [comment]
after long time looking, code above is what I ended up using to get some insight into whats going wrong with chalice
