### ISSUE TITLE
extra index url option for requirements.txt 

### ISSUE THREAD

**Issue by aaj5956** [aws/chalice#936]
**Problem:**
Cannot install private pypi repositories using requirements.txt

**Details on the problem:**
The pip `requirements.txt` has extra options that you can specify in the file. (Ref: [Link](https://pip.readthedocs.io/en/0.8.3/requirement-format.html#indexes-find-links) and another [Link](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format)

I added an `--extra-index-url http://samplepypi.com/` (where samplepypi is a private pypi server hosted on AWS) in the `requirements.txt` but `chalice deploy` was not able to find the package.

I am aware of the `vendor` folder option mentioned in the documents. But this is not the approach I would like to take. I have multiple lambdas (almost 15~20) which are dependent on a single library (custom written). 

If I start putting the wheel file for this internal library in every lambda's vendor folder, it will be a pain to fix bugs for that library as I would be required to update 15~20 wheel files every time I fix a bug and release the next version.

Would like to know some pointers on how to solve this. RFE? Any other solution?

P.S. Thanks for this awesome piece of work.

**Comment by aaj5956** [comment]
I see #502 has been opened as an RFE. Any updates with that request?

**Comment by skwashd** [comment]
While not as clean as using a private package repository you might want to explore using `-e git+ssh://git@example.com/path/to/repo@hashortag#egg=package-name` to pull your packages out of your git repo. The [pip docs](https://pip.readthedocs.io/en/stable/reference/pip_install/#git) has more info on this.

**Comment by aaj5956** [comment]
Thanks for the pointer @skwashd I'll have a look at that. I can probably add it to the `make` file before deploying my app.

**Comment by stealthycoin** [comment]
@aaj5956  @skwashd Thumbs up the linked issue since we use those to track interest. Closing as duplicate.
