### ISSUE TITLE
Returning 404 on routing failure

### ISSUE THREAD

**Issue by k0kubun** [aws/chalice#945]
When a request path is wrong and an even handler is not found, it seems that it's returning 403 and saying "Missing Authentication Token" like [this](https://github.com/aws/chalice/blob/21c6ebd82849b25c57c6b36f131e5d3520047bc7/chalice/local.py#L463-L465). 

Is it intentional, or is there any way to change it to 404 and indicate the request path is wrong?

**Comment by stealthycoin** [comment]
This is a design decision by API Gateway. You can read more about it [here](https://stackoverflow.com/questions/46161538/how-to-make-serverless-return-404-instead-of-403-for-non-existing-endpoints) as well as a workaround at least in the CloudFormation layer.

**Comment by k0kubun** [comment]
Thanks for the answer!
