### ISSUE TITLE
CORS header is not returned

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#946]
I enable the cors=True in the route. However the header could be missing sometime.

POST https://xxxxxx 403 ()
progress.php:1 Failed to load https://xxxxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxxxxx' is therefore not allowed access. The response had HTTP status code 403.

The header eventually returns after a while of trying. The JS runs in a chrome incognito window. It may not be reproduced at will.

Is it a known issue?

**Comment by stealthycoin** [comment]
I need more details to understand what is going on here. In the case where it eventually returns the header is the response not a 403? In which case it is returning the headers for non-403 but isn't for 403, and the intermittent failure would probably be some other issue. Can you show the request-responses with sensitive data edited out and ideally the code that defines the method with `cors=True`?
