### ISSUE TITLE
manage_iam_role throwing "TypeError: str expected, not bool" when set as true/false

### ISSUE THREAD

**Issue by danielfranca** [aws/chalice#949]
According to the [documentation](https://chalice.readthedocs.io/en/latest/topics/configfile.html?highlight=roles#stage-specific-configuration) `manage_iam_role` accepts a boolean type.

However, when I try to setup my own `iam_role_arn` and set `manage_iam_role` to false it throws an exception.

Relevant stack trace:
```
  File "/.../python3.6/site-packages/chalice/cli/__init__.py", line 447, in main
    return cli(obj={})
  File "/.../python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/.../python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/.../python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.../python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
...
  File "/...python3.6/site-packages/chalice/cli/factory.py", line 250, in load_chalice_app
    self._environ.update(environment_variables)
  File "/.../python3.6/_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "/.../python3.6/os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "/.../python3.6/os.py", line 744, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bool
```

I have tried putting false between quotes, the error goes away, but the lambda doesn't respect my chosen role.

Details of my installation:
**chalice 1.6.0, python 3.6.6, darwin 17.7.0**

Btw, I was expecting that `Chalice` would auto-generate the role correctly for my lambda, however, it fails to give it permission to create jobs on ElasticTranscoder, that's the reason I'd to fall back to using my own role.

**Comment by stealthycoin** [comment]
I can't replicate this. This works fine for me:

```
$ chalice --version
chalice 1.6.0, python 3.6.6, darwin 15.6.0
```

```
$ cat .chalice/config.json
{
  "version": "2.0",
  "app_name": "test-role",
  "iam_role_arn": "arn:aws:iam::xxxxxxxxxxxx:role/testing123",
  "manage_iam_role": false,
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}
```

```
$ chalice deploy
Creating deployment package.
Creating lambda function: test-role-dev
Creating Rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:xxxxxxxxxxxx:function:test-role-dev
  - Rest API URL: https://xxxxxxxxxx.execute-api.us-west-2.amazonaws.com/api/
```

And inspecting the function in the console shows it linked to my correct role. Are there any more details you can give about your environment?

**Comment by danielfranca** [comment]
hmm, weird, the only other thing I can see on the stack trace is the library `click`, however, it doesn't seem to affect anything related.

**Comment by stealthycoin** [comment]
@danielfranca can you show me your sanitized config file?

**Comment by marcoslima** [comment]
To help someone with this type of error on chalice: this happens when you have any non-string on **environment variables** section. On this section all values must be string.
