### ISSUE TITLE
Chalice Deploy fails but there is no error message

### ISSUE THREAD

**Issue by PatrickSampaioGERU** [aws/chalice#952]
When i try to deploy a chalice application, it fails and returns no error message

`chalice deploy`
then:
```
Regen deployment package.
'variable_x'
```

**Comment by stealthycoin** [comment]
What version of chalice are you using? I would suggest upgrading since we now show the stack trace for these. Likely this is an issue with your `app.py` which we try to load before deployment.

**Comment by PatrickSampaioGERU** [comment]
I Updated the chalice version, now i have the stack trace and i was able to solve it. Thanks!
