### ISSUE TITLE
Cognito Authorizer - Claims seems outdated

### ISSUE THREAD

**Issue by budowski** [aws/chalice#953]
This might be an API Gateway issue, not 100% sure:
When using a `CognitoUserPoolAuthorizer`, while accessing the `claims` dictionary as:
```python
claims = app.current_request.context['authorizer']['claims']
```

It seems the claims dictionary contains *outdated* attributes - for example, if I update the user's `family_name` attribute, the `claims` dictionary will still show the old one. It takes some time for it to get "refreshed" with the latest result.

**Comment by stealthycoin** [comment]
Yea we do not populate that field that API gateway. I'm not super familiar with that feature off hand so I can't really give you any better advice unfortunately. I would check with the API Gateway team. on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

**Comment by budowski** [comment]
OK, got it - will close this issue and take it up with the API Gateway team, thanks!
