### ISSUE TITLE
Support for API Gateway endpoint configuration as REGIONAL

### ISSUE THREAD

**Issue by dmulter** [aws/chalice#956]
Currently it's very convenient that the API Gateway REST API is created as the EDGE endpoint type. This way the CloudFront distribution is handled by API Gateway.

In a more secure configuration, I would like to create the API as a REGIONAL endpoint and manage the CloudFront distribution myself (outside of Chalice) so I can do things like add WAF on the front-end of requests.

**Comment by dstufft** [comment]
Marking this as a feature request.

**Comment by dmulter** [comment]
Maybe this isn't needed anymore as you can configure WAF directly to API Gateway as described [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-aws-waf.html)?

**Comment by dhruvsakalley** [comment]
Having the ability to deploy as regional has other advantages such as reduced latency, private api < regional <edge-optimized, this is still desirable.

**Comment by crawforde** [comment]
Any progress on this issue? Latency and security are an issue for my project. This would address both of those to some extent.

**Comment by jcomish** [comment]
Is there any workaround while this issue is being worked on? This is currently a blocking issue for us.

**Comment by kapilt** [comment]
i've put up a pull request which enables configuring api endpoint type.
