### ISSUE TITLE
Lambda function handler doesn't appear to be set correctly.

### ISSUE THREAD

**Issue by ScottJWalter** [aws/chalice#957]
### Chalice version
1.6.0

### To reproduce
1.  Set up AWS credentials
1.  Follow chalice installation instructions
1.  Create and change into project directory
1.  run `chalice new_project`
1.  Attempt to deploy the new project template with `chalice deploy`
1.  Browse to the URL returned from the deployment

### Expected Outcome
You should receive a JSON packet back with "hello":"world" in it.

### Actual Outcome
*  You receive a JSON package containing "Internal server error".
*  Cloudwatch logs show the error "No module named 'lambda_function'"

### Issue
When a lambda function is created with Python 3.6, it's handler is set to `lambda_function.lambda_handler`, but chalice doesn't expose a function with that name.  This can be changed dynamically, but it appears chalice isn't doing that.

### Workaround
1.  In the lambda console, open up the  function
1.  Select the **Configuration** tab
1.  In the **Function Code** section, change the value of **Handler** from `lambda_function.lambda_handler` to `app.app`
1.  Click **Save**

**Comment by stealthycoin** [comment]
Can you give details on exactly what you did? The repro steps don't make sense as you say you create a new project multiple times. 
Our CI/CD system runs our integration tests on Python 2 and 3 before releases, and I almost exclusively use python 3.6 in Chalice (except when testing 2.7) so I highly doubt this is the case. I need to see _exactly_ what you did to be of any help.

**Comment by ScottJWalter** [comment]
My fault.  Got sidetracked.  Further investigation showed the issue was mine (somehow, I'd gotten things crossed up during a deployment).  Since then, I've built and deployed additional Chalice apps without the issue surfacing again.  I'm calling it a fluke I created and moving on.
