### ISSUE TITLE
Can we pass env specific app_name?

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#963]
I run same set of code for different end-points. I would like to create app with env specific name when app instance is created.

app = Chalice(app_name='ABC')

Is this possible now at the code build time?

**Comment by stealthycoin** [comment]
It is possible. I'm not sure that its a good idea though, can you explain your use case more? Is there a reason stages aren't good enough for your use case?

Using stages is probably the better solution:
```
$ cat app.py
import os

from chalice import Chalice

app = Chalice(app_name='foobarbaz')


@app.route('/')
def index():
    return 'I am %s!' % os.environ.get('STAGE_NAME', 'unknown')
```
Configure unique env vars for each stage.
```
$ cat .chalice/config.json
{
  "version": "2.0",
  "app_name": "foobarbaz",
  "stages": {
    "foo": {
      "api_gateway_stage": "api",
      "environment_variables": {
	"STAGE_NAME": "foo"
      }
    },
    "bar": {
      "api_gateway_stage": "api",
      "environment_variables": {
	"STAGE_NAME": "bar"
      }
    },
    "baz": {
      "api_gateway_stage": "api",
      "environment_variables": {
	"STAGE_NAME": "baz"
      }
    }
  }
}
```
Deploy all three stages.
```
$ chalice deploy --stage foo
Creating deployment package.
Updating policy for IAM role: foobarbaz-foo
Updating lambda function: foobarbaz-foo
Updating rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:123456789:function:foobarbaz-foo
  - Rest API URL: https://123.execute-api.us-west-2.amazonaws.com/api/
$  foobarbaz chalice deploy --stage bar
Creating deployment package.
Updating policy for IAM role: foobarbaz-bar
Updating lambda function: foobarbaz-bar
Updating rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:123456789:function:foobarbaz-bar
  - Rest API URL: https://456.execute-api.us-west-2.amazonaws.com/api/
$  foobarbaz chalice deploy --stage baz
Creating deployment package.
Updating policy for IAM role: foobarbaz-baz
Updating lambda function: foobarbaz-baz
Updating rest API
Resources deployed:
  - Lambda ARN: arn:aws:lambda:us-west-2:123456789:function:foobarbaz-baz
  - Rest API URL: https://789.execute-api.us-west-2.amazonaws.com/api/
```
Curl the URL for each stage.
```
$ curl $(chalice url --stage foo)
I am foo!
$ curl $(chalice url --stage bar)
I am bar!
$ curl $(chalice url --stage baz)
I am baz!
```

**Comment by wutachih** [comment]
When I create a custom domain name in API gateway with multiple routes, the destination is the app name in the route. If the name is same for all stages, I have to create one custom domain for each stage.

**Comment by stealthycoin** [comment]
Can you elaborate? You can make multiple rule mappings. I just tried it with one name and 3 stages seemed to work fine.

<img width="381" alt="screen shot 2018-10-15 at 1 10 17 pm" src="https://user-images.githubusercontent.com/1010634/46975542-bd487f80-d07b-11e8-99b0-e47bd982afab.png">
 You can make three mappings to the same app and select a different stage for each one.
