### ISSUE TITLE
How to deploy from multiple machines?

### ISSUE THREAD

**Issue by ChillarAnand** [aws/chalice#966]
When user1 deploys from machine1 it creates new api1. When user2 deploys from machine2, it creates new api2. Is there a way to make sure all deployments point to same existing url?

**Comment by BigChief45** [comment]
You probably will have to share or commit to source control the files generated by Chalice after a deployment. So that all machines update a single deployment.

**Comment by kyleknap** [comment]
I would say there are two options here:

1) Use `chalice generate-pipeline` to create a CodePipeline pipeline for full CI/CD so different users can push to the same repository and have it get automatically deployed

2) Do what @BigChief45 suggested. Specifically, you need to make sure to share the `.chalice/config.json` files and the `.chalice/deployed` directory, assuming you are on the latest version of `chalice`. The only caveat is that the `deployed` directory is not documented so its format may change or may even no longer be used from minor version to minor version.

In general, I would recommend option 1, but if you only want to use `chalice deploy`, option 2 is your best bet. Let us know if you have anymore questions.

**Comment by ChillarAnand** [comment]
Thanks @kyleknap @BigChief45
