### ISSUE TITLE
Uncaught exception handling improvement

### ISSUE THREAD

**Issue by dmulter** [aws/chalice#969]
Currently uncaught exceptions log a DEBUG level message (includes stack trace) and return this in the body of the HTTP error response if DEBUG is enabled. An `InternalServerError` is returned without any logging if DEBUG is not enabled.

Please consider the following alternate behavior:

- Always log as ERROR level regardless of the DEBUG level of the app. This makes it much easier to monitor and alert based on these error messages.
- Return the error plus stack trace via the HTTP response if DEBUG is enabled (existing behavior).
- Return `InternalServerError` without stack trace if DEBUG is not enabled (existing behavior).

See this section of code:

https://github.com/aws/chalice/blob/947eb8f22ac74c79755dda0491cab6b74a5fc099/chalice/app.py#L738

**Comment by dmulter** [comment]
Yes, just wanted to be very clear how all the other behaviors are great and I wouldn't want to lose them.

**Comment by dmulter** [comment]
Oops, I guess my reply was actually wrong. I am also suggesting that the ERROR level log message is also generated when DEBUG is not enabled. I went to make the code change and realized my mistake. I'll submit a PR in a second so you can see what I'm thinking. Hopefully this change is also acceptable.

**Comment by dmulter** [comment]
Here's the [code diff](https://github.com/dmulter/chalice/pull/1/files?utf8=✓&diff=split) to be clear, and hopefully to encourage progress on this issue ;-)

**Comment by fquinner** [comment]
Hi @dmulter - just changed this into a PR for the chalice project. This is a pretty big deal for me for operational monitoring too.

**Comment by stealthycoin** [comment]
Merged with #1144
