### ISSUE TITLE
Incompatible with Pip>18.0

### ISSUE THREAD

**Issue by ramlaxman** [aws/chalice#981]
Chalice 1.6.1 is not compatible with latest `pip` version 18.1
Also it depends on previous version of `click` package i.e. 6.6 rather than 7.0.
It becomes difficult to maintain chalice as a part of package environment.

**Comment by dmulter** [comment]
FYI, works fine for me with pip 18.1 even though you get compatibility warnings.

**Comment by danilobrinu** [comment]
I use **easy_install chalice** for now and **pip install** for install another packages

**Comment by dmulter** [comment]
This is a problem again now that pip 19.0.2 is out.

**Comment by duaneking** [comment]
This is a huge issue.

Fix for this seems to be to use Zappa or some other framework instead.

**Comment by dmulter** [comment]
Always add thumbs up to the story to get counts up. The maintainers seem to prioritize based on number of people that have an issue. This is a great framework that needs more active people letting the team know to give it some love.

**Comment by duaneking** [comment]
Python packages shouldn't be dependent on the version of pip anyway, that in itself is a serous defect that creates more work consistently.
