### ISSUE TITLE
Please merge or provide guidance on what it will take to merge #651

### ISSUE THREAD

**Issue by tedivm** [aws/chalice#994]
This is a highly demanded feature that will make using Chalice significantly easier, especially with regards to testing. At this point most Flask developers use the "app factory" model for development, where they have a function that creates an `app` object rather than having one defined for the entire system. This allows testing with different options, but it only works with systems that have blueprints.

Additional blueprints make organizing code a lot easier.

**Comment by jamesls** [comment]
Hi, sorry for the delay on this. I commented over in (https://github.com/aws/chalice/pull/651#issuecomment-444710490),  let's continue the discussion over there.
