### ISSUE TITLE
AWS lambda now supports Python 3.7

### ISSUE THREAD

**Issue by bulletmark** [aws/chalice#996]
As per https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-supports-python-37/ the main README at least needs change to mention this. More importantly, both python 3.6 and 3.7 are supported but 3.6 is the default so the README should state how to change this.

That release note merely says "Customers with existing Python functions can switch to the new runtime by editing their function configuration to set the runtime to “python3.7” and making necessary changes to be compatible with the new runtime." but that is far too vague.

**Comment by bulletmark** [comment]
Actually, just found this https://chalice.readthedocs.io/en/latest/topics/pyversion.html#changing-python-runtime-versions. So it seems chalice is yet to be changed to recognise 3.7 and automatically set this.

**Comment by jamesls** [comment]
Supported now via https://github.com/aws/chalice/pull/992.  This will be available in the next chalice release.
